### ISSUE TITLE
 Participate with suggestions and constructive criticism on reddit.com

### ISSUE THREAD

**Issue by privacytoolsIO** [privacytoolsIO/privacytools.io#1]
It's important for a website like privacytools.io to be up-to-date. Keep an eye on software updates of the applications listed here. Follow recent news about providers that are recommended. We try our best to keep up but we're not perfect and the internet is changing fast. So if you find an error, or you think a provider should not be listed here, or a qualified service provider is missing or a browser plugin is not the best choice anymore or anything else...

**Talk to us please.** [Join our subreddit and start a discussion.](http://www.reddit.com/r/privacytoolsIO/) This is a community project and we're aiming to deliver the best information available for a better privacy. We are also using /r/privacy. Thank you for participating. 

Don't submit suggestions here on GitHub. This is only for developing the website.

**Comment by alexbooker** [comment]
Now that this information is visible in the readme, can we close this now?
