### ISSUE TITLE
💬 Discussion | privacy.trackingprotection.fingerprinting isn't avalible in FireFox-esr

### ISSUE THREAD

**Issue by ghbjklhv** [privacytoolsIO/privacytools.io#1010]
**The Issue**: `privacy.trackingprotection.fingerprinting` is not yet avalible in many FireFox-esr versions provided by popular operating systems.

**Suggestion**: Inform users that this segment may not be available in all version of FireFox.

**Comment by Mikaela** [comment]
Could you check which version of Firefox introduces it and when is it scheduled to come to ESR?

**Comment by Thorin-Oakenpants** [comment]
It landed in FF67 [see https://www.ghacks.net/2019/02/05/firefox-67-cryptomining-and-fingerprinting-protection/], and is therefore part of ESR68 which is due out next week. Just add a `[FF67+]` next to it on the site

**Comment by Mikaela** [comment]
Thanks for the suggestion, I opened #1012 marking you as the author to not lose attribution.

**Comment by Thorin-Oakenpants** [comment]
You don't need to attribute me, and I'd rather you didn't: just point to the facts if you really feel you need to

- Bug [1527917](https://bugzilla.mozilla.org/show_bug.cgi?id=1527917) - Enable cryptomining and fingerprinting blocking options in about:preferences.
- Bug [1522567](https://bugzilla.mozilla.org/show_bug.cgi?id=1522567) - Add cryptomining and fingerprinting protection options to custom content blocking preferences.

**Comment by Mikaela** [comment]
Ok, I removed the attribution and I guess it's enough for people to be able to come here from that pull request if they are interested in the upstream issues.

**Comment by Thorin-Oakenpants** [comment]
^^ it's the same for the cryptomining pref right below it: see the above two bugzilla titles
