### ISSUE TITLE
🌐 Website Issue | Forum and website aren't easily findable from each other

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1017]
https://forum.privacytools.io/t/what-is-the-smartphones-encrypted-memo-app/1040/4?u=mikaela

**Comment by Mikaela** [comment]
Assigning @privacytoolsIO/services

**Comment by nitrohorse** [comment]
I wonder if on the forum, the top-left logo should be updated to something like “privacytools.io forum” rather than just “privacytools.io” to mitigate some confusion?

**Comment by blacklight447-ptio** [comment]
Closing as we now link to the main page from the forum.
