### ISSUE TITLE
💬 Discussion | Add Related issues to Minds

### ISSUE THREAD

**Issue by jkhgvfgvsth** [privacytoolsIO/privacytools.io#1018]
**Short Description**: Add Related Issues for Minds
**Longer Description**: Minds has many differences to the other listed in "Decentralized Social Networks", I assume this is why it is listed under worth mentioning and not main.

I propose the concept of adding related issues to help explain the differences in Minds, not necessarily making it worse but to better inform users. For instance, you can't really self-host Minds (yet).
Minds is also more active and has a significantly cleaner UI than alternatives like Diaspora or Friendica.

Some Issues to Discuss:
[Mind's Supporting Activity Pub isn't yet Active](https://gitlab.com/minds/engine/issues/307)

[Federated & Decentralized](https://gitlab.com/minds/engine/issues/183)

**Comment by Mikaela** [comment]
> Minds - An open source and distributed social networking service, integrating the blockchain to reward the community.

How would you propose adding the issue links to that? I wonder if worth mentioning should also have their official forum threads (@BurungHantu1605)?

**Comment by jkhgvfgvsth** [comment]
@Mikaela I figured you could add a warning badge like:

`<span class="badge badge-warning" data-toggle="tooltip" title="This software has some related information you may be interested in like <a href="https://gitlab.com/minds/engine/issues/183">#183</a> or <a href="https://gitlab.com/minds/engine/issues/307">#307</a>.">notes <i class="far fa-question-circle"></i></span>`

**Comment by Mikaela** [comment]
I fear that tooltips cannot have links or they will be unclickable at least from desktop browsers. With the description I worry about it looking inconsistent, but I admit it's less of an issue than not having this information.

Would you like to send a PR?

**Comment by jkhgvfgvsth** [comment]
@Mikaela :+1:

**Comment by jkhgvfgvsth** [comment]
@Mikaela Would it be better to make "notes" redirect here?

**Comment by blacklight447-ptio** [comment]
updates on this issue? is there any progress?

**Comment by Mikaela** [comment]
It looks like @BurungHantu1605 rejected the PR without explanation.

**Comment by blacklight447-ptio** [comment]
so what are we doing here, closing it?

**Comment by Mikaela** [comment]
I guess
