### ISSUE TITLE
💬 Discussion | Obsolete warning about Privacy Badger and Google Analytics?

### ISSUE THREAD

**Issue by woctezuma** [privacytoolsIO/privacytools.io#1022]
It seems that the Google Analytics issue with Privacy Badger might have been [fixed](https://github.com/EFForg/privacybadger/issues/574#issuecomment-510036366).

This issue was originally discussed in #335, and [a warning](https://www.privacytools.io/browsers/#addons) was added in #917:

![warning](https://i.imgur.com/K5hDGk6.png)

The warning might not be needed anymore. I need to read more about the changes.

**Comment by beerisgood** [comment]
Wow! After years...

uBlock Origin is still better

**Comment by Mikaela** [comment]
> The warning might not be needed anymore. I need to read more about the changes.

After you have read about them, would you mind linking and explaining your findings and opening a PR?

**Comment by woctezuma** [comment]
Privacy Badger used to let Google Analytics slip through, because its heuristic could not deal with tracking based on [cookie-sharing pixels](https://github.com/EFForg/privacybadger/pull/2147). This was visible with uBO-Scope.

I was [informed](https://github.com/EFForg/privacybadger/issues/367#issuecomment-510025402) of a recent patch. After a few days of testing the add-on with uBO-Scope, the claim seem true: Privacy Badger now properly deals with Google Analytics.
