### ISSUE TITLE
💬 Discussion | Payment Processing

### ISSUE THREAD

**Issue by ggg27** [privacytoolsIO/privacytools.io#1025]
**Concept**: Add Payment Section(s) to privacytools.io
This may be a too "divided" section to add, but nonetheless a discussion worth having.

**What do you propose?**:
So, for obvious reasons anonymous cryptocurrencies should almost definitely get the "success" spot ([perhaps bring back this section?](https://archive.fo/wJ1aa#cryptocurrency)). Cash might also be added with that.
The rest will probably need to be some other service.

**Who can you back?**
*Notice*: I'm a US consumer, and my country is very strict with KYC so be warned!
So, this is a discussion thread so it can go beyond this but I have used:

Payment Processors:
- [MangoPay](https://www.mangopay.com) (users doesn't need to execute non-free code)

- [WooComerce](https://www.wikipedia.org/wiki/WooCommerce) ([GPL](https://www.wikipedia.org/wiki/GNU_General_Public_License))

- [LiberaPay](https://www.wikipedia.org/wiki/Liberapay) (non-free payment processing)

- [CiviCRM](https://www.wikipedia.org/wiki/CiviCRM)

Consumer Products:
(all may require non-free software)
- [BitPay](http://www.wikipedia.org/wiki/BitPay) Card (Requires KYC, Accepts Cryptocurrency and works internationally)

- [Privacy.com](https://privacy.com) (fairly lax KYC)

**I have a suggestion**:
To the comments! Please share any thoughts that may add value!

**Definitions**:

- [KYC = Know Your Customer](http://www.wikipedia.org/wiki/Know_your_customer)

- [Cryptocurrency](http://www.wikipedia.org/wiki/Cryptocurrency)

- [Cash](http://www.wikipedia.org/wiki/Cash)

- [Non-free software/code = Software that is not free/libre](https://www.wikipedia.org/wiki/non-free_software)

**Comment by Mikaela** [comment]
I think payment processing isn't the right word as LiberaPay is a platform for recurring payments and they need to use a payment processor which is currently Stripe or PayPal depending on the recepient of the donation. They used to use MangoPay previously, but https://github.com/liberapay/liberapay.com/issues/374#issuecomment-393617792 happened.

There is also a loosely related forum thread [How to support FOSS projects](https://forum.privacytools.io/t/how-to-support-foss-projects/669?u=mikaela).

**Comment by ggg27** [comment]
@Mikaela LiberaPay is more of a way to of a way to accept donations while allowing the users to choose their processor. I really hope they get issues like https://github.com/liberapay/liberapay.com/issues/1374#issuecomment-451637108. Things like adding Bitcoin (https://github.com/liberapay/liberapay.com/issues/364) support and recieveing PayPal might help.
