### ISSUE TITLE
🆕 Software Suggestion | Privoxy

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#1032]
## Basic Information

**Name:** Privoxy
**Category:** https://www.privacytools.io/browsers/#addons - "For Experts Only" section
**URL:** 

https://www.privoxy.org/
https://github.com/essandess/easylist-pac-privoxy#purpose

## Description

Privoxy is a non-caching web proxy with advanced filtering capabilities for enhancing privacy, modifying web page data and HTTP headers, controlling access, and removing ads and other obnoxious Internet junk. Privoxy has a flexible configuration and can be customized to suit individual needs and tastes. It has application for both stand-alone systems and multi-user networks.

maybe it's worth mentioning privoxy in addons section. i know that is not an addon, to a browser. but is very usefull soultion to protect privacy, like ublock origin

**Comment by KonoromiHimaries** [comment]
https://github.com/privacytoolsIO/privacytools.io/issues/980

**Comment by blacklight447-ptio** [comment]
So you would want a new category to be added here?

**Comment by Mikaela** [comment]
Privoxy is not a web extension, but a proxy server that can also be used by other software than web browser.

Why should it be listed, while there are already software suggestion doing the same thing more flexibly? Personally I am using Privoxy only for random software that doesn't support SOCKS directly.
