### ISSUE TITLE
🆕 Software Suggestion | FoxyProxy Extension

### ISSUE THREAD

**Issue by ghbjklhv1** [privacytoolsIO/privacytools.io#1034]
## Basic Information

**Name:** FoxyProxy (extension not VPN)
**Category:** Browser Extensions
**License:** [GPL v2](https://github.com/foxyproxy/firefox-extension/blob/master/LICENSE)
**Git/Source_Code**: https://github.com/foxyproxy/firefox-extension
**URL:** https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/

## Why
**General**: 
Foxy proxy is an amazing tool for managing proxies. 

**Patterns**:
Especially users of darknet services like i2p. It is particularly awesome since you can set different proxies for different TLDs, for instance [.onion](https://www.wikipedia.org/wiki/.onion) for [127.0.0.1:9050](http://127.0.0.1:9050) or [.i2p](https://www.wikipedia.org/wiki/.i2p) for [127.0.0.1:4444](http://127.0.0.1:4444) or even certain DNS services like [NameCoin](https://www.wikipedia.org/wiki/Namecoin).

**Regular Proxies**: 
You can also set it to help manage proxies like Socks5 or http proxies.

**Comment by blacklight447-ptio** [comment]
while its fun for playing around, I don't think we should be encouraging users to approach networks outside of their normal setups, for example, we should not encourage tor usage through Firefox, but through tor browser.

**Comment by TNTBOMBOM** [comment]
I2P has new testing phase its own browser please check out: 

https://geti2p.net/en/download/lab

and also i give my vote to @blacklight447-ptio , because browser extension level is not the best type of security practice. Browser modification level always recommended.

**Comment by blacklight447-ptio** [comment]
AFter some thinking, i don't think we should list it under our recommendations. as firstly normal proxies provide relatively few privacy benefits when compared to other solutions like VPN providers and Tor. secondly, users who would go thru the hassle of managing their own proxy and configure it are very likely to find these tools on their  own. I am closing the issue now, if anyone disagrees, they can comment with arguments on why it should be opened again.
