### ISSUE TITLE
🆕 Software Suggestion | c0x0.com

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1038]
~~I only know [it was suggested at Reddit](https://www.reddit.com/r/privacytoolsIO/comments/ce8j36/another_service_with_anonymous_email_addresses_it/eu7gfsn) and I cannot look deeper at the moment.~~ The below is formatted copy-paste of the first comment from @kolargol which I am hiding so readers won't read it twice:

## Basic Information

** Name**: c0x0.com
**Category**: providers/email
**URL**: https://c0x0.com/

## Description:
c0x0.com is a service that generates random aliases and attach them to any service you use. Think of it as a shield that protect your real address. This service is not ment for disposable addresses, it target problem when signing-up and want to stay away with your private e-mail address.
Among many features you can bring your own domain and it supports API access.
Service offers free plan as well as paid options. Plans starting as low as $2.5/mo

Thanks for consideration. Any opinions are welcome.

**Comment by kolargol** [comment]
Name: c0x0.com
Category: providers/email
URL: https://c0x0.com/

Description:
c0x0.com is a service that generates random aliases and attach them to any service you use. Think of it as a shield that protect your real address. This service is not ment for disposable addresses, it target problem when signing-up and want to stay away with your private e-mail address.
Among many features you can bring your own domain and it supports API access.
Service offers free plan as well as paid options. Plans starting as low as $2.5/mo

Thanks for consideration. Any opinions are welcome.

**Comment by blacklight447-ptio** [comment]
their privacy policy is pretty solid: https://web.c0x0.com/privacy-policy.php
They seem to only save data needed for the operation of the service.

**Comment by kolargol** [comment]
there is also browser addon available: https://coxo.io/

**Comment by Mikaela** [comment]
What do you think, @dngray ?

**Comment by dngray** [comment]
Well I did notice:

> Mail is handled using latest security standards, like TLS1.3, DNSSEC, DANE, MTA-STS, DKIM, SPF and more

which is good. If their privacy policy checks out I don't see why we can't mention them on the new email page.

**Comment by dngray** [comment]
I can't see why we'd recommend this when AnonAddy has source https://github.com/anonaddy/anonaddy ie PR https://github.com/privacytoolsIO/privacytools.io/issues/1673

I was thinking about adding c0x0 but their [logos appear to be PNG images wrapped in SVG](https://saturn.onefellow.com/cdn/c0x0/mainwebsite/img/c0x0-logo-mainA.svg) for some reason.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> I can't see why we'd recommend this when AnonAddy has source https://github.com/anonaddy/anonaddy ie PR #1673
> 
> I was thinking about adding c0x0 but their [logos appear to be PNG images wrapped in SVG](https://saturn.onefellow.com/cdn/c0x0/mainwebsite/img/c0x0-logo-mainA.svg) for some reason.

I mentioned the same and I think it was blacklight who said that since we can't verify that what's on the server it's the same than what's on the repository being open source isn't that important. There are quite some other e-mail forwarder that are FLOSS btw, Ptorx, erine.email, SimpleLogin and ForwardEmail.

**Comment by dngray** [comment]
> There are quite some other e-mail forwarder that are FLOSS btw, Ptorx, erine.email, SimpleLogin and ForwardEmail.

They would also need to meet the other requirements of the email criteria, as they are essentially email providers, that just forward to a real inbox.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> > There are quite some other e-mail forwarder that are FLOSS btw, Ptorx, erine.email, SimpleLogin and ForwardEmail.
> 
> They would also need to meet the other requirements of the email criteria, as they are essentially email providers, that just forward to a real inbox.

Is the criteria just on the preview or is it somewhere else? I could send them an e-mail and create an issue to see whether or not meet it.

**Comment by dngray** [comment]
> > > There are quite some other e-mail forwarder that are FLOSS btw, Ptorx, erine.email, SimpleLogin and ForwardEmail.
> > 
> > 
> > They would also need to meet the other requirements of the email criteria, as they are essentially email providers, that just forward to a real inbox.
> 
> Is the criteria just on the preview or is it somewhere else? I could send them an e-mail and create an issue to see whether or not meet it.

https://deploy-preview-1672--privacytools-io.netlify.com/providers/email/

I'd prefer you wait until this gets merged with master and is live on the main site.
