### ISSUE TITLE
🆕 Software Suggestion | Soverin

### ISSUE THREAD

**Issue by nitrohorse** [privacytoolsIO/privacytools.io#1045]
## Basic Information

**Name:** Soverin
**Category:** Email
**URL:** https://soverin.net

## Email checklist:
[x] Outside of USA
[x] Support SMTP SSL
[x] Accessible Using Free Software (i.e IMAP)

## Description:

Main features:
- ~$4/month
- 25 GB Storage
- Personal domain support
- Email (imap), calendar (caldav) and contacts (cardav) support
- Unlimited aliases on own domain

Further details:
- Since: [2015](https://www.producthunt.com/posts/soverin)
- EU legal base: Amsterdam, the Netherlands (Nine Eyes)
- Mission: ["private communication for everyone."](https://soverin.net/about) 
- [Privacy manifest](https://soverin.net/manifest)
- [ToS/Privacy Policy](https://soverin.net/legal)
- [Warrant canary](https://soverin.net/warrant-canary) (up to date as of: 2019-07-01)
- [Infrastructure details](https://soverin.net/how)
    - [Webmail](https://mail.soverin.net/) runs on [Roundcube](https://en.wikipedia.org/wiki/Roundcube) with [configurable 2FA](https://support.soverin.net/hc/en-us/articles/360008819553-Setting-up-2-Factor-Authentication-2FA-Webmail-only)
- [SSL Labs rating](https://www.ssllabs.com/ssltest/analyze.html?d=soverin.net&latest): A+
- [Site analysis](https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fsoverin.net)
- Bonus: ["No data footprint, no carbon footprint. All our servers run on sustainable energy sources."](https://soverin.net/features)

**Comment by danarel** [comment]
I have used Soverin, it's a good service. I tested it out about a year ago and honestly can't remember what it was that got me to leave, but I don't remember having an overall bad experience.

**Comment by Mikaela** [comment]
Looks good based on your links, but I don't find much else with them using Ecosia and https://alternative.me/soverin seems like it's written for something else (I don't hold that against Soverin though). :+1:

**Comment by blacklight447-ptio** [comment]
I haven't been able to find them either, maybe we can invite one of their employees here to introduce themselves further?

**Comment by blacklight447-ptio** [comment]
Also discovered the journalist Micah flee (onionshare developer as well) uses soverin:https://interc.pt/2WfqQpR
