### ISSUE TITLE
🌐 Website Issue | Instant messengers: Gajim is not Linux-only

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1057]
However I am currently unable to open https://gajim.org/ so I cannot provide the correct platforms at the moment.

* https://www.privacytools.io/software/im/

**Comment by nitrohorse** [comment]
Huh, that's interesting. It's down for me too.

**Comment by nitrohorse** [comment]
[Looks like](https://gajim.org/downloads.php?lang=en) Gajim is available also on Windows.

![gajim](https://user-images.githubusercontent.com/1514352/62014170-435a3080-b18d-11e9-8a74-2508a62abc30.png)

**Comment by Mikaela** [comment]
![Screenshot_2019-07-29 Gajim, an XMPP client](https://user-images.githubusercontent.com/831184/62033107-c5247b00-b1da-11e9-9e56-65231cd6dd1e.png)

hah, we took the same screenshot of https://gajim.org/downloads.php?lang=en

Anyway I would say FreeBSD, Linux, Windows based on that and will open a PR soon.
