### ISSUE TITLE
🆕 Software Suggestion | BCM Messenger

### ISSUE THREAD

**Issue by swe3per** [privacytoolsIO/privacytools.io#1059]
## BCM - Blockchain Messenger

**Name: BCM Messenger**
**Category: Software, Instant Messenger**
**URL: bcm-im.com**
**Platform: iOS / Android**
**Security: https://hackerone.com/bcm/**

## Description
Released a new IM(Instant Messenger), based on the technology of blockchain adopted complete end-to-end encryption (messages, voice and video calls, file transfer, group chat, etc.), all anonymous use (don't need a phone number and email, to avoid any review by SMS gateway regulation), support both sides message destruction, remote account destroyed, and others.
Officials say they are currently developing multiple-hop off-the-grid communications, it's a great feature to look forward to.
They're part of the hackerone security bug bounty program, and the developers are supposed to be privacy-conscious hackers.

**Comment by Mikaela** [comment]
I am worried about it being a "blockchain based messenger" which by definition means that all messages are stored forever and are also publicly available just waiting for the day, its encryption can be broken.

The privacy policy also doesn't reassure me, I am not going to register an account without seeing it.

> Q: Does BCM have a privacy policy?
> 
> You can view our detailed Privacy Policy when registering for a BCM account.


> Q: Will BCM open source?
> 
> BCM is planning to open source, and we will gradually disclose source code of BCM to the public.


* https://bcm-im.com/keys_faq/index.html

Please request reopening after at least these two issues are fixed, Telegram has also been promising open sourcing their server for years.
