### ISSUE TITLE
🆕 Software Suggestion | Intra

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1069]
## Basic Information

**Name:** Intra
**Category:** Android Privacy Add-ons
**URL:** https://getintra.org/

## Description

Open source DNS over HTTPS app by Jigsaw (by *Alphabet* (which is also known of *Google*)).

Problem: not in F-Droid (https://github.com/Jigsaw-Code/Intra/issues/9)

Blocker/link-to: #1054 ?

**Comment by nitrohorse** [comment]
A big concern of mine is that the linked privacy policy from their site points to https://policies.google.com/privacy. Their [ToS](https://jigsaw.google.com/jigsaw-tos) is scary too:

> We provide information to help copyright holders manage their intellectual property online.

> When you upload, submit, store, send or receive content to or through our Services, you give Jigsaw (and those we work with) a worldwide license to use, host, store, reproduce, modify, create derivative works (such as those resulting from translations, adaptations or other changes we make so that your content works better with our Services), communicate, publish, publicly perform, publicly display and distribute such content.

> Our automated systems analyze your content (including emails) to provide you personally relevant product features, such as customized search results, tailored advertising, and spam and malware detection. This analysis occurs as the content is sent, received, and when it is stored.

**Comment by Mikaela** [comment]
I never read those, even if I should. I wonder if the app phones home as in the settings "Select DNS over HTTPS server" it either has inbuild list which also has links to privacy policies or it can take a custom host.

However the UI has links to the same pages as the website, so I guess this is safe to close. I fear the app has no alternatives on Android though as 1.1.1.1 and Quad9 Connect (DoT) are closed source so Android <9 users have nothing.
