### ISSUE TITLE
Add UK's Investigatory Powers Bill

### ISSUE THREAD

**Issue by MuriloDalRi** [privacytoolsIO/privacytools.io#107]
The UK parliament passed a new bill that will require all ISPs to keep a full record of every site that each of its customers has visited: http://www.independent.co.uk/life-style/gadgets-and-tech/news/snoopers-charter-2-investigatory-powers-bill-parliament-lords-what-does-it-mean-a7423866.html

I think this should be mentioned as it is the most extreme spying bill in a western democracy.

**Comment by privacytoolsIO** [comment]
Under what section?

**Comment by Shifterovich** [comment]
It's related to the "don't use US-based services" thing. Maybe expand the Global Mass Surveillance section and make Fourteen Eyes a new section?

**Comment by Hillside502** [comment]
Changing the issue title to "delete me" makes a nonsense of issue tracking!
