### ISSUE TITLE
🆕 Software Suggestion | EDS

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1076]
## Basic Information

**Name:** Encrypted Data Storage / EDS
**Category:** Android addons?
**URL:** https://sovworks.com/eds/

## Description

> Encrypted Data Storage, or EDS, is an F-Droid availaible android application thats is compatible with the Veracrypt and truecrypt formats and is open source. It also provides exFAT support through an additional module. I think it would make a good addition to the “encryption services” section.

VIa https://forum.privacytools.io/t/suggestion-eds/1221

**Comment by blacklight447-ptio** [comment]
Note that only eds lite is free. Full eds costs money.

**Comment by blacklight447-ptio** [comment]
Note: the project seems a bit dead, last commit was i jun 2018 maybe @sovworks could update us on the status of the project.

**Comment by blacklight447-ptio** [comment]
Even though i really like the tool, i have not been able to get a reaction from its developer, and have not seen any comits or other activity for nearly a year now, so im guessing its no longer maintained, closing issue.

**Comment by sovworks** [comment]
I'm sorry, I've missed the discussion. 
We're working on a completely new version of eds. Current version is in maintenance mode for now (we're going to fix critical bugs and compatibility issues).
