### ISSUE TITLE
Merge IM, VoIP & teamchat into communication tools (was: Why do we have a VoIP section?)

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1078]
See https://github.com/privacytoolsIO/privacytools.io/issues/1078#issuecomment-518203744. Original text below the line.

* * * * *

I didn't realize it exists (or at least I didn't look at it) until it was mentioned at #1067. https://www.privacytools.io/software/voip/

It lists:

* Mobile: Signal
* Wire
* Linphone
* Jitsi [Meet]
   * it fails to say [Meet]
* Tox
* Jami

The only different apps from instant messengers are: Linphone, Jitsi [Meet], Tox and Jami. Why are Signal and Wire on both pages? Why does Wire have different warning on both of them? (I think the warning text differed before I PRed the current text to instant messengers.)

Why Linphone, Tox and Jami aren't considered as instant messengers, but are instead VoIP apps? I have used all three and they all include chat functionality (and so does Jitsi [Meet] except that with it you are in call all the time, which used as a definition of VoIP app would make only it and Mumble the only real VoIP apps, maybe Spreed also (I don't remember)).

Suggestions:

* merge VoIP and Instant-messengers pages
* remove instant-messengers from VoIP and begin VoIP by saying that many instant messengers have VoIP capabilities (and say that clearly in instant-messengers if that is not the case)

I think the existence of a separate VoIP page with duplicate software results VoIP being less maintained and causing inconsistency (like already happened with Wire).

**Comment by nitrohorse** [comment]
> I think the existence of a separate VoIP page with duplicate software results VoIP being less maintained and causing inconsistency (like already happened with Wire).

Yeah, good call out; I agree. I think we should merge the VoIP page into the IM page.

**Comment by Mikaela** [comment]
Comments from #1067:

@JonahAragon :

> Thinking about @five-c-d's #999 (comment), would it perhaps make more sense to list Team Chat as a separate section on the existing Instant Messengers page? Or merge IM, VoIP, and this category into one "Communication Tools" page (or something) with separate subheadings for each of them?

@nitrohorse : 

> @JonahAragon I can see having sub-sections under a "Communication Tools" umbrella page being overall more helpful and easier to navigate and compare/contrast. I like that idea.

me: 

> Sounds good to me, that page would just be {% include sections/teamchat.html %} for the separate categories?

additional thinking: 

Do we have `jekyll_redirect` for redirecting the old pages to the new one?

**Comment by JonahAragon** [comment]
> Do we have `jekyll_redirect` for redirecting the old pages to the new one?

We can add 301 redirects in the nginx server config separately, which would probably be preferable to HTML meta redirects.

**Comment by five-c-d** [comment]
"Communication tools" is vague, it would include things like email, firefoxSend, bitMessage, and so on.  This new combo-section should be called "messengers" methinks.  

They are intended to be replacements for FbMessenger, iMessages, gMessages, etc.  Skype is a proprietary product that defined the category; IRC, and to some degree Zephyr and AIM and ICQ and MSN, were the precursors.  SMS for texting, MMS for photos&groupchats, and PSTN/GSM for voice-calls and voice-mail / voiceNotes, are the telecom industry competition.  

The key distinction -- as with tutanota and protonmail versus market leader gmail -- is that all the messengers in the privacyToolsIO listings are **private** messengers, which offer end2end crypto (not mere client-to-server crypto) which is on by default, have various degrees of metadata-resistance, have code which is audited for security, and in general are useful tools in fighting mass surveillance... whereas by contrast SMS and gmail actually *facilitate* surveillance.

**Comment by Mikaela** [comment]
How about *real time communication*?

**Comment by five-c-d** [comment]
That is more precise than "communication tools" but has the downside it is not really correct; the big advantage of Signalapp / Proteus / OMEMO / MegOlm / etc compared to the OffTheRecord protocol of yesteryear, is they are async.  If you want a two-way chat, both parties no longer *must* be online simultaneously, in 2013+ or thereabouts 

This async nature of modern protocols has a critical advantage when it comes to groupchats:  with 9-member groupchats OTR is very difficult, and with 99-member groupchat nigh-impossible.  There are still apps around which are non-async, such as Briar, but most software takes advantage of a combination of realtime (webrtc-cryptocalls) **and** async (teamchats with voiceNotes and other file-attachments can work for very large teamsizes).  

Wikipedia calls the category "[advanced IM](https://en.wikipedia.org/wiki/Instant_messaging)"  -- featuring 'texting, files, link preview, VoIP, video chat' -- when on laptops, and calls it "[messaging apps](https://en.wikipedia.org/wiki/Messaging_apps)" when smartphone-based -- featuring 'chat, groupchat, files, voice call, video call'.  However, in addition to nigh-identical feature-lists, they also list the same software as category-examples for both:  FbWhatsApp/FbMsgr, WeChat/QQ, Skype, iMessage/FaceTime, Viber, Snapchat, Line, Telegram, Discord, Slack. Amusingly, there is an [ongoing edit-war](https://en.wikipedia.org/wiki/Talk:Instant_messaging#Requested_move_13_March_2018) to combine the two articles :-)   Both wikipedia terms make a half-hearted attempt to split out 'Enterprise IM' and 'Workplace Groupchat' software, but only half-hearted.

**Comment by dngray** [comment]
This would close https://github.com/privacytoolsIO/privacytools.io/issues/746

**Comment by Mikaela** [comment]
What do you think of #1136 which you can see in action at https://deploy-preview-1136--privacytools-io.netlify.com/software/real-time-communication/ ?

Comments there, please.
