### ISSUE TITLE
✨ Feature Suggestion | PTIO Updater

### ISSUE THREAD

**Issue by GrimPixel** [privacytoolsIO/privacytools.io#1080]
## Description:

It is tedious to visit every site and check if there are updates. What about developing a software for updating them automatically?

**Comment by Mikaela** [comment]
I think you are looking for a RSS feed reader and https://github.com/privacytoolsIO/privacytools.io/commits.atom ?

**Comment by GrimPixel** [comment]
I mean something like an app store that can detect installed programs and update them. This program provides a list of the programs mentioned on PTIO and let users select whose update they want to keep an eye on.

**Comment by GrimPixel** [comment]
It should be able to detect the programs' version and compare it with the version provided by the user.

**Comment by blacklight447-ptio** [comment]
Creating and maintaining a program like this is outside of the scope of ptio.

**Comment by GrimPixel** [comment]
There are a lot of programs. People may be discouraged from keeping their programs updated. I guess fighting the inconvenience of update can also a part of promoting privacy.

**Comment by GrimPixel** [comment]
*can also be a part of promoting privacy.

**Comment by nitrohorse** [comment]
I think you can achieve what you’re looking for by a mix of using a [package manager](https://en.m.wikipedia.org/wiki/List_of_software_package_management_systems) and an RSS feed reader for apps that are available by other means.
