### ISSUE TITLE
❌ Software Removal | Subgraph OS

### ISSUE THREAD

**Issue by nitrohorse** [privacytoolsIO/privacytools.io#1088]
## Description

Should Subgraph OS be removed from the [OS "Worth Mentioning" section](https://www.privacytools.io/operating-systems/#os)? The only release I could find is the alpha version from [2017](https://subgraph.com/blog/subgraph-sep2017-iso-availability/) but their website doesn't even list a [download](https://subgraph.com/sgos/download/index.en.html) anymore.

Also looks like Subgraph's Twitter feed has this [pinned tweet](https://twitter.com/bleidl/status/969705077471678470):

> We're working on the future of Subgraph OS. Citadel, available soon in early release, is where we start.

So maybe we could update Subgraph and its description to point to "Citadel"?

**Comment by JonahAragon** [comment]
Yes, I would remove it 👍
