### ISSUE TITLE
Document the criteria for DNS servers

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1109]
See https://github.com/privacytoolsIO/privacytools.io/issues/1077#issuecomment-518686581 and follow the links.

I think this issue will become issue after the PR on DNS table is merged. I don't know where to document it though, `.github/` some template?

I will clear this comment on a PC later

_Sent from my Nokia 1 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

* * * * * 

https://github.com/privacytoolsIO/privacytools.io/pull/1097#issuecomment-518189915 / https://github.com/privacytoolsIO/privacytools.io/issues/1077#issuecomment-518694256

* supports at least DoT or DoH (DNSCrypt has public resolvers list and sources, and would be just a nice bonus, but I wouldn't demand it)
     * todo: add links to this issue, consider with the ready PR
* no logs or at least no PII (check AppliedPrivacy/Quad9 for wording?)
* should (not mandatory) support DNSSEC
* should (not mandatory) support qname minimization

**Comment by Mikaela** [comment]
I think I will be able to take a look at this tomorrow taking from https://github.com/privacytoolsIO/privacytools.io/tree/master/.github/ISSUE_TEMPLATE

**Comment by nitrohorse** [comment]
This is good, thanks for capturing this @Mikaela :+1:
