### ISSUE TITLE
🆕 Software Suggestion | CryptPad | Category: Paste

### ISSUE THREAD

**Issue by kryptish** [privacytoolsIO/privacytools.io#1116]
## Description

CryptPad is an open source, zero knowledge, realtime collaborative editor. Data is encrypted/decrypted in the browser. CryptPad is based upon two open-source cryptography libraries: tweetnacl.js and scrypt-async.js.

Scrypt is used to turn your username and password into a unique keyring which secures access to (a registered users) CryptDrive such that only you can access your list of pads. CryptPad can also be used without registering an account.

**xsalsa20-poly1305** and **x25519-xsalsa20-poly1305** cyphers provided by tweetnacl are used to encrypt pads and chat history.

FAQ about privacy: https://cryptpad.fr/faq.html#privacy-me

## Basic Information

**Name:** CryptPad
**Category:** [#paste](https://www.privacytools.io/classic/#paste)
**URL:** https://cryptpad.fr/pad/
**License:** [GNU Affero General Public License v3.0](https://github.com/xwiki-labs/cryptpad/blob/master/LICENSE)
**Git/Source Code:** https://github.com/xwiki-labs/cryptpad

PR: #1115

**Comment by nitrohorse** [comment]
Just realized we already recommend CryptPad in the Productivity Tools section (https://www.privacytools.io/software/productivity/#productivity); makes sense that we'd include their paste service too.
