### ISSUE TITLE
✨ Feature Suggestion | memes.privacytools.io

### ISSUE THREAD

**Issue by jkhgvfgvsth** [privacytoolsIO/privacytools.io#1118]
**Short Description**: memes.privacytools.io

**What?**: Pretty straight forward, a privacy meme explorer and sharing tool.

**But why?**: We seem to look like the tin foil hat people:
![image](https://pics.me.me/tinfoil-hats-check-now-we-must-make-the-facebook-privacy-5101739.png)

But, if we join in, we are the cool kids!

![image](http://static4.businessinsider.com/image/5506af83dd089588628b4567-1200-924/snowden-9.jpg)

Plus, it is an awesome way to educate people!
Lets see Dwight give us an example:

![image](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.DxvlaQKCFWhP1U4QlAhyEwHaFG%26pid%3DApi&f=1)

You could see this showing up on your timeline, right?
People would read this!

**What the point!** We need to show up where people already are!

**How?**: I believe Postmill is freesoftware!

**How can I help?**: Share the memes below? (idk)
[Postmill](https://www.wikipedia.org/wiki/Postmill_(software)) works great, although there are many alternatives.

**Comment by blacklight447-ptio** [comment]
Tbh, it seems a bit out of scope, you can use our forum to post privacy related memes though.

**Comment by erciccione** [comment]
I really cannot see any reason to have a space dedicated to memes on PrivacyTools. They are not helpful in any way and they make the project look not serious.

**Comment by blacklight447-ptio** [comment]
After some further discussion, it was decided that this is a bit to out of scope for PTIO, you are however free to post privacy related memes on our forum :). closing issue.
