### ISSUE TITLE
Firefox OS is discontinued, please remove it from recommendations

### ISSUE THREAD

**Issue by tengwar** [privacytoolsIO/privacytools.io#113]
https://duckduckgo.com/?q=firefox+os+discontinued

**Comment by bakku** [comment]
I agree. Maybe the Sailfish operating system can be added instead?

**Comment by privacytoolsIO** [comment]
Another user on reddit wrote this: 

"Firefox OS development has been discontinued and it should be removed. Perhaps we should recommend CopperheadOS instead?" [Source](https://www.reddit.com/r/privacytoolsIO/comments/5aoxki/suggestions_for_several_changes_in/)

I haven't tried Sailfish or CopperheadOS.

**Comment by kewde** [comment]
I have tried CopperheadOS and it was quite a tough experience getting it to run on my mobile phone.
It also only support a few devices, I believe about 3 devices? It does however deserve a spot as it is the best android fork security wise.

Sailfish OS is not an Android fork and is less commonly used and has not had such a wide exposure to security review, something which Android has been subject to over the years.

**Comment by bakku** [comment]
@kewde about security you are definitely right. Sailfish OS has not gained a big user base therefore the probability of security flaws is higher.

I was wondering about the privacy of Sailfish OS since it being open source and being developed outside of the US, maybe it might a candidate for a "Worth Mentioning"

**Comment by privacytoolsIO** [comment]
I've added Sailfish OS for now. Please let me know if something better comes around.
