### ISSUE TITLE
❌ Software Removal | Consider remove VPN.ht from VPN section

### ISSUE THREAD

**Issue by merlinnusr** [privacytoolsIO/privacytools.io#1131]
## Description

1. vpn.ht offers weak encryption like 64 bit blowfish and 128 bit AES
![image](https://user-images.githubusercontent.com/14082302/62824559-9b1d7200-bb65-11e9-89fd-c19258bc397e.png)

2. vpn.ht offers outdated vpn client for Windows https://github.com/VPNht/desktop/ with a lot of vulnerable and outdated  packages in package.json

[List of vulnerabilities 
](https://bin.privacytools.io/?9236650a4d4e3c0c#HRXrCbigv96ddHYmlCS/TeqXJYOzz29A1dP6nuTVD/g=)

3. It's a scam ( it offers vpn in 24 different countries but only 11 vpn nodes really works)

4. vpn.ht offers a proxy but that service doesn't exist
![image](https://user-images.githubusercontent.com/14082302/62824626-6958db00-bb66-11e9-86a5-99442f96c0f7.png)

5. vpn.ht offers deprecated vpn protocols like PPTP
![image](https://user-images.githubusercontent.com/14082302/62824643-c0f74680-bb66-11e9-94d5-44cbf0f56718.png)

6. .ovpn files has deprecated sentences 
![image](https://user-images.githubusercontent.com/14082302/62824659-0d428680-bb67-11e9-94ba-888f00f4c13e.png)

I would recommend the administrators of privacytools.io to try the services they offer before recommending them at privacytools.io

**Comment by blacklight447-ptio** [comment]
Thank you for bringing this to our attention, I will look into this tonight

**Comment by JonahAragon** [comment]
> I would recommend the administrators of privacytools.io to try the services they offer before recommending them at privacytools.io

Lol. Yeah I don’t actually know when some of these providers were added or who added them. Wasn’t around for the early days of PTIO. 

Since we’re putting this renewed focus on the site we should probably just delist every provider and re-research solutions for each category.

**Comment by blacklight447-ptio** [comment]
> > I would recommend the administrators of privacytools.io to try the services they offer before recommending them at privacytools.io
> 
> Lol. Yeah I don’t actually know when some of these providers were added or who added them. Wasn’t around for the early days of PTIO.
> 
> Since we’re putting this renewed focus on the site we should probably just delist every provider and re-research solutions for each category.

i would agree with this
