### ISSUE TITLE
🌐 Software Suggestion | Umbrella

### ISSUE THREAD

**Issue by Superbug50** [privacytoolsIO/privacytools.io#1132]
## Description
_"Umbrella is an Android app that provides all the advice needed to operate safely in a hostile environment."_
it also has an ios app so i suggest an edit? _"Umbrella is an Android and ios app that provides all the advice needed to operate safely in a hostile environment"_

![image](https://user-images.githubusercontent.com/25424568/62826375-41ba4080-bb6f-11e9-8204-c119d80e9d82.png)
https://secfirst.org/ has an ios,android,f-droid app etc...
![image](https://user-images.githubusercontent.com/25424568/62826471-f7d25a00-bb70-11e9-9f05-87412cc9ab7c.png)

**Comment by ggg27** [comment]
It actually isn't on [F-Droid](https://search.f-droid.org/?q=Umbrella&lang=en).

https://github.com/securityfirst/Umbrella_android/issues/235

**Comment by Mikaela** [comment]
There seems to be a confusion between F-Droid (app) and F-Droid (repository) and going to [secfirst.org](https://secfirst.org/) there is a link to a [F-Droid compatible repo](https://secfirst.org/fdroid/repo/?fingerprint=39EB57052F8D684514176819D1645F6A0A7BD943DBC31AB101949006AC0BC228) that can be added to the app.

I can understand the desire of having app in the official F-Droid repository as it helps with discoverability and is a confirmation that the app fulfils their recommendations, but I think decentralization is also worth thinking about and that it's not desirable for everything to be centralized only on the official F-Droid repo.

I think I am opening an issue about this.

**Comment by blacklight447-ptio** [comment]
I don't think we should list it, as our scope is normally to list tools, and whether this is a tool is most likely debatable.
