### ISSUE TITLE
Real-Time Communication ideas

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1137]
Especially after the three pages are merged, I think these could be done

* [x] Remove duplicate Signal & Wire (which also fixes Wire VoIP warning being wrong)
* [x] Move Tox and Jami to instant messengers
* [x] Change Jitsi to Jitsi Meet
* [x] Consider listing Mumble? (I originally mentioned it in https://github.com/privacytoolsIO/privacytools.io/issues/1078)
    * I also mentioned Spreed there, but I fail at finding my information about it.

* * * * * 

## Basic Information

**Name:** Mumble
**Category:** VoIP
**URL:** https://mumble.info/

## Description

> Mumble is an open source, low-latency, high quality voice chat software primarily intended for use while gaming.

I haven't used Mumble in gaming, but as a general VoIP chat. It doesn't currently have E2EE https://github.com/mumble-voip/mumble/issues/1813 but the server (especially when selfhosting) doesn't store chat logs or audio recordings by itself, [it can be used together with Tor](https://trac.torproject.org/projects/tor/wiki/doc/TorifyHOWTO/Mumble) and [the server can be configured to not log real IPv4 addresses](https://wiki.mumble.info/wiki/Murmur.ini#obfuscate). *There are  caveats though, so please check the links.*

PS. Sorry for merging four issues, I hope I can be forgiven in this case.

**Comment by nitrohorse** [comment]
> Remove duplicate Signal & Wire (which also fixes Wire VoIP warning being wrong)
> Move Tox and Jami to instant messengers

Since both sets fit in both IM and VoiMessengersce/Video sections, I'm wondering if we should merge the IM and Voice/Video sections?

**Comment by Mikaela** [comment]
We list some IM apps that don't support VoIP and at least Jitsi Meet which has pernanent call and thus I wouldn't count it as IM, so I think they can be useful separate

Mumble has inbuild server explorer where selfhosters can advertise their servers by setting certain options in murmur.ini (if I have understood correctly), but personally I have only been using selfhosted instances by organisations, friends, partners and myself
