### ISSUE TITLE
🌐 Website Issue |  Qubes OS Onion Repo is outdated

### ISSUE THREAD

**Issue by TNTBOMBOM** [privacytoolsIO/privacytools.io#1142]
## Description

In this link:
https://www.privacytools.io/operating-systems/#os

Referring to Qubes onion website to: (which doesnt work)

http://qubesos4rrrrz6n4.onion

But this is the old one , please switch to: 

http://qubesosfasa4zl44o4tws22di6kepyzfeqv3tg4e3ztknltfxqrymdad.onion/ 

Ref: https://www.qubes-os.org/news/2019/04/17/tor-onion-services-available-again/

Note: im not sure if website issue is the fitting category for this type of issue.

**Comment by nitrohorse** [comment]
Thanks @TNTBOMBOM :+1: will fix this.
