### ISSUE TITLE
🌐 Website Issue | Update Whonix OS Question Mark

### ISSUE THREAD

**Issue by TNTBOMBOM** [privacytoolsIO/privacytools.io#1144]
## Description

In this page
https://www.privacytools.io/operating-systems/#os
Section Worth Mentioning: 

It says that "Whonix software may depend on or recommend non-free software" 

Whonix doesnt depend on any proprietary/non-free software , other words it doesnt ship any of these types of software. 

Ref: 

https://www.whonix.org/wiki/Why_Whonix_is_Freedom_Software

**Comment by TNTBOMBOM** [comment]
also it has onion entry to the website: (will be good to add)

http://www.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion/

**Comment by JonahAragon** [comment]
This was fixed in #1148.
