### ISSUE TITLE
Finding three good Evernote Alternatives

### ISSUE THREAD

**Issue by privacytoolsIO** [privacytoolsIO/privacytools.io#119]
Good starting point: http://alternativeto.net/software/evernote/?license=opensource

Criteria: 

- Open Source
- Cross-platform
- Easy to use
- Privacy respecting

There can be exeptions if no software is available that meet the criteria.

Edit: My current favorites are: Turtl, Simplenote and Laverna. Not sure about the order yet.

What do you guys suggest?

**Comment by iancnorden** [comment]
Paperwork may be one to check out, though potentially lacking cross platform support.

https://github.com/twostairs/paperwork

**Comment by privacytoolsIO** [comment]
We could add Paperwork under "worth mentioning".

**Comment by different55** [comment]
How about [Turtl](https://turtlapp.com/)?

**Comment by iampox** [comment]
I just use Simplenote since the company behind it open sourced the different desktop and mobile apps.
