### ISSUE TITLE
🆕 Software Suggestion | Trisquel

### ISSUE THREAD

**Issue by ggg27** [privacytoolsIO/privacytools.io#1198]
## Basic Information

**Name:** Trisquel
**Category:** Operating Systems
**URL:** https://trisquel.info/

## Description

Trisquel is an easy to use operating system focusing on software freedoms like privacy.

## Additional

This issue is to add Trisquel to `worth mentioning`.

**Note**: As the team seems to have made it clear freedom is not a concern to them, I would like to discuss Trisquel being listed for users who do care about free/libre software.

**Comment by JonahAragon** [comment]
Trisquel is a listed operating system already. If you can’t find it, it’s right under Arch Linux :)

**Comment by Mikaela** [comment]
Yes, it seems to be listed on https://www.privacytools.io/operating-systems/#os

It was "downgraded" to worth-mentioning in https://github.com/privacytoolsIO/privacytools.io/pull/1156
