### ISSUE TITLE
🗄️ DNS provider suggestion | Snopyta DNS

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1207]
## Basic Information

**Name:** Snopyta
**Filtering:** no
**Privacy policy:** https://snopyta.org/privacy_policy (doesn't mention DNS / IP logging?)
**Protocols:** DoT (853), DoH
**Server/Location:** Finland
**Source:** -
**Type:**  Informal collective
**Website:** https://snopyta.org/service/dns/index.html

## Description

I find their DNS server being in Finland interesting (as the other DNS providers I am aware of are Cloudflare and Quad9 anycast) and they are part of Librehosters (#816) where they were requested to be listed earlier.

I am hoping @Perflyst (please tell me my name memory works and you are the Snopyta admin) can fill us in on the features and list them on the website assuming they are supported.

### Required features:

* [x] supports DoH or DoT 
* [x] supports DNSSEC 
* [x] doesn't log IP addresses during normal operation 

#### Desired features

* [x] supports QNAME minimization

**Comment by Perflyst** [comment]
DNSSEC is supported and of course I do not log anything (expect needed for debugging).
QNAME minimization is enabled.

Please do **not** add the service yet to your website. I want to add it to the privacy policy first and change some setup things in the background.

**Comment by Perflyst** [comment]
Added it to the privacy policy: https://git.snopyta.org/snopyta/snopyta.org/commit/210a3cc8ccd31ba974fefa4e19685b3ce48b7d5d

If this policy is okay for privacytools, feel free to add the it to your website now.
