### ISSUE TITLE
🆕 Software Suggestion | Request Control Firefox Addon

### ISSUE THREAD

**Issue by chiraag-nataraj** [privacytoolsIO/privacytools.io#1211]
## Basic Information

**Name:** Request Control
**Category:** Firefox Addon
**URL:** https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/

## Description
An addon like this one (there are a couple others as well) allows blocking of various classes of resources per host or globally. This is useful in cases where e.g. uMatrix groups them all under 'other' but Request Control has more fine-grained categories.

**Comment by blacklight447-ptio** [comment]
im not sure wheter we should list a third script blocker to the list, does in bring anything else to the table further more fine grained control.
