### ISSUE TITLE
add link for spanish translation

### ISSUE THREAD

**Issue by victorhck** [privacytoolsIO/privacytools.io#122]
Since I knew this great resource I tried to spread about it.
So I create a spanish translated version that I tried to mantain updated (last commits in the english version are not still done in spanish version :) )

Make sense add a link to the page I have translated and mantain hosted in GitLab?
- https://victorhck.gitlab.io/privacytools-es/

Thanks for this great resource!

PS: translation is done for non profit, of course! so links to bitcoins, etc  points to the original links.

**Comment by privacytoolsIO** [comment]
hi victor!

amazing work. thank you so much. I didn't hesitate and linked your spanish version and also a german version in the header area. you can do the same if you want in your version.

please let me know what you think about the integration.

**Comment by victorhck** [comment]
It's ok for me your link in header! :-)

Thanks, I wrote about your project in my blog when I published the first version. And from time to time I spread the word in (free) social media where I'm registered (GNUsocial and Diaspora*) about this!

This days commits are on fire! so I have a lot of work pending!! I'll try to do it ASAP.

Keep on rockin' in the free world and happy hacking !!

**Comment by jony0008** [comment]
@privacytoolsIO Why don't you use Transifex or some other translation platform for translation into more languages?

**Comment by Shifterovich** [comment]
@jony0008 Good point, but side-note: add flag buttons, don't use HTTP-header-locale-detection. Some privacy conscious people (like me) use a forged `en-US` locale.

**Comment by jony0008** [comment]
@Shifterovich What are you talking about?

**Comment by Shifterovich** [comment]
@jony0008 I answered quickly and didn't look up what Transifex is, I though it's a *localisation* platform, but it's specifically **only** a *translation* platform. I meant that all translations could be on the main domain, letting people choose a language manually. Most websites use auto-locale detection via HTTP headers, which won't work for some privacy conscious people.

**Comment by jony0008** [comment]
@Shifterovich Ah, now I understand why you were concerned.
