### ISSUE TITLE
🆕 Software Suggestion | Tresorit Send

### ISSUE THREAD

**Issue by alien2003** [privacytoolsIO/privacytools.io#1227]
## Basic Information

**Name:** Tresorit Send
**Category:** File Sharing
**URL:** https://send.tresorit.com/

## Description

Tresorit Send is good Firefox Send alternative. Not opensource, but E2EE and pretty trusted

**Comment by blacklight447-ptio** [comment]
im also a bit wary about the fact that its closed source, we cannot know if the crypto is backdoored. normally being opensource is big preference instead of an requirement, but for a product like this where the encryption is its distinctive feature, its quite an issue.

**Comment by dawidpotocki** [comment]
I don't see need for it.
We already list Firefox Send, which is free software and
I don't see why this would be better than it.

**Comment by blacklight447-ptio** [comment]
Do we agree on closure then? Or maybe @alien2003 has more arguments.

**Comment by Mikaela** [comment]
Argument against: there is equivalent open source software called LuFi and judging by the config file there is no upload limit unless such specified by instance admin or web server.

* https://framagit.org/fiat-tux/hat-softwares/lufi
