### ISSUE TITLE
Replace Disconnect Search with Qwant?

### ISSUE THREAD

**Issue by privacytoolsIO** [privacytoolsIO/privacytools.io#123]
Just found out about Qwant:

- https://www.qwant.com/privacy
- https://www.qwant.com/about
- Based in France

Should we replace it with Disconnect?

**Comment by g-monk** [comment]
The only issue that I have is this with where it says in the privacy policy, "However, judicial or administrative authorities may require the disclosure of data allowing the identification of a user. The Privacy Service and the DPO undertake to examine them carefully and to refuse any improper disclosure of data." What this means for me is that if a user has to be identified by the authorities, he/she can be, while some information related to him/her can be thrown away.

Again my interpretation might be wrong, but someone please explain me this part of the privacy policy.
