### ISSUE TITLE
🆕 Software Suggestion | LuFi (Let's upload that file)

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1233]
## Basic Information

**Name:** LuFi
**Category:** File sharing
**URL:** https://framagit.org/fiat-tux/hat-softwares/lufi

## Description

A simple open source filesharing service with e2ee working directly in the browser without the need of installing anything.

I closed https://github.com/privacytoolsIO/privacytools.io/issues/1227 in favour of it, so I guess we should talk about listing it.

Demo instance: https://demo.lufi.io/

Production instances:

* https://framadrop.org/
* https://upload.disroot.org/

**Comment by Mikaela** [comment]
I am missing discussion about this with #1684 / #1686 .

**Comment by lrq3000** [comment]
@Mikaela Thanks for the ping, I forgot about that tool, it's a nice alternative to Firefox Send because there is apparently no limit of size (but then files > 500MB are kept only 24h). However, they also [log IP addresses, and they do not specify how long](https://framasoft.org/fr/cgu/).

**Comment by lrq3000** [comment]
The relevant part (in french):

> * Tout comme d’autres services en ligne, Framasoft enregistre automatiquement certaines informations concernant votre utilisation du service telles que l’activité du compte (exemple : espace de stockage occupé, nombre d’entrées, mesures prises), les données affichées ou cliquées (exemple : liens, éléments de l’interface utilisateur), et d’autres informations pour vous identifier **(exemple : type de navigateur, adresse IP, date et heure de l’accès, URL de référence)**.
> * Nous utilisons ces informations en interne pour vous améliorer l’interface utilisateur des services Framasoft et maintenir une expérience utilisateur cohérente et fiable.
> * Ces données ne sont ni vendues, ni transmises à des tiers.

**Comment by lrq3000** [comment]
I have tested and can confirm it's possible to upload arbitrary sized files (there is probably a technical limit somewhere but it's not specified and I could upload/download 2GB without registration). I think it's worth mentioning on PTIO.

**Comment by Mikaela** [comment]
I am not sure, but I think IP address storage depends on instance and the file size is defined by an instance also, I have a faint idea of once having gone through exaple config file.

**Comment by lrq3000** [comment]
Yes of course but that's why in my PR i made the entry about FramaDrop, the
official instance of LuFi (same devs, git repo hosted on framasoft), just
like PRIO already links to firefox sync instance and not just the code
repository to self host, i guess for user convenience (because else what
advantage over onionshare if you need to self host? ;-) ).
