### ISSUE TITLE
Simplenote does not support client-side encryption

### ISSUE THREAD

**Issue by echo743** [privacytoolsIO/privacytools.io#124]
I think we should either remove Simplenote from [the new Digital Notebook section](https://www.privacytools.io/#notebook) or add a warning that it [does not support client-side encryption](https://simplenote.com/help/#encryption). I think it is misleading to recommend Simplenote as a private alternative to Evernote, Google Keep or Microsoft OneNote, because the notes are not encrypted before they are synced to the service provider's servers. In order for it to be more private than the three aforementioned apps, a note-taking app that relies on servers for syncing needs to have client-side encryption on by default, [like in Turtl](https://turtlapp.com/docs/security/).

**Comment by privacytoolsIO** [comment]
I've made Simplenote 3rd choice and added the warning. Thanks for your feedback.
