### ISSUE TITLE
✨ Feature Suggestion | Specify distributions through icons

### ISSUE THREAD

**Issue by GrimPixel** [privacytoolsIO/privacytools.io#1249]
## Description:

There are icons indicating which platforms a service supports, but for Linux and BSD, if the distributions are not explained, it would be less helpful.

**Comment by dawidpotocki** [comment]
> There are icons indicating which platforms a service supports, but for Linux and BSD, if the distributions are not explained, it would be less helpful.

So you want icons that show distributions? That's… stupid. Most stuff
will work on every, they are not that different. Also there is crap ton
of distributions, if we will not list every of them, some will assume
that they don't work on theirs.

Though we should seperate FreeBSD, OpenBSD and NetBSD, I think.
FreeBSD and NetBSD were forked from BSD (which was based on Research
Unix) in 1993. OpenBSD was forked from NetBSD on 1995. They are not
"distributions", but more like independent operating systems.

**Comment by GrimPixel** [comment]
OK, I didn't know that they can run on every distribution, I just knew that not all of them are ready-made to be available for non-programmers.

**Comment by Mikaela** [comment]
I wonder if listing [Flatpak](https://flatpak.org) and [Snap](https://snapcraft.io/) support would make more sense, but they aren't distributions and many don't officially support them and I think it might be going a bit out of scope.

There is also a website that lists which version of a package is available in all Linux distributions it knows of, but I cannot remember the name or find it.

**Comment by dawidpotocki** [comment]
> I wonder if listing [Flatpak](https://flatpak.org) and [Snap](https://snapcraft.io/) support would make more sense, but they aren't distributions and many don't officially support them and I think it might be going a bit out of scope.

Nah. I don't think we should list them.

> There is also a website that lists which version of a package is available in all Linux distributions it knows of, but I cannot remember the name or find it.

https://repology.org

**Comment by Mikaela** [comment]
I guess we could close this then
