### ISSUE TITLE
🌐 Website Issue | Change the Apple icons

### ISSUE THREAD

**Issue by GrimPixel** [privacytoolsIO/privacytools.io#1250]
## Description

The Apple icon together with the Apple Store icon are ambiguous: do they stand for macOS or iOS?

I think both should be replaced with proper ones:

https://img.icons8.com/ios-filled/2x/mac-logo.png
https://img.icons8.com/ios-filled/2x/ios-logo.png

**Comment by Mikaela** [comment]
I cannot open your links for some reason, they open an empty page.

I think the icons come from https://fontawesome.com/icons?d=gallery&m=free and are specified in the card files, can you find any icons there that are more descriptive?

**Comment by GrimPixel** [comment]
OK, they are black icons with transparency. If the background of your browser is black, you can't see anything.
Give me a moment to find other icons.

**Comment by GrimPixel** [comment]
Nowhere else has icons suitable like icons8. You can search for black-white icons for mac and ios.
https://icons8.com/

**Comment by Mikaela** [comment]
I am not sure if changing the icon set would be a good idea.

@privacytoolsIO/editorial Thoughts?

**Comment by nitrohorse** [comment]
> The Apple icon together with the Apple Store icon are ambiguous: do they stand for macOS or iOS?

Yeah, I agree that it’s a bit difficult to tell at first which platform the icons target. But I don’t know if we can/want to use images for icons currently.

**Comment by GrimPixel** [comment]
If combined with dawidpotocki's suggestion on BSD, icons will be required.

https://github.com/privacytoolsIO/privacytools.io/issues/1249

**Comment by JonahAragon** [comment]
We cannot use any icons other than FontAwesome icons.

**Comment by Shifterovich** [comment]
If the change is necessary, svg icons work too.

**Comment by blacklight447-ptio** [comment]
well Tor browser blocks SVG images, so we probably don't wanna do that.
