### ISSUE TITLE
✨ Feature Suggestion | Black List & Grey List

### ISSUE THREAD

**Issue by GrimPixel** [privacytoolsIO/privacytools.io#1264]
## Description:

Add a section about exposed privacy-violating open-source programs, such as Ubuntu in “Operating Systems”. If there is no such a section, people won't know if the program is violating privacy or simply neglected by PTIO.

Also, there can be a grey list about uncertain ones, such as integrating closed-source part in open-source program.

**Comment by blacklight447-ptio** [comment]
I personally don't feel comfortable with this idea. It seems to be really likely to cause unnecessary drama. first of all it will cost more resources and time to research things on the list and come up with proper arguments. secondly, if we get something wrong, it would harm our reputation.

**Comment by Mikaela** [comment]
I happened to think if there would be any sense in listing why we list the current ones, or what are they actively doing for privacy?

* QubesOS - the containers separating everything and you will have to look hard to have such privacy/security?
* Fedora - I don't know, other than it replaced Trisquel and is something from RHEL side of the Linux family and hopefully easier than Debian.
* Debian - provides most (if not all?) of their services through Tor having index at https://onion.debian.org/ (and http://5nca3wxl33tzlzj5.onion/)

Worth mentioning:

* OpenBSD - probably the BSD you think of when you think of BSD and security, source of many critical services such as OpenSSH
* Arch Linux - Keep It Simple Stupid, no additional tracking or anything unless you by yourself go and install it
* Whonix - separate from your usual system enforcing Tor without leaving atrace?
* Tails - the defacto standard for secure the amnestiastic incognito live system

The others I don't have enough of an idea to say anything upon.

I have already [bashed Ubuntu on our forum](https://forum.privacytools.io/t/least-favorite-gnu-linux-distribution/379/5?u=mikaela).
