### ISSUE TITLE
🌐 Website Issue |  Delete Cloudflare 1.1.1.1 source code repo link

### ISSUE THREAD

**Issue by theel0ja** [privacytoolsIO/privacytools.io#1265]
## Description

https://www.privacytools.io/providers/dns/#icanndns

https://github.com/cloudflare/dns is irrelevant to 1.1.1.1 resolver (the repo seems to be a library instead of a resolver), that's why I think the source code link should be removed.

**Comment by blacklight447-ptio** [comment]
@mikeala most likely your cup of tea.
