### ISSUE TITLE
🌐 Website Issue | mailbox.org no longer accepts BTC

### ISSUE THREAD

**Issue by nitrohorse** [privacytoolsIO/privacytools.io#1268]
## Description

From the Keybase chat group (privacytools_io) this was brought up:
> ...please update mailbox.org to pull out cryptocurrency as payment or `*` it with a note that their processor no longer operates out of .de so btc payments are disabled.

https://www.privacytools.io/providers/email/

**Comment by blacklight447-ptio** [comment]
So does it also no longer operate under German jurisdiction?

**Comment by blacklight447-ptio** [comment]
We will have to see if mailbox will stay listed at all, because the plans are to, after the browser page is done, to redo the mail provider page with new strict criteria, just like we did with the vpn provider page.

**Comment by nitrohorse** [comment]
> Note: At this point we cannot offer bitcoin payments anymore. These will be available again at a later point in time.

https://kb.mailbox.org/display/MBOKBEN/How+to+pay

**Comment by dngray** [comment]
> We will have to see if mailbox will stay listed at all, because the plans are to, after the browser page is done, to redo the mail provider page with new strict criteria, just like we did with the vpn provider page.

I will be working on this early next year, as I have given other providers an opportunity to met our criteria (all but one has promised).
