### ISSUE TITLE
Add sharing-opportunities for federated networks

### ISSUE THREAD

**Issue by FlxAlbroscheit** [privacytoolsIO/privacytools.io#127]
Just stumbled upon this service and felt a bit disappointed as there was no possibility to share privacytools.io to those social networks which originally were suggested within the paragraph _Decentralized Social Networks_.

E.g. for Diaspora there is https://sharetodiaspora.github.io/about/ which works just like usual share-buttons (having configurable title- and uri-params) and could therefore be added to the main-nav ("share") and footer ("spread the word") without any doubt. I even heard that this tool also works for Friendica-installations, but haven't yet tested that. If you confirm this issue, I'd just push the regarding lines.

**Comment by privacytoolsIO** [comment]
Confirmed. Do you know how to implement those links? I'd be happy to have them on the website.
