### ISSUE TITLE
🌐 Website Issue | Tahoe LAFS logo looks a bit bad with the dark theme

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1278]
## Description

Dark against dark.

* https://www.privacytools.io/software/cloud/#mycloud

## Screenshots

![Screenshot from 2019-09-07 13-57-31](https://user-images.githubusercontent.com/831184/64474069-a5885700-d177-11e9-96a0-0685982d8566.png)

**Comment by dawidpotocki** [comment]
Well we can replace it to light version with JavaScript.

**Comment by Mikaela** [comment]
Closing in favour of https://github.com/privacytoolsIO/privacytools.io/issues/1318.
