### ISSUE TITLE
A Warm Hello

### ISSUE THREAD

**Issue by g-monk** [privacytoolsIO/privacytools.io#128]
Hi everyone, I have been reading about your discussions and what not and I am getting to say that as someone who is interested in privacy and security, I am getting to learn a lot! I wanted to ask that if it was okay with me being able to do a derivative of this project and share the same license. My derivative though is going to be a little bit more broken down and easy to understand, as the goal is trying to get adolescents of today to be able to know about privacy. 

My main project is called [EducateLife101](https://sites.google.com/site/educatelife/home/platforms-of-educatelife101). I have many platforms all dedicated towards learning and yes you can download the official app for it also. 

Thanks,

G-Monk

**Comment by privacytoolsIO** [comment]
> I wanted to ask that if it was okay with me being able to do a derivative of this project and share the same license.

Yeah, sure. Go ahead and share the link with us once you have updates!

**Comment by g-monk** [comment]
Okay Thanks.

I wanted you to also checkout my main platforms, there are three that I work on strongly and I would love to get some feedback about the work I have done. 

They are: Computer App [Hub](https://sites.google.com/site/capphub/), Virtual [TechTrix](https://sites.google.com/site/virtualtechtrix/) and Mobile Media [Hub](https://sites.google.com/site/mobilemedhub/). I plan on adding the derivative to feature things that are easy to do for kids and merge all three hubs plus this one. However its not possible on Google Sites. Plus, I am not a programmer. I have yet to learn programming.

I am aware that some company featured things are scary such as the Google Suite I put together on Mobile Media Hub, but I plan to get some help in finding alternatives from the privacytools.io community. I also didn't get fully aware of all this privacy and mass surveillance until I read _No Place To Hide by Glenn Greenwald.

**Comment by Shifterovich** [comment]
You got an answer. Please use GitHub issues for software recommendations, or issues with the website. If you want to share your projects with our community, use our [subreddit](https://www.reddit.com/r/privacytoolsIO/).
