### ISSUE TITLE
❌ Software Removal | GNU Social

### ISSUE THREAD

**Issue by dawidpotocki** [privacytoolsIO/privacytools.io#1281]
More people are on ActivityPub platforms, while GNU Social uses older OStatus and from what I know it doesn't work with ActivityPub.
https://git.gnu.io/gnu/gnu-social/issues/256

**Comment by ggg27** [comment]
Erm, plenty of people use it. :/

**Comment by ggg27** [comment]
> Nobody uses it :P.

On that logic a lot of software should be removed.

___________

I think if more people knew what software like GNU Social and Diaspora exist then we would have more users. I always considered that the point of PTIO was to inform users of stuff like this.

**Comment by dawidpotocki** [comment]
Still, what does GNU Social do that other platforms don't?
More people are on ActivityPub platforms, while GNU Social uses older OStatus and from what I know it doesn't federate with ActivityPub.
https://git.gnu.io/gnu/gnu-social/issues/256
