### ISSUE TITLE
🆕 Software Suggestion | Pleroma

### ISSUE THREAD

**Issue by dawidpotocki** [privacytoolsIO/privacytools.io#1282]
## Basic Information

**Name:** Pleroma
**Category:** Social Networks
**URL:** https://pleroma.social/

What is Pleroma?: https://blog.soykaf.com/post/what-is-pleroma/

## Description
Pleroma is a free, federated social network, compatible with other ActivityPub and OStatus platforms. It is bundled with 2 frontends, PleromaFE and the one from Mastodon. Mastodon applications should work just fine with Pleroma also.

**Comment by ggg27** [comment]
Pleroma is awesome. Considering switching to it instead of Mastadon.

____________

Plus, (ok?) I2P support:
https://git.pleroma.social/pleroma/pleroma/wikis/I2P-Federation
