### ISSUE TITLE
🆕 Software Suggestion | Vikings Hosting 

### ISSUE THREAD

**Issue by RunOpenBSD885** [privacytoolsIO/privacytools.io#1293]
## Basic Information

**Name**: Vikings
**Category**: Enterprise Hosting
**URL**: https://vikings.net/
**Provider's Focus**: Free/Libre Hardware and Enterprise Level Hosting
**Hosting Signup**: Email Only [[Sep 2019](https://store.vikings.net/index.php?route=information/information&information_id=9)] 

## Description

Vikings is probably the only hosting provider to use Libreboot and gain mostly-widespread support in the free/libre software community. Much of their hardware is supported by the FSF:
https://www.fsf.org/resources/hw/endorsement/vikings

From a security and privacy standpoint I am unaware of any hardware manufacturer to come close to promoting free/libre and privacy respecting techniques except possibly [Raptor Computing Services](https://www.raptorcs.com/) which does not offer any hosting services as of Sep 2019:
https://www.fsf.org/blogs/licensing/interested-in-a-powerful-free-software-friendly-workstation

_____________________________________
__________________________________

### Where to put Vikings?

This thread originally came from the discussion to replace DataCell with Vikings.
- https://forum.privacytools.io/t/replace-datacell-with-vikings/1570

Unlike most of the other listed providers, Vikings is not yet accepting low-usage consumers.
However, they do sponsor many projects like [Peers](https://peers.community/).

**Comment by sakura974201** [comment]
vikings.net does not support IPv6. Not good

**Comment by Mikaela** [comment]
I am unable to find any details on their hosting or where I would get it. They also advertise their short keyid on the frontpage without mentioning the fingerprint which is a bad practice and they don't specify keyserver to use which may lead to a flooded certificate if SKS keyservers are used (and the key is not on keys.openpgp.org at time of writing).
