### ISSUE TITLE
🆕 Software Suggestion | CyberBunker | Hosting

### ISSUE THREAD

**Issue by ggg27** [privacytoolsIO/privacytools.io#1299]
## Basic Information

**Name:** CyberBunker
**Category:** Hosting
**URL:** https://www.cyberbunker.com/
**FLOSS + Anonymous Signup**: [Email Supported](https://archive.is/o/TPXBe/https://www.cyberbunker.com/web/faq-orders.php#)

## Description
CyberBunker is a popular bullet proof hostig provider and a competitor to Bahnhof.

**Comment by blacklight447-ptio** [comment]
I feel pretty turned off by them claiming they are "bulletproof" any hosting provider thinking that does clearly not know how the internet work, and is only giving users a false sense of security for marketing purposes.

**Comment by nitrohorse** [comment]
We’re talking about __this_ CyberBunker](https://arstechnica.com/information-technology/2019/09/german-police-seize-bulletproof-hosting-data-center-in-former-nato-bunker/)?

**Comment by Mikaela** [comment]
I believe we can close this, please feel free to request reopening if this is different business.
