### ISSUE TITLE
❌ Software Removal | Sparkleshare

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1309]
## Description

Potentially dead judging by a quick glance. It's listed as [top File Sync recommendation](https://privacytools.io/software/file-sync/#sync).

* https://github.com/hbons/SparkleShare/tags
* https://github.com/hbons/SparkleShare/pulse/monthly

**Comment by dawidpotocki** [comment]
> Potentially dead judging by a quick glance.

Last commit was May 25th and also it just can be "feature-complete" or
whatever. No need to change anything, if everything works as it should.

**Comment by Mikaela** [comment]
Do you use it? I haven't looked deeply in their issue tracker.

**Comment by blacklight447-ptio** [comment]
maybe we should just ask the project themselves for an update on the situation?
