### ISSUE TITLE
🌐 Website Issue | The VPN page doesn't mention encrypted DNS

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1314]
## Description

![Screenshot from 2019-09-15 11-24-14](https://user-images.githubusercontent.com/831184/64918749-5fe91100-d7ab-11e9-8366-9d4f5abe32f6.png)

I think the warning should also include recommending encrypting DNS as otherwise the network administrator or attacker in local network can manipulate DNS queries or even anyone between you and the DNS server can do that.

I don't know if this would require more explanation including that if you use a VPN, your DNS goes through the VPN and using both simultaneously would require trusting both providers. And if the user is using Tor, they should let Tor/exit-nodes perform DNS to not taint circuits or send all traffic through one circuit (even while Tor exit-node is comparable to untrusted/unsecured open network).

* https://www.privacytools.io/providers/dns/#icanndns

**Comment by blacklight447-ptio** [comment]
Im not sure about this one, the warning is already pretty long, if we make it any longer people my skip reading it at all.

**Comment by Mikaela** [comment]
I think encrypted DNS is an important base for https as the untrusted network could otherwise be sending users to wrong places and trigger certificate warnings.

**Comment by blacklight447-ptio** [comment]
Could you make a pull request to show how you would like it?

**Comment by Mikaela** [comment]
Sure, seems simple enough and I think HTTPS could become a link alongside it. I cannot give schedule promises though:
