### ISSUE TITLE
🆕 Software Suggestion | Opt-out.eu

### ISSUE THREAD

**Issue by yoavaviram** [privacytoolsIO/privacytools.io#1315]
## Basic Information

**Name: Out Out
**Category: Privacy services & Browser extension
**URL : https://opt-out.eu/

## Description

Opt Out is a free & open source service which helps individuals get organizations to erase their personal data by automating the process of sending GDPR erasure (right to be forgotten) requests.

Source code (website): https://github.com/opt-out-eu/opt-out
Source code (extensions): https://github.com/opt-out-eu/opt-out-web-extensions

**Comment by blacklight447-ptio** [comment]
hmm, I don't think this would be important enough to be linked at the extensions section, however for the people the live in the EU it might be nice to look at, made we can fill it into a worth mentioning somewhere?/

**Comment by yoavaviram** [comment]
@blacklight447-ptio In case it makes a difference we will soon be rolling out support for the California Consumer Protection Act. It be from a different domain though.

**Comment by Mikaela** [comment]
Closed in favour of https://github.com/privacytoolsIO/privacytools.io/issues/1585 ?
