### ISSUE TITLE
🌐 Website Issue | Dark theme issues

### ISSUE THREAD

**Issue by dawidpotocki** [privacytoolsIO/privacytools.io#1318]
These are the issues I noticed, if there are more, please reply to this issue.
I will try to fix all of these things in some free time.

#### White on Yellow button hover
![image](https://user-images.githubusercontent.com/38681822/64923144-b7e14100-d7c6-11e9-8608-2f43c2685b73.png)

#### Black GitHub logo
![image](https://user-images.githubusercontent.com/38681822/64923160-dd6e4a80-d7c6-11e9-9b6d-01a9b3aa0dae.png)

#### White border on kopimi logo
![image](https://user-images.githubusercontent.com/38681822/64923173-f37c0b00-d7c6-11e9-8387-97e2bf94bb6e.png)

#### White border on Privacy Badger logo
![image](https://user-images.githubusercontent.com/38681822/64923277-e9a6d780-d7c7-11e9-9827-0793ed09674f.png)

#### Not desaturated social media colors
![image](https://user-images.githubusercontent.com/38681822/64923204-30480200-d7c7-11e9-8919-aa439a897ba8.png)

#### Anchor color on warning badge
![image](https://user-images.githubusercontent.com/38681822/64923242-8ae15e00-d7c7-11e9-91a4-e8a74671e637.png)

#### Anchor color on banners
![image](https://user-images.githubusercontent.com/38681822/64923254-b106fe00-d7c7-11e9-9334-6c4613c896e5.png)
![image](https://user-images.githubusercontent.com/38681822/64923305-3ab6cb80-d7c8-11e9-8de4-7fcd752ead05.png)

#### VPN warning banner
![image](https://user-images.githubusercontent.com/38681822/64923299-283c9200-d7c8-11e9-81ea-f7e760ec618e.png)

**Comment by Mikaela** [comment]
https://github.com/privacytoolsIO/privacytools.io/issues/1278

![](https://user-images.githubusercontent.com/831184/64474069-a5885700-d177-11e9-96a0-0685982d8566.png)

**Comment by Strappazzon** [comment]
**Smile on the donations page**

![](https://user-images.githubusercontent.com/19752093/65068233-86b06e80-d988-11e9-8011-ab38a35671f0.png)

**VeraCrypt logo**

![](https://user-images.githubusercontent.com/19752093/65068385-dabb5300-d988-11e9-9d94-e49870925e00.png)

**Write.as logo**

![](https://user-images.githubusercontent.com/19752093/65068469-04747a00-d989-11e9-91ba-bef98615aa09.png)

**Onion Browser logo**

![](https://user-images.githubusercontent.com/19752093/65068543-27069300-d989-11e9-8411-a7e5efc6441e.png)

**Fingerprint**

![](https://user-images.githubusercontent.com/19752093/65068592-3c7bbd00-d989-11e9-8b23-0778220d10ba.png)

**Comment by blacklight447-ptio** [comment]
Can this issue be closed @dawidpotocki?

**Comment by dawidpotocki** [comment]
> Can this issue be closed @dawidpotocki?

PR is not merged, I'm waiting for Jonah. So, no.
