### ISSUE TITLE
Remove trust.zone

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#132]
According to https://thatoneprivacysite.net/vpn-comparison-chart/, trust.zone logs bandwidth, but privacytools.io says "All providers listed here are outside the US, use encryption, accept Bitcoin, support OpenVPN and have a no logging policy."

Should we remove trust.zone?

**Comment by privacytoolsIO** [comment]
Trust.Zone was actually recommend by our VPN expert TheOnePrivacyGuy. Because the logging doesn't involve traffic logs. We could add additional informating regarding Trust.Zone.

**Comment by Shifterovich** [comment]
TODO: `add additional informating regarding Trust.Zone.`
