### ISSUE TITLE
🆕 Software Suggestion | Manjaro 

### ISSUE THREAD

**Issue by Evernow** [privacytoolsIO/privacytools.io#1320]
## Basic Information

**Name:** Manjaro 
**Category:** Operating System
**URL:** https://manjaro.org/

## Description

A Linux distribution based off Arch. While they have made some mistakes like forgetting to renew their certificates, honest do happen, and I believe small incidents like that shouldn't discourage people from recommending and testing them out.

They have been positive towards providing sources for their packages, something even Arch does not completely do 

https://forum.manjaro.org/t/could-it-be-possible-to-provide-package-sources/103064/26

They do hold updates for 1-2 weeks, but important security updates for popular software do get pushed moments after release, sometimes even faster than Arch itself. https://forum.manjaro.org/tags/c/announcements/security

**Comment by Mikaela** [comment]
As far as I am aware, they ship with propietary office suite and Steam and aren't doing anything more to privacy than our current recommendations.

**Comment by Evernow** [comment]
> As far as I am aware, they ship with propietary office suite and Steam and aren't doing anything more to privacy than our current recommendations.

In the installer you have the choice to install them or not.

**Comment by dawidpotocki** [comment]
> > As far as I am aware, they ship with propietary office suite and Steam and aren't doing anything more to privacy than our current recommendations.
>
> In the installer you have the choice to install them or not.

I don't think you have option not to install Steam and MS Office Online,
but I can be wrong about that.

Anyway there are also other problems with Manjaro.

Manjaro is not really user-friendly and doesn't provide any
privacy/security benefits over OSes we already list. Which is rather the
most important thing here.

They suggested users to change system time when their TLS certificate
expired https://archive.is/JeOLo
After that it also expired one year later https://archive.is/XV70t

From what I remember Manjaro was bundeled with `yaourt` before, AUR
helper, which had few security issues, but they did not had problems
with that.

Also AUR by itself, even though it could be helpful, it is just a
repository of build scripts made by random people.

While maybe we can consider using terminal for more "advanced" people,
access to AUR is also given by the graphical package manager (octopi?),
which makes it easy to install stuff from AUR without reading PKGBUILDs,
which are just saying what command and other stuff should be executed,
it could do anything (though it is not run as root, but still, it's
bad).

**Comment by AlekseiMarinichenko** [comment]
> I don't think you have option not to install Steam and MS Office Online,
> but I can be wrong about that.

I use Manjaro and just wonder where do you found Steam or Office  `¯\_(ツ)_/¯`


Also, I agree with @dawidpotocki about AUR, but a user can install programs via "Add/Remove Software" only **from community source**. Nobody force a user to build from AUR.
