### ISSUE TITLE
🌐 Website Issue |  Add more categories for Browser Add-ons

### ISSUE THREAD

**Issue by DF2NwasJiMYLNFyAOQarZtfPPj0qXh4G** [privacytoolsIO/privacytools.io#1327]
## Description
Currently, we only have two types of categories for add-ons:
1. Improve your privacy with these browser add-ons.
2. These addons require quite a lot of interaction from the user. Some sites will not work properly until you have configured the add-ons.

However, like [I previously mentioned](https://github.com/privacytoolsIO/privacytools.io/issues/1301#issuecomment-533294429), certain extensions don't really fit in either definitions.
Namely:
* Terms of Service; Didn’t Read
* Snowflake
* Cookie AutoDelete (might have uses?)

I think there ought to be a new category for these kind of extensions.

**Comment by Mikaela** [comment]
Requested to be closed in favour of https://github.com/privacytoolsIO/privacytools.io/issues/1346 in case the reporter will get flagged again.
