### ISSUE TITLE
Self hosted riot web uses vector.im when adding email

### ISSUE THREAD

**Issue by afonari** [privacytoolsIO/privacytools.io#1338]
Might be related to #1049.

Open riot.privacytools.io Set home server and identity server to chat.privacytools.io (this is currently defaults). You should see orange message about connection failure to the identity server. Login with your account. From the settings, try to add email address. Receive email from vector.im.

**Comment by blacklight447-ptio** [comment]
@JonahAragon

**Comment by jryans** [comment]
The recent privacy work in Riot 1.4 and Synapse 1.4 fixes this issue by ensuring that the HS manages validating your email when you are adding it your HS account. The IS is no longer involved in adding an email to your HS account.

Please note that you must be using both Riot 1.4 and Synapse 1.4 (which is currently only an RC, full release expected in a few days) for this issue to be fixed. The HS privacy changes are already live on matrix.org, so you could use that to test the experience if you like.

So, what you are seeing is expected for now, but will be fixed once the privacytools.io HS is updated to Synapse 1.4 and configured to handle email validation itself.

**Comment by afonari** [comment]
I've with Riot-web and Synapse 1.4 on matrix.org. I still get the email when I try to add one, even without any integration server set:
"You are not currently using an identity server. To discover and be discoverable by existing contacts you know, add one below."

**Comment by afonari** [comment]
1.4.0 is out: https://github.com/matrix-org/synapse/releases
Hopefully PIO can update soon.

**Comment by JonahAragon** [comment]
The actual reason this was happening was because of an apparent bug in an earlier version of Synapse that did not allow me to set custom email settings. After updating to 1.4.0 I was also able to configure my own mailserver.

Just tested this myself, email verification messages are sent from `matrix-notifications@privacytools.io`. Closing issue :)

**Comment by afonari** [comment]
Noice! Thanks!
