### ISSUE TITLE
Add link for the I2P mirror

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#134]
The site (privacytools.i2p) has been running for a while and it's very stable. Are we going to add a link to it? I didn't create a PR, as I don't know where to place the link.

**Comment by privacytoolsIO** [comment]
Thanks again for creating the I2P mirror. I've linked to it next to the languages. What do you think?

**Comment by Shifterovich** [comment]
Great. Thanks.
