### ISSUE TITLE
❌ Software Removal | Posteo

### ISSUE THREAD

**Issue by scafroglia93** [privacytoolsIO/privacytools.io#1343]
In order to avoid misunderstandings we have tried to replicate the problem reported regarding 2FA
This is why I would like to request the removal of the following service from the dedicated page

https://www.reddit.com/r/privacytoolsIO/comments/d7o3qz/posteo/
(read comment made by sacca25)

https://privacy-watchdog.io/the-truth-about-posteo/

**Comment by blacklight447-ptio** [comment]
While the lack of 2fa on mobile is troubling, i wouldn't see it as a reason for removal.
Also, I would not really be quoting that privacy watchdog site, it seems to be just yet another site pushing his personal opinion.


In in case, we plan to redo the email section just like we did with the VPN section, with a new set list of criteria, we will see here whether Posteo stays, in any case, thank you for the report on the 2fa problem, we will keep it in mind.

**Comment by beerisgood** [comment]
Posteo ist fine. Same as Mailbox.org but without Google captcha for registration.

Also posteo support 2FA with any 2FA totp app you like.
