### ISSUE TITLE
✨ Feature Suggestion |  New email  Criteria.

### ISSUE THREAD

**Issue by blacklight447-ptio** [privacytoolsIO/privacytools.io#1345]
## Description:
This post is to kick of the discussion for our new email criteria.

The new criteria should include:
I started with a list of things i things should be required:
secure mail extensions: SPF,DMARC, DKIM, StartTLS, DNSSEC, and Dane at a minimum, with a best case scenerio of also supporting mta-sts and smtp tls reporting.

We also have to discuss whether we will make GDPR compliancy a requirement or a preference.

Another thing that has to be discussed is if we hold on to our 5 eyes rule. this is because we don't know what has changed over the years, and which countries are trustworthy and which are not.

As a last thing, we need to figure out what we see as an acceptable privacy policy:
what gets stored. why does something get stored? for how long? do other providers store it  as well (is it an industry standard)?

**Comment by blacklight447-ptio** [comment]
Pinging  @tya99  from issue #603 so we can get started

**Comment by mfed3** [comment]
Recommend to add two additional columns with headers "Open Source Client" and "Open Source Server" with possible enumerated values as "Yes", "No" and ("Planned" or "No, Planned" for sortability. For example, Proton Mail and Tutanota both have open source clients, with (as of 9/30/2019) closed source servers, but claim that they plan to open source them in the future.

**Comment by tya99** [comment]
Just wanted to let you know I will be handing https://github.com/privacytoolsIO/privacytools.io/issues/603 and this issue over to @dngray, newest member of [privacytoolsIO](https://github.com/privacytoolsIO) and capable email provider shepherd.
