### ISSUE TITLE
🆕 Software Suggestion | Registry Cleaner

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#1352]
## Basic Information

**Name:** don't use `registry cleaner` article
**Category:** https://www.privacytools.io/operating-systems/#win10
**URL:** https://blog.ipswitch.com/should-you-use-a-registry-cleaner-like-ccleaner

**Comment by Mikaela** [comment]
I think this may be out-of-scope. Are registry cleaners currently recommended somewhere?

**Comment by beerisgood** [comment]
Even Microsoft warn about such tools and block them as solution in their forums

**Comment by Mikaela** [comment]
I guess I can close this in that case. If you have heavy arguments for reopening, please feel free to comment.
