### ISSUE TITLE
CONTRIBUTING.md#images has example links going to 404 errors

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1359]
* https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md#images

Assigning @dawidpotocki for likely being most familiar with how the images should be.

**Comment by dawidpotocki** [comment]
To be fair, I knew about this :P.

**Comment by szTheory** [comment]
Fixed, I hope.
