### ISSUE TITLE
✨ Feature Suggestion | Use svgs and convert them to png

### ISSUE THREAD

**Issue by dawidpotocki** [privacytoolsIO/privacytools.io#1361]
Now we just have pngs uploaded to the repository. I suggest to remove them
and put svgs instead, which would be later converted to png.

What are the advantages of this? We would no longer have big binary files
and changing the resolution would be much easier, as we now actually have to
find the image again and replace it (now do it for all images), with svgs,
we would just have to change one line in shell script/Makefile.

**Comment by blacklight447-ptio** [comment]
This would reduce maintenance, also only listing png's also keeps the site good looking on tor browser while on "safest" mode. i approve.

**Comment by Mikaela** [comment]
So at what level does Tor Browser get a problem and could we document it somewhere?

**Comment by blacklight447-ptio** [comment]
to my knowledge, on highest security mode, tor browser blocks SVG images

**Comment by JonahAragon** [comment]
One issue we'd have is a few images we have don't lend themselves to vector formats well:

![](https://github.com/privacytoolsIO/privacytools.io/raw/master/assets/img/tools/Bitmessage.png)

![](https://github.com/privacytoolsIO/privacytools.io/raw/master/assets/img/tools/Claws-Mail.png)
