### ISSUE TITLE
✨ Feature Suggestion | Increase image resolution

### ISSUE THREAD

**Issue by dawidpotocki** [privacytoolsIO/privacytools.io#1362]
Current images with 120px resolution look pixelated on a lot of devices. I
think we should decide on new resolution for them. I think 256px should
improve situation a lot, but that should be tested.

**Comment by blacklight447-ptio** [comment]
How much bigger will the images be? (regarding file size.)

**Comment by dawidpotocki** [comment]
> How much bigger will the images be? (regarding file size.)

Depends on resolution and image.

**Comment by blacklight447-ptio** [comment]
ofcourse, but i think we should keep an eye on it so we don't make the page 8 times as big data wise so it becomes slightly less pixelated on some devices.

**Comment by zenithium** [comment]
@dawidpotocki Shouldn't this be closed because of the switch to SVGs?
