### ISSUE TITLE
🆕 Software Suggestion | chrlauncher

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#1366]
## Basic Information

**Name:** chrlauncher
**Category:** https://www.privacytools.io/operating-systems/#win10
**URL:** https://github.com/henrypp/chrlauncher#readme

## Description

Small and very fast portable launcher and updater for Chromium.

**Comment by Mikaela** [comment]
I am not confident it would bring additional value as there is ungoogled Chromium strongly hinting that Chromium isn't much better than Chrome and we wish to discourage Windows use.

**Comment by dawidpotocki** [comment]
We only recommend free operating systems like Debian, Fedora, OpenBSD
and Arch which come with Chromium in the repositories. Another thing is
that we don't even recommend Chromium, so why would we list installer
for it? Also listing Windows-only software doesn't make any sense.

**Comment by blacklight447-ptio** [comment]
I do like to add that we currently don't have any chromium recommendations on desktop. This is because we have not found a good recommendation yet(both ungoogled chromium and iridium have their own sets of problems.)
