### ISSUE TITLE
Remove Archlinux from the OS section

### ISSUE THREAD

**Issue by wonderboom** [privacytoolsIO/privacytools.io#1368]
Hello,

Claiming that Archlinux is a simple distro is misleading, as [Archlinux’ ’KISS’ moto is for the developers, and not for it’s users](https://lists.archlinux.org/pipermail/arch-general/2015-July/039443.html).

IME, Archlinux is extremely complex and time-consuming, and as such shouldn’t be recommended to beginners. Because of:
1. a poor documentation, because most of the user’s tasks are made through systemd, a monstruously complex init system which hides most of the inner mechanics to the user (such as the logs); and
2. a wiki of extremely low quality, because so far, the developers let the wiki admins share any community meme they want (including [this article statically pinned on the front page](https://wiki.archlinux.org/index.php/Arch_compared_to_other_distributions)).

Speaking as a former Archlinux user, this distro may be considered as a harmful [total institution](https://en.wikipedia.org/wiki/Total_institution), whose damages extend way beyond its user base. From a non-techie user’s perspective, this is especially problematic because they’ll have to go through [a lot of security-sensitive stuff](https://wiki.archlinux.org/index.php/Matrix) in order to install [a mere music player](https://wiki.archlinux.org/index.php/Music_Player_Daemon).

As I suppose you wouldn’t recommend to your visitors to run a third-party server as root, I’d like to stress out that the Archlinux _official_ documentation does this for [synapse](https://wiki.archlinux.org/index.php/Matrix#Configuration) _and_ for [MPD](https://wiki.archlinux.org/index.php/Music_Player_Daemon#System-wide_configuration).

You shouldn’t recommend a distro that enabled an always-updating ("Firefox Nightly v.99") source-based package: because it definitely won’t fit for beginners, and, in my opinion, because it shows how low-quality the packages may be in the AUR (which are, regardless of the devs’ denying of social phenomenons, statically linked to on [the front page](https://archlinux.org)).

And finally, Archlinux, just like [OpenPGP](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html), is making cryptography, confidentiality, and security sound extremely complex for end-users, unlike [OpenBSD](https://openbsd.org), which is extremely secure and extremely simple to use, or HTTPS, which is transparently used by billions of people.

For all of these reasons, I think you should consider removing Archlinux from the operating systems section.

**Comment by Mikaela** [comment]
> Claiming that Archlinux is a simple distro is misleading, as Archlinux’ ’KISS’ moto is for the developers, and not for it’s users.

>  - A simple, lightweight Linux distribution. It is composed predominantly of free and open-source software, and supports community involvement. Parabola is a completely open source version of Arch Linux.

is what we currently say about Arch Linux. Do I understand correctly that your problem is the use of "simple" that can be interpreted multiple ways?

> a poor documentation, because most of the user’s tasks are made through systemd, a monstruously complex init system which hides most of the inner mechanics to the user (such as the logs); and

I think Arch Wiki is generally used also by users of other distributions and often praised for the good quality. I was personally recently helped by it as a Debian user in case where pulseaudio muted everything when volume went below 22 %. We also don't have a policy against systemd and I think most of the operating systems we list are using systemd.

>  From a non-techie user’s perspective, this is especially problematic because they’ll have to go through a lot of security-sensitive stuff in order to install a mere music player.

I don't see the connection between installing Matrix homeserver and installing a music player?

> As I suppose you wouldn’t recommend to your visitors to run a third-party server as root, I’d like to stress out that the Archlinux official documentation does this for synapse and for MPD.

I don't see this recommendation, so I hope you or someone else fixed the documentation after noticing a problem. I am not going through edit history right now.

> You shouldn’t recommend a distro that enabled an always-updating ("Firefox Nightly v.99") source-based package: because it definitely won’t fit for beginners, and, in my opinion, because it shows how low-quality the packages may be in the AUR (which are, regardless of the devs’ denying of social phenomenons, statically linked to on the front page).

I cannot comment on this specific case, but I would argue that automatic updating can be important for non-techie users considering security. I also wouldn't interpret our current listing for Arch Linux as encouraging it for non-techies, only saying that it's worth mentioning when listing operating systems.

> And finally, Archlinux, just like OpenPGP, is making cryptography, confidentiality, and security sound extremely complex for end-users, unlike OpenBSD, which is extremely secure and extremely simple to use, or HTTPS, which is transparently used by billions of people.

I don't understand this argument and have no personal experience with OpenBSD. I have been Arch Linux user in the past.

**Comment by dawidpotocki** [comment]
> Claiming that Archlinux is a simple distro is misleading, as
> [Archlinux’ ’KISS’ is for the developers, and not from the
> users](https://lists.archlinux.org/pipermail/arch-general/2015-July/039443.html).

Yes, I agree and I said this on our Matrix chat.

> IME, Archlinux is extremely complex and time-consuming, and as such
> shouldn’t be recommended to beginners.

I wouldn't say that OpenBSD good for beginners, even though we list it
and I think is a good OS.

> 1. a poor documentation, because most of the user’s tasks are made
> through systemd, a monstruously complex init system which hides most
> of the inner mechanics to the user (such as the logs); and

Yes, systemd is complete crap, but other distros we list like Debian or
Fedora also use it, and I wouldn't say we should remove them for that
reason.

> 2. a wiki of extremely low quality, because, unless it had changed in the last two years, the developers let the wiki admins share any community meme they want (including [this article statically pinned on the front page](https://wiki.archlinux.org/index.php/Arch_compared_to_other_distributions)).

I wouldn't call it low quality.

> Speaking as a former Archlinux user, this distro may be considered as a harmful [total institution](https://en.wikipedia.org/wiki/Total_institution), whose damages extend way beyond its user base. From a non-techie user’s perspective, this is especially problematic because they’ll have to go through [a lot of security-sensitive stuff](https://wiki.archlinux.org/index.php/Matrix) in order to install [a mere music player](https://wiki.archlinux.org/index.php/Music_Player_Daemon).

What does MPD have to do with Synapse?

> As I suppose you wouldn’t recommend to your visitors to run a
> third-party server as root, I’d like to strees that the Archlinux
> _official_ documentation does this for synapse _and_ for MPD.

Where do you have this for MPD and Synapse? I'm blind or it's not there.

> You shouldn’t recommend a distro that enabled an always-updating
> ("Firefox Nightly v.99") source-based package: because it definitely
> won’t fit for beginners, and, in my opinion, because it shows how
> low-quality the packages may be there in the AUR (which are,
> regardless of the devs’ denying of social phenomenons, statically
> linked to on [the front page](https://archlinux.org)).

I guess you are talking about `-hg` AUR package, if so, that's the whole
point of `-hg`, `-cvs` and `-git` packages. There are also normal
packages that are not using newest commit.

**Comment by blacklight447-ptio** [comment]
Also to note: the worth mentioning section are not our recommendations, they are just some alternatives that are out there that people could consider in case our main recommendations are not Fit for their usecase.

**Comment by dngray** [comment]
> Claiming that Archlinux is a simple distro is misleading, as [Archlinux’ ’KISS’ moto is for the developers, and not for it’s users](https://lists.archlinux.org/pipermail/arch-general/2015-July/039443.html).

By simple they mean in terms of implementation, yes it's mostly config based and that's sometimes what is wanted.

Things like AUR can certainly simplify the process of compiling software, although it does come with warnings (mentioned in the documentation for setting that up).

> IME, Archlinux is extremely complex and time-consuming, and as such shouldn’t be recommended to beginners. Because of:

I would also argue that Archlinux is not necessarily "time consuming" and that is your anecdotal opinion

> 1. a poor documentation, because most of the user’s tasks are made through systemd, a monstruously complex init system which hides most of the inner mechanics to the user (such as the logs); and


I'll just leave this here: https://www.youtube.com/watch?v=o_AIw9bGogo

> 2. a wiki of extremely low quality, because so far, the developers let the wiki admins share any community meme they want (including [this article statically pinned on the front page](https://wiki.archlinux.org/index.php/Arch_compared_to_other_distributions)).

The Arch wiki is one of the best Linux documentation sources out there. I have in fact found it useful in other distributions that are not Archlinux.

I can't speak for that article specfically, but i have found many of the articles especially around [disk encryption](https://wiki.archlinux.org/index.php/Disk_encryption) to be of very high quality

> Speaking as a former Archlinux user, this distro may be considered as a harmful [total institution](https://en.wikipedia.org/wiki/Total_institution), whose damages extend way beyond its user base. From a non-techie user’s perspective, this is especially problematic because they’ll have to go through [a lot of security-sensitive stuff](https://wiki.archlinux.org/index.php/Matrix) in order to install [a mere music player](https://wiki.archlinux.org/index.php/Music_Player_Daemon).

Be careful when making an argument not to engage in an [argument from authority](https://en.wikipedia.org/wiki/Argument_from_authority) especially when you're not.

> As I suppose you wouldn’t recommend to your visitors to run a third-party server as root, I’d like to stress out that the Archlinux _official_ documentation does this for [synapse](https://wiki.archlinux.org/index.php/Matrix#Configuration) _and_ for [MPD](https://wiki.archlinux.org/index.php/Music_Player_Daemon#System-wide_configuration).
> 
> You shouldn’t recommend a distro that enabled an always-updating ("Firefox Nightly v.99") source-based package: because it definitely won’t fit for beginners, and, in my opinion, because it shows how low-quality the packages may be in the AUR (which are, regardless of the devs’ denying of social phenomenons, statically linked to on [the front page](https://archlinux.org)).


It's only mentioned as worth mentioning. It has a good reputation, and has been around a long time. It's the same reason Debian is recommended.

Believe it or not there are situations where Qubes is inappropriate, so it's important to have other options.

> And finally, Archlinux, just like [OpenPGP](https://latacora.micro.blog/2019/07/16/the-pgp-problem.html), is making cryptography, confidentiality, and security sound extremely complex for end-users, unlike [OpenBSD](https://openbsd.org), which is extremely secure and extremely simple to use, or HTTPS, which is transparently used by billions of people.
> 
> For all of these reasons, I think you should consider removing Archlinux from the operating systems section.

Without trying to sound adversarial this request seems ranty and sounds like it comes from someone who has recently changed linux distribution and feels the need to preach the qualities of their new home.

I do not agree with it's removal. Debian is mentioned, it has an installer for those looking for an easy-quick point and click deployment.

**Comment by wonderboom** [comment]
To bring a little bit of context, I’ve run Archlinux for two years, then Fedora, then OpenBSD.

Now, if you’re asking me if my post was due to a primary intolerance for the Archlinux distro, I’ll positively answer. Because, at least where I live, Archlinux looks like a crypto community-endorsed outsider distro with discreet and unique advantages deserving more praise, and it’s used by outsiders as well. Mentally fragile people who’d rather solve their real-life problems than running a flexible distro fixing the 1% of the unfixable use cases.

In my head, the power of Archlinux is just "a large, community-moderated source-based package manager and a curated binaries manager". Maybe it’s power went over my head, but even then I don't see how this power would be a privacy bonus over Debian or Devuan. We may recommend to a careful car driver to learn to pilot a rocket, just to be prepared – I’m not sure this would be worth the investment over trivialities like having a family or avoiding scurvy.

**Comment by Mikaela** [comment]
From what I understood, there isn't any critical issue with Arch that would require us to delist it, so I am closing this in favour of https://github.com/privacytoolsIO/privacytools.io/issues/1376, so we can compare Arch Linux again at that time.
