### ISSUE TITLE
Add mail.i2p

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#137]
1. Accessible via I2P - your IP address is seen as 127.0.0.1, your connection to the server is end-to-end encrypted
2. Lets you receive emails from clearnet using i2pmail.org
3. Lets you send emails to clearnet using i2pmail.org (20 emails/day quota)
4. Supports SMTP TLS
5. Strips some headers which could be a privacy/anonymity issue
6. Free

- More info on 2., 3., and 4.: http://hq.postman.i2p/?page_id=12
- More info on 5.:

> - All User-Agent: and X-Mailer: header lines are automatically removed and replaced by the line X-Mailer:
> 
>     smtp.postman.i2p Official I2P Mailer.
> - All X- header lines are completely removed
> - All message IDs are replaced by server-side generated message-IDs
> - All Date: tags are removed and replaced by server-side generated Dates in UTC
> - All Received: tags are removed (apart from the very last one)

(http://hq.postman.i2p/?page_id=8)

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@Shifterovich 
Wouldn't mentioning be actually damaging since it would put more users, and hence more cost to maintain those services, and Postman already manages quiet a big number of other costly projects (tracker2.postman.i2p comes to mind)?

**Comment by Shifterovich** [comment]
True, the service has issues often. It's _the_ privacy email, but has infrastructure issues.
