### ISSUE TITLE
🌐 Website Issue | CoC is not linked from participate

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1371]
I think it should be.

* https://www.privacytools.io/index.html#participate

**Comment by blacklight447-ptio** [comment]
Updates on this?

**Comment by Mikaela** [comment]
I don't see the CoC there, do you?

**Comment by JonahAragon** [comment]
I think people can find it themselves from the linked resources.

**Comment by Mikaela** [comment]
I think it can lead into a situation where malicious parties claim that the CoC doesn't affect service X, because the PTIO website for service X doesn't mention the CoC.

**Comment by zenithium** [comment]
The CoC is technically linked because of the link to Matrix which leads to https://chat.privacytools.io/ though perhaps the CoC should be mentioned anyway. IMO it would be better to move the CoC to a page on the main site and link to it from all other places.

**Comment by Mikaela** [comment]
The new canon source everything should link to is https://wiki.privacytools.io/view/PrivacyTools:Code_of_Conduct
