### ISSUE TITLE
❌ Software Removal | Firefox

### ISSUE THREAD

**Issue by castrated** [privacytoolsIO/privacytools.io#1375]
## Description

Firefox is spyware.
https://spyware.neocities.org/articles/firefox.html

**Comment by blacklight447-ptio** [comment]
So you think we should delete firefox because of some randos blog who over uses the word spyware to the point where it becomes meaningless?

**Comment by beerisgood** [comment]
Instead of a random blog, Twitter source is a lot better:

What happens at browser start comparison - Firefox
https://twitter.com/jonathansampson/status/1165858896176660480
(privacy friendly version of twitter: https://nitter.net/jonathansampson/status/1165858896176660480

**Comment by blacklight447-ptio** [comment]
@beerisgood which is also made by a compatitor.




In any case we have already established that we keep firefox, we already had this discussion. Firefox is good for people new to privacy, we will not be replacing it with shitty forks that will be behind on security updates, support unsigned addons ( palemoon and waterfox) and dont keep op with modern browser security like sandboxing (palemoon).

We are not removing firefox.
