### ISSUE TITLE
❌ Software Removal | Disroot

### ISSUE THREAD

**Issue by smnthermes** [privacytoolsIO/privacytools.io#1378]
## Description
From their [privacy policy:](https://disroot.org/en/privacy_policy) 

> We do not read/look nor process your personal data, emails, files etc. stored on our servers unless needed for troubleshooting purposes, or under suspicion of breaking Terms Of Services in which case we ask for prior permission from you or inform you afterwards of all actions taken against the account in the transparency report addressed to account holder.

**Comment by Mikaela** [comment]
I asked about this from Disroot MUC as I was under impression that this isn't a terribly uncommon clause and according to them only Protonmail and Tutanota could be kept.

The email criteria is discussed in issue https://github.com/privacytoolsIO/privacytools.io/issues/1345 if you would like to contribute.

**Comment by dngray** [comment]
> We do not read/look nor process your personal data, emails, files etc. stored on our servers unless needed for troubleshooting purposes, 

This may be things like queue logs, and stuff like that. Email does leave metadata (every provider cannot avoid that), as it has to know where the email came from, where it needs to be sent and the subject.

The contents should be protected with PGP if it's sensitive.

> or under suspicion of breaking Terms Of Services in which case we ask for prior permission from you or inform you afterwards of all actions taken against the account in the transparency report addressed to account holder.

It basically says if they are issued a court order they will comply, that will usually happen through [MLAT](https://en.wikipedia.org/wiki/Mutual_legal_assistance_treaty). If we removed Disroot for that reason we would have to remove *every* provider.
