### ISSUE TITLE
Cannot disconnect from the identity server from riot web

### ISSUE THREAD

**Issue by afonari** [privacytoolsIO/privacytools.io#1381]
Open https://riot.privacytools.io/
Login with your PIO account. Go Settings -> General: Click Disconnect.
For me it spinner activates, but never actually disconnects.

**Comment by afonari** [comment]
Apparently, it was possible to disconnect in 1.4.0.

**Comment by JonahAragon** [comment]
Can't reproduce this issue. Does it happen in another browser? Does your browser console show any connection errors?

**Comment by afonari** [comment]
Cannot reproduce it now too, thanks for testing @JonahAragon.

**Comment by JonahAragon** [comment]
We have been experiencing what appear to be DDoS attacks over the last 5 or so days. That could have been causing intermittent server issues.
