### ISSUE TITLE
🆕 Software Suggestion | winchrome

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#1384]
## Basic Information

**Name:** winchrome
**Category:** https://www.privacytools.io/operating-systems/#win10
**URL:** https://github.com/macchrome/winchrome/releases/

## Description

ungoogled-chromium for 64-bit windows

**Comment by beerisgood** [comment]
No explanation in readme.
Also builds are not signed

**Comment by Mikaela** [comment]
How would this differ from https://github.com/privacytoolsIO/privacytools.io/issues/1366?

Also please make the issues you open more detailed. I think you are opening a lot of issues without reasoning why they should be acted upon which I find additional burden.
