### ISSUE TITLE
Website Issue | fourteen-eyes.html could be revamped

### ISSUE THREAD

**Issue by Atavic** [privacytoolsIO/privacytools.io#1387]
Electrospaces blog has good info on [UKUSA](https://electrospaces.blogspot.com/search?q=ukusa), [5-Eyes](https://electrospaces.blogspot.com/2019/09/from-9-eyes-to-14-eyes-afghanistan.html) etc.

There's a [page about fourteen-eyes](https://github.com/privacytoolsIO/privacytools.io/blob/48fd518cb781944bb1472bdc13daf14f88d94423/_includes/sections/fourteen-eyes.html) that could be revamped with the info provided.

I got it from [Cryptome](https://cryptome.org/).

**Comment by Mikaela** [comment]
Closing in favour of #1437 which has more details.
