### ISSUE TITLE
🆕 Operating system suggestion | Worth noting Clip OS

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [privacytoolsIO/privacytools.io#1388]
https://clip-os.org/en
> The CLIP OS project is an open source project maintained by the National Cybersecurity Agency of France (ANSSI) that aims to build a hardened, multi-level operating system, based on the Linux kernel and a lot of free and open source software.

A gentoo based linux distribution, which have similar isolation features as QubeOS.
The reasons worth putting it in the worth mentioning (or the reasons on not mentioning it at all)
- It is developed **FOR**  the french government (It's not directly developed by them). As the TOR browser as a similar story, it should be fine. Especially since this one have all the source opened, fully done documentation, and needing to be build manually.
- The curently developed version is still under development (However, the previous version is still available there)
- Far too complicated for new users, not everyone can compile their own gentoo distro.
- Redundant with the inclusion of QubeOS in the same section.
- Not that very known, even in the gentoo community i suppose.

 [Here's a presentation talk from one of the devs of the ANSSI. ](https://invidio.us/PjRE0uBtkHU)

**Comment by dawidpotocki** [comment]
> https://clip-os.org/en

Website is using default Jekyll theme, lol.

> For now, there are no pre-packaged version of CLIP OS 5 made
> available. The documentation contains all the instructions to enable
> you to build your own version of CLIP OS 5.

Yeah, too much effort.

> The CLIP OS project is still in alpha stage.

No, thanks.

**Comment by Mikaela** [comment]
I agree that missing binary packages and especially being in alpha stage disqualify it.

Out of curiosity would they have a security tracker that I request in https://github.com/privacytoolsIO/privacytools.io/issues/1370? 

In general if you are interested in OSes, we have an issue about rewriting the section in https://github.com/privacytoolsIO/privacytools.io/issues/1376.
