### ISSUE TITLE
Is it possible to 301 redirect anchors to a new site using .htaccess?

### ISSUE THREAD

**Issue by BurungHantu1605** [privacytoolsIO/privacytools.io#140]
Example:
https://www.privacytools.io/#vpn

Redirect to a new folder:
https://www.privacytools.io/vpn/

Just in case we split the website into more sub pages.

**Comment by joas8211** [comment]
You cannot use .htaccess or PHP or anything in the host side to manipulate the fragment. Fragment is not sent to the server by default.

You can use javascript to redirect based on fragment.
```javascript
if (document.location.hash.length > 0) {
  document.location.href = document.location.hash.substr(1);
}
```

But you cannot do 301 redirect using anchors unless you send the anchor to the server.
```javascript
if (document.location.hash.substr(1).length > 0) {
    var form = document.createElement("form");
    form.method = "POST";
    var input = document.createElement("input");
    input.name = "fragment";
    input.value = document.location.hash.substr(1);
    document.location.hash = "";
    form.appendChild(input);
    form.submit();
}
```

```php
if (isset($_POST["fragment"])) {
    header("HTTP/1.1 301 Moved Permanently"); 
    header("Location: " . $_POST["fragment"]);
}
```

**Comment by Vincevrp** [comment]
Closing this since we're hosted on Github pages, which doesn't support editing `.htaccess`.

**Comment by BurungHantu1605** [comment]
I'm late, but thanks @joas8211 

We'll look into it now.

**Comment by JonahAragon** [comment]
We don't want to use Javascript. We have full nginx control so let's look into redirects there.

**Comment by BurungHantu1605** [comment]
> Closing this since we're hosted on Github pages, which doesn't support editing `.htaccess`.

We just moved away from GitHub pages. Let's see what we can do

**Comment by JonahAragon** [comment]
Actually, we may need to use Javascript on second thought if we wish to preserve the `/#vpn`, etc links after switching to multiple pages, since the browser doesn't send hash fragments to the server at all 🙁
