### ISSUE TITLE
🌐 Website Issue | Broken in Edge?

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1400]
https://forum.privacytools.io/t/privacytoolsio-broken-in-edge/1768

> So i just found that the main site is broken in ms edge.
> is it just me?

![](https://forum.privacytools.io/uploads/default/optimized/2X/1/112e340cdbf03f9189a7c90cacd665b68266c241_2_1035x624.png)

I am not sure how important this is though as Edge is going to move to Chromium and I have no idea on the schedule.

**Comment by blacklight447-ptio** [comment]
I dont have any windows machines at hand, can anyone using windows reproduce it?

**Comment by beerisgood** [comment]
Can confirm that.
Anyway old Edge is nearly dead. Switch to Chromium-Edge which shouldn't have that issue

**Comment by dawidpotocki** [comment]
I will try to fix in some free time.

**Comment by dawidpotocki** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#Browser_compatibility

Oh well, Edge is not supporting `<details>`. I guess we would have to
use checkboxes. Meh.

**Comment by dawidpotocki** [comment]
Edge is based on Chromium since 2020-01-15.
