### ISSUE TITLE
Add robots.txt to Gitea service

### ISSUE THREAD

**Issue by Perflyst** [privacytoolsIO/privacytools.io#1407]
On your gitea instance there is no robots.txt file. A lot of commits and their content gets indexed by Google and other search engine robots which make search results of specific search strings (sorry I cannot give an example here right now because it would leak things) very ugly.

**Comment by Mikaela** [comment]
Upstream: https://github.com/go-gitea/gitea/issues/705 & https://github.com/go-gitea/gitea/issues/6028.

From Gitea instances I have remembered to list on mikaela.info#dev, only Snopyta (obviously :)) and Nixnet appear to have a robots.txt, the latter based on GitHub if I understood a comment correctly.

* https://git.snopyta.org/robots.txt (`Disallow: /`)
* https://git.nixnet.xyz/robots.txt

*I am not counting Codeberg as they only `Disallow: /Codeberg/org/src/branch/master/Imprint.md`*

**Comment by JonahAragon** [comment]
[Done](https://git.privacytools.io/robots.txt). Hopefully that will fix our search engine issue, I've been seeing that too. Took the nixnet one since I don't want to block *everything*.
