### ISSUE TITLE
Add XMPP servers

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#141]
We should add XMPP servers too.

I can suggest 2:

- DuckDuckGo's XMPP server (dukgo.com)
- xmpp.is

**Comment by Atavic** [comment]
Big Jabber comparison list: https://gultsch.de/compliance_ranked.html

Posted [here](https://github.com/nylira/prism-break/issues/1688)

**Comment by beardog108** [comment]
cock.li has XMPP for all of it's domains

**Comment by driminicus** [comment]
Maybe mention [prosody](https://prosody.im/) and [ejabberd](https://www.ejabberd.im/) for the self-hosting crowd?

**Comment by infosec-handbook** [comment]
We recently [wrote an article](https://infosec-handbook.eu/blog/xmpp-aitm/) about the power of XMPP admins. For instance, they are able to:

- see and manipulate your contact lists, groups and group membership and vCard
- log your password in cleartext even if SCRAM is enabled
- monitor all of your activities (typing, reading messages, changing profile info)
- inject fake messages from arbitrary senders
- read all of your non-encrypted chats (1-to-1 and group messaging)
- …

The clear recommendation here is to **always run your own XMPP server** and never use one on the internet run by people you don't know. Even if you trust the admin, there is the risk that your personal data and tons of metadata will be exposed due to a data breach. This is basically a security and privacy nightmare.

**Comment by Shifterovich** [comment]
What's wrong with that? XMPP is just the protocol we choose for OTR.

**Comment by Shifterovich** [comment]
If you always use OTR, how is receiving an unencrypted message from one of your friends a major concern? What you listed isn't anything specific to XMPP, it's like that with all sorts of third party servers. I see your point but we should be warning users about this instead of deciding what's good for them. There are secure ways to communicate over insecure channels. One of them is only trusting OTR messages.

**Comment by Mikaela** [comment]
> Jabber servers comparison list: https://gultsch.de/compliance_ranked.html

This has moved to https://compliance.conversations.im/ where you recognise at least Disroot.org. Many Diaspora* pods are also running XMPP servers.

> DuckDuckGo's XMPP server (dukgo.com)

This doesn't exist anymore.

**Comment by Mikaela** [comment]
Could https://xmpp.org/getting-started/ be linked to instead or should Privacytools.io host XMPP in addition to Matrix?

**Comment by Shifterovich** [comment]
We could host our own XMPP server, but we should advise our users not to have all their accounts centralized on our servers.

**Comment by Mikaela** [comment]
@privacytoolsIO/editorial Do you have new thoughts on this?

@JonahAragon commented at https://github.com/privacytoolsIO/privacytools.io/pull/915#pullrequestreview-242417487:

> What concerns me about this PR is I'm not sure if recommending specific instances is in the best interest of our users. The point of these federated protocols especially is to promote decentralization. We host social.privacytools.io and chat.privacytools.io as a convenient way for people to join our discussions on privacy and leave centralized services like Twitter and Facebook. We do not host them as a service that everybody should be using, and indeed I would recommend people self-host the software every time I'm asked, even though I personally maintain chat and social.privacytools.io.
> 
> I fear if we recommend a specific instance to people for these services, they won't do the research on their own to make a more informed decision.

and so did @blacklight447-ptio at https://github.com/privacytoolsIO/privacytools.io/pull/915#issuecomment-496449555

> I feel the same as jonah, listing these services can feel like an endorsement to some people. if their choice happens to turn out in a bad way, it could backfire to us.

Could this be read as an support to not list specific instances (until hypothetical privacytools.io XMPP server starts?) and instead link to the previously mentioned lists?

* https://xmpp-servers.404.city
* https://list.jabber.at
* https://compliance.conversations.im

**Comment by Mikaela** [comment]
https://www.privacytools.io/software/im/ currently has XMPP clients in a sublist in worth mentioning and I hope that if people are interested in it, they click the link to XMPP.org and thus find https://xmpp.org/getting-started/ which two of the lists mentioned above.

If this is not a satisfying solution, please request reopening with new comments or preferably suggestions.
