### ISSUE TITLE
🆕 Software Suggestion | OpenInternetAccess

### ISSUE THREAD

**Issue by NickTheLim** [privacytoolsIO/privacytools.io#1412]
## Basic Information

**Name:** https://openinternetaccess.com/
**Category:** VPN, Proxies, Tor Bridge
**URL:** https://openinternetaccess.com/

## Description

Tons of free privacy and anonymity services.

Including OpenVPN, Wire Guard, Deep Web Proxies, Proxy Checker, and Proxy Lists

**Comment by Mikaela** [comment]
Doesn't fullfill our [VPN criteria](https://www.privacytools.io/providers/vpn/#criteria)

:x: based in the USA
:heavy_check_mark: OpenVPN
:heavy_check_mark: no logging, however personally I am suspicious of that being free.
:x: no audits from third party firms
:x: no public-facing leadership or ownership that I can see.
