### ISSUE TITLE
🌐 Website Issue | Mullvad has Android & iOS apps while we say they are in the works

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1413]
* https://www.privacytools.io/providers/vpn/

> mullvad got both android and ios app the vpn section says its in the works and not here yet

Reported on Matrix, https://matrix.to/#/!UaaAOhKtQbizRegDfH:privacytools.io/$7veMnD-rkbNR44fyL8lSJrVzw0hZg_2itY8MC6VSIC8?via=privacytools.io&via=matrix.org&via=librem.one

**Comment by danarel** [comment]
They have an Android app now, but they don't have an actual iOS app. They recommend Wireguard or OpenVPN, neither of which are their apps.

**Comment by djoate** [comment]
Should probably wait until it's published to Google Play and F-Droid. Quoting from a developer at https://github.com/mullvad/mullvadvpn-app/issues/1126#issuecomment-534007313

> We are still in very early stages of the Android app, the very first beta just came out. When things stabilizes a bit we will be available both on Google Play and F-Droid.

**Comment by contentkraft** [comment]
I think the wording on the website could still be improved though as it’s not mentioning WG at all (and it’s very easy to set up on mobile).

> […] mobile users will need to use a traditional OpenVPN client and configuration files, which are a bit more difficult to configure.

Instead write something like:

> mobile users will either need to use a traditional OpenVPN client and configuration files or download the WireGuard app and scan the QR code generetad by the Mullvad configuration generator.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
I use Mullvad as my VPN provider and the Android app is in beta, you just can turn off and on the VPN and you have no kind of settings option besides choosing where you want the server to be.

**Comment by krapans** [comment]
https://github.com/mullvad/mullvadvpn-app/releases/tag/ios/2020.1

iOS release

**Comment by dngray** [comment]
We can close this now thanks to https://github.com/privacytoolsIO/privacytools.io/pull/1824
