### ISSUE TITLE
🆕 Software Suggestion | Nitter - Twitter front-end focused on privacy

### ISSUE THREAD

**Issue by rdgdhztdhtzhtdht** [privacytoolsIO/privacytools.io#1415]
## Basic Information
An open source alternative Twitter front-end focused on privacy. It basically allows you to use Twitter without JavaScript, IP-tracing and fingerprinting. For those people that don't wanna use the legacy version of Twitter this replaces everything. 

**Name:** Nitter
**Category:** Providers: Social Workaround?
**URL:** https://github.com/zedeus/nitter

## Description
It can be self-hosted using Nginx or Apache, Docker and systemd. It's hosted on the Clear Net and as a Tor Hidden Service (https://github.com/zedeus/nitter/wiki/Instances).

It's features:

   - No JavaScript or ads
   - All requests go through the backend, client never talks to Twitter
   - Prevents Twitter from tracking your IP or JavaScript fingerprint
   - Unofficial API (no rate limits or developer account required)
   - AGPLv3 licensed, no proprietary instances permitted
   - Dark theme
   - Lightweight
   - Native RSS feeds

I just saw, this is being talked about in #1402. But imma post this either way.

**Comment by rdgdhztdhtzhtdht** [comment]
This is a burner account. I will not be able to respond any further.

**Comment by PoorPocketsMcNewHold** [comment]
I suppose this will be better to add it trough #1402.

**Comment by Mikaela** [comment]
I am going to close this in favour of https://github.com/privacytoolsIO/privacytools.io/issues/1402
