### ISSUE TITLE
🆕 Software Suggestion | DecSync CC

### ISSUE THREAD

**Issue by smnthermes** [privacytoolsIO/privacytools.io#1416]
## Basic Information

**Name:** DecSync CC
**Category:** Contacts/Calendar sync
**URL:** https://github.com/39aldo39/DecSync

## Description
It can be used in combination with Syncthing

**Comment by Mikaela** [comment]
Could you add more explanation in your words on why it should be listed?

**Comment by JonahAragon** [comment]
I don't see how this is better than the current recommendations, but can re-open if debated otherwise.

**Comment by moritztk** [comment]
@Mikaela @JonahAragon One "gripe" I have with privacytools is, that it puts the emphasis on external services, even though the most privacy friendly option might be to not have data ever leave your devices. 

For this purpose, SyncThing is great. In many cases, if you use syncthing, you dont need things like Etherpad, Bitwaren and StandardNotes. Syncthing enables you to just use LibreOffice, Keepass and any text editor. Why pay or maintain a nextcloud instance if anything you need can just live and be backed up on your devices? 

All DecSync does is enabling you to use SyncThing as your Calendar/Contact syncthing tool. No need for uploading those to (sometimes paid) third parties. The benefit should be obvious.

**Comment by Mikaela** [comment]
I personally never even opened the link hoping the issue author would do basic research or at least say what is the point of DecSync / reply to my initial comment, but with your addition I am open to reading more about this.

**Comment by moritztk** [comment]
The best place to read about it is the [docu repo](https://www.privacytools.io/software/productivity/#productivity) (same as linked above). 

> 
> DecSync (Decentralized Synchronization) synchronizes key-value mappings using the file system in a conflict-free way. It uses a synchronized directory to synchronize the mappings. This can be done without a server by using for example Syncthing.
> 
> Currently, DecSync can be used to synchronize RSS, contacts and calendars using the following applications.

[The](https://github.com/39aldo39/DecSyncCC) [apps](https://github.com/39aldo39/Evolution-DecSync) are well maintained by [Aldo Gunsing ](https://github.com/39aldo39), mobile apps [available via F-Droid](https://f-droid.org/app/org.decsync.cc).

IMHO it would be good addition to "Worth Mentioning" section of [productivity](https://www.privacytools.io/software/productivity/#productivity).
