### ISSUE TITLE
🌐 Website Issue | CryptPad doesn't use AES

### ISSUE THREAD

**Issue by djoate** [privacytoolsIO/privacytools.io#1417]
## Description
At https://www.privacytools.io/providers/paste/, CryptPad is described to be using "256bit AES" for encryption and decryption, but their [FAQ](https://cryptpad.fr/faq.html#security-crypto) and [whitepaper](https://blog.cryptpad.fr/images/CryptPad-Whitepaper-v1.0.pdf) do not mention AES.

**Comment by djoate** [comment]
I'm not sure why all website issues created with the template are automatically classified as high priority.

**Comment by danarel** [comment]
I also did a search for their domain and mentions of AES and it only comes up in one blog post, which happens to be an April Fools post announcing they are partnering with the NSA.

**Comment by Mikaela** [comment]
> I'm not sure why all website issues created with the template are automatically classified as high priority.

Same.

*Assign is just so it appears for me at github.com/issues, please feel free to work on it or send a PR etc. regardless.*
