### ISSUE TITLE
🆕 Software Suggestion | Mailcow (Selfhosted Email)

### ISSUE THREAD

**Issue by FingerlessGlov3s** [privacytoolsIO/privacytools.io#1419]
## Basic Information

**Name:** Mailcow
**Category:** Selfhosted Email
**URL:** https://mailcow.email/

## Description
Mailcow is a dockerized selfhosted email server, that uses Postfix, Spamd, Dovecot, SOGo and others to give you a very usable user experience (Mail, Contacts and Calendar all in one place). It supports, Calendar, Contacts and Email sync via Exchange Active Sync to your mobile devices. Can also be sync'd with Thunderbird Contacts and Calendar using SOGo Connector. (Thunderbird 68 connector is in testing currently).

**Comment by JonahAragon** [comment]
This is a better solution than Mail-in-a-Box (our current listing) and could replace it or be listed alongside it.

**Comment by FingerlessGlov3s** [comment]
I use it myself and it does feel like a more polished solution over Mail-in-a-box. Plus it's super easy to install.
