### ISSUE TITLE
uBlock blocks piwik.js

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#142]
![piwik](https://cloud.githubusercontent.com/assets/4354706/21574458/5d1cb03a-cef3-11e6-985d-ecf05d94123b.png)

**Comment by bakku** [comment]
I can confirm this. For what is the research required ? to find a way that piwik will not get blocked ?

**Comment by Shifterovich** [comment]
Yes. It blocks piwik, because it matches a specific pattern (`/piwik.$script`). Renaming the file should do the trick.

**Comment by Atavic** [comment]
[`piwik` included in _EasyPrivacy_](https://github.com/gorhill/uBlock/issues/710)
