### ISSUE TITLE
🗄️ DNS provider suggestion | Quad9 more DNS

### ISSUE THREAD

**Issue by Kcchouette** [privacytoolsIO/privacytools.io#1422]
## Description

Quad9 has its primary DNS listed on your website:
![Screenshot_2019-10-24 DNS Domain Providers privacytools io](https://user-images.githubusercontent.com/3000936/67466701-ccc3b680-f647-11e9-8220-09d316b43aae.png)
But Quad9 can be used in "unsecure mode" with "no security blocklist, no DNSSEC, no EDNS Client-Subnet sent" (see https://www.quad9.net/faq/#Is_there_a_service_that_Quad9_offers_that_does_not_have_the_blocklist_or_other_security )

**Comment by Mikaela** [comment]
I don't think listing insecure DNS makes sense, people can find it from the websites or other public DNS listings.

IIRC we require DNSSEC support
