### ISSUE TITLE
🌐 Website Issue | About the format of “Self-contained Networks”

### ISSUE THREAD

**Issue by GrimPixel** [privacytoolsIO/privacytools.io#1426]
## Description
This page is the only one with the earlier taste of design:
https://www.privacytools.io/software/networks/
Any plan to change it?

**Comment by Mikaela** [comment]
Yes, I think it's just waiting for someone who understands cards.

Closing as a duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/1286.
