### ISSUE TITLE
Password generator's secure password <input>'s size is not dynamic

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#143]
> The available characters in each set are user friendly - there are no ambiguous characters such as i, l, 1, o, 0, etc.

Therefore users seem to be encouraged not to use clipboard to store the password (but rather write it down), however some generated passwords doesn't fit into the secure password <input> tag.

**Comment by bookercodes** [comment]
Ah, unambiguous are really for the benefit of someone **reading** a password, not **writing** it down. In any case, the `input` is too narrow, you're right. The solution, I think, is to replace the `input` with a `p` and to wrap `break-word` or something.

**Comment by Vincevrp** [comment]
Password generator has been removed in 43a14c32502a565f7e68120e90a5ce34168c64b0
