### ISSUE TITLE
Method to report issues without GitHub account

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1432]
AFAIK there is currenty no official method for reporting issues other than using a GitHub account.

Unofficially we are saying that feedback is welcome on all channels, but in practice I think that is just me forwarding issues/comments from other platforms and I don't know is anything coming through from Reddit anymore since I removed my account and stopped following it.

**Comment by dawidpotocki** [comment]
> AFAIK there is currenty no official method for reporting issues other
> than using a GitHub account.

As I said before, we should add support for emailing issues. One of such
services I know is https://fire.fundersclub.com/.

**Comment by Mikaela** [comment]
@JonahAragon What do you think of https://github.com/fire-bot ? It looks good to me at a first glance.

**Comment by JonahAragon** [comment]
I configured it and sent it a test email and it hasn't shown up yet. The setup process wasn't very clear but I *suspect* it only accepts emails from a whitelist of team members. Unless my issue appears at some point in the future, highly delayed... We'll see.

**Comment by JonahAragon** [comment]
Oh, look at #1444 lol — The email is `privacytools@fire.fundersclub.com`

**Comment by Mikaela** [comment]
and there is no reply option https://github.com/FundersClub/fire/issues/61. I don't know where I asked if it's possible or was it in team chat.
