### ISSUE TITLE
Add 2FA column to the email provider comparison table

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#144]
We should add more data to email provider comparison table.

TODO:
1. **2FA**

**Comment by nikhiljha** [comment]
The 2FA thing should require very little research (hopefully). It's all listed on 2fa.io.

**Comment by tya99** [comment]
It should be noted that I am working on something like this and have begun research. https://github.com/privacytoolsIO/privacytools.io/issues/603

**Comment by nitrohorse** [comment]
I like this idea :+1:
