### ISSUE TITLE
Create a default community health file?

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1440]
I became aware of the fact that it's possible to put CODE_OF_CONDUCT.md and similar files into a `.github` repository and I wonder if that would be helpful for us?

* https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file-for-your-organization

**Comment by JonahAragon** [comment]
Yes I was just planning on doing that for FUNDING.yml actually and we can definitely move other ones too.
