### ISSUE TITLE
Edit the top panel

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#145]
The top panel should be edited, it's hard to navigate in.

- I'll create a PR once we decide the design.
- The most current design will be in this post (better than being lost somewhere in the comments)

Also, in my opinion
- we shoudln't capitalize the first letters of words, as it's harder to read with small font _(at least for me)_
- we should keep the text as short as possible, even if it isn't same as the headers on the page

My proposal:

Provider | Theory<sup>1</sup> | Browser | Software | OS | Participate | Share | Twitter | Donate <3
----------- | ----------------------------- | ---------- | ------------ | ---- | --------------  | -------- | -------- | ----------
VPN       | I don't have anything to hide | Recommendation | Email clients | PC | | Email
Email     | Warrant canaries | Fingerprinting |  Email alternatives | Live CD | | Facebook
Cloud storage | Key disclosure law | WebRTC IP leak | Instant messenger<sup>3</sup> | Mobile | | Twitter
Social networks | Fourteen eyes | Add-ons<sup>2</sup> | Video & Voice Messenger<sup>4</sup> | Router firmware | | Google+
DNS      | US based services | Tweaks | Password manager | | | reddit
Search engines | Windows 10 | | File encryption | | | LinkedIn
| | | | File sync | | | StumbleUpon
| | | | Password generator | | | Diaspora*
| | | | Self-contained networks
| | | | Self-hosted cloud servers
| | | | Digital notebook
| | | | Paste services
| | | | Productivity tools
| | | | Don't use Windows 10<sup>5</sup>

<sup>1</sup> Better title?
<sup>2</sup> We should recommend addons for more than one browser.
<sup>3</sup> change to IM?
<sup>4</sup> change to VOIP (even though it's not 100% accurate)?
<sup>5</sup> It's worth mentioning twice

**Comment by privacytoolsIO** [comment]
Good job. Go ahead, we can make corrections along the way.

**Comment by mprobson** [comment]
Apologies if this isn't the right place to put this (maybe a new issue?) but I noticed that the top panel on the site and your proposed design are missing the "Privacy Respecting Search Engines" [link](https://www.privacytools.io/#search). If you can point me at the right place to edit this file I'm happy to submit a new PR and/or open an issue. Thanks for such a great site!

**Comment by Shifterovich** [comment]
@Vincevrp

**Comment by blacklight447-ptio** [comment]
It seems like this task is completed, closing issue.
