### ISSUE TITLE
Software labels

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#146]
I think we should add a label to each piece of software, to prevent people who don't see much difference from choosing the first option (why would they choose the second or the third one?)

- We'd use Bootstrap labels.
- I'll create a PR once we decide enough labels
- 2 kinds of labels
    1. Labels, like "easy to use"
    2. Short notes, like "routes everything through the Tor network by default"
- Feedback is needed on labels written *like this*

Section | 1 | 2 | 3
---------- | -- | - | --
Browser Recommendation | **Firefox**: *popular* | **Brave**: natively blocks ads | **Tor Browser**: routes everything through the Tor network by default

Other (not the main 3):

- TorBirdy: `beta` or `experimental`

**Comment by bakku** [comment]
Good idea! But when using Labels then they should be short in my opinion and not a description since there is already a description for each tool right? E.g. for your Tor Browser label we could just say "Uses Tor Network".

**Comment by Shifterovich** [comment]
I meant labels and short descriptions as a separate thing, but had issues describing it, let me edit the post :P. Some tools might need a short description more than a tiny label.

 **Tool name**    
_Note: short description_
\<audited> \<easy to use>
long description

**Comment by kewde** [comment]
Would there be a limit on the amount of labels?
inb4: color book :rainbow:

**Comment by Shifterovich** [comment]
I think the limit would be "doesn't look bad"

**Comment by Shifterovich** [comment]
You could have two longer labels as well as five very short ones.

**Comment by kewde** [comment]
@Shifterovich I think some hard limit to fallback to might be appropriate, "doesn't look bad" is very subjective :stuck_out_tongue: I know people are going to want to put more information into this than they can beautifully handle

**Comment by bakku** [comment]
I think labels should not span more than one "line" when the site is at its full width. This might be a limit as well...

**Comment by Shifterovich** [comment]
All PRs are reviewed by us. But alright, we should define some limit. If it were up to me, I'd define it like this:

```python
total_length = 0
for label in labels:
    total_length += 2+len(label)  # there are two small spaces on both sides
```

such that `total_length <` (some) `n`

That'd be the mathematical equivalent of "doesn't look bad".

:P

**Comment by Shifterovich** [comment]
@Vincevrp

**Comment by Vincevrp** [comment]
Great idea, though I'm not sure where we'd place them.

**Comment by Shifterovich** [comment]
How about this?

![screenshot from 2018-10-27 15-00-38](https://user-images.githubusercontent.com/4354706/47604368-13f97600-d9f9-11e8-8b35-e543474e6b3b.png)
![screenshot from 2018-10-27 15-00-06](https://user-images.githubusercontent.com/4354706/47604369-14920c80-d9f9-11e8-9765-c126c63b19e2.png)

**Comment by Shifterovich** [comment]
https://github.com/privacytoolsIO/privacytools.io/commit/ca93d61b45ba8ab7ee934c515ef11fbfd053b2fa Feature added, but we still need to add the labels to the cards.

**Comment by blacklight447-ptio** [comment]
it seems like the labels are now added, would everyone be okay with closing this issue? @Mikaela  @JonahAragon @nitrohorse @Shifterovich ?

**Comment by Mikaela** [comment]
I don't think the labels were added or at least https://www.privacytools.io/browsers/#browser which seems to be mockupped is missing those.

Also why is Tor Browser only for experts?

**Comment by blacklight447-ptio** [comment]
I wouldn't know, and i think that one should be removed anyway, as it could scare away people who might really need it.

**Comment by Mikaela** [comment]
Resolved in https://github.com/privacytoolsIO/privacytools.io/pull/1126

**Comment by blacklight447-ptio** [comment]
okay then, closing issue.
