### ISSUE TITLE
🌐 Website Issue | Missing I2P buttons

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1461]
## Description

Would it be possible to then have button in card for i2p/garlic addresses? I2P's official addresses should be:

* http://udhdrtrcetjm5sxzskjyr5ztpeszydbh4dpl3pl4utgqqw2v4jna.b32.i2p/ (I prefer this due to being more onion, even if it automatically sends me to the other one)
* http://i2p-projekt.i2p/en/

*Salvaged from https://github.com/privacytoolsIO/privacytools.io/issues/1286#issuecomment-529453663, assigning old assignees.*

**Comment by Mikaela** [comment]
See also https://github.com/privacytoolsIO/privacytools.io/pull/1033

**Comment by JonahAragon** [comment]
Is this fixed? I see this button now: https://www.privacytools.io/software/networks/

**Comment by Mikaela** [comment]
Yes, resolved by https://github.com/privacytoolsIO/privacytools.io/pull/1469.
