### ISSUE TITLE
🆕 Provider Suggestion | erine.email

### ISSUE THREAD

**Issue by weeeee-alias-21** [privacytoolsIO/privacytools.io#1480]
## Basic Information

**Name:** [erine.email](https://erine.email/)
**Category:** Email
**URL:** https://erine.email/
**Source Code**: https://gitlab.com/mdavranche/erine.email ([GPL 3.0](https://www.wikipedia.org/wiki/GPL_3.0))

## Description

> erine.email is a strong shield for your emails against spam. Based on
> unlimited disposable email addresses, erine.email is completely free,
> open-source, and simple. Really. 

I have started using it recently and so far it works really well.

Basic features are listed on their WIKI:

- https://gitlab.com/mdavranche/erine.email/wikis/home

The only major caveat I can find is that all addresses are just an 
{emai-ID} plus {username}. Therefore, you could create `toast.food@erine.com` and `apple.food@erine.email` but not `something.apple@erine.email`.

Plus, each user's {username} is different and wouldn't take much (just knowing how erine.email works) to send that user emails or piece their accounts together via their username.

**Comment by beerisgood** [comment]
[IPv6 problems](https://www.ssllabs.com/ssltest/analyze.html?d=erine.email), bad [Security Headers](https://securityheaders.com/?q=https%3A%2F%2Ferine.email%2F&followRedirects=on), and bad [website security](https://observatory.mozilla.org/analyze/erine.email) itself.

No thanks

**Comment by Mikaela** [comment]
Working IPv6 is going to become a criteria for VPNs and can in general be considered as a good marker on provider knowing what they are doing.
