### ISSUE TITLE
Add steps to disable WebRTC in Safari

### ISSUE THREAD

**Issue by vol24pl** [privacytoolsIO/privacytools.io#1483]
Please update the webRTC section about the Safari support. Current version of Safari just started working with webRTC.

EDIT: Sorry for the bad labeling, but you don’t have a good label for outdated info on the site, and this seemed like a close enough label 😅

**Comment by nitrohorse** [comment]
Thanks for bringing this up @vol24pl :+1: For team reference, looks like these are the steps to disable WebRTC on Safari: https://www.privateproxyguide.com/how-to-disable-webrtc/#Safari

**Comment by rex4539** [comment]
This is how the latest Safari version Experimental Features debug menu looks like.

<img width="653" alt="Screen Shot 2019-12-01 at 13 24 30" src="https://user-images.githubusercontent.com/227442/69913238-043f3300-143e-11ea-88c5-ce17a0d6545a.png">
