### ISSUE TITLE
Remove android OS from chatsecure

### ISSUE THREAD

**Issue by p43b1** [privacytoolsIO/privacytools.io#149]
The End of ChatSecure Android

The End of ChatSecure Android

The developers of the Android version have hard forked the code and are no longer maintaining the upstream version. If you still use ChatSecure Android you should migrate to another app immediately. For a similar user experience and the best compatibility with the latest features of ChatSecure iOS, we recommend downloading Conversations.

The development of ChatSecure iOS is unaffected by this change and we will continue to release new features and updates.

Written By Chris Ballinger — December 16, 2016

[https://chatsecure.org/blog/](url)

**Comment by kewde** [comment]
addressed in #192
