### ISSUE TITLE
Please specifify that Torbirdy is still in beta

### ISSUE THREAD

**Issue by p43b1** [privacytoolsIO/privacytools.io#150]
Current TorBirdy version is 0.2.1 released on Nov 30, 2016. The recommended Thunderbird version for use with TorBirdy is Thunderbird 45 or higher.

TorBirdy is in beta and should be considered experimental. Please make sure that you read the Before using TorBirdy section below before using it for the first time.

**Comment by Shifterovich** [comment]
TODO: Add `beta` or `experimental` label
