### ISSUE TITLE
/about/: Could the profile links of contributors have rel="me" ?

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1502]
Having `rel="me"` links would allow "Verify Me" extension and sites using it e.g. Mastodon show a :heavy_check_mark: when linking between websites/profiles of contributors and https://www.privacytools.io/about/ .

**Comment by JonahAragon** [comment]
Does rel="me" make sense when a page is about multiple people? 

Not a rhetorical question, I actually don't know, but Indieweb seems to indicate that perhaps rel="author" might be slightly better (as in, everyone listed on the page is an author of the site) or we shouldn't include one at all. https://indieweb.org/rel-me#Can_I_add_rel-me_to_non-profile_pages.3F

**Comment by Mikaela** [comment]
I don't know and I also don't know if anything blocks multiple different rel="me"s. Does Mastodon or anything support rel="author" and would it work for validation?

**Comment by JonahAragon** [comment]
I don’t think they support anything other than rel=me. I just don’t think it makes sense to verify /about/ on your or anyone’s Matrix profile because /about/ isn’t a profile of yours, right?

**Comment by Mikaela** [comment]
I am thinking of having team members have one box for saying team member and linking to about page and then Mastodon would make it green, but please feel free to close if you don't see any practical use for the idea.

**Comment by JonahAragon** [comment]
rel="me" is used to indicate ownership of a page, which is not the case here. The specific use-case you mentioned wouldn't be a big deal, but rel="me" is used in other cases (notably IndieAuth) where linking a single page on a single domain with multiple identities would be problematic.
