### ISSUE TITLE
❌ Software Removal | Bromite can not be found in the Android Playstore 

### ISSUE THREAD

**Issue by zounp** [privacytoolsIO/privacytools.io#1505]
## Description

Bromite is listed as a prefered browser for Android. However Bromite can not be found in the Android Playstore.

**Comment by dawidpotocki** [comment]
> Bromite is listed as a prefered browser for Android. However Bromite
> can not be found in the Android Playstore.

It is available in 3rd party F-Droid repository and you can just
download an `.apk`. I don't see this as a big problem and there aren't
better alternatives in Play Store.

**Comment by blacklight447-ptio** [comment]
Yeah, we list bromite so people have a chromium based option on android. Asside from that, its pretty easy to install via  the ways dawid described above.

**Comment by Mikaela** [comment]
I understand that we don't consider Bromite not being in Play Store as an issue and on the website we aren't claiming Bromite to be available from there comparing Tor Browser and Bromite cards (screenshot below)

![Tor Browser vs Bromite cards](https://user-images.githubusercontent.com/831184/69370370-81ccab80-0ca6-11ea-8beb-49c1c0725549.png)

**Comment by beerisgood** [comment]
Also Bromite isn't in Google playstore because it block ads, which is against google policy

**Comment by zounp** [comment]
Aha, I see. Maybe it then is a good idea to mentoin on Privacytools.io at the Bromite section:
"Bromite can be installed form the F-Droid repository or you can just
download an `.apk`"
to make it more clear where it can be found.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Mikaela** [comment]
How would you make it more obvious and can you perhaps open a pull request to do that?

In my previous screenshot you can see the F-Droid logo which is also a link.

**Comment by dawidpotocki** [comment]
> Aha, I see. Maybe it then is a good idea to mentoin on Privacytools.io
> at the Bromite section: "Bromite can be installed form the F-Droid
> repository or you can just download an `.apk`"

Why would you do it? You clearly have icons for Android (apk) and
F-Droid. That's unnecessary.

**Comment by zounp** [comment]
I updated the F-droid store and on my phone and searched for Bromite but Bromite is nowhere to find.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dawidpotocki** [comment]
> I updated the F-droid store and on my phone and searched for Bromite
> but Bromite is nowhere to find.

Because it's in 3rd party repository, not the main F-Droid one.
