### ISSUE TITLE
New section - Hard disk/Filesystem Encryption

### ISSUE THREAD

**Issue by p43b1** [privacytoolsIO/privacytools.io#152]
Privacytools.io could suggest using the Linux Unified Key Setup or LUKS to encrypt internal/external hard drives and usb thumb drives.

https://en.wikipedia.org/wiki/Linux_Unified_Key_Setup

**Comment by Shifterovich** [comment]
2. VeraCrypt

**Comment by loganmarchione** [comment]
I have the code for this, but didn't create a branch for https://github.com/privacytoolsIO/privacytools.io/pull/156 (I commited to master), so I can't create a PR until that PR is closed.

**Comment by Atavic** [comment]
3. [Gostcrypt](https://www.gostcrypt.org/gostcrypt.php)

**Comment by 2E0PGS** [comment]
VeraCrypt I can vouch for. Also you can use PGP to encrypt files.

Keybase.io also have a PGP encrypted file sharing service. Also they have PGP encrypted git repos.

**Comment by blacklight447-ptio** [comment]
Veracrypt and luks would seem like good options, I know also that veracrypt is audited.
@nitrohorse , would you have time to make a PR for this?

**Comment by blacklight447-ptio** [comment]
So can this issue be closed?

**Comment by Mikaela** [comment]
https://www.privacytools.io/software/encryption-tools/ - I guess so.

**Comment by beerisgood** [comment]
Also Bitlocker for Windows

**Comment by blacklight447-ptio** [comment]
We already list veracrypt, no need to list Microsoft's closed source alternative.

**Comment by beerisgood** [comment]
@blacklight447-ptio well, Bitlocker works better with Windows 10 & uEfi then VeraCrypt.
Also it's native available - but only for Pro and higher version

**Comment by blacklight447-ptio** [comment]
I know, but we generally tend to follow the model: we don't require software to be opensource if there is no alternative, in this case there is: veracrypt, thus we require it to be open source. Bitlocker does not fall over it. plus the requirement to have an more expensive windows license for it makes me weary to recommend it.

**Comment by 2E0PGS** [comment]
No mention of phone encryption still however. Suggest using Android's encryption.

⁣Cheers,

**Comment by blacklight447-ptio** [comment]
to my knowledge, all phones encrypt by default for a few years now, same story for IOS.

**Comment by 2E0PGS** [comment]
Android isn't by default in my experience.

⁣-- 
Peter Stevenson (2E0PGS)
http://www.m3pgs.co.uk​

**Comment by blacklight447-ptio** [comment]
google says its the default since android 5.0:https://source.android.com/security/encryption/full-disk

**Comment by dawidpotocki** [comment]
> I know, but we generally tend to follow the model: we don't require software to be opensource if there is no alternative, in this case there is: veracrypt, thus we require it to be open source.

VeraCrypt is not free, it is a combination of source-available code and
code under Apache 2.0.

**Comment by blacklight447-ptio** [comment]
Well yes, but I meant open source, not fsf free

**Comment by dawidpotocki** [comment]
> Well yes, but I meant open source, not fsf free

Still not open source and they pretty much mean the same thing.
https://web.archive.org/web/20131029185711/http://projects.opensource.org/pipermail/license-discuss/2013-October/001313.html

**Comment by blacklight447-ptio** [comment]
What part of veracrypt has no aviable source?

**Comment by dawidpotocki** [comment]
> What part of veracrypt has no aviable source?

There is source, but you can't do "whatever you want", this part is
coming from TrueCrypt, which VeraCrypt forked.

https://lists.opensuse.org/opensuse-buildservice/2008-10/msg00055.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=364034
https://lists.freedesktop.org/archives/distributions/2008-October/000276.html

**Comment by blacklight447-ptio** [comment]
i know, but its what i meant, its opens source, we can see how it runs and compile it yourself, you just cant do everything you want with it.
