### ISSUE TITLE
✨ Feature Suggestion | Start using a Bech32 Bitcoin donation address

### ISSUE THREAD

**Issue by slioch5** [privacytoolsIO/privacytools.io#1520]
## Description:

The donations page is currently using a legacy bitcoin address which is associated with much higher fees. Switching to a Bech32 (now the standard address format of Bitcoin core) will save you and your donators significantly in bitcoin tx fees (~50%). 

details can be found here: https://whensegwit.com/

**Comment by JonahAragon** [comment]
This is not currently a possibility for us as far as I’m aware.
