### ISSUE TITLE
Create a cron job to git pull every day/hour

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#154]
As more people push into the repo and only 1 person controls the website, the repo tends to be ahead of the website. @privacytoolsIO could you create a cron job to pull from the repo?

**Comment by bookercodes** [comment]
Yes please. Or a Git hook 👍

**Comment by walletdude** [comment]
It would be nice to see changes contributed by the community enacted every hour or day.  This would allow verification that the site is indeed pulling from the git repo as its source.
