### ISSUE TITLE
🆕 Software Suggestion | Brave Browser

### ISSUE THREAD

**Issue by Gamegenorator** [privacytoolsIO/privacytools.io#1541]
## Basic Information

**Brave**
**Browser**
**Brave.com**

## Description

Brave has shown no Privacy related problems and has shown that they are working it improve privacy on the internet. It's 100% open source and I think it's worth putting them in the "Worth Mentioning" section at the very least.

**Comment by dawidpotocki** [comment]
Please search issue tracker on GitHub before making another issue.
https://github.com/privacytoolsIO/privacytools.io/pull/1169
