### ISSUE TITLE
❌ Software Removal | "Email Alternatives" Section

### ISSUE THREAD

**Issue by JonahAragon** [privacytoolsIO/privacytools.io#1542]
## Description

In general this section doesn't make sense to me. **RetroShare** could be merged into either social networks or RTC (or removed entirely, because the current social network and IM suggestions both accomplish their goals better than RS it seems like). We do have it as worth mentioning in RTC currently anyhow. **BitMessage** could be merged into RTC as well, but again I'm not sure if it would be worth recommending alongside the current P2P listings. Perhaps as a worth mentioning product only, again.

From a security perspective I strongly believe the only email alternatives we should be recommending *for communication* are RTC tools that are purpose-built for that task, like Signal.

**Comment by Mikaela** [comment]
:+1: I wasn't even aware we have this section (kind of reminds me of Instant Messengers + VoIP having been separate pages) and I don't know anyone using those.

**Comment by dawidpotocki** [comment]
Agree, never understood why we have this section.

**Comment by dngray** [comment]
I agree, bitmessage could go under the peer-to-peer worth mentioning section.

**Comment by dngray** [comment]
Although that still leaves i2pbote.xyz, maybe that should go under the self contained section, with i2p, as it requires that?
