### ISSUE TITLE
🆕 Software Suggestion | Lavabit

### ISSUE THREAD

**Issue by JonahAragon** [privacytoolsIO/privacytools.io#1546]
## Basic Information

**Name:** Lavabit
**Category:** "Interesting Email Providers Under Development"
**URL:** https://lavabit.com/

## Description

Lavabit is back and appears to be developing their own mail protocol for secure communication. Since we list [Confidant](https://www.confidantmail.org/) here would we want to list this as well?

**Comment by ManMade-cube42** [comment]
Ya'll may consider adding Magma (by lavabit) to self-hostable email clients:

https://magmadaemon.org/

**Comment by Mikaela** [comment]
From the descrption and link I guess this issue means Flow, Volcano and Magma?

![kuva](https://user-images.githubusercontent.com/831184/71697441-abf2ac80-2dc0-11ea-8350-075e5d56b3a3.png)

**Comment by nitrohorse** [comment]
Their marketing for Flow however makes it sound that this definitely a stable product and not “in development.” 🤔

> ...Flow is the most secure email solution available in the world.

**Comment by JonahAragon** [comment]
> I guess this issue means Flow, Volcano and Magma?

No, it means Lavabit. But I suppose they could also be considered.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
They also started this a while ago, but it looks dead since the website is pretty horrible in terms of design and it hasn't been updated. https://darkmail.info/
From the wikipedia webpage: 

> The Dark Mail Alliance is an organization dedicated to creating an email protocol and architecture with end-to-end encryption.
> 
> In October 2013, Silent Circle and Lavabit announced a project to create a more secure alternative to email and began a fundraising effort. The Dark Mail Alliance team consists of Phil Zimmermann, Jon Callas, Mike Janke, and Ladar Levison.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> 
> 
> > I guess this issue means Flow, Volcano and Magma?
> 
> No, it means Lavabit. But I suppose they could also be considered.

I think Magma is dead also? From their website: 

>9-19-18 Code Cleanup
>
>The v7.0.92 point release is available. This release contains a large number of minor improvements, code cleanup changes reccomended by static analysis tools, and bug fixes. This version also address several minor issues affecting alternative Linux distributions.

**Comment by sakura974201** [comment]
DNS CAA is not set.
It is not good.
https://www.hardenize.com/report/lavabit.com/1585052333

**Comment by blacklight447-ptio** [comment]
> DNS CAA is not set.
> It is not good.
> https://www.hardenize.com/report/lavabit.com/1585052333

we don't require dns CAA as we already require DANE.
However,  lavabit seems to lack mta-sts and TLS-RPT, which we do require, which is why we are not able to add lavabit at this time.
