### ISSUE TITLE
Remove Ubuntu Mobile

### ISSUE THREAD

**Issue by soaringowl2145** [privacytoolsIO/privacytools.io#155]
It seems that the project will no longer be continued.  Source:

http://www.omgubuntu.co.uk/2017/01/ubuntu-phone-ota-15-ditched

**Comment by bookercodes** [comment]
Although Cannonical will continue to release security patches for Oxide, etc., I do not think we should promote sunset tools.


What do you recommend we replace Ubuntu Mobile with? [Replicant](http://www.replicant.us/)?

**Comment by soaringowl2145** [comment]
By sunset tools do you mean dead projects?

**Comment by Shifterovich** [comment]
#196
