### ISSUE TITLE
🆕 Software Suggestion | lukol search engine

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#1557]
## Basic Information

**Name:** lukol
**Category:** https://www.privacytools.io/providers/search-engines/
**URL:** https://www.lukol.com/

## Description
anonymous search engine
Powered by Google custom search

**Comment by danarel** [comment]
They use Google cookies to serve you ads. This isn't a privacy respecting search engine. They don't collect your personal information, but they allow Google to.
