### ISSUE TITLE
🌐 Website Issue | Confusing XMPP vs Matrix sentence

### ISSUE THREAD

**Issue by alohapersona** [privacytoolsIO/privacytools.io#1561]
## Description
The current website has the following sentence on https://www.privacytools.io/software/real-time-communication/:
> Unlike Matrix, clients are only developed by the community and not by the foundation itself.

I think this sentence is both confusing and misleading for various reasons:
- There is no XMPP Foundation, only the XMPP Standards Foundation (XSF). The name already suggests it's a guardian organization for the standard and thus doesn't develop any clients.
- The XSF is a community foundation - a membership organization where majority of developing community is directly or indirectly involved. All "positions" within the XSF are elected by the members. Thus there is no real difference between community and XSF.
- There is no mentioning of the XSF before, so it's a little unclear which foundation you talk about.
- Riot, the reference client of Matrix, is developed by _New Vector, Ltd._ **not** _The Matrix.org Foundation C.I.C._, thus this is not "unlike".
- "*only* developed by the community" sounds as if that was something bad. Both the community and the XSF are in fact rather diverse, companies that develop XMPP software (like ProcessOne, Isode, Tigase) are represented in the XSF through their employees (but the XSF has a restriction in the bylaws to ensure no company can take over more than 15% of the foundation with their employees).

I thus suggest to replace the aforementioned sentence with something like:
> Multiple clients (and servers) are developed independently by a diverse community.

If you want to keep some "unlike Matrix", one could prepend that sentence with:
> Unlike Matrix, there is no reference client implementation.

**Comment by Mikaela** [comment]
> Riot, the reference client of Matrix, is developed by New Vector, Ltd. not The Matrix.org Foundation C.I.C.

I commented this also and Matthew from there commented that they are practically the same thing or have same people inside, but I am unable to find their comments in #1500 anymore and GitHub only links me to https://github.com/privacytoolsIO/privacytools.io/pull/1500/files/f35df6b7b2cbdcd49d51a1d2ac483404a12387f0 which tells me that it cannot find anything.

On the rest at the moment the only thing I can do is assign @dngray (for #1500) and myself so either of us can look at this at a better time.

**Comment by dngray** [comment]
> I commented this also and Matthew from there commented that they are practically the same thing or have same people inside, but I am unable to find their comments in #1500 anymore and GitHub only links me to https://github.com/privacytoolsIO/privacytools.io/pull/1500/files/f35df6b7b2cbdcd49d51a1d2ac483404a12387f0 which tells me that it cannot find anything.

@ara4n 's comment is here https://github.com/privacytoolsIO/privacytools.io/pull/1500#discussion_r349962616

As for the other points I will review those, shortly. I do think some of the suggestions are improvements.

**Comment by dngray** [comment]
I have thought about this, now that there's too much information, and XMPP does not have a card, we could go with https://github.com/privacytoolsIO/privacytools.io/pull/1574 perhaps.
