### ISSUE TITLE
🌐 Website Issue | Should Signal (Android) have a warning about the insecurity of SMSes?

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1573]
## Description

Currently the card just says:

> All communications are E2EE unless you choose to send as SMS. 

I wonder if it should be expanded to warn about SMSes in general and how the carrier can read them and store/share them and what other problems there are? Or perhaps there should be a blog post we could link to?

This was brought up to me as a result of a private query asking about #859 and referring to Signal's metadata when SMS option is chosen.

**Comment by blacklight447-ptio** [comment]
Ehh, as this isn't a signal issue, i would say your better off making a seperate section of why sms is bad.

**Comment by danarel** [comment]
This was discussed in a group chat a while back and I think it fell somewhere in the realm that @blacklight447-ptio mentioned. The insecurity of SMS isn't Signal's fault and they make no claim that if you choose to use Signal as your SMS messenger than those texts are E2EE. 

The description on PT also states "All communications are E2EE unless you choose to send as SMS." - which I would say makes it clear enough that this is the case. I think a warning would be overkill and make it seem as though it's a security flaw in Signal.

**Comment by Mikaela** [comment]
https://github.com/privacytoolsIO/privacytools.io/issues/1578
