### ISSUE TITLE
🌐 Website Issue | Bromite description

### ISSUE THREAD

**Issue by csagan5** [privacytoolsIO/privacytools.io#1588]
I have seen in the past some privacytoolsIO GitHub issues about Bromite but I have only loosely followed them; now I realise it is a recommendation in the [browsers section of the website](https://www.privacytools.io/browsers/).

I have a suggestions to improve the description: if one has to choose a single project to mention for the patches, I would mention [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium) rather than [GrapheneOS](https://grapheneos.org/) because there are only few patches used from the latter (the majority are Bromite patches, see [here](https://github.com/bromite/bromite/tree/master/build/patches)).

Aside from that, great work on the website! It looks very clear and understandable for different types of visitors.

Edit: not sure why it got added the `high priority` label on its own, maybe it's a default - but I do not consider this as high priority.

**Comment by blacklight447-ptio** [comment]
Yeah the label is the default ( note to self, I should probbaly change that) in any case, who you like to make a quick PR for this? :)
