### ISSUE TITLE
🆕 Software Suggestion | Criptext (Secure Email)

### ISSUE THREAD

**Issue by wuniversales** [privacytoolsIO/privacytools.io#1589]
Name: Criptext
Category: Secure Email
URL: https://criptext.com/

I recently discovered this tool that I think can be very useful for the security of our emails.
Take a look to see what you think.
Cheers

**Comment by danarel** [comment]
This came up in the PrivacyTools AMA on Reddit. The comment I link to is rather credible, and correct in his assesment and for that, I would not recommend Criptext at all.

https://www.reddit.com/r/privacy/comments/dn09g8/we_are_the_privacytoolsio_team_ask_us_anything/f59e2l4/?utm_source=share&utm_medium=web2x

**Comment by dngray** [comment]
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/1287
