### ISSUE TITLE
Add Onionshare

### ISSUE THREAD

**Issue by e5f3c2ea895af0f27667** [privacytoolsIO/privacytools.io#160]

**Comment by Hillside502** [comment]
To put some flesh on the VERY bare bones:-

Onionshare
https://onionshare.org/

micahflee/onionshare: Securely and anonymously share a file of any size
https://github.com/micahflee/onionshare

DuckDuckGo
https://duckduckgo.com/?q=Onionshare

Onionshare Alternatives and Similar Software - AlternativeTo.net
https://alternativeto.net/software/onionshare/

**Comment by bookercodes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Something else](https://trello.com/c/hfNKBEZM/2-something-else)

**Comment by kewde** [comment]
I have heard of this before, under which section would this go?

**Comment by Hillside502** [comment]
@kewde 
suggest File Encryption Software
https://www.privacytools.io/#encrypt

**Comment by bezcitu** [comment]
@Hillside502 
OnionShare is a tool for anonymous file sharing and not a tool for file encryption.

**Comment by Hillside502** [comment]
@bezcitu 
then, maybe as a footnote to:-
Self-contained Networks
https://www.privacytools.io/#network

**Comment by Shifterovich** [comment]
Or make a new section with OnionShare and SecureDrop?

**Comment by Hillside502** [comment]
SecureDrop
https://securedrop.org/

SecureDrop - Wikipedia, the free encyclopedia
https://en.wikipedia.org/wiki/SecureDrop

**Comment by kewde** [comment]
A new section seems appropriate. What should the name in case we go that route?

On a personal note, is it right to assume that OnionShare is more targeted at providing a tool for individuals looking to quickly and secretly share a file? SecureDrop IMO seems more like a tool for businesses and news orgs etc. Not that it matters, I just like to make the distinction in my head :P

**Comment by e5f3c2ea895af0f27667** [comment]
@Shifterovich Maybe make a new "File Sharing" section?

**Comment by Shifterovich** [comment]
The name of the section would make BitTorrent elitists angry if we didn't mention the BitTorrent protocol :P. Anyway, I can recommend I2PSnark and iMule as file sharing tools.

**Comment by kewde** [comment]
address in #192

**Comment by kewde** [comment]
addressed in #162
