### ISSUE TITLE
🌐 Website Issue | Move the text to proper place

### ISSUE THREAD

**Issue by GrimPixel** [privacytoolsIO/privacytools.io#1611]
## Description
In this page https://www.privacytools.io/software/real-time-communication/
The text
"If you are currently using an Instant Messenger like Telegram, LINE, Viber, WhatsApp, or plain SMS, you should pick an alternative here."
is placed under "Centralized - Disadvantages". In fact, if someone want to replace these centralized apps, they can also choose Federated and Peer-to-Peer. The text should be moved to just under "Encrypted Instant Messengers".

**Comment by Mikaela** [comment]
@dngray What do you think, should I assign this to you?

**Comment by GrimPixel** [comment]
I have already created a pull request. I am new to all this stuff. If it breaks any rule I don't know, I feel sorry.
https://github.com/privacytoolsIO/privacytools.io/pull/1612

**Comment by GrimPixel** [comment]
Hello? Seems didn't work? @Mikaela @dngray

**Comment by Mikaela** [comment]
@JonahAragon Is there some issue with Netlify not having deployed #1612 when it was merged? It's correct [in the preview](https://deploy-preview-1612--privacytools-io.netlify.com/software/real-time-communication/), but [not the live site](https://www.privacytools.io/software/real-time-communication/).
