### ISSUE TITLE
🌐 Website Issue | Remove DNSCrypt from Cloudflares listed protocols

### ISSUE THREAD

**Issue by User486375** [privacytoolsIO/privacytools.io#1616]
## Description
Seems pretty redundant to have to make an issue but pull requests say it's required. Cloudflare has never supported the DNScrypt protocol only DoH and DNS over TLS.

See https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/#dnscrypt-proxy

**Comment by dawidpotocki** [comment]
> Seems pretty redundant to have to make an issue but pull requests say
> it's required

It's not.
