### ISSUE TITLE
🆕 Software Suggestion | EncFs

### ISSUE THREAD

**Issue by haluzpav** [privacytoolsIO/privacytools.io#1620]
## Basic Information

**Name:** EncFs
**Category:** Encryption Tools
**URL:** https://vgough.github.io/encfs/

## Description

Per-file encryption, useful for cloud. Similar to Cryptomator, which you already include.

I understand you must have given EncFs a thought before but I couldn't find any discussion about it. It's not as shiny as Cryptomator, but EncFs is older and IMHO more established (e.g. it is included in Linux repos).

I think it deserves public reason for rejection. Is it only because of lower user-friendliness and similarity to Cryptomator, or does is also have other issues?

**Comment by Mikaela** [comment]
I was upgrading one Ubuntu to 20.04 and got this prompt earlier today:

```
 ┌────────────────────────┤ encfs:n asetusten säätö ├────────────────────────┐  
 │                                                                           │  
 │ Encfs security information                                                │  
 │                                                                           │  
 │ According to a security audit by Taylor Hornby (Defuse Security), the     │  
 │ current implementation of Encfs is vulnerable or potentially vulnerable   │  
 │ to multiple types of attacks. For example, an attacker with read/write    │  
 │ access to encrypted data might lower the decryption complexity for        │  
 │ subsequently encrypted data without this being noticed by a legitimate    │  
 │ user, or might use timing analysis to deduce information.                 │  
 │                                                                           │  
 │ Until these issues are resolved, encfs should not be considered a safe    │  
 │ home for sensitive data in scenarios where such attacks are possible.     │  
 │                                                                           │  
 │                                  <OK>                                     │  
 │                                                                           │  
 └───────────────────────────────────────────────────────────────────────────┘  
```

Probably needs more research and putting a warning if we start listing it.

**Comment by Mikaela** [comment]
Possbly relevant links:

* https://defuse.ca/audits/encfs.htm - the audit itself
* https://github.com/vgough/encfs/labels/2.x%20candidate - label which I understand to contain issues mentioned in the audit?

@privacytoolsIO/content I wonder if we should close this for now?

**Comment by danarel** [comment]
I'd vote to close it. Doesn't seem like something we should recommend.

**Comment by dngray** [comment]
I think this might have be been on privacytools.io and removed ages ago. I think it's mostly been superseded by [eCryptfs](https://en.wikipedia.org/wiki/eCryptfs) in most Linux distributions.

**Comment by Mikaela** [comment]
I take it that we can close this in favour of https://github.com/privacytoolsIO/privacytools.io/issues/1631.
