### ISSUE TITLE
🆕 Software Suggestion | OpenSMTP (+ IMAP/POP Server)

### ISSUE THREAD

**Issue by ManMade-cube42** [privacytoolsIO/privacytools.io#1626]
## Basic Information

**Name:** [OpenSMTP](https://www.wikipedia.org/wiki/OpenSMTPD) + IMAP/POP Client (example: [Dovecot](https://www.wikipedia.org/wiki/Dovecot_(software)))
**Category:** [Become Your Own Email Provider](https://www.privacytools.io/providers/email/)
**URL:** https://www.opensmtpd.org/
**Developer**: OpenSMTPD is part of the [OpenBSD Project](https://www.openbsd.org/).
**License**: "[...] an ISC license" [[1](http://archive.ph/LCDol)]

## Description

> OpenSMTPD is a Unix system daemon implementing the Simple Mail Transfer Protocol to deliver messages on a local machine or to relay them to other SMTP servers. - [Wikipedia](https://www.wikipedia.org/wiki/OpenSMTPD)

Considering OpenSMTP is only an SMTP server, users will likely also want an IMAP server (example: [Dovecot](https://www.wikipedia.org/wiki/Dovecot_(software)))

**Tutorial**: https://poolp.org/posts/2019-09-14/setting-up-a-mail-server-with-opensmtpd-dovecot-and-rspamd/

________________________

In my experience, clients like Mail-In-A-Box lack the required documentation for users of platforms like BSD or even popular Linux distros like Debian; For example Mail-in-a-Box only has docs for Ubuntu. [[2](http://web.archive.org/web/20200102215620/https://mailinabox.email/guide.html)]

**Comment by Mikaela** [comment]
@dngray thoughts?

**Comment by dngray** [comment]
We could incorporate this into the new email section, but would very much have to be under an advanced heading. Setting up a mail server and maintaining it is by no means a trivial process.

#### 20 Aug 2017
- [How To Run Your Own Mail Server (c0ffee.net)](https://www.c0ffee.net/blog/mail-server-guide/)

**Comment by ManMade-cube42** [comment]
> We could incorporate this into the new email section, but would very much have to be under an advanced heading. Setting up a mail server and maintaining it is by no means a trivial process.

I definitely agree, anyone attempting to set up their own email server is going to be unleashed to a moderately difficult set of tools and pieces of software. 

However as I stated in my original post, I do think users will realize that not all of them are running supported platforms by Mail-in-a-Box like OpenBSD or even CentOS. 
Other users will probably want something a bit easier and lightweight than MailCow.

For these instances, OpenSMTP could really thrive.

________________________________

Also, I do think much of the headache with setting up a server is the documentation.
Perhaps, PTIO and c0ffee.net could help with this, and add links to a tutorial.

**Comment by dngray** [comment]
> **Edit**: Users may also want to consider the resources provided by [IRCNow](https://ircnow.org/kb/doku.php?id=openbsd:mail).

We will only be putting high quality resources there. That page is largely missing any meaningful documentation. It won't be added.

> For these instances, OpenSMTP could really thrive.

OpenSMTP is only one piece of the complete puzzle, we're not going to start recommending individual pieces.
