### ISSUE TITLE
✨ Feature Suggestion | Add a Chelsea Manning quote?

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1629]
## Description

Suggestion from the forum, please see the forum thread for more details.

https://forum.privacytools.io/t/changing-or-adding-a-chelsea-mannings-quote-on-the-home-page/2390?u=mikaela

**Comment by Mikaela** [comment]
> What about a “how we got here” section that plays homqge to all the privacy heroes?

[Asks Someone](https://forum.privacytools.io/t/changing-or-adding-a-chelsea-mannings-quote-on-the-home-page/2390/11?u=mikaela) in the forum thread.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Hello Mikaela, has more thought been put into this? You told me this was an easy thing to do and I do understand you are under a lot of work now, but I just wanted to know if it has been talked at least. Thanks!

**Comment by nitrohorse** [comment]
I do like this idea. For reference here’s the suggested quote from the forum post:
> If you deny my request for a pardon, I will serve my time knowing that sometimes you have to pay a heavy price to live in a free society. I will gladly pay that price if it means we could have a country that is truly conceived in liberty and dedicated to the proposition that all women and men are created equal.

Additionally I also found this quote from [a piece she wrote](https://www.theguardian.com/commentisfree/2016/feb/22/privacy-is-a-right-not-a-luxury-and-its-increasingly-at-risk-for-lgbt-people):
> Privacy is not a luxury in America: it is a right – one that we need to defend in the digital realm as much as in the physical realm.

**Comment by nitrohorse** [comment]
Created a PR to get some traction on this. I just added the privacy-related quote although both are great.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Thanks @nitrohorse ! I  really can't decide between those two, on one side -as stated by Mikaela- one mightbe more  broader or international but focuses more on the subject of privacy, and the other while it is more universal in terms of nationality, does not have such a clear reference to privacy; although it clearly intertwines.

I would prefer to hear someone else's opinion or that you decide tbh.

Thanks again! <3
