### ISSUE TITLE
❌ Software Removal | Firefox

### ISSUE THREAD

**Issue by smnthermes** [privacytoolsIO/privacytools.io#1637]
## Description

Aside from not even releasing the source code for Pocket (which is integrated to Firefox), Mozilla has now a strong partnership with Cloudflare, whose problems are well known: https://codeberg.org/crimeflare/cloudflare-tor/src/branch/master/README.md

Therefore, only **Tor Browser** should be recommended.
Edit: SecBrowser is also a good choice: https://www.whonix.org/wiki/SecBrowser

**Comment by blacklight447-ptio** [comment]
We have already had very long threads about whether to keep firefox or not.
Also we are aware of the issues with cloudflare.


Really though, you need to understand that people have different threatmodels, and only recommending tor browser will mean a lot of people who are new to privacy will be scared away, which goes against our goal: bring privacy to the masses. In the end i hope you want to take a look at the firefox issues which have been discussed on here before, closing for now.

**Comment by beerisgood** [comment]
> SecBrowser ™ default configuration offers better security than Firefox, Google Chrome or Microsoft Edge

I would call this misinformation. Chrome and new (Chromium-) Edge had a lot better isolation/ sandbox and more hardening then Firefox.

**Comment by Mikaela** [comment]
Previous issues: https://github.com/privacytoolsIO/privacytools.io/issues/1375 https://github.com/privacytoolsIO/privacytools.io/issues/856
