### ISSUE TITLE
Seafile for Cloud Storage Service

### ISSUE THREAD

**Issue by albertocoronado** [privacytoolsIO/privacytools.io#164]
This has been on my mind for a bit now so I figured I would just ask. 

I used to use Seafile as my main cloud provider and everything was fine until months ago when Seafile Ltd. had a legal problem with Seafile GmbH, someone did the other one wrong. 
[https://blogs.seafile.com/2016/07/22/statement-about-stopping-cooperation-with-seafile-gmbh/](https://blogs.seafile.com/2016/07/22/statement-about-stopping-cooperation-with-seafile-gmbh/)

So long story short I believe [Seafile.com](https://www.seafile.com/en/home/) does not offer the cloud service hosted in Germany anymore, now it's [Seafile.de](https://seafile.de/en/) (with a different color logo also) and their prices start at 0,84 €/month for 10GB and goes up from there. [https://shop.seafile.de/en/product/seafile-cloud-account-subscription/](https://shop.seafile.de/en/product/seafile-cloud-account-subscription/)

So, can we still promote Seafile for cloud storage after everything that happened? Is Seafile GmbH trustworthy? 

I am asking for opinions here, I had data on their German servers before everything went down. I feel like it's too much to worry about just to have my files "safe" in the cloud. Also, if I am wrong on anything I typed, please let me know. 

If Seafile stays on the website, it needs to have updated information.

**Comment by jospoortvliet** [comment]
It highly depends on what you are looking for here. Security isn't Seafile's stong point anyway with very few developers, no security experts, self-developed encryption and no public security bug bounty program or clearly defined and followed security processes. 

But development is still happening, it isn't dead so if that is the concern then you can keep it. But don't link to the German project. From what I've heard the German side is mostly dead. At the moment the site even has an invalid security certificate so I can't see if it is still up but I wouldn't trust a team that can't even maintain TLS...
![spectacle z16509](https://user-images.githubusercontent.com/551757/27013625-6077f568-4ee7-11e7-9db6-bc89d38f23af.png)

The Chinese team continues development and offers support etc so they are alive and active. They do not offer hosting, from what I can tell.

**Comment by Vincevrp** [comment]
#491
