### ISSUE TITLE
🆕 Software Suggestion | Oscobo

### ISSUE THREAD

**Issue by wuniversales** [privacytoolsIO/privacytools.io#1640]
Name: Oscobo
Category: Search Engine
URL: https://www.oscobo.com/

Another search engine, supposedly private, from london, uk
https://www.oscobo.com/ctnt.php?c=privacy

**Comment by Mikaela** [comment]
Would you mind also performing and commenting research by yourself and opening PRs sometime too and not only issues?

**Comment by wuniversales** [comment]
Excuse me, I find interesting websites and I post it in case someone wants to dig deeper.
I will try to change this.
Thank you

**Comment by Mikaela** [comment]
I have opened https://github.com/privacytoolsIO/privacytools.io/pull/1651 which I hope to resolve this.

**Comment by sakura974201** [comment]
It's SSL3.0 enabled.
It is not good.
https://www.hardenize.com/report/oscobo.com/1585051900#www_tls

**Comment by Mikaela** [comment]
Thank you
