### ISSUE TITLE
✨ Feature Suggestion | Create a list of Nextcloud providers

### ISSUE THREAD

**Issue by xDazlD** [privacytoolsIO/privacytools.io#1647]
## Description
Would be almost identical to the DNS/email section. The criteria for selecting providers would need to be worked out. Self hosting should also still be mentioned.

**Comment by Mikaela** [comment]
I don't think this would bring additional value to anyone. There wasn't a page like our DNS page before we made it while even the homepage of Nextcloud has an instance picker.

* https://nextcloud.com/signup/

**Comment by danarel** [comment]
Yeah, I don't think this would be helpful and would take a lot of work to test and vet each provider.
