### ISSUE TITLE
🆕 Software Suggestion | Pass

### ISSUE THREAD

**Issue by FishCoding** [privacytoolsIO/privacytools.io#1648]
## Basic Information

**Name:** Pass
**Category:** Password Manager
**URL:** https://www.passwordstore.org/ 

## Description
It is a password manager that basically uses GPG keys as a method of encryption and decryption and contain all the password in a git repository (password storage).

**Comment by adalricus** [comment]
I'm surprised pass was not listed here. @Mikaela I could help with research on this. It's a simple password manager which uses existing tools, each entry is a gpg encrypted file store in pass root directory ($HOME/.passwordstore is default).

Example tree:
```
Password Store
├── service1.org
│   ├── accounts
│   └── email
├── service2.com
│   └── www
├── Bank
│   └── bank1
```
Other users having access to pass root directory (which they shouldn't have, it should be rwx------) can read services names.

**Comment by FishCoding** [comment]
It also has several plugins to for example be less permissive with the folder hierarchy encrypting the folder tree and more. Other plugins allow generating 2FA codes. 

In the overall, it's not more than a bash script for encrypting and decrypting the passwords with the gpg pair keys.

**Comment by Mikaela** [comment]
Would any of you mind making a PR?

@privacytoolsIO/editorial and would any of you mind researching this? I imagine it's encryption should be OK if it really does use GPG for that.

**Comment by dngray** [comment]
I actually use pass already, for mbsync, msmtp, vdirsyncer It's really quite good.
