### ISSUE TITLE
add Tor Link to ProtonMail

### ISSUE THREAD

**Issue by victorhck** [privacytoolsIO/privacytools.io#165]
Since ProtonMail has recently launched their own .onion domain in Tor Network [1] to add an extra security layer [2] 
Maybe make sense to add the link somewhere?

Regards

[1] https://protonmail.com/tor
[2] https://protonmail.com/blog/tor-encrypted-email/

**Comment by kewde** [comment]
dealt with in #166

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@Shifterovich This has been fixed.
