### ISSUE TITLE
🆕 Software Suggestion | ELUDE MAIL (MAIL SUGGESTION)

### ISSUE THREAD

**Issue by sell** [privacytoolsIO/privacytools.io#1652]
## Basic Information

**Name:** Elude
**Category:** Email
**URL:** eludemaillhqfkh5.onion
**URL:** elude.in is there normal url but you are not able to use the email on it, it will tell you how to sign up and lead you to the tor link.

## Description
Email service that only works on tor, and they collect no ip address, no Browser fingerprint, and no Message metadata. They also do not use any scripts that track users. All mail is encrypted and they collect very little data. You are also to delete your account whenever and everything will be deleted. You also do not need another email/phone to register. 

**Information they do collect:**
- Registration information ("When you create an account, we retain the date you registered and the alternate email address that you specify. You may choose to delete your alternate email address after short period of time, but if you do so, we will not be able to restore access to your account if you lose the password.")
- Session identifiers ("we keep a temporary session identifier on your computer that prove your authentication state. This is erased immediately after you log out or the session expires. We do not use any third party cookies or tracking of any kind.")
- Email transit logs ("In order to detect when our servers are under attack from a “spam bombs” or when a spammer is using our system, we keep a log of the “from” and “to” information for every message relayed. These logs are purged on a daily basis.")
- Last login month ("We keep a record of the current calendar month and year of your last successful authentication (in order to be able to disable and delete dormant accounts).
The exact date and time of the last log in is not recorded.")

Privacy policy: eludemaillhqfkh5.onion/privacy-policy

## Why am I making this suggestion?
I am making this suggestion because it is a great alternative to the other mail services you have listed. You do not need a email to make an account with this service. It only works on tor, has no trackers. Also, collects almost no data. 

## My connection with the software
I am not connected to the software in any way, I am just a user of the platform and I believe it is a great choice.

**Comment by sell** [comment]
I am not familiar with github, so I do not know how to really add labels, sorry.

**Comment by Mikaela** [comment]
Would you mind also responding to the questions presented by #1651 ?

>  * Why I am making the suggestion
> * My connection with the software

> I am too not familiar with github, so I do not know how to really add labels, sorry.

Sadly that can only be done by issue tracker collabators or organisation members.

**Comment by sell** [comment]
> Would you mind also responding to the questions presented by #1651 ?
> 
> > * Why I am making the suggestion
> > * My connection with the software
> 
> > I am too not familiar with github, so I do not know how to really add labels, sorry.
> 
> Sadly that can only be done by issue tracker collabators or organisation members.

I updated it, and added those two.

**Comment by sell** [comment]
Does this mean that dngray is adding it under the new email section, or is there going to be a new way to request for email services?

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Why is this issue being closed?

**Comment by dngray** [comment]
Couple of reasons:

It does not meet the minimum requirements https://www.privacytools.io/providers/email/#criteria in particular MTA-STS, TLS-RPT and DANE.

Although this service is only accessible via .onion service, anyone who sends you email is going to benefit from these things.

Secondly, I would not suggest you trust your email with anonymous parties. Trust is a huge part of any of our recommendations, and we really have no idea who runs this service.
