### ISSUE TITLE
🌐 OpenCollective Issue | Issue with Pricing on Sponsors page (Quick Fix)

### ISSUE THREAD

**Issue by sell** [privacytoolsIO/privacytools.io#1653]
## Description
On the https://opencollective.com/privacytoolsio/contribute/bronze-12311 page it states that gold is $1,000 a month, but on the gold page (https://opencollective.com/privacytoolsio/contribute/gold-12312) it states that it is $500 a month. I am unable to upload screen shots.

Also on the silver page the price is messed up. 
**url:** https://opencollective.com/privacytoolsio/contribute/silver-12313

**Comment by Mikaela** [comment]
![kuva](https://user-images.githubusercontent.com/831184/72469376-f2480280-37e7-11ea-9b37-2f2f76dda8bc.png)

![kuva](https://user-images.githubusercontent.com/831184/72469400-fb38d400-37e7-11ea-9b8c-77fb25ddb276.png)

![kuva](https://user-images.githubusercontent.com/831184/72469413-03910f00-37e8-11ea-9d6c-8d1956a131a0.png)

**Comment by JonahAragon** [comment]
Thank you!

**Comment by sell** [comment]
No problem @JonahAragon 👍 , quick question how does one make it too the contribution list? Does one of our service suggestions have to added to the site to be added to the contribution list?
