### ISSUE TITLE
🆕 Software Update | ProtonVPN

### ISSUE THREAD

**Issue by JonahAragon** [privacytoolsIO/privacytools.io#1655]
## Basic Information

**Name:** ProtonVPN
**Category:** Providers: VPN
**URL:** https://protonvpn.com/blog/open-source/

## Description

ProtonVPN has now open sourced client apps on all major platforms, and has undergone an independent security audit of said client applications. They theoretically now meet all of our criteria for inclusion, so we should review and reevaluate their listing.

**Comment by danarel** [comment]
I second this. I would personally love to see them promoted.

**Comment by dngray** [comment]
See https://github.com/privacytoolsIO/privacytools.io/pull/1658
