### ISSUE TITLE
🌐 Website Issue | Qubes OS

### ISSUE THREAD

**Issue by sell** [privacytoolsIO/privacytools.io#1659]
## Description
Was curious if I was able to make a pull request about adding another button for system requirements on
https://www.privacytools.io/operating-systems/#os for the qubes os as it does need a pretty good pc to run it.

**Comment by sell** [comment]
Something like this:

![Screenshot_2020-01-23 Operating Systems PrivacyTools](https://user-images.githubusercontent.com/34258275/72974109-7ed06300-3d9c-11ea-9802-42d8f5873bda.png)

**Comment by dawidpotocki** [comment]
I'm not a fan of this idea.

**Comment by sell** [comment]
@dawidpotocki oh okay, sorry. Just wasn't sure, simply because Qubes needs a pretty good machine to run.

**Comment by danarel** [comment]
> I'm not a fan of this idea.

Same. I do think we need to assume someone looking at a new OS will go ahead and look at the system requirements on their own. I would hate to over confuse users with too many buttons.

**Comment by sell** [comment]
> > I'm not a fan of this idea.
> 
> Same. I do think we need to assume someone looking at a new OS will go ahead and look at the system requirements on their own. I would hate to over confuse users with too many buttons.

Okay sorry for bad suggestion, will close it.
