### ISSUE TITLE
❌ Software Removal | Status.im

### ISSUE THREAD

**Issue by wuniversales** [privacytoolsIO/privacytools.io#1661]
I comment, I have tried this software on my android (Without google services installed), and just open the application, a sign appears indicating that it requires the services of google play.
By pressing accept, the application continues to run smoothly.
But the truth is, I am not inspired by this app that uses Google services for its operation.
Maybe google services, if they track the ip using the services that the application requires.

**Comment by danarel** [comment]
Doesn't seem like this warrants a post calling for its removal though. I don't use plenty of the services we recommend and some because I don't personally like them, but if they accomplish the goal of giving someone better control of their data, then why remove it unless it's malicious?

Also, I think being under worth mentioning and labeled as experimental also ensures that it's not "highly recommended" but something we think is good, but not top of the line, if that makes sense.

**Comment by sell** [comment]
I am not sure how come, the only google service they use are the fonts as stated in there privacy policy. Also, they parted ways with using google analytics in 2018. So they do not use google analytics to collect your data/ip. I feel as though this is not a good reasoning for removal as you do have an android device, and you use the google play store I assume. 

Here is the privacy policy of the applications they use: [Status Privacy Policy](https://www.iubenda.com/privacy-policy/94457202)

**Comment by wuniversales** [comment]
Google keeps the information of your ip, it is understandable that Status.im does not collect data.
But when using google, you know, google keeps the ip, as a result of your location, etc ...
We know how Google works, which sells up the socks we use.
Step screenshot with the warning message that I don't have google services.
![image](https://user-images.githubusercontent.com/48658161/73109450-6a5aaa80-3f03-11ea-9c51-0dbb725e35cd.png)
I do not consider "Safe Service" to something that is using non-open features of google, in this case the services of google play.
regards

**Comment by JonahAragon** [comment]
We recommend a lot of apps that use Google Play Services while not necessarily requiring them: Signal, Riot, Keybase...

If Status *required* Google Play that'd be a different story.
