### ISSUE TITLE
🆕 Software Suggestion | Independent security audits for IVPN

### ISSUE THREAD

**Issue by djoate** [privacytoolsIO/privacytools.io#1664]
## Basic Information

**Name:** IVPN
**Category:** VPN
**URL:** https://www.ivpn.net/blog/independent-security-audit-concluded

## Description
IVPN has now released the results of their independent security audit.

## Why I am making the suggestion

The PrivacyTools VPN page has "No Security Audit" as a blocker for recommendation.

**Comment by Mikaela** [comment]
Why do you remove these sections from the issue template?

> My connection with the software
[x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
See https://github.com/privacytoolsIO/privacytools.io/pull/1667

**Comment by dngray** [comment]
> The PrivacyTools VPN page has "No Security Audit" as a blocker for recommendation.

Yes, we do have that requirement. The only reason these providers stayed is because we knew ahead of time about the audits.

**Comment by Mikaela** [comment]
I prefer to keep issues open until the PRs referencing them are merged and close them automatically so  it's easier to see that the issue has been reported and is being worked upon.
