### ISSUE TITLE
🆕 Software Suggestion | Bisq

### ISSUE THREAD

**Issue by wuniversales** [privacytoolsIO/privacytools.io#1666]
Name: Bisq
Category: Exchange
URL: https://bisq.network/

Simply from the best exchange programs.
Being an open source program, it is known that it does not save logs.

Characteristics:
- 100% anonymous
- Decentralized
- Works through the tor network
- No records
- Open source https://github.com/bisq-network

**Comment by sell** [comment]
I dont see any bad rep on this exchange, I do see that it is slow. I cannot confirm nor deny it as I never used it. 

I found a pretty good [review](https://www.forexbrokerz.com/brokers/bisq-review) about bisq.

**Comment by danarel** [comment]
Currently, PT doesn't recommend any crypto exchanges or wallets and I don't know of any plans to do so at the moment.

**Comment by sell** [comment]
Okay, I don't see a problem with that. With crypto wallets and exchanges, I feel as though we should do our own prior research and choose a one that we want to use.

**Comment by Mikaela** [comment]
In addition to the previous comments, you haven't stated your connection with Bisq and you are missing the reasons why you are making the suggestion that is part of the issue template.
