### ISSUE TITLE
🆕 Software Suggestion | ForwardEmail.net Email Provider

### ISSUE THREAD

**Issue by niftylettuce** [privacytoolsIO/privacytools.io#1671]
## Basic Information

**Name:** ForwardEmail
**Category:** Email
**URL:** https://forwardemail.net

## Description

Create and forward an unlimited amount of email addresses with your domain name. Plus get catch-all, wildcard, and disposable forwarding addresses. It is 100% open-source.

About: https://forwardemail.net/en/about
Privacy Policy: https://forwardemail.net/en/privacy (we don't store logs nor emails)
Terms: https://forwardemail.net/en/terms

## Why I am making the suggestion

No email-forwarding service existed that was free, secure, and open-source – so we built one.

## My connection with the software

I am the author.

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by niftylettuce** [comment]
@dngray 	I don't see ForwardEmail mentioned anywhere - not sure why this was closed, but I think it should be added to the Email Cloaking section at <https://www.privacytools.io/providers/email/#cloaking>.  We do not store logs and have a way better privacy policy than any other service that exists.  We don't store any logs and I set up load balancing around the world using Cloudflare's privacy-first load balancing and DNS.

cc @Mikaela

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> @dngray I don't see ForwardEmail mentioned anywhere - not sure why this was closed, but I think it should be added to the Email Cloaking section at https://www.privacytools.io/providers/email/#cloaking. We do not store logs and have a way better privacy policy than any other service that exists. We don't store any logs and I set up load balancing around the world using Cloudflare's privacy-first load balancing and DNS.
> 
> cc @Mikaela

You don't meet the security criteria, that's why, you can check your website's security here: https://www.hardenize.com/report/forwardemail.net/1583092497 and you can check the criteria on the new email provider's web page.

**Comment by niftylettuce** [comment]
The criteria on the new email provider's web page is extremely biased.  Even if I pass the "hardenize" test, we will still be rejected because we use Digital Ocean as our server hosting?  I operate a privacy-first service that is also reliable and is lightning fast globally, it is a shame to not honor that instead.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
I don't see anywhere that there's a prohibition against hosting your service with Digital Ocean or something like that, the only thing similar to that is that you must host your own analytics.
All in all I think the criteria is pretty good, you don't have to pass every part of the hardenize test, but you do need to not use old TLS that are going to be depreacted, for example.

Stil, I didn't create the criteria, so...
