### ISSUE TITLE
🆕 Software Suggestion | AnonAddy.com

### ISSUE THREAD

**Issue by willbrowningme** [privacytoolsIO/privacytools.io#1673]
## Basic Information

**Name:** AnonAddy (short for anonymous email address)
**Category:** Email
**URL:** https://anonaddy.com

## Description

Open-source anonymous email forwarding. Create unlimited aliases for free.

Features Include:

- GPG/OpenPGP encryption on forwarded emails
- Browser extension
- Custom domains
- Reply to forwarded emails and send from aliases (paid feature)
- UUID / Random Word aliases at shared domains
- API

**FAQ**: https://github.com/anonaddy/anonaddy#anonymous-email-forwarding
**Privacy Policy**: https://anonaddy.com/privacy/
**Terms**: https://anonaddy.com/terms/

## Why I am making the suggestion

I believe this service can complement email providers such as Tutanota/Protonmail by allowing users to create a different email alias for each site/service that they use.

If someone is still using a provider such as Gmail they can add their own GPG key to encrypt all forwarded emails and prevent inbox snooping.

## My connection with the software

I am the author of this software, working on it full time.

- [X ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by nitrohorse** [comment]
I only have positive things to say about this service, I think it'd be worth adding to the "Interesting email providers or services under development" section.

**Comment by Zcr34** [comment]
Seems to be entirely open source, something I like to see. 

**Source Code**: https://github.com/anonaddy
**Self Hosting Instructions**: https://github.com/anonaddy/anonaddy#self-hosting
___________________

@willbrowningme How is your project different from SpamGourmet or Enrine.email?

Related to #1672

**Comment by dngray** [comment]
We could put mention of it at the bottom where me mention c0x0.com

**Comment by willbrowningme** [comment]
Yes the service is open-source and can be self-hosted (although I need to add to the instructions).

@Zcr34 The ability to add your own GPG key to encrypt all fowarded emails. You can send from aliases (initiate email conversation), I know Erine.email does support this too. You can use aliases at shared domains that are not linked back to you by your username. You can add multiple recipients per alias. API access is available as well as a browser extension. AnonAddy is also all green on hardenize.com.

**Comment by dngray** [comment]
Keep in mind all email forwarding must abide by the email criteria or it shall not be listed see #1672 for that.

**Comment by willbrowningme** [comment]
@dngray Thanks, it has MTA-STS, TLS-RPT, DANE, DNSSEC, CAA, PFS, registration on the EFF's STARTTLS-Everywhere list, 2FA (on accounts).

**Comment by dngray** [comment]
> @willbrowningme How is your project different from SpamGourmet or Enrine.email?

I meant in regard to these.

**Comment by ceptonit** [comment]
Have they been audited?

I really like the concept but if there are flaws, one could just read all the emails coming through, isn' it?

**Comment by dngray** [comment]
No they haven't but virtually no email provider has.

**Comment by ceptonit** [comment]
> No they haven't but virtually no email provider has.

Protonmail is the only one I know of that has been audited, they get audited every year.

**Comment by dngray** [comment]
That's right, ProtonMail [was audited by Cyberkov](https://old.reddit.com/r/ProtonMail/comments/6i3w4t/has_protonmail_been_audited_and_how_can_i/dj3mnln/).

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> We could put mention of it at the bottom where me mention c0x0.com

Why mentioning c0x0 if it's closed source when there are other open source alternatives?

**Comment by blacklight447-ptio** [comment]
To be fair, as its a service, being open source matters a lot less since you cannot be sure that the code they publish is the same code they are running. Open source with services only really matter if you want to self host.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> To be fair, as its a service, being open source matters a lot less since you cannot be sure that the code they publish is the same code they are running. Open source with services only really matter if you want to self host.

Well, you have the option to self-host with all of them if that's the case, still a feel a lot more safe with open source alternatives and if it's the same I still don't see the problem with recommending the options I mentioned.

**Comment by dngray** [comment]
Closing this as it's already been taken care of.
