### ISSUE TITLE
🆕 Software Suggestion | SimpleLogin

### ISSUE THREAD

**Issue by nguyenkims** [privacytoolsIO/privacytools.io#1693]
## Basic Information

**Name:** SimpleLogin
**Category:** Email alias/forwarding and identity provider service.
**URL:** https://github.com/simple-login/app

## Description

SimpleLogin is an open source, self-hostable email alias/forwarding service.
It also offers a privacy-focused alternative to the "Sign in with Facebook|Google|Apple" button.

Website: https://simplelogin.io

## Why I am making the suggestion

The service allows you to not expose your real email address using `email alias`.

You can also use alias as your "business emails". 

## My connection with the software

I'm this service's founder. 

- [X ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
I think they deserved to be listed, they have made a lot of changes to their website and platforms when users on reddit and the forum asked them to do it for privacy concerns, and have answered the questions created by @LizMcIntyre . They also have a really nice free plan.

**Comment by nguyenkims** [comment]
Is there anything that I should address in this issue?

**Comment by blacklight447-ptio** [comment]
Could you tell me on what domain this forward server is hosted? i would like to see what scurity features are supported (like DANE and MTA-STS)

**Comment by sakura974201** [comment]
> Could you tell me on what domain this forward server is hosted? i would like to see what scurity features are supported (like DANE and MTA-STS)
It is mx1.simplelogin.co .

**Comment by sakura974201** [comment]
Scan results.
https://www.ssllabs.com/ssltest/analyze.html?d=simplelogin.io
https://www.hardenize.com/report/simplelogin.io/1583486360

https://www.ssllabs.com/ssltest/analyze.html?d=app.simplelogin.io
https://www.hardenize.com/report/app.simplelogin.io/1583486987

https://www.hardenize.com/report/simplelogin.co/1583228460

**Comment by blacklight447-ptio** [comment]
Thanks for the scanning @sakura974201 . @nguyenkims simplelogin does currently not fulfill our minimum requirements for email services. I recommend you to take a look in our criteria list on the email page and fix the areas where the service is lacking, and then comment here again so we can take another look :)

**Comment by nguyenkims** [comment]
@blacklight447-ptio Should we open another ticket issue?
