### ISSUE TITLE
🌐 Website Issue | Update Key Disclosure Law section for Belgium

### ISSUE THREAD

**Issue by jeroen7s** [privacytoolsIO/privacytools.io#1696]
## Description
The Belgian "Hof van Cassatie", which is the highest court in belgium, has recently concluded that forcing a suspect to unlock his own devices is lawful.
https://tweakers.net/nieuws/163116/belgische-rechter-verdachte-mag-verplicht-worden-code-smartphone-af-te-staan.html
(Article is in dutch)

So I think the star next to belgium on the page referencing to the: 
"people who know how to access a system may be ordered to share their knowledge, **however, this doesn't apply to the suspect itself or family members.**"
is no longer applicable

**Comment by blacklight447-ptio** [comment]
Thanks for the heads up! Are you willing to make a quick PR for this? :)

**Comment by lrq3000** [comment]
A bit more background on applicability, at the end of the article: "A judge cannot simply impose the obligation [to reveal the encryption code], they must be able to prove that the suspect knows the code. For example, this is possible if someone saw the suspect use their smartphone for a while."

**Comment by blacklight447-ptio** [comment]
> 
> 
> A bit more background on applicability, at the end of the article: "A judge cannot simply impose the obligation [to reveal the decryption code], they must be able to prove that the suspect knows the code. For example, this is possible if someone saw the suspect use their smartphone for a while."

could you link to that btw?

**Comment by lrq3000** [comment]
In my PR it's linked, but the article is not in english, this text is my
own translation (but it's quite straightforward, no interpretation
necessary)

Le lun. 10 févr. 2020 à 09:34, blacklight447 <notifications@github.com> a
écrit :

**Comment by blacklight447-ptio** [comment]
The PR just got merged, thanks guys!
