### ISSUE TITLE
🌐 Website Issue | Hidden service is down

### ISSUE THREAD

**Issue by rex4539** [privacytoolsIO/privacytools.io#1697]
`privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion` is unreachable.

**Comment by blacklight447-ptio** [comment]
@JonahAragon

**Comment by sell** [comment]
It loads for me, I am on it at the moment.

**Comment by rex4539** [comment]
Now it loads for me too.

**Comment by blacklight447-ptio** [comment]
We had some issues with our hardening which made tor stop working, all fixed now
