### ISSUE TITLE
🆕 Software Suggestion | search engine gibiru

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#1702]
## Basic Information

**Name:** gibiru
**Category:** search engine
**URL:** https://gibiru.com/

## Description

privacy search engine

## Why I am making the suggestion

Zero retargeting

You’ll never be solicited to buy item you have already purchased. We don’t log your searches, IP address or place cookies on your computer. This means there is not data to sell to advertisers or to use to retarget you.
Honest Earnings.

We generate our revenue strictly on a commission basis. When our users buy something or place a call to action while using Gibiru, we take a commission. We don’t make any money by selling your hobbies, political interests and search logs.
We don’t store or sell your privacy.

Our mission is to provide our users access to free and private information.

## My connection with the software

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
>You’ll never be solicited to buy item you have already purchased.

**Comment by Mikaela** [comment]
Template not filled properly, connection with software missing and confusing pronoun.
