### ISSUE TITLE
"Built-in Encryption" not clear

### ISSUE THREAD

**Issue by desk7** [privacytoolsIO/privacytools.io#1706]
In Privacy-Conscious Email Providers what does "Built-in Encryption" actually mean? That the email are sent encrypted (TLS) or that they are zero-knowledge encrypted?
I thought the second option but then I see that for example in disroot.org "All emails, unless encrypted by user (with gpg for example) are stored on our servers in plain-text."
Tutanota and protonmail, for example, implement E2E encryption instead. The difference is huge and not evident from the table.

So, please make clearer the meaning of "built-in encryption" or remove the providers that doesn't offer E2E encryption.

Thanks

**Comment by danarel** [comment]
We are re-doing the entire email section which can be seen at #1672 which will make items like this more clear and better define email providers we recommend.
