### ISSUE TITLE
✨ Feature Suggestion | General glossary page

### ISSUE THREAD

**Issue by dngray** [privacytoolsIO/privacytools.io#1708]
We should have a general glossary page which is sorted alphabetically.

**Comment by dngray** [comment]
I'm thinking we could use the https://wiki.privacytools.io/ for that maybe.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> I'm thinking we could use the https://wiki.privacytools.io/ for that maybe.

Is it already usable?

**Comment by dngray** [comment]
Yes and therefore I have decided this information is best suited there.
