### ISSUE TITLE
🆕 Hardware Suggestion | Ubiquiti UniFi

### ISSUE THREAD

**Issue by JonahAragon** [privacytoolsIO/privacytools.io#1715]
## Basic Information

**Name:** UniFi
**Category:** Hardware > Routers #1713 
**URL:** https://unifi-network.ui.com/

## Description

Enterprise-grade networking solution. Their lineup includes anything from dedicated routers and AP hardware to all-in-one devices like the [UniFi Dream Machine](https://store.ui.com/collections/routing-switching/products/unifi-dream-machine). I wouldn't describe any of these products as extremely consumer friendly, even the UDM, but they are easy enough to use if you have technical/routing experience. The entire installation is extremely modular, making future upgrades easier.

## Why I am making the suggestion

I personally have a UniFi installation and I am very happy with their products. Everything can be installed locally although they do have some cloud-enabled services you can optionally utilize.

 - [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by blacklight447-ptio** [comment]
What makes it privacy friendly though :p

**Comment by JonahAragon** [comment]
> Everything can be installed locally although they do have some cloud-enabled services you can optionally utilize.
