### ISSUE TITLE
🆕 Software Suggestion | dismail.de

### ISSUE THREAD

**Issue by sakura974201** [privacytoolsIO/privacytools.io#1719]
## Basic Information

**Name:** dismail.de
**Category:** Email
**URL:** https://dismail.de/

## Description
dismail.de is a German email service that values privacy.

## Why I am making the suggestion
We actively disclose information on our website news page.

ToS
https://dismail.de/tos.html

## My connection with the software
I am just a user.
Not an operator or stakeholder.

- [✔] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
>We actively disclose information on our website news page.

Why do you talk as if you were part of the team?

--------------------------------------------------------

I order to have an e-mail account you have to contact the administrators via XMPP, so I don't know if that goes along with the rest of the recommendations, since providers such as RiseUp, Autistici/Inventati and Systemli are not recommended.  They also don't pass the criteria.
https://www.hardenize.com/report/webmail.dismail.de/1582052641

**Comment by sakura974201** [comment]
> Why do you talk as if you were part of the team?
I am not good at English.
I think that was a misleading expression.
I'm sorry.

**Comment by blacklight447-ptio** [comment]
Dismail does not  currently meet our minimum security criteria for Email providers.
Closing this issue.

**Comment by a-kriya** [comment]
@blacklight447-ptio Since you already seem to have validated it, will you be able to share which parts of [the criteria](https://www.privacytools.io/providers/email/#criteria) does it not meet?

**Comment by dngray** [comment]
> https://www.hardenize.com/report/webmail.dismail.de/1582052641

That link is actually incorrect, you don't want to be testing against their webmail subdomain. Instead you would test against the main domain `dismail.de` which would give you the MX records:

```
dismail.de.		14400	IN	MX	10 mx1.dismail.de.
dismail.de.		14400	IN	MX	10 mx2.dismail.de.
```

While it does meet the [hardenize recommendations](https://www.hardenize.com/report/dismail.de/1587136163) that is not all we consider in the [criteria](https://www.privacytools.io/providers/email/#criteria).

This provider would not meet the trust component of the criteria. A look of the website, it appears the owner does not provide a public-facing leadership or ownership.

We do not allow anonymous email providers, **period**. Email has a lot of sensitive metadata and most often unencrypted plain-text contents of emails. You need to know who is managing that data for it to be a trustworthy service.

Anything else is just gambling it is not a bad person or organization doing a bad thing. Why should you trust an anonymous stranger on the internet with your identity, possibility to reset passwords to associated accounts etc?

With public-facing ownership and leadership that person's reputation (and that of their company) is known and on the line. This motivates them to actually know what they are doing and keep things secure.

If an anonymous provider got breached, they could just close up shop and re-open again another time.

**Comment by a-kriya** [comment]
@dngray Thanks for sharing some details that are taken into account when considering a provider. 

>Anything else is just gambling it is not a bad person or organization doing a bad thing. Why should you trust an anonymous stranger on the internet

Isn't it still a gamble to trust a registered organization or company when we have examples of them mishandling email data intentionally or unintentionally? Perhaps that gamble has lesser risk? But I can't really see that, and don't think this has much significance.

**Comment by dngray** [comment]
> > Anything else is just gambling it is not a bad person or organization doing a bad thing. Why should you trust an anonymous stranger on the internet
> 
> Isn't it still a gamble to trust a registered organization or company when we have examples of them mishandling email data intentionally or unintentionally without repercussions? Perhaps that gamble has lesser risk? But I can't really see that, and don't think this has much significance.

It is, ultimately any server that is not run by you, has that risk. The thing is though, if the owner is able to just disappear they may not put much importance on getting things right.

Ultimately a person's reputation running a service increases accountability somewhat.
