### ISSUE TITLE
🌐 Website Issue | Dead Link to „Code of Conduct“ on write.privacytools.io

### ISSUE THREAD

**Issue by github-userx** [privacytoolsIO/privacytools.io#1722]
On https://write.privacytools.io/about there is a link to PTIO’s Code of Conduct but that file/url doesn’t exist anymore it seems:
https://github.com/privacytoolsIO/privacytools.io/blob/master/CODE_OF_CONDUCT.md

**Comment by hugoncosta** [comment]
COC has been moved to this [link](https://github.com/privacytoolsIO/.github/blob/master/CODE_OF_CONDUCT.md), can't find where the about page on the write page is though.

**Comment by github-userx** [comment]
write.privacytools.io redirects automatically to write.privacytools.io/about

**Comment by JonahAragon** [comment]
Fixed thanks.
