### ISSUE TITLE
🌐 Website Issue | Suggested video link for Tor being better than VPNs

### ISSUE THREAD

**Issue by Hxmwqk79** [privacytoolsIO/privacytools.io#1723]
At the bottom of the page at https://www.privacytools.io/providers/vpn/ there is a header 'Related VPN information'. I have a video suggestion to be added there as a link which expertly and convincingly explains why Tor is much better than a VPN. https://www.youtube.com/watch?v=6ohvf03NiIA Mirror: https://www.bitchute.com/video/6ohvf03NiIA/

**Comment by hugoncosta** [comment]
The beginning of the video isn't the most "professional", let's leave it at that, but I do see the value that video explanations can bring to the table, especially since most sources/references are usually long and technically heavy for the average user.

**Comment by blacklight447-ptio** [comment]
Yeah, i agree with hugo here, i don't know if this is the content we want to send  our newer users toward.

**Comment by Hxmwqk79** [comment]
> Yeah, i agree with hugo here, i don't know if this is the content we want to send our newer users toward.

Well that video is much better than the other link on your site which outright says VyprVPN is better than Tor https://www.goldenfrog.com/blog/myths-about-vpn-logging-and-anonymity

**Comment by blacklight447-ptio** [comment]
That is most likely a link added in the early days of ptio, ill make a pull request to remove it.

**Comment by blacklight447-ptio** [comment]
fixing that bad link in #1798
