### ISSUE TITLE
Add a warning that Jami is partially centralized

### ISSUE THREAD

**Issue by lrq3000** [privacytoolsIO/privacytools.io#1727]
## Description

Although it is described as a P2P client, Jami uses 5 different central servers to provide some functionalities, as described [here](https://git.jami.net/savoirfairelinux/ring-project/issues/765) and [here](https://jami.net/why-is-jami-truly-distributed/). Hence, without self-hosting, these servers are points of failure where meta-data can leak (see also #1357).

This by the way goes counter to the [cited advantage of P2P clients](https://www.privacytools.io/software/real-time-communication/#peer-to-peer): "There are no servers that could potentially intercept and decrypt your transmissions, unlike centralized and federated models."

I suggest a warning is added about the possibility to disable/self-host these servers.

**Comment by blacklight447-ptio** [comment]
I think small note is would be a proper solution to this. this issue is one of the grey areas which are always difficult to define.

**Comment by lrq3000** [comment]
@blacklight447-ptio yes I'll do it :-)
