### ISSUE TITLE
🆕 Software Suggestion | ExifCleaner (Metadata Removal Tools)

### ISSUE THREAD

**Issue by szTheory** [privacytoolsIO/privacytools.io#1729]
## Basic Information

**Name:** ExifCleaner
**Category:** Metadata Removal Tools
**URL:** https://exifcleaner.com/ and https://github.com/szTheory/exifcleaner

## Description

ExifCleaner is a freeware, open source GUI app that removes exif metadata from images, videos, and PDF documents using a simple drag and drop interface. It supports multi-core batch processing and dark mode. It's an Electron app built on top of the open source ExifTool library, and is available for Linux, Windows, and Mac.

## Why I am making the suggestion

I couldn't find any other free and open source GUI apps that allowed removing metadata data with a simple drag and drop workflow. I think it's important that an app like this is easy to use so that you don't require technical chops, and is cross platform so you can use it no matter what type of computer you're on. There is no automatic updates or other network traffic. And it's built on top of ExifTool, which is a proven and trusted open source tool. The application is very feature light and I plan on keeping it that way to avoid bloat and release churn. It can be downloaded over HTTPS from Github Releases which is conveniently located right next to the source code and issue tracker. The source code is very simple vanilla Javascript without any type of UI framework. It's been out for a few months now and I've ironed out the biggest bugs. I proactively maintain a list of open issues on the Issue Tracker. I use it daily myself without issue, and there are users in various countries that use it on all platforms.

## My connection with the software

I'm the author of the software. The software will always remain free and open source, and is MIT licensed.

Note that I've already [created a fork](https://github.com/szTheory/privacytools.io/commit/8d32de7d5302bde7b79da200e732fdec6e1452af) of the privacytools.io website with the section updated, built the Jekyl site and tested it. So you could either use that directly or as a reference. I removed a superfluous `div.row.mb-2` which was causing the Markdown generated `<br>` tag between the two entries to not give any spacing. Below is a screenshot of how it came out. If you need any further assistance please let me know. I've used privacytools.io for years, it's a great resource and I hope to be able to contribute back.

![update](https://user-images.githubusercontent.com/28652/74992611-85f09c80-5440-11ea-9bc6-322947597e5b.png)

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by blacklight447-ptio** [comment]
Looking pretty great so far. ill do some more digging when i have time ( should be somewhere this week.) Thank you for your willingness to contribute :)

**Comment by blacklight447-ptio** [comment]
couldnt find anything dodgy, ill give it an approval, are you willing to to make a PR for this @szTheory

**Comment by szTheory** [comment]
Thanks @blacklight447-ptio here's a PR https://github.com/privacytoolsIO/privacytools.io/pull/1802. Just let me know if I have to change anything or do something to set up the Netlify preview.
