### ISSUE TITLE
Section for web hosting services?

### ISSUE THREAD

**Issue by kenshi84** [privacytoolsIO/privacytools.io#173]
Currently there's only information about cloud file storage and hosting services, but no information about web hosting services such as prq.se and nforce.com. I'm not knowledgeable at all, so anyone who knows this area, your help would be appreciated!

**Comment by Shifterovich** [comment]
Web hostings aren't private per se. If you care about your users' privacy, you should host the website on your own.

**Comment by Atavic** [comment]
Every website hosting service agrees with the laws of the country it operates on.
Most of them fall under the Five Eyes, Nine Eyes or Fourteen Eyes countries alliances.

@kenshi84 Why don't you search and share here a list of reliable website hosting services outside these Global Mass Surveillance Agreements?

**Comment by p2635** [comment]
I'll be interested in this too. I somewhat agree with @Shifterovich but it's still a good idea to find out generally what companies are good for privacy even if they're not perfect.

**Comment by Shifterovich** [comment]
Depends on threat model. I agree it might be a good idea for people who just want to host their websites with *some* privacy, but I would definitely recommend self-hosting as well.

**Comment by p2635** [comment]
I have a pending project and I'm actually in need of some ideas now. I do need to clarify my threat model and go from there. Anyone have any ideas of any good solutions they already use?

@Shifterovich might actually be a good idea to also add good self-hosting solutions like http://freedomboxfoundation.org/

**Comment by Shifterovich** [comment]
Can't recommend a hosting provider, but take a look at [this domain registration service](njal.la).

**Comment by p2635** [comment]
@Shifterovich - can you send again? link is broken

**Comment by Shifterovich** [comment]
Forgot the `https://`. Works now.

**Comment by p2635** [comment]
@Shifterovich Thanks! And to the admin peops, sorry for the off topic posts.

**Comment by Kcchouette** [comment]
you can now close this issue @Shifterovich @privacytoolsIO
