### ISSUE TITLE
❌ Software Removal | JiveSearch

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [privacytoolsIO/privacytools.io#1739]
## Description
Request of the removal of the JiveSearch search engine, from the worth mentionning sub-section of the Privacy Respecting Search Engines section on PrivacyTools.io
https://www.privacytools.io/providers/search-engines/#search
`Jive Search - A free-software search engine with a similar look and feel to Google.`
## Why I am making the suggestion
https://www.reddit.com/r/privacytoolsIO/comments/f7xgt5/jive_search/
https://github.com/jivesearch/jivesearch/issues/122

A those two source confirms it, it seems that the JiveSearch search engine isn´t maintained anymore.
- [Their main website domain is offline](https://jivesearch.com).
- [Their twitter account hasn´t been active since April 2019](https://nitter.snopyta.org/JiveSearch).
- [Their GitHub repo hasn´t received any new commits since April 2019 aswell](https://github.com/jivesearch/jivesearch).
- [The only public member of the GitHub Jivesearch organisation, was last active in November 2019](https://github.com/brentadamson).
## My connection with the software
I´m neither affiliated, or neither an user of this software.
As noticing the reddit post of an user asking about the state of the JiveSearch search engine on the privacytoolsIO subreddit (First source, the author seems to have used a throwaway account, and don´t want to report it on GitHub itself).
I´ve took the liberty, of reporting it by myself.

- [✅] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by danarel** [comment]
Does seem to be a dead project. I do think it's a good idea to remove it.

**Comment by blacklight447-ptio** [comment]
i vote for removal as well.

@PoorPocketsMcNewHold , would you be willing to make a quick pull request for this?
