### ISSUE TITLE
🆕 Discussion | Are Samsung Galaxy S3 and Galaxy Note II any worse than the Pinephone or the Librem 5?

### ISSUE THREAD

**Issue by DontUseGithub** [privacytoolsIO/privacytools.io#1740]
_This Issue/Discussion is based on the comment I made [here](https://github.com/privacytoolsIO/privacytools.io/pull/1713/commits/842964dfeac004b8126158fc87e9949fc12102eb#r385634119)._

IDK if Samsung Galaxy S3 and Galaxy Note II are any worse than the Pinephone or the Librem 5, but they both [have modem isolation](https://www.replicant.us/freedom-privacy-security-issues.php) and are capable of [running mainline Linux](https://redmine.replicant.us/issues/1882).

Both phones are widely available, they're cheap and specs-wise they're similar to the Pinephone: 

- [Samsung Galaxy S3 (i9305, i9300)](https://wiki.postmarketos.org/wiki/Samsung_Galaxy_SIII_LTE_(samsung-i9305)) 
- [Galaxy Note II (n7100)](https://wiki.postmarketos.org/wiki/Galaxy_Note_II_(samsung-n7100))

**Comment by beerisgood** [comment]
Librem 5 don't plan to update baseband firmware, which means if security vulnerability are known, the device isn't secure any more. No matter what hardware is used or which hardware switch are exist.

The same is for all other phones. If the vendor don't provide system and firmware updates, the device get unsecure. Mostly after 1 month / after next patchday.

Also it doesn't matter if LineageOS or other random ROMs support the device. These ROMs doesn't (and can't!) provide firmware updates, so only the half of both security sides are protected. And we all know how bad unsecure hardware can be.
Also these custom ROMs mostly even increase the attack surface as they only care about customization or adding some useless features.
The only ROM which realy care about Security and Privacy is: GrapheneOS.

**Comment by dngray** [comment]
Lets keep the issue tracker about privacytools.io. There is already [/r/privacytoolsIO](https://www.reddit.com/r/privacytoolsIO/) and forums [forum.privacytools.io](https://forum.privacytools.io/) for general discussions.
