### ISSUE TITLE
🆕 Software Suggestion | postmarketOS

### ISSUE THREAD

**Issue by DontUseGithub** [privacytoolsIO/privacytools.io#1742]
## Basic Information

**Name:** postmarketOS
**Category:** Mobile Operating Systems
**URL:** https://postmarketos.org/

## Description

We are sick of not receiving updates shortly after buying new phones. Sick of the walled gardens deeply integrated into Android and iOS. That's why we are developing a sustainable, privacy and security focused free software mobile OS that is modeled after traditional Linux distributions. With privilege separation in mind. Let's keep our devices useful and safe until they physically break!

## Why I am making the suggestion

It's a great OS, that has a huge community behind it and it's based on a very popular Linux OS called [Alpine](https://en.wikipedia.org/wiki/Alpine_Linux). They currently have over [150 devices](https://wiki.postmarketos.org/wiki/Devices) that can boot into postmarketOS.

## My connection with the software

I'm not connected with it, I just like this OS.

**Comment by danarel** [comment]
Given that it's in Alpha, I don't think it's worth listing yet, but it is a good project that I hope continues to grow.

**Comment by blacklight447-ptio** [comment]
Yeah , I don't think we should be listing it right now, but we should keep an eye for it when it has a stable release.
