### ISSUE TITLE
Add Lavabit to List of Email Providers

### ISSUE THREAD

**Issue by 0verk1ll** [privacytoolsIO/privacytools.io#175]
Lavabit recently reopened for business. You can find them at https://lavabit.com/
You might want to consider adding them to the list of privacy conscious email providers.

**Comment by xdtnguyenx** [comment]
Is it actually out for use yet or is it an announcement for now? I'd just hold off before adding them to the list until someone has actually tried it out.

**Comment by ImSeth** [comment]
It is just an announcement for now. They will open their services to the general public soon.

**Comment by privacytoolsIO** [comment]
We don't recommend US based services. 

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
