### ISSUE TITLE
📝 Correction | Mailbox.org

### ISSUE THREAD

**Issue by desk7** [privacytoolsIO/privacytools.io#1750]
## Description
In their site https://kb.mailbox.org/display/MBOKBEN/The+Encrypted+Mailbox they say: "We  offer the option of automatically encrypting your incoming e-mails and the sent e-mails as well. This means they are secure in your inbox/sent folder and **can be decrypted and read only by you.**"

About Mailbox.org email provider, in Data Security, you say "Mailbox.org allows for encryption of incoming mail using their encrypted mailbox. New messages that you receive will then be immediately encrypted with your public key. **This only protects message content while at rest so you should request that the sender encrypt the email message before sending in order to ensure confidentiality.**"

The last sentence is misleading: in fact it is applicable to any provider while they offer zero-access encryption for the message content of incoming emails.

In addition, in the detailed comparison table there is already "Zero access".

## Why I am making the suggestion
I was searching for alternatives to gmail and I noted this

## My connection with the software
no connection

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by blacklight447-ptio** [comment]
@dngray

**Comment by dngray** [comment]
> The last sentence is misleading: in fact it is applicable to any provider while they offer zero-access encryption for the message content of incoming emails.

Yes I do agree with that. I think we could safely omit it. I'm not actually sure how that slipped in there, might have been during some of the re-organization.
