### ISSUE TITLE
No Google Analytics?

### ISSUE THREAD

**Issue by paperbag** [privacytoolsIO/privacytools.io#176]
But I found other tracker which tracking vistors.
I know [pravicy policy](https://support.google.com/analytics/answer/6004245) about Google Analytics.
But I doesn't know how privacytools.io to deal these information and pravicy.
 It is not transparent.
```
<script type="text/javascript">
		var _paq = _paq || [];
		_paq.push(['trackPageView']);
		_paq.push(['enableLinkTracking']);
		(function() {
			var u = "//www.privacytools.io/stats/";
			_paq.push(['setTrackerUrl', u + 'piwik.php']);
			_paq.push(['setSiteId', 1]);
			var d = document,
				g = d.createElement('script'),
				s = d.getElementsByTagName('script')[0];
			g.type = 'text/javascript';
			g.async = true;
			g.defer = true;
			g.src = u + 'piwik.js';
			s.parentNode.insertBefore(g, s);
		})();
	</script>
<noscript>
<p><img src="//www.privacytools.io/stats/piwik.php?idsite=1" style="border:0;" alt=""/></p>
</noscript>
```

**Comment by paperbag** [comment]
Sorry, I found piwik is open-source analytics platform.
But I still feel unfortable about this word --"No Ads, No Google Analytics, No Affiliates, No Cross-Site Requests".
It may make vistors feel these are no trackers on the website.

**Comment by Shifterovich** [comment]
The sentence `No Ads, No Google Analytics, No Affiliates, No Cross-Site Requests` is completely true. Piwik isn't Google Analytics and analytics platforms aren't trackers.

**Comment by Hillside502** [comment]
https://en.wikipedia.org/wiki/Piwik
https://piwik.org/
