### ISSUE TITLE
🌐 Website Issue | Font icons not displaying properly when using NoScript

### ISSUE THREAD

**Issue by zenithium** [privacytoolsIO/privacytools.io#1763]
## Description
One way this could be solved is by introducing a class to problematic font icons called `hideicon`, setting their style to `"display:none"` and then using JavaScript `document.getElementsByClassName("hideicon").stlyle.display = ";` to revert the display property to the CSS default value.

This mostly solves the issues with the navigation bar (excluding home button) but other sections like the "Spread the word and help your friends" at the bottom of the page will have to be tweaked differently as the icons are the only thing there. Perhaps a similar approach as above but instead of just hiding the icon, a fallback logo image would be shown in the opposite way that was described above.

## Screenshots
![2020-03-05_23-13-51](https://user-images.githubusercontent.com/48525551/76031645-0084e600-5f30-11ea-829b-566d6b61579a.png)

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
It works okay for me, are you using No Script?

**Comment by zenithium** [comment]
This does seem to be caused by NoScript exclusively and not TB Safest, weird. I thought that Safest implies NoScript being enabled.

**Comment by JonahAragon** [comment]
We are not currently interested in fixing this issue. If you have browser-side extensions that break compatibility with the websites you visit, those are use-cases that we can not prepare for. Your alternative solution would break icons for *all* users with Javascript disabled, which is not ideal.

**Comment by zenithium** [comment]
1. The issue is caused by NoScript which is one of the recommended add-ons, it seems inconsiderate to not account for users of it if we're encouraging it's use.
2. I would argue that most users that have JavaScript disabled are accomplishing that through NoScript and not by manually adjusting their settings (e.g. about:config). AFAIK most browsers have this kind of option hidden away from regular users as it break UX on many sites.
3. I wouldn't really say this change "breaks" the site, as it only hides eye candy icons that are accompanied by descriptive text anyway.
