### ISSUE TITLE
🌐 Website Issue | SVGs not displayed on Tor Browser with Security Level on Safest

### ISSUE THREAD

**Issue by zenithium** [privacytoolsIO/privacytools.io#1764]
## Description
This issue was brought up in #275 and addressed in #308 but brought back in #1563. I guess it should be decided whether this problem will be addressed or not. Reverting to PNGs would fix this but there is more maintenance for PNGs than SVGs which was the cause of the change in the first place.

## Screenshots

![2020-03-05_23-50-11](https://user-images.githubusercontent.com/48525551/76033311-da614500-5f33-11ea-8fc6-8768251af3ee.png)

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Same as on the other issue, are you using NoScript?

**Comment by zenithium** [comment]
This is not caused by NoScript as both disabling restrictions globally and disabling the extension completely don't fix the issue.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> This is not caused by NoScript as both disabling restrictions globally and disabling the extension completely don't fix the issue. IIRC SVGs are disabled on Safest. Try closing all tabs of the site and opening it again, since if you only enabled Safest mode and reloaded the page it will still work.

Mmm, weird, it could be a bug then.

**Comment by zenithium** [comment]
> Mmm, weird, it could be a bug then.

If you set the security to Safest and then go to about:config and find svg.disabled it will be set to true, this is an intended feature. On Standard security it is set to false which is the FF default.

**Comment by blacklight447-ptio** [comment]
This is a known issue, its why i voted against the change to SVG at the time.
In any case, the amount of people running tor browser, which is also run in safest mode, is quite low.
So its not really a major issue, espeically considering as the information itself is still perfectly accesible.

Still we could see if we can make a fallback to png in here. @dawidpotocki

**Comment by JonahAragon** [comment]
This is intentional behavior as decided in #1563.
