### ISSUE TITLE
❌ Software Removal | Tutanota

### ISSUE THREAD

**Issue by sakura974201** [privacytoolsIO/privacytools.io#1769]
## Description
Suggest removal of Tutanota.

## Why I am making the suggestion
- No value for Mode=block in X-XSS-Protection

- Content-Security-Policy contains 'unsafe-inline' value

- Does not support DNS CAA.

- Does not support payment in cryptocurrencies.

- Operated in Fourteen Eyes countries

## My connection with the software
Unrelated

- [✔] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> * Does not support payment in cryptocurrencies.
>
> * Operated in Fourteen Eyes countries

I don't know about the others, but if you are going to accept only BTC it's not the big deal, since you are only pseudo-anonymous, and the latter it's not a necessary point on the criteria.

**Comment by blacklight447-ptio** [comment]
> 
> ## Description
> 
> Suggest removal of Tutanota.
> ## Why I am making the suggestion
> 
>     * No value for Mode=block in X-XSS-Protection
> 
>     * Content-Security-Policy contains 'unsafe-inline' value
> 
>     * Does not support DNS CAA.
> 
>     * Does not support payment in cryptocurrencies.
> 
>     * Operated in Fourteen Eyes countries
> 
> 
> ## My connection with the software
> 
> Unrelated
> 
>     * [✔] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

Being outside the fourteen eyes is not in our minimum criteria, neither is anonymous payments.

We also don't require CAA since we already require DANE.

And the other two: those are on track on becoming part of the minimum criteria next year.

So so far, I don't really see a reason that would validate delisting. @dngray

**Comment by dngray** [comment]
Agreed.
