### ISSUE TITLE
Source Code Optimization

### ISSUE THREAD

**Issue by Atavic** [privacytoolsIO/privacytools.io#177]
Meta tags seem good, except that there are no Robots and Author meta tags:
_meta name="author" lang="en" content="Privacytools.io"
meta name="robots" content="Index,Follow"_

Maybe the homepage has too much content?
**URLs found in the page: 447 urls and 351 unique ones.**

I suggest that Windows 10 section should appear earlier on the page.
Also, the VPN section is listed too early and should go after File Encryption Software section?

A gist about different providers: [Most VPN Services are Terrible](https://gist.github.com/ridgewell/e0b34f49f1ff138e43c7577c60363e4d)

**Comment by Shifterovich** [comment]
The gist is about shared keys, not different providers. I don't think all content being on the homepage is an issue. I *think* it's very good for SEO.

**Comment by Atavic** [comment]
These VPN providers have a known "Secret" Key:

EarthVPN 
IBVPN 
NordVP
