### ISSUE TITLE
❌ Software Removal | Keybase

### ISSUE THREAD

**Issue by sakura974201** [privacytoolsIO/privacytools.io#1783]
## Description
Suggest to remove Keybase.

## Why I am making the suggestion
Because it's closed source

## My connection with the software
Unrelated

- [✔] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dawidpotocki** [comment]
> Because it's closed source

That's backend, which you can't verify if it's running the same code anyway.

**Comment by blacklight447-ptio** [comment]
open source is not a requirement for us (unless there is an easy to use open source alternative that is privacy friendly.) Also, as Dawid noted, you cannot verify what runs on there servers anyway, so opensource server side code only matters in the context of selfhosting and decentralization. And considering we already have other options for decentralized chats, i would consider this a none issue.
