### ISSUE TITLE
🆕 Software Suggestion | 7-Zip

### ISSUE THREAD

**Issue by sakura974201** [privacytoolsIO/privacytools.io#1784]
## Basic Information

**Name:** 7-Zip
**Category:** File Encryption Software
**URL:** https://www.7-zip.org/

## Description
Suggest to add 7-Zip.
It is an archiver with file encryption.

## Why I am making the suggestion
As an alternative to PeaZip mentioned in #1782 .
You can use it to create AES encrypted 7-Zip archive files. 
Safer than the older encrypted Zip.

## My connection with the software
Unrelated
- [✔] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by beerisgood** [comment]
> Safer than the older encrypted Zip.

What did you mean with that?

**Comment by sakura974201** [comment]
> 
> 
> > Safer than the older encrypted Zip.
> 
> What did you mean with that?

Encrypted Zip does not protect some metadata. 7-Zip is protected if properly configured.
https://en.wikipedia.org/wiki/Zip_(file_format)#Encryption

**Comment by beerisgood** [comment]
> 
> 
> > > Safer than the older encrypted Zip.
> > 
> > 
> > What did you mean with that?
> 
> Encrypted Zip does not protect some metadata. 7-Zip is protected if properly configured.
> https://en.wikipedia.org/wiki/Zip_(file_format)#Encryption

And 7-Zip don't care about Mark of the Web while Windows internal Zip does.
Metadata are not for security, they're for privacy.

**Comment by dngray** [comment]
I am surprised this wasn't already added to the site. I wonder why Peazip was suggested over this? I do use 7-Zip on Windows.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> I am surprised this wasn't already added to the site. I wonder why Peazip was suggested over this? I do use 7-Zip on Windows.

Same here, I have used 7-Zip my whole life and searching for alternatives I found Peazipa little while ago and tried it, and when I look up the website I thought PZ was better at something since 7Z wasn't listed.

**Comment by Mikaela** [comment]
While not directly related to the pull request,

> My connection with the software
> Unrelated

this is a red flag for me and I have seen it multiple times in my email now. Please clarify your connections and let the reader decide whether it is related to the issue or not.

**Comment by sakura974201** [comment]
> While not directly related to the pull request,

I am not the author of 7-Zip.
I have never sent a pull request or donated to 7-Zip.
I have downloaded and used 7-Zip.

**Comment by blacklight447-ptio** [comment]
my vote goes out to swapping peazip with 7zip, and keep and eye on peazip to see if their serverside issues will be resolved.
