### ISSUE TITLE
❌ Software Removal | PowerDNS

### ISSUE THREAD

**Issue by sakura974201** [privacytoolsIO/privacytools.io#1785]
## Description
I suggest removing PowerDNS from the recommended DNS providers.

## Why I am making the suggestion
The order of the Cipher Suites on `doh.powerdns.org` is out of order.

https://www.ssllabs.com/ssltest/analyze.html?d=doh.powerdns.org&s=136.144.215.158

## My connection with the software
https://www.ssllabs.com/ssltest/analyze.html?d=doh.powerdns.org&s=136.144.215.158

- [✔] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by blacklight447-ptio** [comment]
we currently do not have that as a requirement on dns providers. we are planning to make it a requirement soon though., closing, with the thought of re opening once we got the dns requirements live.
