### ISSUE TITLE
✨ Feature Suggestion | Joining CanvasBlocker to the Add-Ons List

### ISSUE THREAD

**Issue by hugoncosta** [privacytoolsIO/privacytools.io#1786]
## Description
Currently, CanvasBlocker is discretly mentioned under Browser Fingerprinting. Since it's a plugin like all the others, I believe it should join the Add-Ons, where all the others are.

**Comment by blacklight447-ptio** [comment]
> ## Description
> 
> Currently, CanvasBlocker is discretly mentioned under Browser Fingerprinting. Since it's a plugin like all the others, I believe it should join the Add-Ons, where all the others are.

one issue is though, we don't want folks to have to download 20 different addons before they are done following our advice, so i would wait with this, until with have figuired out a better way of tackling this problem.
