### ISSUE TITLE
📝 Correction | Add warning that Signal stores attachments unencrypted and messages unsafely on desktop

### ISSUE THREAD

**Issue by Zenithium** [privacytoolsIO/privacytools.io#1789]
## Description
As said in [signalapp/Signal-Desktop/#2815](https://github.com/signalapp/Signal-Desktop/issues/2815#issuecomment-432883836) Signal-Desktop stores all received attachments such as photos and videos unencrypted and while the messages are encrypted in a database, the decryption key is in plaintext in config.json

## Why I am making the suggestion
I think users should be warned about this because it deviates from the usual behavior of the mobile app.

**Comment by blacklight447-ptio** [comment]
tbh, signal encrypts them in transit, if someone gets access to your computer to access the messages, you have got much bigger problems on your hands. there is a reason why disk encryption is becoming more common.

**Comment by dngray** [comment]
I'm inclined to agree with @blacklight447-ptio 

If a user saves a file from the application elsewhere on there machine it won't be encrypted either unless they were using full disk encryption.

If the passwords were hashed, then Signal would have to ask for it every time the user opened the app.

We could still put a warning that the app should not be used on a multi-user system.

**Comment by lrq3000** [comment]
I agree it should not change Signal's "ranking" on PTIO, but I also think this merits a warning, maybe not specific to Signal BTW as I think this may affect nearly all softwares currently presented in Realtime communications.

Indeed, there's a reason why it's one of the criteria used on [securechatguide listing](https://github.com/Perelandra0x309/secure-im), and why this was considered a big issue for [Whatsapp](https://www.forbes.com/sites/zakdoffman/2019/07/16/whatsapptelegram-issue-has-put-a-billion-users-at-risk-check-your-settings-now/#130a1be95ab8) or [Telegram a few years ago until v2](https://www.bleepingcomputer.com/news/security/telegram-desktop-saves-conversations-locally-in-plain-text/) of their protocol which seems to fix the issue.

**Comment by blacklight447-ptio** [comment]
Seems like we agree, closing issue.
