### ISSUE TITLE
🌐 Website Issue | Enabling Chacha20 in TLS 1.2

### ISSUE THREAD

**Issue by sakura974201** [privacytoolsIO/privacytools.io#1792]
## Description
I propose to activate Chacha20-Poly1305 in TLS1.2 at `www.privacytools.io` and `privacytools.io`.

https://www.ssllabs.com/ssltest/analyze.html?d=www.privacytools.io
https://www.hardenize.com/report/privacytools.io/1584778546#www_tls

**Comment by blacklight447-ptio** [comment]
Any particular reason why you want this though?

**Comment by dngray** [comment]
Not much point in this.

Chacha20-Poly1305 was an extension to TLS 1.2, and is included in TLS 1.3. It's unlikely there would be a device old enough to not support TLS 1.3 that would have the Chacha20-Poly1305 extension ciphers.
