### ISSUE TITLE
📝 Correction | Nextcloud is NOT End-To-End encrypted

### ISSUE THREAD

**Issue by grasmanek94** [privacytoolsIO/privacytools.io#1794]
## Description

The text on https://www.privacytools.io/software/cloud/ reads:

> Nextcloud is a suite of client-server software for creating your own file hosting services on a private server you control. Nextcloud is free and open-source, and **supports end-to-end encryption with many of its clients**. The only limits on storage and bandwidth are the limits on the server provider you choose.

(emphasis mine)

I'd suggest to remove any references to E2EE entirely for this software, unless Nextcloud can provide proof / instructions that it's possible.

## Why I am making the suggestion

False advertising of features.

## My connection with the software

I have tried the software because privacytoolsIO recommends it, especially because I was looking for E2EE. I followed the self-installation instructions for my Debian server (using docker), installed the client on Windows and Android, only to find that there exists no E2EE option anywhere in the app on Windows, Android or on the server Web UI. The files can be read **unencrypted** in clear-text on the server(!) when accessing the server via either SSH or SFTP.

**Comment by Mikaela** [comment]
Their website has:

* https://nextcloud.com/endtoend/

and if I understand correctly, to enable it as admin you install this

* https://apps.nextcloud.com/apps/end_to_end_encryption

However we should probably have a warning label that the upstream says *End-to-end encryption is still in alpha state, don't use this in production and only with test data!*

**Comment by thatrobotdev** [comment]
It looks like the issue that has been linked to the warning label (https://github.com/nextcloud/end_to_end_encryption/issues/111) was closed after this PR was merged. Should we update the link to somewhere like https://help.nextcloud.com/t/help-test-the-latest-version-of-e2ee/87590 instead?

**Comment by dngray** [comment]
probably create a new issue or PR, would be the right place.
