### ISSUE TITLE
❌ Software Removal | AnonAddy

### ISSUE THREAD

**Issue by sakura974201** [privacytoolsIO/privacytools.io#1795]
## Description
I suggest removing AnonAddy.

## Why I am making the suggestion
It alters the body and subject of the email.

## My connection with the software
Users of it.

- [✔] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by blacklight447-ptio** [comment]
Elaborate on "alter'

**Comment by sakura974201** [comment]
> 
> 
> Elaborate on "alter'
Insert a string at the beginning of the email.
`This email was sent to … from … and has been forwarded by AnonAddy
Click here to deactivate this alias`.

**Comment by Mikaela** [comment]
I am also their user and I imagine they need to have that information somewhere. Paid users would have an option to disable it.

I am not concerned on the link getting hijacked as they have GPG.

**Comment by dngray** [comment]
> > Elaborate on "alter'
> 
> Insert a string at the beginning of the email.
> `This email was sent to … from … and has been forwarded by AnonAddy Click here to deactivate this alias`.

That is intended and not a requirement. Also in regard to [future standard](https://datatracker.ietf.org/doc/draft-autocrypt-lamps-protected-headers/):

> 4.2.  Confidential Subject
>
>   When a message is encrypted, the Subject should be obscured by
>   replacing the Exposed Subject with three periods: "..."
>
>   This value ("...") was chosen because it is believed to be language
>   agnostic and avoids communicating any potentially misleading
>   information to the recipient (see Section 7.1 for a more detailed
>   discussion).
