### ISSUE TITLE
✨ Feature Suggestion | Add secushare's comparison page to Guides

### ISSUE THREAD

**Issue by mehlon** [privacytoolsIO/privacytools.io#1796]
## Description
The [secushare](http://secushare.org) project provides a nice [comparison of secure messenging tools](https://secushare.org/comparison) that's highly in-depth and still relatively up-to-date. I suggest it be added to the "Guides" section under "More Privacy Resources".

**Comment by dngray** [comment]
I vote no on this, the table is fugly and in fact the site is pretty hideous too. That narrow column format being used is ugh.
