### ISSUE TITLE
Translate it to Portuguese-BR

### ISSUE THREAD

**Issue by trmendes** [privacytoolsIO/privacytools.io#180]
Hey guys. I want to translate your website to Portuguese-BR but I have just another 2 days with a computer to do so, after that I'm on the road again and I won't be able to do it so easily. Wondering how do I start this translate thing. I couldn't find any guideline about the best way to do it here.

Sorry about bringing up an issue for that.

Anyway it would be nice to have a guideline to people who wanna help you guys to translate.

Well....just let me know how I can help you with the Portuguese version of it so I can start doing it.

Cheers

**Comment by victorhck** [comment]
Hello!
I made and mantain the spanish translation.
Only 2 days to do everything?? O_o

Where are you going to host your translation? GitHub pages? host in your own server? etc...

Clone or download the whole repo and start translation step by step in index file. 
Translate a section, and check if everything it's ok. Fix your mistakes or typos, and when it's done just continue the work.
It's a good idea ask someone else to make a proofreading.
When finished it's a good idea to check the changes in the english repo to mantain your translated version updated.

Bye!

**Comment by trmendes** [comment]
Well...gonna try it in 2 days...I'm gonna fork it on github.

Thanks Victor...I'll let you know when I'm done with it, if I manage to do so :)

**Comment by trmendes** [comment]
Victor...it's translated to the Brazilian Portuguese already. Unfortunately I don't have a server to host the files. Any tip or free one? Anyway. A few friends of mine are checking the translation so I can give you an OK with that.

Thanks for helping me.

**Comment by bakku** [comment]
We might host it on privacytools.io as well on a separate HTML page !?

**Comment by trmendes** [comment]
That would be great. I've forked the privacytools.io respository and now I'm fixing my translations. I'm not home so I'll have a computer just for today and maybe tomorrow....so I might be done with all the translation until tomorrow. I update the status here when I'm done. Is that ok?

**Comment by Shifterovich** [comment]
Use [GitHub pages](https://pages.github.com/).

**Comment by trmendes** [comment]
Translation [done]
Language: Brazilian Portuguese
Repo: https://github.com/trmendes/privacytools.io

**Comment by Shifterovich** [comment]
@trmendes Set GitHub pages to use the master branch.

**Comment by trmendes** [comment]
@Shifterovich https://trmendes.github.io/privacytools.io/

**Comment by Shifterovich** [comment]
I'll add the link tomorrow.

**Comment by trmendes** [comment]
I have one question about this fork that I don't know how would be the best way of doing it. How do I keep track of the original project? I mean, how do I compare the updates to check what do I have to change for future releases?

**Comment by Shifterovich** [comment]
https://stackoverflow.com/questions/40983514/most-efficient-way-to-keep-a-fork-up-to-date
