### ISSUE TITLE
📝 Correction | VoIP: mention Zoom as something to avoid

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1803]
## Description

In other RTC apps, we mention software to avoid and in case of (FACEBOOK) WhatsApp we also have a link.

I wonder if we should also have a link and mentioning of Zoom.

* https://www.privacytools.io/software/real-time-communication/#voip

## Why I am making the suggestion

Zoom has been going around the news a lot on hoarding a lot of data on the users and cnnections to FACEBOOK etc.

## My connection with the software

I have been made to use Zoom a few times in some associations and have the Flatpak of it installed. I am not affiliated with them though.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
We're going to be doing a blog article on this.

Unfortunately its not something that can be avoided with institutions that mandate it's students use it.

Therefore we'll be writing a blog article detailing how to set this up in a virtual machine.

**Comment by dngray** [comment]
I think we can close this now https://blog.privacytools.io/protecting-your-privacy-while-using-zoom-at-home/

**Comment by Mikaela** [comment]
Not yet, but I can open a PR.
