### ISSUE TITLE
🆕 Software Suggestion | Brave Browser

### ISSUE THREAD

**Issue by Abruptive** [privacytoolsIO/privacytools.io#1806]
## Basic Information

**Name:** Brave
**Category:** Browser
**URL:** https://brave.com/

## Description

Brave fights malware and prevents tracking, keeping your information safe and secure. It’s our top priority.

[https://brave.com/features/](https://brave.com/features/)

## Why I am making the suggestion

Plenty of anti-tracker features.

## My connection with the software

User

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by Mikaela** [comment]
Brave was previously removed in https://github.com/privacytoolsIO/privacytools.io/pull/1169 and there are still issues such as https://github.com/brave/brave-browser/issues/3420 so I don't think it's inclusion can be reconsidered yet.
