### ISSUE TITLE
🆕 Software Suggestion | IceDrive

### ISSUE THREAD

**Issue by altechzilla** [privacytoolsIO/privacytools.io#1810]
## Basic Information

**Name:** IceDrive
**Category:** Cloud Storage
**URL:** https://icedrive.net/encrypted-cloud-storage

## Description

Claim: "Secure cloud storage. Because privacy matters. Take back control of your data with the strongest encrypted cloud storage in the world."

## Why I am making the suggestion

There's a good lifetime deal on the app going on, it has OS integration and apps.

## My connection with the software

No connection, just interested in getting it.

- [X ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by danarel** [comment]
Honestly, this doesnt look like a bad service (I have not dug deep), but I don't think it fits PTIO as it we have open source alternatives to this. Mainly Nextcloud. I would be interested to take some time and learn more about the company, though I am always and forever weary of lifetime accounts from companies like this.

**Comment by lucmos** [comment]
I bought their lifetime deal during the Black Friday offers.

I'm still not able to use it. Their app crashes, at least from linux, and they [do not provide public API](https://github.com/rclone/rclone/issues/3182) so you can't use third-party clients.

**Comment by ph00lt0** [comment]
@lucmos isn't that just a common problem with webdav in general.  I see they support that and I assume their client uses it too.

**Comment by lucmos** [comment]
> @lucmos isn't that just a common problem with webdav in general. I see they support that and I assume their client uses it too.

Most cloud storage providers that I know allow some form of interaction through public API (even Google drive).
What did you see they support?

**Comment by blacklight447-ptio** [comment]
As we currently list open source alternatives, i do not think icedrive is good addition to the site, closing issue.


p.s. if  people know reasons why it may actually be a good addition after all, feel free to comment.
