### ISSUE TITLE
✨ Feature Suggestion | WebRTC info box / wiki / something near the VoIP section about profiles/users

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1815]
## Description

We are telling people to disable WebRTC, but not why and with the COVID-19 pandemic a lot of WebRTC based tools are popular.

I think we should have a infobox telling *why to disable WebRTC* or at least *how to temporarily enable WebRTC*.

To answer the latter question, I would mention:

* `firefox --ProfileManager` and `about:profiles` and how creating a separate profile just for WebRTC (or to simplify it, JitsiMeet*
* Chromium's users menu and adding a separate user for WebRTC.

When the user is using a different profile or user account, they are missing all the tweaks and extensions from their normal browser and thus WebRTC is more likely to work with less pain than unloading extensions and tweaking `about:config`.

I don't know how well known those features are, but they are how I handle WebRTC and also some people I presume technical have found them useful.

Heavily related: #1814 (at least in my mind)

**Comment by dngray** [comment]
I think this might be a good idea actually

**Comment by lgrahl** [comment]
FYI, Chromium does [not expose private IP addresses any more](https://groups.google.com/forum/#!topic/discuss-webrtc/6stQXi72BEU) unless A/V permissions have been granted (which I think is a questionable move but that is another matter). They use mDNS to conceal private IP addresses.

For Firefox, this is still an [open issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1544770).

So, you can think of partially dropping this recommendation (if the exposed IP addresses were the only reason).

**Comment by Mikaela** [comment]
We seem to already have a "related information" below VoIP, so maybe the WebRTC infobox could go there.

I think dropping the recommendation would be a separate issue and this infobox would still be necessary as there are extensions blocking WebRTC and I don't know what they are in my usual setup, but I think it may be something popular like PrivacyBadger or µMatrix.

> They use mDNS to conceal private IP addresses.

Does this mean that they use `hostname.local` addresses and leak that identifiable bit of information?

**Comment by lgrahl** [comment]
> Does this mean that they use hostname.local addresses and leak that identifiable bit of information?

No, it is supposed to be a random UUID, so `<UUID.local>`. See https://github.com/rtcweb-wg/mdns-ice-candidates for details.

That being said, last time I fiddled around with it, there were some issues with it that [can leak information about the whole private network](https://github.com/rtcweb-wg/mdns-ice-candidates/issues/121#issuecomment-582891964). The related Chromium issue is currently not publicly visible, so I don't think they have fixed it, yet.

**Comment by dngray** [comment]
I'm not sure we should be recommending people use Firefox with Jitsi because of https://github.com/privacytoolsIO/privacytools.io/issues/1814 hmm.

**Comment by dngray** [comment]
I believe we can close this as we have a warning for Jitsi:

```html
<span class="badge badge-warning"
      data-toggle="tooltip"
      title=""
      data-original-title="Our Firefox tweaks recommend disabling WebRTC as it can be used to leak your IP address even behind a VPN, which is why Tor Browser disables it.">
      Requires WebRTC
</span>
```

**Comment by lgrahl** [comment]
> Chromium does [not expose private IP addresses any more](https://groups.google.com/forum/#!topic/discuss-webrtc/6stQXi72BEU) unless A/V permissions have been granted (which I think is a questionable move but that is another matter). They use mDNS to conceal private IP addresses.

Thought you might be interested: This is now active in Firefox (75 but probably also in older versions), too. Try it yourself:

1. Open https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2. Click "Gather Candidates"
3. You will only see your public IP and a couple of `.local` mDNS names with random UUIDs.

**Comment by dngray** [comment]
I checked this in 68.7ESR, and it does leak the IP, whereas you're right Firefox 75 does not. Debian has the ESR version in their repositories.

So maybe need to  modify the warning.

**Comment by Thorin-Oakenpants** [comment]
Not my area of expertise - and there are other reasons, but I'd have to check, as to why WebRTC is disabled.

If you look in the diffs at ghacks user.js: there have been some WebRTC prefs and changes in core FF: I say recently, but that's subjective: but certainly since 68/ESR. One of which ~~we~~ Earthlng tried to bring to @gorhill 's attention in [this comment, at the end](https://github.com/ghacksuserjs/ghacks-user.js/issues/805#issuecomment-557538162)


---

here's a couple

flipped in FF74
pref("media.peerconnection.ice.obfuscate_host_addresses", true); // prev: false

added in Ff70
pref("media.peerconnection.ice.proxy_only_if_behind_proxy", false)
