### ISSUE TITLE
📝 Correction | Please update the logo of Signal App in your website in Instant Messengers Column.

### ISSUE THREAD

**Issue by Lostname777** [privacytoolsIO/privacytools.io#1819]
You can find it on: https://lh3.googleusercontent.com/jCln_XT8Ruzp7loH1S6yM-ZzzpLP1kZ3CCdXVEo0tP2w5HNtWQds6lo6aLxLIjiW_X8=s180

**Comment by Mikaela** [comment]
Would you be open to sending a pull request or have any idea where to get an svg?

**Comment by Lostname777** [comment]
I just wanted to say that signal has updated their logo and you should do that too.
And in worth mentioning column of your P2P Messengers of the Real-Time Communication, you have mentioned about Status.im and when I hover my mouse on the yellow object named "Experimental", I don't get any short note too, please add that

**Comment by dngray** [comment]
We wouldn't be using that logo above.

https://raw.githubusercontent.com/signalapp/Signal-Desktop/development/images/signal-logo.svg

**Comment by Lostname777** [comment]
Why don't you update signal logo?
