### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by trmendes** [privacytoolsIO/privacytools.io#182]
It would be great to have a version at the main page telling what version are being displayed to the user after render the html. That could help people who are translating or reading the html in another language (!= from the original one - english) to be sure (or have a idea) if that page is updated or not.

--- A changelog would be awesome :D

**Comment by Shifterovich** [comment]
[This](https://github.com/privacytoolsIO/privacytools.io/commits/master) basically works like a changelog. Versions aren't a good idea because of small changes.

**Comment by trmendes** [comment]
Cool...it does works like a changelog and that's great.

The idea for the version was more for those people who are not helping the project, for those who are just reading the main html in another language. Something else to help them just to be sure if what they are reading in Chinese, Portuguese, etc, is updated or not with the last official version (the English one). 

But yes, small changes make the version number big. Maybe "Last English Update: MM/DD/YYYY HH:MM". But that is just an idea.
