### ISSUE TITLE
Brave should be listed again

### ISSUE THREAD

**Issue by thwi84** [privacytoolsIO/privacytools.io#1820]
Hi there,

I read this article: https://www.ghacks.net/2020/02/25/study-finds-brave-to-be-the-most-private-browser/

`If you just want the result, the study found that used out of the box, Brave "is by far the most private of the browsers studied" followed by Chrome, Firefox and Safari. Brave is the only web browser that did not use identifiers that allowed tracking of the IP address over time and did not share details of web pages visited to backend servers.`

Maybe Brave should be listed again?

**Comment by beerisgood** [comment]
This "study" is a fail and only compare connection's at browser startup which doesn't say anything on browser itself.

Also remember that Brave has it's own advertising program which i would call "Adware".

**Comment by ceiphr** [comment]
I would be open to that idea. I think more evidence is necessary, although this is a good start.

**Comment by Mikaela** [comment]
Duplicate of https://github.com/privacytoolsIO/privacytools.io/issues/1806 where I said

> Brave was previously removed in #1169 and there are still issues such as brave/brave-browser#3420 so I don't think it's inclusion can be reconsidered yet.

and I haven't heard of any big developments happening within ten days.
