### ISSUE TITLE
📝 Correction | status.privacytools.io / privacytools.statuspage.io is not mentioned at all

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1823]
## Description

The status page is not mentioned anywhere that I or GitHub search can see and apparently has to be known by the service user/visitor.

## Why I am making the suggestion

Today there was a long downtime due to datacenter migration that multiple people have been wondering about now that it's back up and probably weren't aware of it.

* https://privacytools.statuspage.io/incidents/jjbjhtx32pj2

## My connection with the software

I am a team member who was aware of the page existing, but didn't think of distributing the information about either (sorry).

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by nitrohorse** [comment]
Huh, TIL we have this :smile: We could link to it from https://www.privacytools.io/services/ and even embed a badge it looks like: https://help.statuspage.io/help/configure-the-recommended-status-embed

**Comment by FreddyMarsden** [comment]
Why not use https://cachethq.io/ - its an open source alternative?

**Comment by Mikaela** [comment]
I think that would be a question for @JonahAragon , but I imagine it's so it's not in PrivacyTools infrastructure and in case everything is down, the status page won't be.

I also remember that Cachet dropped RSS support some time ago and with a quick look I didn't find if they have returned it yet.

**Comment by JonahAragon** [comment]
> but I imagine it's so it's not in PrivacyTools infrastructure and in case everything is down, the status page won't be.

yes
