### ISSUE TITLE
📝 Correction | Update ProtonVPN pricing

### ISSUE THREAD

**Issue by tbnv** [privacytoolsIO/privacytools.io#1827]
## Description
It's mentioned that the ProtonVPN paid plan costs $96/year. However, their paid offer starts at $48/year. Of course it doesn't have all the features of the most expensive plan, but it's still a great option.

## Why I am making the suggestion
I think stating their plans are either _FREE_ or _USD $96/year_ makes them appear more expensive than they really are. Also, there are 2 prices displayed for IVPN so why not do the same for ProtonVPN?

## My connection with the software
None.

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
> Also, there are 2 prices displayed for IVPN so why not do the same for ProtonVPN?

Yeah we should do this, I think we initially only had whatever the bottom plan was, but then added the other one for IVPN due to the remote port forwarding, so we certainly can for ProtonVPN.
