### ISSUE TITLE
🆕 Software Suggestion | Mysterium VPN

### ISSUE THREAD

**Issue by wuniversales** [privacytoolsIO/privacytools.io#1831]
Name: Mysterium VPN
Category: VPN
URL: https://mysterium.network/
GIT: https://github.com/MysteriumNetwork

**Why do I make this suggestion?**

- As mentioned on the website, it is technologically impossible to save logs.
- Increases security, the VPN is decentralized.
- I have noticed that it is open source, so it gives me some confidence.
- Mysterium VPN works with OpenVPN or WireGuard protocols.

I do the holding because I use it on Android.

**My connection with the software:** 

None, only user.

**Comment by dngray** [comment]
At this point I would say it is far too experimental to be listed.

From a cursory glance, it seems to be a proxy service with some cryptocurrency incentives for exit nodes who provide bandwidth.

The guts of it being their brokerage protocol, that allows consumers and providers to know about each other. It seems very much like a lot of work went into marketing materials.

It doesn't seem to be truly decentralized despite the marketing materials according to the [high level documentation](https://docs.mysterium.network/en/latest/architecture/node-high-level/).

> At the moment Mysterium network uses a centralized message broker for communicating between nodes in the network. It allows sending and receiving messages by registered network participants.

I was a bit disappointed to see now [low level spec](https://docs.mysterium.network/en/latest/architecture/node-low-level/), the documentation seems missing, despite a link in their contents page.

Their [FAQ](https://mysterium.network/faq/) also indicates that not multi-hop, unlike say a Tor circuit.

> Do you plan on adding multi-hop routing where the traffic is routed through multiple VPN nodes from different providers?
>
> We are considering a traffic routing mechanism which would combine splitting request data through different nodes and changing the end-to-end circuits between requests. This is, of course subject, to how our technology and the wider market evolves.

This means its really quite centralized depending on who controls the node you're brokered to. As the exit nodes are provided by residential connections with static IP addresses (all 578 of them). The bandwidth going through the exits is likely a lot less than that on Tor, and quite possibly a lot easier to fingerprint.

> Will I need a static IP address to run a node?
>
> Yes, you will need to have a static IP address for nodes. A domain is not needed as we don’t detect and use it in proposals. For nodes to operate you need a public IP address.
To participate in Bounty pilot, you will have to set up on your Residential IP.

There certainly seems some interest there in static residential IP addresses. It sounds vaguely like some of the other networks that encourage users to give up their residential IP address for "usage".

I would not depend on this for strong anonymity. I think in some cases it may even be worse than a commercial VPN service provider [such as the trusted ones we select](https://www.privacytools.io/providers/vpn/) based on our criteria as you really do not know who is running the exit you're connected to. At the same time I doubt it would be as fast either.
