### ISSUE TITLE
🆕 Software Suggestion | SimpleLogin

### ISSUE THREAD

**Issue by nguyenkims** [privacytoolsIO/privacytools.io#1832]
## Basic Information

**Name:** SimpleLogin
**Category:** Email alias/forwarding and identity provider (SSO) service
**URL:** https://simplelogin.io and https://github.com/simple-login

## Description
SimpleLogin is an open source, can be *self-hosted* email alias/forwarding service.
It also offers a privacy-focused alternative to the "Sign in with Facebook|Google|Apple" button.

## Why I am making the suggestion
The service allows you to not expose your real email address using email alias.
Email aliases can also be used as "business emails", i.e. email addresses like contact@my-domain.com, sales@my-domain.com, etc

A same request has been opened and closed sometimes ago: https://github.com/privacytoolsIO/privacytools.io/issues/1693

Since then we have implemented necessary measures to satisfy criterias on https://www.privacytools.io/providers/email/

Our hardenize and ssllabs scan results:

For the main domain simplelogin.io
https://www.hardenize.com/report/simplelogin.io/1585823060
https://www.ssllabs.com/ssltest/analyze.html?d=simplelogin.io

For the main email domain (simplelogin.co)
https://www.hardenize.com/report/simplelogin.co/1585845645
https://www.ssllabs.com/ssltest/analyze.html?d=simplelogin.co

## My connection with the software

I'm the founder of this service.

- [X ] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
It would be great if they added your service, I hope someone can look into this.

**Comment by nitrohorse** [comment]
Thanks for sharing! I see mentioned on the home page:

> The only email forwarding solution that is self-hostable...

@nguyenkims I'm wondering if you're familiar with https://anonaddy.com? -- also open-source, MIT-licensed, and self-hostable.

Comparing SimpleLogin's [privacy policy](https://simplelogin.io/privacy/) (not linked anywhere on the main page?) to [AnonAddy's](https://anonaddy.com/privacy/), is it possible for you to provide more specific details regarding

- Information SimpleLogin collects from users
- How SimpleLogin Uses users' personal information
- How SimpleLogin protects users' personal information
- Security of services, infrastructure
- Third party services used (any analytics, payment processor)

**Comment by nguyenkims** [comment]
@nitrohorse thanks for your message. 

> @nguyenkims I'm wondering if you're familiar with https://anonaddy.com? -- also open-source, MIT-licensed, and self-hostable (and listed here).

As far as I know, the self-hosting instructions on AnonAddy aren't complete: `More instructions to follow soon...` has been there on https://github.com/anonaddy/anonaddy since quite some times. Please don't take this as a critics towards AnonAddy, it is a great service and has a similar mission to SimpleLogin. As we spent a lot of time making SimpleLogin (relatively) easy to be self-hosted and some people have been running their own SimpleLogin instance successfully since several months, we think we can put that statement on our website.  

![image](https://user-images.githubusercontent.com/3167780/79699448-fa548a00-828f-11ea-8368-803cb606e453.png)

SimpleLogin privacy policy is on the website footer on every page. Its link is https://simplelogin.io/privacy

Almost all questions are answered in our privacy policy and terms and condition page (https://simplelogin.io/terms/)

**Comment by nitrohorse** [comment]
> As far as I know, the self-hosting instructions on AnonAddy aren't complete: More instructions to follow soon...

Ah, you're right, it [looks like the instructions on their readme](https://github.com/anonaddy/anonaddy#self-hosting) aren't fully there yet. :thinking: 

> SimpleLogin privacy policy is on the website footer on every page.

Apologies, looks like I have a [filter list](https://raw.githubusercontent.com/Hunter-Github/the-best-stack-overflow/master/se_filters.txt) in uBlock Origin which was removing `###footer` elements from the DOM, yikes. I see the footer now with the links.

Also, appreciate you taking the steps to have a solid hardenize report. From my perspective I think I'm comfortable with adding SimpleLogin to our [cloaking services section](https://www.privacytools.io/providers/email/#cloaking). Interested in more feedback from @privacytoolsIO/editorial

**Comment by nitrohorse** [comment]
Cross-posting a [Reddit thread](https://reddit.com/r/privacytoolsIO/comments/g4927c/request_to_add_simpleloginio_browser_addon/) with some discussion.

**Comment by LongJohn-Silver** [comment]
> > As far as I know, the self-hosting instructions on AnonAddy aren't complete: More instructions to follow soon...
> 
> Ah, you're right, it [looks like the instructions on their readme](https://github.com/anonaddy/anonaddy#self-hosting) aren't fully there yet. thinking
> 
> > SimpleLogin privacy policy is on the website footer on every page.
> 
> Apologies, looks like I have a [filter list](https://raw.githubusercontent.com/Hunter-Github/the-best-stack-overflow/master/se_filters.txt) in uBlock Origin which was removing `###footer` elements from the DOM, yikes. I see the footer now with the links.
> 
> Also, appreciate you taking the steps to have a solid hardenize report. From my perspective I think I'm comfortable with adding SimpleLogin to our [cloaking services section](https://www.privacytools.io/providers/email/#cloaking). Interested in more feedback from @privacytoolsIO/editorial

By the way, SimpleLogin has also fully answered QtASK, I think they are in another issue.

**Comment by LongJohn-Silver** [comment]
> Cross-posting a [Reddit thread](https://reddit.com/r/privacytoolsIO/comments/g4927c/request_to_add_simpleloginio_browser_addon/) with some discussion.

Regarding the jurisdiction, I don't really think that's an issue since they can't see the messages and the things about metadata will not be that interesting, if your threat model is that high you shouldn't even use e-mail.

**Comment by fabianski7** [comment]
please take a look at simple-login/app#117

**Comment by ankushdas9** [comment]
Totally recommend this. They've also added a new security page that I spotted on twitter: 

https://simplelogin.io/security/

**Comment by nitrohorse** [comment]
Good to see; thanks for the headsup!

**Comment by DirkAmiably3829** [comment]
I'm against the addition.
The website user interface uses poor quality machine translation.

**Comment by dngray** [comment]
>  The website user interface uses poor quality machine translation.

This may be because of a lack of native speakers. @nguyenkims would it be easy for native speakers to submit PRs with native speech corrections?

**Comment by nguyenkims** [comment]
@dngray Yes! We'd be happy to accept PRs that correct the texts. 

We are indeed not native speakers - apologies for any grammar/expression mistakes on the website!

**Comment by DirkAmiably3829** [comment]
> 
> 
> @dngray Yes! We'd be happy to accept PRs that correct the texts.
> 
> We are indeed not native speakers - apologies for any grammar/expression mistakes on the website!

Where can I send a pull request to improve the translation?

**Comment by nguyenkims** [comment]
@DirkAmiably3829 our website is on https://github.com/simple-login/website, for example here you can see different pages https://github.com/simple-login/website/tree/master/content

The FAQ section is in this file https://github.com/simple-login/website/blob/master/static/custom.js

The main page is in https://github.com/simple-login/website/blob/master/layouts/index.html

The website uses Hugo https://gohugo.io/ to build, you can refer to the README on how to run it locally.

Thanks in advance!

**Comment by blacklight447-ptio** [comment]
at this point, i believe that simple login does meet our requirements. @dngray are you aware of any real issues left?

**Comment by dngray** [comment]
> at this point, i believe that simple login does meet our requirements. @dngray are you aware of any real issues left?

No, I'll work on a PR for this.
