### ISSUE TITLE
Consider dropping LibreWRT for LEDE

### ISSUE THREAD

**Issue by Atavic** [privacytoolsIO/privacytools.io#184]
_Open Source Router Firmware > LibreWRT_ has no landing page (https://librewrt.org/).

I suggest https://lede-project.org/, with an active [mirror](https://github.com/lede-project/source).

**Comment by KevinAT** [comment]
didn't LibreWRT merge into the LibreCMC project?

and if i'm not mistaken LEDE planned on re-merging with OpenWRT

**Comment by Atavic** [comment]
LibreWRT was merged to the libreCMC project in 2015.

https://librecmc.org/
