### ISSUE TITLE
❌ Software Removal | Minds.com

### ISSUE THREAD

**Issue by danarel** [privacytoolsIO/privacytools.io#1848]
I believe we should delist the Minds.com in worth mentioning under Social Networks.

Minds.com is a popular home to neo-Nazis, fascists, holocaust deniers, and racists.

https://www.vice.com/en_us/article/wjvp8y/minds-the-anti-facebook-has-no-idea-what-to-do-about-all-the-neo-nazis

https://www.vice.com/en_us/article/qv7q87/trump-invites-fringe-social-media-company-popular-with-nazis-to-the-white-house

https://www.engadget.com/2018-04-20-minds-anti-facebook-crypto-social-network-extreme-content.html

https://www.mediamatters.org/tucker-carlson/tucker-carlson-promotes-another-social-media-platform-full-bigotry

It holds conferences with speakers as Carl Benjamin (openly uses the n-word, mocked UK politician after her sexual assault), Andy Ngo (popular pro-fascist "journalist" who was involved in the serious life threatening injuries to an anti-fascist at a bar), Tim Pool (YouTube fascist apologist), and more. 

Minds.com, while being an "anti-Facebook" isn't a welcoming community for all. Unlike say, Mastodon, where you can find an instance on the far left, the far right, apolitical, etc, Minds.com offers one destination and it's not a good one.

With that, I don't believe Privacy Tools should suggesting people sign up, unknowingly sending them to a cesspool of the worlds worst Minds (see what I did there?).

**Comment by dngray** [comment]
If this hasn't improved I would approve the removal of this.

We really shouldn't be making recommendations that endorse or encourage any kind of criminal behavior. Hate speech and violence against particular groups is encompassed in this.

Likewise we shouldn't be approving platforms that encourage grooming other individuals that that lead to criminal activity.
