### ISSUE TITLE
Remove national flags from the language select

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#185]
I think that it should remove national flag on language choice.
It may cause misleading.
Not only Taiwai use traditional chinese, but also Hongkong and other region written in this language.
Same as traditional chinese, the symbol of English language is flag of the United Kingdom is unreasonable on [spanish version](https://victorhck.gitlab.io/privacytools-es/).

**Comment by Hillside502** [comment]
Maybe "natioanal" flags can be found on ships' sterns  :-)

**Comment by GrimPixel** [comment]
Yes, using flags to represent languages is a popular terrible idea.

http://www.flagsarenotlanguages.com/blog/

**Comment by BurungHantu1605** [comment]
You guys are technically right. It just looks really bad without flats and usability is important to me.

**Comment by troutperch** [comment]
I don't think remove flags will be ugly. I could pull request if you think it's okay:

![2019-04-02_15-11](https://user-images.githubusercontent.com/47532693/55383421-b72b5a00-555a-11e9-97b1-be8f8b4d8eb4.png)

![2019-04-02_15-18](https://user-images.githubusercontent.com/47532693/55383422-b7c3f080-555a-11e9-88cf-e015b45aac51.png)

**Comment by troutperch** [comment]
Sad to see https://github.com/privacytoolsIO/privacytools.io/pull/181 was merged after open this issue 2 months.

**Comment by JonahAragon** [comment]
I actually like that first mock-up image, I don't think the flags are necessary to convey a good aesthetic.

**Comment by BurungHantu1605** [comment]
@troutperch Can you include both solutions in your pull requests please? Like shown in the screenshot.
