### ISSUE TITLE
🆕 Software Suggestion | Backblaze

### ISSUE THREAD

**Issue by lucmos** [privacytoolsIO/privacytools.io#1867]
## Basic Information

**Name:** Backblaze
**Category:** Cloud Storage
**URL:** https://www.backblaze.com

## Description

From their website:
 
> Cloud storage that's astonishingly easy and low-cost.
> 
> As a highly open company, Backblaze publishes detailed information on the Storage Pod hardware, the Vault software, and the reliability statistics behind the hard drives it uses.
> 
> Backblaze has won numerous awards and recognitions including #1 cloud backup service by About.com, SIIA CODiE Best Cloud Storage and Backup Solution, and Deloitte Fast 500 fastest growing technology companies. 

## Why I am making the suggestion

I'm interested in the opinion of privacy experts on it and why it isn't a suggested cloud provider.

## My connection with the software

No connection. I just started to use the B2 Cloud Storage for my backups after some research on cloud providers.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by FreddyMarsden** [comment]
When visiting the site I got hit with a barrage of cookies:

> Advertising Partners:
Manage
NextRoll
Google
Facebook
AOL
Yahoo
Bidswitch
AppNexus
Liveramp
OpenX
MicroAd
Rubicon
Index
Pubmatic
Taboola
Outbrain
TripleLift
LinkedIn
Pixalate
Oath
AOL One: Video

Also can't find the source code. Considering the [alternatives](https://www.privacytools.io/providers/cloud-storage/) I don't think I'd advise anyone using this right now.

**Comment by beerisgood** [comment]
@FreddyMarsden 
https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fwww.backblaze.com%2F#requests

**Comment by strafer** [comment]
Backblaze recently updated their cookie information. It's very detailed.
https://www.backblaze.com/company/cookies.html

**Comment by danarel** [comment]
> Backblaze recently updated their cookie information. It's very detailed.
> https://www.backblaze.com/company/cookies.html

It's very detailed, which is great, but also shows that it has no business being on this site. Its not a privacy focused cloud storage company. They may offer great security (I did not look), but they do not respect user privacy.

**Comment by danarel** [comment]
Closing as this is not really a privacy focused product given the amount of tracking they use.
