### ISSUE TITLE
❌ Software Removal | SecureDNS

### ISSUE THREAD

**Issue by benbeierwaltes** [privacytoolsIO/privacytools.io#1869]
## Description
It looks like SecureDNS is offline and the host is asking for people to not use it anymore.

## Why I am making the suggestion
Service Offline

## My connection with the software
User

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by beerisgood** [comment]
> SecureDNS has been shutdown since the 30th of April 2020. Please do not use SecureDNS anymore.

https://securedns.eu/

**Comment by danarel** [comment]
This is mentioned in #1841 as part of the DNS page cleanup, but since it's dead now, I think we should remove it and not wait for the cleanup to be done.
