### ISSUE TITLE
🆕 Software Suggestion | Keybase KBFS

### ISSUE THREAD

**Issue by JonahAragon** [privacytoolsIO/privacytools.io#1870]
## Basic Information

**Name:** KBFS
**Category:** Providers > Cloud Storage
**URL:** https://keybase.io/docs/kbfs

## Description

Keybase provides 250GB of end-to-end encrypted cloud storage for free. It also has sharing functionality with any other Keybase user. Users are currently unable to purchase additional storage at this time.

## Why I am making the suggestion

We currently recommend Keybase as an instant messenger. Because we currently don't recommend any specific cloud storage provider (just Nextcloud providers generically) it may be worth a look.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by dngray** [comment]
I don't see any reason why this couldn't be added.

**Comment by FreddyMarsden** [comment]
Linking the new Keybase book page on it here:
https://book.keybase.io/files

**Comment by danarel** [comment]
I think it's a good addition

**Comment by ph00lt0** [comment]
Please see https://github.com/privacytoolsIO/privacytools.io/issues/1894
