### ISSUE TITLE
📝 Correction | Don't mention Privacy Badger/uBlock in fingerprint desc

### ISSUE THREAD

**Issue by dngray** [privacytoolsIO/privacytools.io#1880]
https://www.privacytools.io/browsers/#fingerprint

> Modern web browsers have not been architected to assure personal web privacy. Rather than worrying about being fingerprinted, it seems more practical to use free software plugins like Privacy Badger and uBlock Origin.

**Comment by blacklight447-ptio** [comment]
i agree, would you be willing to make a quick pr for this?

**Comment by dngray** [comment]
Doing it now
