### ISSUE TITLE
📝 Correction | Keybase acquired by Zoom

### ISSUE THREAD

**Issue by JanOstrowka** [privacytoolsIO/privacytools.io#1895]
## Description
It has just been announced that[ Keybase has been acquired by Zoom
](https://keybase.io/blog/keybase-joins-zoom).
I believe it is a good idea, to inform potential users about the acquisition of Keybase, on the [software website](https://www.privacytools.io/software/real-time-communication/).

## Why I am making the suggestion
Based on the numerous news about Zoom, not taking privacy or security seriously:
- lie about e2ee ([source](https://theintercept.com/2020/03/31/zoom-meeting-encryption/))
- sending data to Facebook without consent ([source](https://www.vice.com/en_us/article/k7e599/zoom-ios-app-sends-data-to-facebook-even-if-you-dont-have-a-facebook-account))
- others ([link](https://amp.theguardian.com/technology/2020/apr/02/zoom-technology-security-coronavirus-video-conferencing))

## My connection with the software
I am in no way affiliated with Keybase or Zoom.

- [x] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by danarel** [comment]
I also think the fact that Keybase doesn't even know what their future is can be seen as a red flag. 

A lot of times after sales like this, you get a clear comment from the company. Take Facebook buying Instagram. That same day Instagram made it clear they were not going anywhere and would continue to operate, just now with more resources.

Keybase said they don't know what their future is, which tells me this was not a sale for their product, but for their staff and part of the technology. So I think Keybase's future is dire.

**Comment by dngray** [comment]
Duplicate

**Comment by ph00lt0** [comment]
@dngray it's not really a duplicate right? Keybase KBFS (cloud) is not the same as Keybase (messaging) on the website.

**Comment by dngray** [comment]
They are part of the same product and the reasoning is the same as my comment in https://github.com/privacytoolsIO/privacytools.io/issues/1894#issuecomment-625379920

**Comment by JanOstrowka** [comment]
Thank you @ph00lt0 ! I was about to point out the same thing.
