### ISSUE TITLE
❌ Software Removal | Keybase

### ISSUE THREAD

**Issue by Noeliel** [privacytoolsIO/privacytools.io#1896]
## Description

I'm proposing the removal of the Keybase app for real-time communication.

## Why I am making the suggestion

Today they announced that they are joining Zoom.
As per [1], Keybase's future is still written in the stars:

> What the Keybase team will be doing

> Initially, our single top priority is helping to make Zoom even more secure. There are no specific plans for the Keybase app yet. Ultimately Keybase's future is in Zoom's hands, and we'll see where that takes us. Of course, if anything changes about Keybase’s availability, our users will get plenty of notice.

> So, our shortest-term directive is to significantly improve our security effectiveness, by working on a product that's that much bigger than Keybase. We can't be more specific than that, because we're just diving in.

---

I believe the acquisition, Zoom's bad track record and the statement presented above warrant a discussion.

Resources:
[1] https://keybase.io/blog/keybase-joins-zoom
[2] https://blog.zoom.us/wordpress/2020/05/07/zoom-acquires-keybase-and-announces-goal-of-developing-the-most-broadly-used-enterprise-end-to-end-encryption-offering/

HN thread:
[3] https://news.ycombinator.com/item?id=23102430

## My connection with the software

Unaffiliated. Had the app installed on my device just in case, but never used it.

- [X] I will keep the issue up-to-date if something I have said changes or I remember a connection with the software.

**Comment by Noeliel** [comment]
Related: #1894 and #1895.

**Comment by dngray** [comment]
Duplicate
