### ISSUE TITLE
🌐 Website Issue | panopticlick.eff.org doesn't have target="_blank"

### ISSUE THREAD

**Issue by GrimPixel** [privacytoolsIO/privacytools.io#1899]
## Description
On this page https://www.privacytools.io/browsers/

There are two “Test your browser now”, one is opening in the current tab, the other opening in the new tab. Actually it's better to open in a new tab, because after the test, you have already gone through many pages and need some more effort to come back to PTIO.

**Comment by danarel** [comment]
I just tested this and didn't have this issue. The code on both links is also target="_blank".

**Comment by GrimPixel** [comment]
This line doesn't have that:
https://github.com/privacytoolsIO/privacytools.io/blob/f1878a80eb1c1cd42d071440f7e1cdb1c3d11b75/_includes/sections/browser-fingerprint.html#L10

Comparing to the other:
https://github.com/privacytoolsIO/privacytools.io/blob/f1878a80eb1c1cd42d071440f7e1cdb1c3d11b75/_includes/sections/browser-webrtc.html#L10
