### ISSUE TITLE
Trace - firefox add-on recommendation

### ISSUE THREAD

**Issue by EvgenijM86** [privacytoolsIO/privacytools.io#1901]
I have been using this add-on for quite some time and it offers a lot of control over how your fingerprint is generated. Maybe you should list it as a privacy addon on page like here? - https://www.privacytools.io/browsers/#addons 

https://addons.mozilla.org/en-US/firefox/addon/absolutedouble-trace/
https://github.com/jake-cryptic/AbsoluteDoubleTrace/

**Comment by dngray** [comment]
Won't be added as it doesn't work correctly. See: https://github.com/privacytoolsIO/privacytools.io/issues/1801#issuecomment-605403671 and https://github.com/privacytoolsIO/privacytools.io/issues/1801#issuecomment-621732429

Also duplicate.
