### ISSUE TITLE
Additional suggestions for the "File Sharing" section

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#193]
The purpose of this issue is to track further suggestions for the "File Sharing" section (once this [PR](https://github.com/privacytoolsIO/privacytools.io/pull/189) gets merged).

-------

@Shifterovich mentioned in the [earlier thread](https://github.com/privacytoolsIO/privacytools.io/issues/160#issuecomment-272947426):

> The name of the section would make BitTorrent elitists angry if we didn't mention the BitTorrent protocol :P. Anyway, I can recommend I2PSnark and iMule as file sharing tools.

I completely agree with his suggestion, using i2p to torrent is really the only "widely" adopted way to torrent anonymously for free. However torrenting using i2p is not limited only to the I2P Snark client, there's also a Vuze plugin, as well as other options. What should we thus link to?

**Comment by jeroen7s** [comment]
I've never been able to get any torrent downloaded through i2p
And i've tried the popular ones
