### ISSUE TITLE
I2P Addresshelper wrong

### ISSUE THREAD

**Issue by matteke-games** [privacytoolsIO/privacytools.io#198]
You should not use your b32.i2p address, its just so people can access it without knowing the base64 which is: "`5GOHmoHjcG3c55VitD6OZmDHFpDfetZkwsgLUsq4EgM5SgJIFYYgxeDXFLJSrrUxjgD70bC-ZUKzGZ-hf8l4RUUrM7aUGCSC3Yk~tAZMIVMni6hDCw269GQRJUYrOeGX9Ufze2ln~gWssUsH8BErV1HHJ-FS2oKQZYR-rROEGRJ3ptR5LiZmsKgfcObU3Y4pBfK~yq9s~V7XV-7YD8v8eEjiEeyBVKKddeoguj~Uq9N2NsR4rm~FclpAZi2HS50wD4Ph96di7DxgKdk96uDHFeIQJzvdK6VPuvuX6jZUA-LVbwlnLM~~mh4hv5jT7w~KaJPkTFWRRO1~lrrhiS4WLjjBnhfAty7PZ4W4GSuJKPPGhLPF65Yz7Ji--T3p2ZLLkpjPbNpgokNAKHfOkr~uR7F1rjnkcRTi3ZzYciiALCJNwNgLEOXowuAbdLyM5GO3gXm27~PZpsttxvCBlHkmD8L2xinybADaDvrAe3ReWbi9zd9WMGm5zc2sfZ1G~1E1BQAEAAEAAA==`" in your case so the link you provide on the top should be: "`http://privacytools.i2p/?i2paddresshelper=5GOHmoHjcG3c55VitD6OZmDHFpDfetZkwsgLUsq4EgM5SgJIFYYgxeDXFLJSrrUxjgD70bC-ZUKzGZ-hf8l4RUUrM7aUGCSC3Yk~tAZMIVMni6hDCw269GQRJUYrOeGX9Ufze2ln~gWssUsH8BErV1HHJ-FS2oKQZYR-rROEGRJ3ptR5LiZmsKgfcObU3Y4pBfK~yq9s~V7XV-7YD8v8eEjiEeyBVKKddeoguj~Uq9N2NsR4rm~FclpAZi2HS50wD4Ph96di7DxgKdk96uDHFeIQJzvdK6VPuvuX6jZUA-LVbwlnLM~~mh4hv5jT7w~KaJPkTFWRRO1~lrrhiS4WLjjBnhfAty7PZ4W4GSuJKPPGhLPF65Yz7Ji--T3p2ZLLkpjPbNpgokNAKHfOkr~uR7F1rjnkcRTi3ZzYciiALCJNwNgLEOXowuAbdLyM5GO3gXm27~PZpsttxvCBlHkmD8L2xinybADaDvrAe3ReWbi9zd9WMGm5zc2sfZ1G~1E1BQAEAAEAAA%3d%3d`"

**Comment by Shifterovich** [comment]
Tested and indeed, `http://privacytools.i2p/?i2paddresshelper=5GOHmoHjcG3c55VitD6OZmDHFpDfetZkwsgLUsq4EgM5SgJIFYYgxeDXFLJSrrUxjgD70bC-ZUKzGZ-hf8l4RUUrM7aUGCSC3Yk~tAZMIVMni6hDCw269GQRJUYrOeGX9Ufze2ln~gWssUsH8BErV1HHJ-FS2oKQZYR-rROEGRJ3ptR5LiZmsKgfcObU3Y4pBfK~yq9s~V7XV-7YD8v8eEjiEeyBVKKddeoguj~Uq9N2NsR4rm~FclpAZi2HS50wD4Ph96di7DxgKdk96uDHFeIQJzvdK6VPuvuX6jZUA-LVbwlnLM~~mh4hv5jT7w~KaJPkTFWRRO1~lrrhiS4WLjjBnhfAty7PZ4W4GSuJKPPGhLPF65Yz7Ji--T3p2ZLLkpjPbNpgokNAKHfOkr~uR7F1rjnkcRTi3ZzYciiALCJNwNgLEOXowuAbdLyM5GO3gXm27~PZpsttxvCBlHkmD8L2xinybADaDvrAe3ReWbi9zd9WMGm5zc2sfZ1G~1E1BQAEAAEAAA%3d%3d` is the correct link.
