### ISSUE TITLE
Website shows 503 Service Unavailable error

### ISSUE THREAD

**Issue by cgsmith** [privacytoolsIO/privacytools.io#201]
![capture](https://cloud.githubusercontent.com/assets/570018/23958217/5a5d0532-096f-11e7-8492-d75cbc33103e.PNG)

**Comment by bakku** [comment]
You are right, happens with me too

**Comment by Shifterovich** [comment]
We know. There's nothing we can do with it.

**Comment by cgsmith** [comment]
:( DNS? Just curious.

**Comment by dnguyen01** [comment]
So I'm assuming only one person has access to the server? Or is it the constant DDOS that I saw on Reddit?

**Comment by Hillside502** [comment]
@Shifterovich 
Is the person Burung Hantu @privacytoolsIO ?

**Comment by Shifterovich** [comment]
Yes.

**Comment by Hillside502** [comment]
@Shifterovich 
Is Burung contactable?
If not, maybe it's time to fork.

**Comment by Shifterovich** [comment]
We used a fork under similar circumstances for some time a few months ago. https://github.com/privacytools-io/privacytools-io.github.io

**Comment by mitchellcash** [comment]
@Shifterovich who controls the domain? If you do, maybe it's time to host the site somewhere new and point the domain to the new host?

**Comment by Shifterovich** [comment]
@privacytoolsIO does.

**Comment by mitchellcash** [comment]
@Shifterovich I see your predicament!

**Comment by Hillside502** [comment]
Plenty of privacytools.* domains available at https://www.gandi.net

How about:-
privacytools.tools
privacytools.online
privacytools.solutions
privacytools.website
privacytools.site
privacytools.expert
privacytools.tips
privacytools.guide
privacytools.zone
privacytools.help

Hope this helps!

**Comment by Shifterovich** [comment]
We're not buying a domain because the current domain owner is away for 2 months. When we were using the fork, we were also using GitHub Pages. https://privacytools-io.github.io

**Comment by cgsmith** [comment]
GH.io pages is a good work around until the domain is figured out. I thought it'd be best to open an issue in case others are checking for workarounds.

**Comment by privacytoolsIO** [comment]
Guys, I'm back. Fixing this currently. The hoster complained about too much traffic and decided to deny access to it. I've noticed too late. Currently travelling in remote places with slow internet connection.

**Comment by Shifterovich** [comment]
@privacytoolsIO 
```
This site can’t be reached

privacytools.io unexpectedly closed the connection.
```

**Comment by Hillside502** [comment]
@privacytoolsIO 
503 Service Temporarily Unavailable
https://www.privacytools.io/

**Comment by Hillside502** [comment]
Geotool
https://iplookup.flagfox.net/?ip=104.31.91.13&host=www.privacytools.io

**Comment by privacytoolsIO** [comment]
Did u all ignore the word **soon**? Works like a charm now.

**Comment by Shifterovich** [comment]
Soon is a relative term. It can mean both "in a few minutes" and "in a few years".

**Comment by Hillside502** [comment]
@privacytoolsIO 
It's My Party?
