### ISSUE TITLE
Encryptr isn't being actively developed

### ISSUE THREAD

**Issue by WildYorkies** [privacytoolsIO/privacytools.io#203]
https://github.com/SpiderOak/Encryptr/issues/286

I don't think this should be featured on the site.

**Comment by dnguyen01** [comment]
The last commit was in July 19, 2016 (https://github.com/SpiderOak/Encryptr/commits/master). I checked the App Store (iOS) and last release was in Dec 19, 2015; Play Store in December 7, 2015. Looks like development for the password manager is secretly dropped. Probably a good note to remove software that isn't actively developed and not been given the silent treatment.

**Comment by WildYorkies** [comment]
Same with some other Spider Oak tools.

I think there should be a threshold for activity, but also for *how many developers contribute*. 

No one should be recommending a tool that only has 1 contributor, either.

**Comment by kewde** [comment]
As a note that shares some relevance to this issue, I don't think inactivity of development in itself is a reason to drop a project unless there are outstanding security issues. If a tool is secure as is and it works as expected, then I don't see an issue with discontinued development as long as there is a commitment to fixing upcoming security issues (which isn't the case in this example so the removal is okay imo).

**Comment by Shifterovich** [comment]
Depends on the kind of tool.
