### ISSUE TITLE
Destroy Win10 Spying link is broken

### ISSUE THREAD

**Issue by masvil** [privacytoolsIO/privacytools.io#206]
Destroy Win10 Spying "Official Website" [link](http://dws.wzor.net/) in [Windows 10 section](https://privacytoolsio.github.io/privacytools.io/#win10) is broken.

**Comment by Atavic** [comment]
Seems that Github is the only place for it.

BTW all these applications will never completely close Windows from reporting user's telemetry.
- After every update, some service is restarted.
- hosts are bypassed by various means (hardcoded IP, SYSTEM initiated connections).

The only serious idea about it is [WindowsSpyBlocker](https://github.com/crazy-max/WindowsSpyBlocker).

[Here](https://github.com/CHEF-KOCH/regtweaks) there are some registry tweaks.

**Comment by gene1wood** [comment]
Should we recommend [OOSU](https://www.oo-software.com/en/shutup10)?

**Comment by Atavic** [comment]
The best recommendation is to use MSMG ToolKit and create your own *No Bloatware Edition* of Windows 10 Pro or Home.

**Comment by beerisgood** [comment]
@Atavic What youre recommendations?

**Comment by Atavic** [comment]
I installed:
*Windows 10 Pro No Bloatware Edition 64-Bit*
from majorgeeks.

**Comment by Vincevrp** [comment]
I can't find this link on the website anymore, I assume it has been removed a while ago. Further discussion can continue in a new issue.
