### ISSUE TITLE
Digital Notebook Suggestion

### ISSUE THREAD

**Issue by albertocoronado** [privacytoolsIO/privacytools.io#215]
Add [Standard Notes](https://standardnotes.org/) to the website. It meets ALL of the PT criteria.

Here is their [Github](https://github.com/standardnotes) 

They also support all platforms (Web, IOS, Mac, Windows, Linux and Android)

Encryption is also available. 

Also, they offer an [Extended Subscription Package](https://standardnotes.org/extended) as their means of making money/sustaining the development. 

Or if you don't have the means to pay for it, they have this thing called "Pay with Social Post" which means "If you don't have any financial means, you can help support the project by posting about it on Twitter, Facebook, or other social networks. In exchange, you'll receive 3 months of access to Extended. You should have at least 200 followers/friends." which I think is pretty cool. 

I'm sure I am not covering all the features but that should be enough to be able to add it as a recommended service. 

Let me know what you think.

**Comment by asarkanyfole** [comment]
Ping ... this is done.  StandardNotes is on the site (yeay).  Can close this out.
