### ISSUE TITLE
Suggestions about android browser

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#216]
Hey, guys.
I finda problem that the android version of firefox collect privacy even if the user changes settings. For example, you can not completely stop the location service of android firefox.
So, I find a browser called Iron provided by Srware, You can download the source code in this page: http://www.srware.net/en/software_srware_iron_download.php
Please help me determine whether it leaks privacy.

**Comment by Freenetaround** [comment]
and how about K-9 Mail for android?
https://github.com/k9mail/k-9/releases

**Comment by Atavic** [comment]
Iron desktop had issues regarding the injection of ads in the past. I suggest the tools developed by [Guardian Project](https://guardianproject.info/)

**Comment by Atavic** [comment]
Privacy Browser is an open source Android web browser focused on user privacy:
https://www.stoutner.com/

**Comment by beerisgood** [comment]
@Atavic privacy browser is available in F-DROID.
Same for "FOSS browser" which I like more as second browser beside Fennec from F-DROID

**Comment by Atavic** [comment]
Yes, I didn't check... BTW there are too many issues opened, I think I'll list some by topic this weekend.

**Comment by sorenstoutner** [comment]
I am the developer of Privacy Browser.  I can answer any questions you might have about it.

**Comment by Atavic** [comment]
:+1: I just find it *perfect* and is running on phone and tablet (that won't accept icecat or fennec installs for unknown reasons).
