### ISSUE TITLE
Mobile Operative Systems

### ISSUE THREAD

**Issue by easyKL** [privacytoolsIO/privacytools.io#218]
_CyanogenMod is an open-source..._
project is now RIP

Please replace by LineageOS. 

URL: www.lineageos.org
logo small: www.lineageos.org/images/logo-2.png

https://privacytoolsio.github.io/privacytools.io/#mobile_os

**Comment by Hillside502** [comment]
Also, http://www.cyanogenmod.org/ is a deadlink

**Comment by Kendos-Kenlen** [comment]
Ubuntu Mobile is now abandoned (with Unity for desktop). Canonical decided to stop working on convergence between PC and mobiles. It should be removed.

Plasma Mobile is currently in development but could be a future choice (if it manage to really work and to be available on devices).

**Comment by Hillside502** [comment]
404 Page not found | Ubuntu
https://www.ubuntu.com/mobile

**Comment by pExeen** [comment]
Yes we should delete Ubuntu mobile or link this instead : https://ubports.com/

**Comment by Atavic** [comment]
[CopperheadOS](https://github.com/CopperheadOS): Hardened variant of the Android Open Source Project. 

https://copperhead.co/android/

**(limited range of supported devices)**

**Comment by Atavic** [comment]
@pExeen https://github.com/ubports
