### ISSUE TITLE
Matrix/riot

### ISSUE THREAD

**Issue by driminicus** [privacytoolsIO/privacytools.io#220]
I think the  [matrix](https://www.matrix.org/) federated protocol with [riot](https://riot.im) as an IM messaging client is certainly worth mentioning.

Advantage over signal and wire would be that it's federated, while it has a (completely voluntary) identity server, which helps with contact discovery, which is an issue with XMPP.

I self-host a matrix server, and I successfully got quite a few people to create a matrix account and I haven't had many complaints (other than my server going down :cry: )

In my opinion the riot client works quite well, and the end to end crypto is awesome, though it's still a little rough around the edges.

Plus the matrix/irc bridges are cool.

**Comment by arcadius3d** [comment]
Agreed with you, even though encryption is not enabled by default (cmon its just two clicks to enable), Riot is awesome plus it doesn't necessarily have a lifespan since anyone who cares can set up a server for it.

**Comment by driminicus** [comment]
The plan is to enable end to end encryption on all private rooms by default, but the encryption is currently still in beta (though I have had no trouble with losing any data) but AFAIK as soon as the MEGOLM encryption is considered stable it'll be on by default.

**Comment by jospoortvliet** [comment]
A big +1 from me on this, Matrix is very nice and becoming a very serious solution.

**Comment by driminicus** [comment]
Happy you agree, @jospoortvliet any chance if matrix integrating with nextcloud at some point? Nextcloud seems to have gone the xmpp route, though.

**Comment by jospoortvliet** [comment]
@driminicus it might not be the appropriate place for a discussion but let me very subtly link to the discussion at https://twitter.com/Nextclouders/status/873256630011482112 :joy_cat:
