### ISSUE TITLE
Add Standard Notes to digital notebooks.

### ISSUE THREAD

**Issue by mobitar** [privacytoolsIO/privacytools.io#221]
Hi @privacytoolsIO, I suggested to the community on Reddit that we add Standard Notes: https://www.reddit.com/r/privacytoolsIO/comments/69zwcz/suggestion_to_add_standard_notes_to_digital/

The feedback was positive from the community, so I wanted to see about adding it to the Digital Notebooks section.

Currently there are 3 options up:
Laverna, Turtl, and Simplenote

As per the reddit comment, and aside from merging pull requests, I do not believe Laverna nor Turtl are in active development anymore. As for Simplenote, as noted, it is not a privacy focused product and does not offer client-side encryption.

Standard Notes focuses on privacy, and offers end-to-end encryption and a stringent privacy policy as well. It's well used and liked in the privacy and productivity community.

I'd be happy to submit a pull request, but given there are already 3 items in that row, I did not want to make any decisions on which to remove. I believe Simplenote would be the easy (and right) choice here.

Please let me know what your thoughts are.

**Comment by Shifterovich** [comment]
> I believe Simplenote would be the easy (and right) choice here.

I agree. From their website:
> In terms of security, Simplenote works a lot like other popular online services such as Gmail and Facebook. Your personal information is protected by a strict Privacy Policy. But due to the need for searching your notes from the web, the contents must remain unencrypted while in storage so the software can find your search terms. For this reason we recommend not using Simplenote to store anything particularly sensitive.

Make a PR replacing Simplenote with Standard Notes and I'll merge it.

**Comment by mobitar** [comment]
Done, thanks! https://github.com/privacytoolsIO/privacytools.io/pull/222

**Comment by Shifterovich** [comment]
Merged. Thanks for helping keep the website up to date.

**Comment by mobitar** [comment]
Thanks for all your hard work! This site is an incredible resource.
