### ISSUE TITLE
StartMail now accepts Bitcoin

### ISSUE THREAD

**Issue by LizMcIntyre** [privacytoolsIO/privacytools.io#226]
NOTE: I submitted pull request #227 to address this: StartMail now accepts Bitcoin. The StartMail Bitcoin column should be changed to a "yes."

**Comment by Nightfirecat** [comment]
You can leave this issue open, and add a line in your PR code's commit message that reads: `Closes privacytoolsIO/privacytools.io#226`.

**Comment by LizMcIntyre** [comment]
There is a pull request that is still open for this so I am re-opening this issue.
