### ISSUE TITLE
Incorrect VPN sorting

### ISSUE THREAD

**Issue by IDKwhattoputhere** [privacytoolsIO/privacytools.io#23]
Regarding https://www.privacytools.io/#vpn
The sorting of prices is all wrong. Some prices are in EUR others in USD. And even the sorting of the same currency doesn't work.
![privacy_tools_-_encryption_against_global_mass_sur_2016-01-12_14-43-43](https://cloud.githubusercontent.com/assets/16030872/12265030/ee732c82-b93a-11e5-9e3c-86b9e2f75e1a.png)

**Comment by alexbooker** [comment]
Thank you bringing this to our attention, @IDKwhattoputhere.

Someone recently shared [this spreadhseet](https://docs.google.com/spreadsheets/d/1FJTvWT5RHFSYuEoFVpAeQjuQPU4BVzbOigT0xebxTOw/edit#gid=0) with the Reddit community. @privacytoolsIO, maybe we could use that to improve the data on the website?

**Comment by HiLivin** [comment]
I guess you should change Privatoria pricing to $ 23.

**Comment by OKNoah** [comment]
To fix this, add or edit the `data-value` attribute of each table field.

**Comment by privacytoolsIO** [comment]
@IDKwhattoputhere Thanks. It's fixed now!

@alexbooker Good idea. I've linked to the spreadsheet here: https://www.privacytools.io/#vpn (More VPN Provider)

@HiLivin Why? "one off payment of $22,8" Source: https://privatoria.net/
