### ISSUE TITLE
Blahker Content Blocker 

### ISSUE THREAD

**Issue by wangkesen** [privacytoolsIO/privacytools.io#231]
Hi there, just opening an issue to suggest adding [Blahker](https://github.com/ethanhuang13/blahker) to the list. Blahker is an open-sourced content blocker available on both iOS/OSX with a focus on users in Taiwan but presumably other locations in Asia/Worldwide as well. Their Github page has more information. They also have a Facebook page [https://m.facebook.com/blahker/](Facebook Page) 

Thanks! Please let me know if you have any questions . ! ! ![](http://i.imgur.com/qEzt574.jpg)

**Comment by Vincevrp** [comment]
[This isn't cross-platform.](https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md#software-criteria)
