### ISSUE TITLE
Replace Qubes logo

### ISSUE THREAD

**Issue by hugoncosta** [privacytoolsIO/privacytools.io#234]
Yeah, small thing, but should be done.

![qubes_os_logo svg](https://user-images.githubusercontent.com/29380568/27328785-38921270-55ab-11e7-870d-52aed64dda39.png)

You can get the svg here https://upload.wikimedia.org/wikipedia/commons/6/61/Qubes_OS_Logo.svg

**Comment by arcadius3d** [comment]
Done, just need to wait for approval.
https://github.com/privacytoolsIO/privacytools.io/pull/237
