### ISSUE TITLE
Add perfect forward secrecy to the VPN/Communication criteria

### ISSUE THREAD

**Issue by haroon-ali** [privacytoolsIO/privacytools.io#240]
Hi,
I think that "perfect forward secrecy" should not be optional in a serious secure service any more.

So for communication services/apps and VPN it should be included in the criteria. 
Per connection, per session or per time-interval whatsoever but it should be implemented & enabled by default.

**Comment by Hillside502** [comment]
Forward secrecy - Wikipedia
https://en.wikipedia.org/wiki/Forward_secrecy

SSL Server Test (Powered by Qualys SSL Labs)
https://www.ssllabs.com/ssltest/index.html

**Comment by kewde** [comment]
PFS-by-default is already an industry standard alive among messaging applications and SSL/TLS, I don't know how many VPN support it however.

**Comment by JonahAragon** [comment]
- [x] IVPN: https://www.ivpn.net/knowledgebase/106/Does-IVPN-offer-Perfect-Forward-Secrecy-PFS.html
- [x] ProtonVPN: https://protonvpn.com/secure-vpn
- [x] NordVPN: https://support.nordvpn.com/Getting-started/1047408592/Which-protocol-should-I-choose.htm
- [x] Mullvad: https://mullvad.net/en/what-is-vpn/
