### ISSUE TITLE
Add Privacy Badger under Privacy Add-Ons for Firefox

### ISSUE THREAD

**Issue by SirExtremis** [privacytoolsIO/privacytools.io#244]
Privacy Badger is made and supported by the EFF, and is actually working fine on the latest Firefox for Windows, which I tested myself. Here is the [Link](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/)

This addon can also work alongside UBlock Origin and Decentraleyes.

A excerpt from their page:

> When you view a webpage, that page will often be made up of content from many different sources.  (For example, a news webpage might load the actual article from the news company, ads from an ad company, and the comments section from a different company that's been contracted out to provide that service.)  Privacy Badger keeps track of all of this.  If as you browse the web, the same source seems to be tracking your browser across different websites, then Privacy Badger springs into action, telling your browser not to load any more content from that source.  And when your browser stops loading content from a source, that source can no longer track you.  Voila!

**Comment by hugoncosta** [comment]
Interestingly enough, Privacy Badger is in the code of the website, but as a comment. I believe it was removed, but I believe it should be featured as well.

**Comment by Shifterovich** [comment]
It was removed by @privacytoolsIO iirc. I suggested adding it back. It's a TODO https://github.com/privacytoolsIO/privacytools.io/projects/2.

Thanks for reminding.
