### ISSUE TITLE
Add AOSP as a secondary alternative in Mobile OS

### ISSUE THREAD

**Issue by SirExtremis** [privacytoolsIO/privacytools.io#245]
A lot of devices have AOSP roms made for their device, for example the AOSP Extended for Oneplus 3/3T. 

So, I think the page should show AOSP as a secondary alternative.

**Comment by hugoncosta** [comment]
AOSP is the base project. Every rom is built on AOSP. That "AOSP Extended" is just a rom derived from the AOSP, I believe you can't install it directly, like you can on Lineage OS. I believe it's like saying "As a computer OS, use Linux" - which one, you'd ask.

**Comment by SirExtremis** [comment]
Oh, alright....my bad. Closing this.

**Comment by kewde** [comment]
What @hugoncosta said is pretty accurate. 
You can however install a pure "AOSP" ROM on the devices sold by Google.
