### ISSUE TITLE
Email providers

### ISSUE THREAD

**Issue by OKNoah** [privacytoolsIO/privacytools.io#25]
There are some problems with the email providers. For example, Tutanota says it's free, which it is. But it also says it accepts Bitcoin, but why does a free service accept Bitcoin? It also says it supports custom domains, which is does, but only if you pay. But wait, isn't it free?

It seems like there should be another column, like "Free option" with the choices "yes" or "no.

Also, there should be more options under "Custom domain": "Yes", "Yes (Paid accounts only)" and "No".

I think this would add clarity. I will make a PR if there's no disagreement.

**Comment by OKNoah** [comment]
Here is the PR https://github.com/privacytoolsIO/privacytools.io/pull/26

**Comment by privacytoolsIO** [comment]
See #26
