### ISSUE TITLE
Add ZeroNet to "Self-Contained Networks" Section

### ISSUE THREAD

**Issue by 0verk1ll** [privacytoolsIO/privacytools.io#254]
https://zeronet.io/ is a decentralized network that works with Tor. Privacy Tools already has a ZeroNet mirror, so it would make sense if you suggested ZeroNet in the "Self-Contained Networks" section of the website.

**Comment by Shifterovich** [comment]
Maybe replace Freenet with it and move Freenet to Worth Mentioning?

**Comment by 0verk1ll** [comment]
ZeroNet is relatively new, so maybe it shouldn't be prioritized above Freenet since it still only has a few users.
