### ISSUE TITLE
Add some add-ons 

### ISSUE THREAD

**Issue by KhalidVIP** [privacytoolsIO/privacytools.io#255]
Why don't Add
Disconnect
Random agent apoofer

**Comment by Shifterovich** [comment]
Disconnect does the same as uBlock and Random Agent Spoofer was removed for some reason, I'll look into that.

**Comment by Atavic** [comment]
Random Agent Spoofer isn't ready for Webextensions yet. [Here](https://github.com/dillbyrne/random-agent-spoofer/issues/544) the author called for maintainers and a fork appeared [here](https://github.com/Mylainos/random-agent-spoofer).
