### ISSUE TITLE
lesspass password manager is better than master password app

### ISSUE THREAD

**Issue by ara11** [privacytoolsIO/privacytools.io#257]
hi , i thins https://lesspass.com/ is better than master password app beacuase support browser and have firefox and chrome addons. and don't store any data such as masterpasswordapp

**Comment by Shifterovich** [comment]
Master Password does have a web client. https://js.masterpasswordapp.com/

**Comment by Nightfirecat** [comment]
And anyway, [LastPass is US-based, no?](https://lastpass.com/about-lastpass/)

**Comment by Shifterovich** [comment]
That doesn't matter. It's an offline open-source password manager.

**Comment by hugoncosta** [comment]
Looks nice, more friendly than KeePass' website, has docker support. The password section is missing one tile, maybe we can fill it with this one?

**Comment by Shifterovich** [comment]
@hugoncosta Good point. I wouldn't replace Master Password, but we sure can add it.

**Comment by hugoncosta** [comment]
I'll add it soon
