### ISSUE TITLE
DisableWinTracking deprecated, no longer maintained

### ISSUE THREAD

**Issue by OKNoah** [privacytoolsIO/privacytools.io#27]
See this issue on the Windows 10 privacy tool:

https://github.com/10se1ucgo/DisableWinTracking/issues/147

We will need to find an alternative, or someone to take up maintenance of that app.

**Comment by alexbooker** [comment]
Thank you for bringing this up. 

As per the [Contributing Guidelines](https://github.com/privacytoolsIO/privacytools.io#contributing), suggestions belong on Reddit. I took the liberty of moving he discussion [there](https://www.reddit.com/r/privacytoolsIO/comments/44fzov/disablewintracking_is_not_currently_under_active/).

Please feel free to open a pull request if and when a consensus is reached.
