### ISSUE TITLE
Tor Browser should be the de-facto #1 choice in the Browser section, and not #3

### ISSUE THREAD

**Issue by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [privacytoolsIO/privacytools.io#271]
For starters: https://www.torproject.org/projects/torbrowser/design/#Implementation

I'm even on the front that Brave should be dissed altogether but I'm not gonna take part in that fight before fixing this horrible issue.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
This is fixed by this pull: https://github.com/privacytoolsIO/privacytools.io/pull/276

**Comment by Shifterovich** [comment]
There have been extensive discussions regarding Brave already, but we haven't reached a conclusion.
