### ISSUE TITLE
Look into the Tor Browser design document to pick new elements for "Firefox: Privacy Related "about:config" Tweaks"

### ISSUE THREAD

**Issue by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [privacytoolsIO/privacytools.io#272]
The Tor Browser design document: https://www.torproject.org/projects/torbrowser/design/#Implementation

An example: `privacy.resistFingerprinting` should be set to `true`.

Maybe this is a bad idea, and maybe suggesting that one should tweak the Tor Browser itself to use clearnet as an alternative to Firefox + about:config tweaks.

Anyway, discuss. I'll compile a list in the meantime: (complete)

--------

- [ ] privacy.resistFingerprinting = true (A result of the [Tor Uplift](https://wiki.mozilla.org/Security/Tor_Uplift) effort, this preference makes Firefox more resistant to browser fingerprinting.)
- [ ] privacy.firstparty.isolate = true (A result of the [Tor Uplift](https://wiki.mozilla.org/Security/Tor_Uplift) effort, this preference isolates all browser identifier sources (e.g. cookies) to the first party domain, with the goal of preventing tracking across different domains.)

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
We should also consider reviewing the Tor Uplift project since some prefs aren't documented in the Tor Browser Design document, such as `privacy.firstparty.isolate`. https://wiki.mozilla.org/Security/Tor_Uplift/Tracking

Note that this was the only pref not mentioned in the design document, so I guess I did all the work then for this part.

**Comment by Shifterovich** [comment]
https://gist.github.com/Shifterovich/ba649d96a1618cad294bc9b47f0541c8

**Comment by Shifterovich** [comment]
A post from my now-dead blog. I did some research on browser fingerprinting in general.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
Two first ones are addressed in this pull: https://github.com/privacytoolsIO/privacytools.io/pull/284

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@Shifterovich 
There's a feature request that is now in the review phase https://bugzilla.mozilla.org/show_bug.cgi?id=967895 which will integrate the HTML5 Canvas blocking inside Firefox, not sure if default but there will be for sure some pref for this, in which case Canvas Blocker would no longer be needed and you can close this issue, https://github.com/privacytoolsIO/privacytools.io/issues/99

**Comment by Atavic** [comment]
There are tickets dealing with [privacy.resistFingerprinting](https://github.com/ghacksuserjs/ghacks-user.js/issues/7) and [privacy.firstparty.isolate](https://github.com/ghacksuserjs/ghacks-user.js/issues/8).

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@Atavic Oh, ghacks' user.js :) Might be a good idea instead of having the tiresome manual approach but it will require auditing all their options, we only want privacy related ones.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
Reviewed all options, seems those two are the only ones that stick out. @Shifterovich Is there anything preventing the merge for https://github.com/privacytoolsIO/privacytools.io/pull/284?

**Comment by Shifterovich** [comment]
Waiting for approval.

**Comment by privacytoolsIO** [comment]
Approved.
