### ISSUE TITLE
Some elements don't show up in the Tor Browser with Security Settings set to high since they are written in SVG

### ISSUE THREAD

**Issue by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [privacytoolsIO/privacytools.io#275]
Solution: Convert them to PNG?

**Comment by kewde** [comment]
Will do this.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@kewde Is it possible to show PNG only if SVG is blocked since that would lead to faster loading times?

**Comment by kewde** [comment]
@C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N 
I haven't seen a trick like this that works in pure html/css, I know it's possible in JavaScript however, but I think we all agree to avoid that.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@kewde 
It's possible using HTML/CSS only: https://css-tricks.com/svg-fallbacks/
That's great because I think the images should be entirely transformed to SVG and with this method even browsers that don't display SVG may still be compatible. Should I make a separate issue for the "transform all images to SVG" part?

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
ping @kewde

**Comment by kewde** [comment]
#308
