### ISSUE TITLE
Configure DNS properly

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#282]
@privacytoolsIO https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
If this is the case,

- [ ] Edit CSP to reflect this change.

**Comment by kewde** [comment]
Ping me if that's the case.

**Comment by Shifterovich** [comment]
- [x] Configure DNS properly
- [ ] Add HTTPS support

**Comment by privacytoolsIO** [comment]
Thanks @Shifterovich, I didn't know that's possible. Will work on it.

**Comment by privacytoolsIO** [comment]
Okay, DNS settings are working. But "Add HTTPS support" turns out to be a problem. I know how to add a ssl certificate if I host the website myself, but not when it's hosted on GitHub. I need assistance.

**Comment by Shifterovich** [comment]
That's *the* major drawback to using GitHub. I think this can be solved with CF, though. We could use [deflect](deflect.ca) -- a free alternative for projects like PTIO.

**Comment by Shifterovich** [comment]
https://www.reddit.com/r/privacytoolsIO/comments/6s5auh/privacytoolsio_invalid_security_ticket_when/

**Comment by privacytoolsIO** [comment]
Everything should be back to normal now. I like the new solution. 

We're hosting at GitHub and getting SSL from CloudFlare. I've whitelisted Tor Traffic in the CloudFlare panel.

**Comment by Shifterovich** [comment]
Great! Thanks
