### ISSUE TITLE
Searx engine bar that was on privacytools.io

### ISSUE THREAD

**Issue by NIXOYE** [privacytoolsIO/privacytools.io#29]
I remember privacytools.io had a search bar for its instance of a searx engine.  I want to include one like that on my site with my searx engine instance and i was hoping you could share the html\css\js. Also why isnt searx in the recommended list anymore?

**Comment by privacytoolsIO** [comment]
HTML Code: https://github.com/privacytoolsIO/privacytools.io/commit/a1b0d6cdcfbc4fda0d090a088b386eba4a099ab7 starting from line 172.
