### ISSUE TITLE
Embed Snowflake badge on main page or another for helping censored users?

### ISSUE THREAD

**Issue by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [privacytoolsIO/privacytools.io#295]
What Snowflake is:

https://trac.torproject.org/projects/tor/wiki/doc/Snowflake

To become a Snowflake temporary bridge (Click Yes):

https://keroserene.net/snowflake/options.html

Code to embed to allow for visitors to become Snowflake bridges plus general information:

https://keroserene.net/snowflake/

---------------

This could be a great initiative to help censored users.

Note that the Snowflake Pluggable Transport is now available for both Linux and Mac, and is currently distributed in the alpha Tor Browser releases. It also uses WebRTC.

(Can anyone say whether the Snowflake widget has an opt-in option? Edit: Just found out that no, so the solution is to have a banner with "Do you want to help censored users connect to the Tor network by just having a tab stay open? [Yes] [No]" and then redirect to a page snowflake.html with the Snowflake badge.)

**Comment by privacytoolsIO** [comment]
It's a nice idea! But it uses WebRTC, but we recommend to disable WebRTC for privacy reasons. Not sure how that will work.

**Comment by Shifterovich** [comment]
A completely separate file with instructions would be better. Could look like donate.html.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@privacytoolsIO 

> and we recommend to disable WebRTC for privacy reasons. Not sure how that will work.

The idea is that one would run that WebRTC bridge outside of the browser that they normally use.

**Comment by blacklight447-ptio** [comment]
We alreayd list the snowflake addon on the website so users can chose to become a snowflake bridge whenever they want, making this seem redundant. closing issue.
