### ISSUE TITLE
Tooltips stopped working (JavaScript)

### ISSUE THREAD

**Issue by privacytoolsIO** [privacytoolsIO/privacytools.io#302]
I couldn't figure out why this morning. Help wanted.

**Comment by Shifterovich** [comment]
> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src https://privacytoolsio.github.io http://privacytoolsio.github.io". Either the 'unsafe-inline' keyword, a hash ('sha256-YGV9MIL1c0rkSok/aWLbfjEHkctcp8JgNYrCgrweuBo='), or a nonce ('nonce-...') is 
required to enable inline execution.

**Comment by kewde** [comment]
Removed the CSP security policy that was breaking this.

**Comment by privacytoolsIO** [comment]
Thanks, guys.
