### ISSUE TITLE
Secure Password Gen - Error

### ISSUE THREAD

**Issue by davidclarke-au** [privacytoolsIO/privacytools.io#305]
On Chrome Version 60.0.3112.90 (Official Build) (64-bit)

Hold on. It looks like you are using an unsupported browser (probably Internet Explorer...) Unfortunately, this tool will not work until you upgrade your browser. Sorry for any inconvenience caused.

https://privacytoolsio.github.io/privacytools.io/password.html

**Comment by Shifterovich** [comment]
#303

**Comment by kewde** [comment]
Please try again, I removed the CSP.

**Comment by davidclarke-au** [comment]
Confirmed fixed, thanks.
