### ISSUE TITLE
Add 2017 TorrentFreak VPN-overview

### ISSUE THREAD

**Issue by scharmach** [privacytoolsIO/privacytools.io#307]
As of now, in the "Related VPN information"-section, there is only a link to the old 2016 TorrentFreak VPN-overview: https://privacytoolsio.github.io/privacytools.io/#vpn

They have made a new overview for 2017 by now: https://torrentfreak.com/vpn-services-anonymous-review-2017-170304/

I suggest to replace the 2016 link or to simply add the 2017 link for comparison reasons.

**Comment by privacytoolsIO** [comment]
Done.

Good idea. Thanks!
