### ISSUE TITLE
Suggestion: add "browser.sessionstore.privacy_level = 2" to Firefox: Privacy Related "about:config" Tweaks

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#310]
### browser.sessionstore.privacy_level
> Firefox 2.0 introduces a built-in Session Restore feature, allowing the user to continue browsing from where they left off if browser restarts. This preference controls when to store extra information about a session: contents of forms, scrollbar positions, cookies, and POST data.

> 2 = Never store extra session data. 

http://kb.mozillazine.org/Browser.sessionstore.privacy_level

I use the setting "When Firefox starts: Show your windows and tabs from last time" but found that this causes Firefox to keep session data such as cookies even after restarting the program. This is because the setting that controls such behavior, browser.sessionstore.privacy_level, defaults to a value of 0 (Store extra session data for any site.). I think this information would be a helpful addition to **Firefox: Privacy Related "about:config" Tweaks** as it's important for privacy reasons to make sure session data is being handled properly (i.e. session-only cookies actually being deleted after restarting Firefox).

**Comment by hugoncosta** [comment]
Why not add this website? https://ffprofile.com/

It automatically creates a Privacy focused firefox where you can easily tweak the settings.

**Comment by JonahAragon** [comment]
Added in #427.
