### ISSUE TITLE
Disroot as email service

### ISSUE THREAD

**Issue by davidtabernerom** [privacytoolsIO/privacytools.io#312]
Disroot (disroot.org) seems to be a good candidate for the list of email (& other services) providers.
Features said by them:
- Only Open Source software
- 100% free, it lives with donations
- Communication (mail) of changes in the infrastructure and eventually new services available
- Rainloop as modern, mobile-friendly web UI for email management
- Nextcloud 12 with many apps, so you can sync you contacts and calendars with calDAV and cardDAV and your files with webDAV or Nextcloud's apps. You can also sync your notes and RSS subscriptions (like Feedly).
- Matrix and Riot for instant messaging, voIP and videocalls. Matrix is a federated service like email so you can contact people on other servers.
- XMPP support
- A forum based on the modern Discourse
- Diaspora as social network
- Everything is setup with just one account
- Many other apps, like Taiga to organise with other people.

Could you please check it out?

**Comment by privacytoolsIO** [comment]
Sounds great. Do you have information about the jurisdiction?

**Comment by privacytoolsIO** [comment]
done! great suggestion, mate.

**Comment by gustavo-depaula** [comment]
Why disroot is not on the email service list anymore?

**Comment by Kovaelin** [comment]
Shouldn't rainloop itself be mentioned on the site as well?
