### ISSUE TITLE
Spideroak and Tresorit as another trustworthy cloud storage services

### ISSUE THREAD

**Issue by davidtabernerom** [privacytoolsIO/privacytools.io#318]
A lot of people, including Edward Snowden, trust in Spideroak as cloud storage service (paid only) as their NSA-proof personal+profesisonal cloud storage service. I would life to add to these Tresorit, which offers you a 5GB free account with up to 3 "tresors" (like shared folders).
I have only tried the second one, good service.
Could you check them out?

**Comment by privacytoolsIO** [comment]
https://www.reddit.com/r/privacytoolsIO/search?q=Spideroak&restrict_sr=on&sort=relevance&t=all

**Comment by ecksteinz** [comment]
Neither SpiderOak nor Tresorit offer the option to self-host. According to my knowledge Tresorit is also not open-source and only published the third party sources (see https://tresorit.com/third-party-code). Both are viable options for anything business related, but as far as privacytools.io is concerned, I think it is better to stick to stricter rules for determining the eligibility of cloud storage services / software.

**Comment by davidtabernerom** [comment]
Understood, totally agree.
