### ISSUE TITLE
KeePassXC instead of KeePassX for password managers

### ISSUE THREAD

**Issue by stratacast** [privacytoolsIO/privacytools.io#319]
It has been almost a year since the last commit to KeePassX, meaning there are no security updates or feature updates. [KeePassXC](http://keepassxc.org/) is a fork of KeePassX and has been very active with almost 80 contributors and 2200 commits since the fork began. KeePassXC has gotten many updates such as conversion to Qt5, TOTP, passphrase creation, KeeHTTP, auto-type across all platforms, and others. I think KeePassXC should be placed on privacytools.io instead of KeePassX

**Comment by Shifterovich** [comment]
#261
