### ISSUE TITLE
Freedombox - add to Self-Hosted Cloud Server Software section?

### ISSUE THREAD

**Issue by p2635** [privacytoolsIO/privacytools.io#321]
Maybe add Freedombox?
http://freedomboxfoundation.org/
http://freedomboxfoundation.org/learn/

I first found out about this from watching one of the videos on DebConf17 which can be viewed here: [FreedomBox, Libre Personal Server](https://debconf17.debconf.org/talks/113/)

**Comment by Atavic** [comment]
A mature project. :+1:

**Comment by Atavic** [comment]
It's a mature project.

**Comment by hex-m** [comment]
imho this needs a new category. Maybe "Homeserver OS". Other contenders for the category would be YUNOhost, Cozy, Sandstorm.io, Cloudron.

**Comment by nitrohorse** [comment]
Closing as dupe of https://github.com/privacytoolsIO/privacytools.io/issues/407.
