### ISSUE TITLE
StationX - linux laptops/desktops seller

### ISSUE THREAD

**Issue by p2635** [privacytoolsIO/privacytools.io#322]
Link: https://stationx.rocks/

I found out about them from the quidsup Youtube Channel, let the discussion begin. 

Good to include? Bad?

**Comment by kewde** [comment]
I haven't seen many websites that sell desktop and laptops that come preloaded with linux, thanks for the link. I've sent them a message to add the option for QubesOS.

While it's fantastic to see linux getting into the desktop market, I don't think this is suited for our website.

**Comment by Shifterovich** [comment]
Would be suited for the Secure HW section #331 if it were open-source.

**Comment by kewde** [comment]
Kewde -> StationX

> Please add QubesOS as an option!

Reply:

> It's on our list !!! Stay tuned !!

:+1:

**Comment by Vincevrp** [comment]
Closing in favor of #331
