### ISSUE TITLE
Rename 'OS' to 'Operating System' in the nav bar

### ISSUE THREAD

**Issue by p2635** [privacytoolsIO/privacytools.io#323]
I know OS is generally a known term amongst most people, but for the benefit of the non-techies it may be worth renaming 'OS' to 'Operating System'.

**Comment by Shifterovich** [comment]
Changing it might be a good idea, but do you think non-techies can install Qubes OS?

**Comment by p2635** [comment]
@Shifterovich probably not but if they're motivated enough, they'll ask people and find a way. I just want to make the website more accessble to all audiences and plant the seed of awareness.

**Comment by hugoncosta** [comment]
I believe OS is already in the minds of normies, since they see it a lot on the Apple world (macOS, OS X). I don't see the need for it.

**Comment by p2635** [comment]
Ok shall I close?

**Comment by Shifterovich** [comment]
Feel free. It's just different words, no big change. @privacytoolsIO's feedback would be useful, though.

**Comment by p2635** [comment]
@Shifterovich I'll close for now.
