### ISSUE TITLE
[Minor detail] Download button vs external links

### ISSUE THREAD

**Issue by p2635** [privacytoolsIO/privacytools.io#324]
In the [Tor Browser section](https://www.privacytools.io/#darknets) this text 'OS: Windows, Mac, Linux, iOS, Android, OpenBSD.'  - iOS, Android and OpenBSD are linked.

However for the other sections we don't include links for OS, we let the user click the Download button to direct them to the site. This is more a consistency thing and I'll leave the admins to discuss this one.

**Comment by Shifterovich** [comment]
It's because of the lack of official support for those platforms. Windows, Mac, Linux aren't linked because they are officially supported, the rest isn't.

**Comment by p2635** [comment]
@Shifterovich that makes sense, thanks.
