### ISSUE TITLE
minilock.io site unavailable

### ISSUE THREAD

**Issue by stayen** [privacytoolsIO/privacytools.io#328]
On main page, reference to minilock Chrome/Chromium extension is placed; however, minilock.io site is no more available.

**Comment by Atavic** [comment]
Repo: https://github.com/kaepora/miniLock

**Comment by stayen** [comment]
Fine, so the https://minilock.io link should perhaps be replaced with the above one.

The piece of software anyway wasn't updated for 3 years.

**Comment by Atavic** [comment]
Last issue listed in 2016.

**Comment by Shifterovich** [comment]
Should we remove it, then?

**Comment by Atavic** [comment]
Seems abandoned... are there any alternatives?

**Comment by gastaunda** [comment]
It looks like https://minilock.io/ now is being used by someone named Mi Nilock.  So the link probably should be replaced now.

**Comment by Shifterovich** [comment]
Can anyone create a PR?

**Comment by Vincevrp** [comment]
66d68a0
