### ISSUE TITLE
Privacy Badger & Google Analytics

### ISSUE THREAD

**Issue by woctezuma** [privacytoolsIO/privacytools.io#335]
I see that _Privacy Badger_ is listed in first position in the section called [Excellent Firefox Privacy Add-ons](https://i.imgur.com/FjsyBMY.png).

![screencapture](https://i.imgur.com/FjsyBMY.png)

I would like to point out that _Privacy Badger_ is **unable by design** to detect and block trackers such as _Google Analytics_. This is not the case with _uBlock Origin_, for which privacy-related subscription lists do block _Google Analytics_.

To put it simply: _Google Analytics_ is considered first-party and not blocked by _Privacy Badger_. The current heuristic of _Privacy Badger_ is too limited, and it does not look like it is going to change. I think it is important that users are aware of this limitation of Privacy Badger and do not imagine that _uBlock Origin_ is not needed when using _Privacy Badger_.

My review about it [on Mozilla Addons](https://addons.mozilla.org/fr/firefox/addon/privacy-badger17/) was deleted. My second review about it was also deleted. My third review is currently still on there, but for how long?

You can easily check it by yourself by installing uBO-Scope:
https://addons.mozilla.org/fr/firefox/addon/ubo-scope/

You can also check the discussions on the Github repository of _Privacy Badger_:
https://github.com/EFForg/privacybadger/issues/340
https://github.com/EFForg/privacybadger/issues/367

**Comment by Hillside502** [comment]
https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/reviews/917905/

**Comment by Atavic** [comment]
Maybe the tone in your review (which I agree to) didn't help. Privacy Badger has a different purpose than uBo. The options and lists in uBo can be difficult to some, while PB works by itself.

It leaves 1st party snoopers alone by design.

**Comment by Atavic** [comment]
Maybe the tone in your review (which I agree to) didn't help. Privacy Badger has a different purpose than uBo. The options in uBo can be difficult to some, while PB works by itself.

It leaves 1st party snoopers untouched by design.

**Comment by Shifterovich** [comment]
> I think it is important that users are aware of this limitation of Privacy Badger and do not imagine that uBlock Origin is not needed when using Privacy Badger.

I agree.

Can you create a PR?

**Comment by woctezuma** [comment]
For info, it seems that the Google Analytics issue might have been [fixed](https://github.com/EFForg/privacybadger/issues/574#issuecomment-510036366).

**Comment by beerisgood** [comment]
After years..
