### ISSUE TITLE
Destroy Win10 spying: official website link is dead

### ISSUE THREAD

**Issue by stayen** [privacytoolsIO/privacytools.io#337]
The "Destroy Win10 spying' official website link

http://dws.wzor.net/

isn't working any more (3 NXDOMAIN - no such DNS A record). No link to another site is supplied on its GitHub page.

**Comment by Atavic** [comment]
Seems like the author abandoned DWS.

**Comment by stayen** [comment]
@Atavic Looks like that. Perhaps the corresponding notice should be added?

**Comment by Atavic** [comment]
I'd substitute the entry with [WindowsSpyBlocker](https://github.com/crazy-max/WindowsSpyBlocker).

**Comment by kewde** [comment]
I quickly patched this to WindowsSpyBlocker. Seems more up to date & no risk of domain hijacking.
