### ISSUE TITLE
Add PGP and GPG tutorials to the website.

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#347]
(4-month-old) background [here](https://www.reddit.com/r/privacytoolsIO/comments/6cx4d9/tutorials/):

> A few months ago, I suggested adding tutorials for tools, and we agreed that it's a good idea, as there are amazing tools like GPG which when used correctly can provide maximum privacy possible for a certain part of one's online activities, but are extremely hard to use for regular users. Even Glenn Greenwald was too busy to sit down and learn GPG when Edward Snowden contacted him. There's not much use in recommending tools like GPG to regular users without explaining how to use it. So I was thinking about the best way to implement the tutorials, both technically and regarding SEO.
> 
> I created a completely separate project (refering to PTIO) that will hopefully one day have enough content to teach regular users online privacy and give them the ability to orientate on websites like PTIO. At the time of writing, there are only 2 tutorials: Understanding VPNs and Choosing a VPN.
> 
> I would very much appreciate any volunteers. There's a lot of work to do, so whether you'd want to check grammar, write entire tutorials, explain terms (i.e. public key cryptography), create graphic visualisations of concepts for tutorials, or many other things, there will surely be something you can help with.
> 
> The website is an very early stage now. The website are far from perfect, the tutorials may not be really good at this stage.
> 
> Once we have a few (like 3 or 5) tutorials, I'll add them to PTIO.
> 
> https://theprivacyguide.org
> 
> https://github.com/theprivacyguide/theprivacyguide.org
> 

Both PGP and GPG tutorials are good-enough-to-be-published now.

Links:
- [PGP tutorial](https://theprivacyguide.org/tutorials/pgp.html)
- [GPG tutorial](https://theprivacyguide.org/tutorials/gpg.html)

Any ideas on how to include the tutorials (the links to the tutorials)?

~~Maybe add them to the description of GPG and other PGP tools?~~ Add another button?

**Comment by hugoncosta** [comment]
Searching a few engines, I see that the words commonly used with PGP are "guide", "tutorial", "how to". Having this in mind, maybe we could add a button that'd link to the tutorial? I assume we'd want it to stand out in the crowd.

**Comment by Shifterovich** [comment]
Sorry, I forgot, my original idea was a button next to the one that redirects the user to the website. Thanks. Edited.

**Comment by Shifterovich** [comment]
@hugoncosta I will create a PR tomorrow.

**Comment by shifterovich2** [comment]
Should we link to the PGP tutorial as well? Or is a link in the GPG tutorial enough?

**Comment by hugoncosta** [comment]
Well, explaining PGP wouldn't be a tool. I think we think put up the GPG tutorial and in the first paragraph or so create a link to the PGP tutorial. "GPG is a tool that bla bla bla using PGP. But what is PGP? Read more about (link)here(/link)"

**Comment by Shifterovich** [comment]
> Before reading this tutorial, make sure you [understand PGP](https://theprivacyguide.org/tutorials/pgp.html).

I guess this is enough.

**Comment by hugoncosta** [comment]
Well, taking into account this is targeted to "normal" people, that usually don't care about what's behind something, as long as it works, I believe that making them "learn" about PGP before using GPG might be a waste. I imagine someone accessing the GPG tutorial, start reading the PGP tutorial and just say "this is too hard to understand, the programme must be even harder, ahhh f$$k it."

With this, I just reinforce my opinion that we should give them advices on tools, not necessarily on what's behind them.

**Comment by Shifterovich** [comment]
> I believe that making them "learn" about PGP before using GPG might be a waste.

Good luck understanding `--armor`, public key crypto, revocation certs, etc.

No point in explaining stuff twice. Theory is explained in the PGP tutorial, GPG syntax in the GPG one.

**Comment by hugoncosta** [comment]
> Good luck understanding public key crypto
You indeed have a point, I forgot about that. Than yeah, I guess it's needed that they understand at least the syntax/basic concepts behind PGP to work with GPG.
