### ISSUE TITLE
Privacy Related "about:config" Tweaks prevent decentraleyes to work correctly

### ISSUE THREAD

**Issue by stemy2** [privacytoolsIO/privacytools.io#354]
Hello,

Since i tweaked my browser according your recommendations, Decentraleyes doesn't work anymore and it didn't injected any resource. I wonder wich tweak is the source of the problem.

Thanks.

**Comment by Hillside502** [comment]
Personally, I would ignore most direct "about:config" tweaks and install:-

Privacy Settings :: Add-ons for Firefox
https://addons.mozilla.org/en-US/firefox/addon/privacy-settings/

Switching between this addon's settings:-
```
Privacy (compatible) & Security
Privacy (compatible)
Privacy & Security
Full Privacy
```
and comparing the on/off states of each affected Firefox config setting (in the add-on's display) is the best way to understand what is going on under the hood.

For me, the `Privacy (compatible) & Security`setting provides the best compromise, including a fully working Decentraleyes.

**Comment by stemy2** [comment]
Actually, the problem resolved itself and i don't know how. But thanks anyway.
