### ISSUE TITLE
Privacy tweaks reset the page zoom

### ISSUE THREAD

**Issue by stemy2** [privacytoolsIO/privacytools.io#355]
Hello,

Because of the config of my screen, i'm forced to zoom into pages to make it readable and to prevent space waste with void when the zoom is at 100%. Since i followed the recommendation of the «Privacy tweaks» section, the zoom is not memorized anymore and reset to 100% every time i load a page and this is a bit annoying. Wich parameter is the source of the problem ?

Thanks.

**Comment by Atavic** [comment]
`network.cookie.lifetimePolicy` deletes the cookies when you close the browser. You should go to Options > Privacy > Cookie exceptions to allow the sites you change the zoom on. Otherwise there are Webextensions as [zoom page](https://addons.mozilla.org/en-US/firefox/addon/zoom-page/)
