### ISSUE TITLE
consider magic-wormhole for the file-sharing section

### ISSUE THREAD

**Issue by emanresusername** [privacytoolsIO/privacytools.io#357]
https://github.com/warner/magic-wormhole

if so, maybe also consider tweaking the title of the section for clarity/discoverability to reflect that it is also for `arbitrary 1-time text message sharing`... working title :thinking:

**Comment by shifterovich2** [comment]
Thanks. We weren't sure about only one program being recommended in the File Sharing section when we added it; this program looks good.

@kewde @hugoncosta

**Comment by hugoncosta** [comment]
I checked the PyCon presentation, it does look interesting! It's a shame that the website is off and the repo isn't that used. Nonetheless, it appears that'd be a nice addition to the website. I could do this if @kewde also likes it.

**Comment by kewde** [comment]
@hugoncosta Feel free, I think it would be a great addition. I wonder tho if it still works, with the website being down and all?

**Comment by Shifterovich** [comment]
@emanresusername Could you create a PR?

**Comment by emanresusername** [comment]
yezzir (￣^￣)ゞ
i'll shoot for this weekend

**Comment by kewde** [comment]
Merged, closing.
