### ISSUE TITLE
Add zoho.eu to email list?

### ISSUE THREAD

**Issue by formatme** [privacytoolsIO/privacytools.io#358]
zoho.eu safe from five eyes and it's free, supports your own domain and has pain plans.

**Comment by Shifterovich** [comment]
@kewde

**Comment by Hillside502** [comment]
https://www.zoho.eu/ is hosted in the United Kingdom

Geotool
https://iplookup.flagfox.net/?ip=31.186.226.52&host=www.zoho.eu

How does that make Zoho "safe from five eyes"?

**Comment by Shifterovich** [comment]
Will look into it more in depth a little later, but it seems business-focused, not privacy-focused.

@Hillside502 They seem quite multinational.

ToS says:

> Zoho Corporation B.V., a private company with limited liability (besloten vennootschap met beperkte aansprakelijkheid), incorporated and existing under Dutch law

Footer says `Zoho Corporation Pvt. Ltd.`

https://www.zoho.eu/contactus.html Apparently they have multiple companies for different countries. They have a US company as well. And yeah, their website being hosted in UK isn't very good either.

**Comment by Hillside502** [comment]
Even worse, the **sign in** server is USA located:-

Geotool
https://iplookup.flagfox.net/?ip=8.40.222.100&host=accounts.zoho.com

"business-focused, not privacy-focused" indeed!

**Comment by Shifterovich** [comment]
Meh. Won't waste my time looking into the service.

> safe from five eyes and it's free, supports your own domain and has pain plans.

Could be said about a lot of email providers based in Europe. Not enough; should be privacy-focused in some way.

Closing.

**Comment by kewde** [comment]
I agree, zoho doesn't seems like they have a focus on privacy.
