### ISSUE TITLE
Random User-Agent Firefox Extension deprecated

### ISSUE THREAD

**Issue by stefnats** [privacytoolsIO/privacytools.io#365]
Because FF57 disabled all legacy extensions, Random Agent Spoofer does not work anymore:
https://addons.mozilla.org/de/firefox/addon/random-agent-spoofer/

It is linked in the *Browser Fingerprint* section.

Are there any alternatives to this extension for FF57+?

**Comment by Atavic** [comment]
[RandomUA](https://github.com/LeoTindall/randomua) on  [AMO](https://addons.mozilla.org/firefox/addon/randomua/).

**Comment by kewde** [comment]
I'm okay with replacing it.

@Shifterovich thoughts?

**Comment by Shifterovich** [comment]
RandomUA seems to change the user agent on every request, which is quite annoying. Random User-Agent had a lot of settings (like what User-Agents should it use, how often should it change the User-Agent, etc). If we can't find a good alternative I think we should wait for an update.

**Comment by Atavic** [comment]
[User-Agent Switcher](https://gitlab.com/alexander255/user-agent-switcher)

**Comment by Shifterovich** [comment]
On [AMO](https://addons.mozilla.org/firefox/addon/uaswitcher/)

**Comment by Shifterovich** [comment]
Seems like a good alternative.

**Comment by Atavic** [comment]
You can migrate prefs from User Agent Overrider by @muzuiget

**Comment by stefnats** [comment]
Created PR. This is my first PR, hope everything went right.

**Comment by kewde** [comment]
fixed by #373
