### ISSUE TITLE
Adding EteSync

### ISSUE THREAD

**Issue by tasn** [privacytoolsIO/privacytools.io#372]
Hey,

EteSync is an end-to-end encrypted contact and calendar sync. Originally for Android (integrates seamlessly with the OS), but now also for the desktop (beta), and the web (alpha).

I've previously posted it on the subreddit where it got a warm response: https://www.reddit.com/r/privacytoolsIO/comments/7dt583/etesync_open_source_and_endtoend_encrypted/

I think it should be added, either in a PIM Sync section and move NextCloud there too. Or maybe in its own Encrypted PIM Sync section. Not sure. Even without EteSync, it's probably a section that should be created.

Should I start a PR that adds such a section? What should I do next?

Disclaimer: I created EteSync.

Thanks.

**Comment by Hillside502** [comment]
https://www.etesync.com/

https://github.com/etesync

https://www.reddit.com/r/ProtonMail/comments/7g4hrm/fyi_etesync_and_prontonmail_are_a_good/

**Comment by tasn** [comment]
Thanks for adding the links!

Another clarification that I forgot to mention in the original ticket: everything is open source (see github link in @Hillside502's comment), so you can also self-host instead of use the EteSync service itself.

**Comment by hugoncosta** [comment]
Very interesting programme! From what I see, they'll try to be a one-size-fits-all type of server. For now, I'd categorize it as a Secure File Sync Software [https://www.privacytools.io/#sync](url), since their main objective is to sync contacts and calendar info.

I also believe this one should be featured on the "Top 3" panels, but I'm not familiar with any of the other programmes, so I could not point out which one should "leave".

**Comment by tasn** [comment]
@hugoncosta, thanks for your input.

I can see the case for putting it under "file sync", but I think it's probably not the best place. EteSync does not deal with files at all, only with PIM info and integrates at a deep level (Cal/CardDAV proxy on desktop and full integration on Android), so it may be confusing. I know for one that I would not look in that section for such a solution.

Thinking about it a bit more, I wonder if maybe DAVDroid should be put next to EteSync in a new PIM sync section, and then nothing needs to be moved.

I personally use syncthing, and am familiar with sparkle-share. Never heard of syncany.

**Comment by tasn** [comment]
Just following up. How should I proceed?

**Comment by NeverDucky** [comment]
I submitted a PR #417 to add a contacts and calendar section that includes EteSync.

**Comment by tasn** [comment]
Awesome, thanks!
