### ISSUE TITLE
Why was IceCat removed in favor of Brave?

### ISSUE THREAD

**Issue by angela-d** [privacytoolsIO/privacytools.io#380]
While submitting PR https://github.com/privacytoolsIO/privacytools.io/pull/379 I seen IceCat was previously listed and then removed, with seemingly no explanation.
![icecat-removed](https://user-images.githubusercontent.com/33108490/34321037-87ea8250-e7fd-11e7-8186-108967a40c43.png) 
(this is modified code from the PR, so the line #s in the current master repo won't be exact)

I have nothing against Brave, I think it's fantastic there's an additional alternative among the Chrome and Firefox's of the world.  
Someone will be hard-pressed to suggest that [Brave](https://en.wikipedia.org/wiki/Brave_(web_browser)) are greater champions of privacy than [IceCat](https://en.wikipedia.org/wiki/GNU_IceCat), though.

What's the deal with the switch?

***
Another curious removal (albeit unrelated):
![csp](https://user-images.githubusercontent.com/33108490/34321201-341bc748-e801-11e7-8d2f-9f9b27a581e3.png)
Why was the CSP removed?
There's a lot of sloppy inline on index.html; to prevent it from breaking the page, `'unsafe-inline'` (or stop using inline css, ideally) is all that had to be added.  (I am inquiring to see if there's another reason for its disabling before I go through and modify the pages)

Update:
CSP cause: https://github.com/privacytoolsIO/privacytools.io/issues/302

**Comment by beerisgood** [comment]
IceCat is not up2date.
Brave is shit. Just a chromium fork with own telemetry

**Comment by z0m8i3** [comment]
Point taken about IceCat, the last ESR (IceCat's upstream) vulnerability is from 12/7: https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox-esr/

No disagreement about Brave!  Though for users who prefer Chromium for whatever reason, Brave is a substantially better choice for privacy than Chrome.

**Comment by Shifterovich** [comment]
I think ungoogled chromium beats both.

**Comment by beerisgood** [comment]
@Shifterovich it is up2date and without any telemetry?

**Comment by Atavic** [comment]
Latest release is 62.0.3202.94-2

Eloston did the following:

    Disable or remove offending services and features that communicate with Google or weaken privacy
    Strip binaries from the source tree, and use those provided by the system or build them from source
    Add, modify, or disable features that inhibit control and transparency (these changes are minor and do not have significant impacts on the general user experience)

https://github.com/Eloston/ungoogled-chromium 

[Review](https://www.ghacks.net/2016/10/05/ungoogled-chromium-removes-google-traces-from-chromium/)

**Comment by kewde** [comment]
The CSP was something I was toying with, I had initially merged, suspecting it wouldn't cause much harm.
It broke a lot of things however, and I haven't had the chance to get back to it. 
Thanks for bringing this up, I completely forgot about it too :P

**Comment by z0m8i3** [comment]
The CSP is definitely useful (when it doesn't break things)

**Comment by kewde** [comment]
I'm also more a fan of ungoogled chromium.

---

I have been working the past few weeks with the electron fork of Brave (also known as Muon) and I've really grown to like it. If one day we make a `privacytools.io for programmers` with a list of good libraries and frameworks then Muon from Brave deserves the top spot over electron in  the NodeJS realm.
