### ISSUE TITLE
Add Shaarli in worth to mention in netbook section

### ISSUE THREAD

**Issue by victorhck** [privacytoolsIO/privacytools.io#385]
Hello.

Recently I read about Shaarli: The personal, minimalist, super-fast, database free, bookmarking service.

https://github.com/shaarli/Shaarli
Maybe can be a good option to include in "worth to mentioning" in netbook section. It's free software

What do you think?

**Comment by Hillside502** [comment]
For "netbook section" read "Digital Notebook section".

**Comment by victorhck** [comment]
> For "netbook section" read "Digital Notebook section".
do'h!
yep, sorry for the typo!

**Comment by blacklight447-ptio** [comment]
I don't really see though what Shaarli brings to the table that our current recommendations don't offer. I am closing the issue for now, but anyone is free to comment with further arguments to have it included.
