### ISSUE TITLE
Vilfo - VPN router (but not open source)

### ISSUE THREAD

**Issue by captaindoe** [privacytoolsIO/privacytools.io#386]
The team behind OVPN.com has created a router dedicated for VPN usage, [Vilfo](https://www.vilfo.com). Any VPN provider can be used and it's most likely the easiest user interface there is to use on routers.

People can decide exactly which devices use which VPN connection and set up killswitch rules.

I can create a pull request to add some information about Vilfo. But I wanted to touch base first to see whether people believe it qualifies for the exception regarding the open source criteria.

**Comment by Hillside502** [comment]
Although OVPN.com runs an excellent VPN service and the Vilfo appears to be a very useful turnkey device, IMO the firmware needs to be open source to be considered for inclusion.

https://www.privacytools.io/#firmware

**Comment by hugoncosta** [comment]
Honestly you can do a not-so-pretty version of this with a r-pi if I'm not mistaken. But like @Hillside502 said, it has to be open source.

**Comment by Shifterovich** [comment]
Open source is like the most important criteria on PTIO. Also what @hugoncosta said.
