### ISSUE TITLE
Include PureOS

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#387]
[PureOS](https://pureos.net) is the latest addition to the FSF/GNU [OS recommendations](https://www.gnu.org/distros/free-distros.html).
It includes only free software and is set up to be privacy/security respecting.

**Comment by 0verk1ll** [comment]
I would recommend it above Trisquel because it has a modern GNOME interface and is much easier to use. It is much more friendly for the layman who is used to Windows or MacOS.

**Comment by blacklight447-ptio** [comment]
seeing how we already list a bunch of different  os's which are perfectly usable, and that purism is not the most trustworthy company, im am seeing no reason to include it into privacytools.io. also adding more distros means having a bigger chance of one of those distros going bad, and harming ptio's reputation and our users data. closing the issue for now, unless someone wants to step in for  more argumentation to include pureos into privacytools.io
