### ISSUE TITLE
Open Source Hardware U2F Devices

### ISSUE THREAD

**Issue by 0verk1ll** [privacytoolsIO/privacytools.io#391]
For extra security on user accounts, U2F hardware tokens are potentially easier to use than an app like Google Authenticator.
[U2F Zero](https://www.u2fzero.com/) and [Nitrokey](https://www.nitrokey.com/) are open source hardware/software tokens that are worth looking into.

**Comment by Hillside502** [comment]
USB Dongle Auth List
http://www.dongleauth.info/

**Comment by hugoncosta** [comment]
The current privacy tools featured on the website are all softwared-based. Maybe we should think about venturing into the hardware world?

**Comment by Vincevrp** [comment]
Discussion can continue in #420
