### ISSUE TITLE
Enable CSP

### ISSUE THREAD

**Issue by kewde** [privacytoolsIO/privacytools.io#396]
Move
https://github.com/privacytoolsIO/privacytools.io/blob/dbc9dee8115ba519dc3a3cb3e82a2e990095ef35/index.html#L3175-L3179

And move 
https://github.com/privacytoolsIO/privacytools.io/blob/dbc9dee8115ba519dc3a3cb3e82a2e990095ef35/index.html#L3187-L3199

Into their own files and re-enable the CSP.

**Comment by blacklight447-ptio** [comment]
updates on this?

**Comment by JonahAragon** [comment]
CSP is enabled. It could still be improved, potentially. See #801.
