### ISSUE TITLE
[Suggestion] Lightbeam Add-on

### ISSUE THREAD

**Issue by zero77** [privacytoolsIO/privacytools.io#404]
I don’t know what category this would be under but, I think it’s definitely worth adding.

Lightbeam basically displays all first and third party domains you consciously or unconsciously connect to and how they connect to each other, when you are browsing the web.

![lightbeam](https://github.com/mozilla/lightbeam-we/raw/master/docs/images/lightbeam.gif)

https://addons.mozilla.org/en-US/firefox/addon/lightbeam

https://github.com/mozilla/lightbeam-we

**P.S.** 
Lightbeam is not designed as a tracker or ad blocker, instead it is designed to show users who actually is tracking them, so they can take appropriate action If desired.

**Comment by beerisgood** [comment]
Useless addon. It doesnt block anything and all Blocktools show which and how many are blocked

**Comment by zero77** [comment]
@beerisgood 
I could be mistaken but I don’t think that is really the point of Lightbeam.

I think Its more designed to show sites that are tracking you and some of what they can see, like what domains you have visited but in a graphical lay out.

**Comment by Shifterovich** [comment]
Not a privacy addon per se, but might be useful to show the user the measure of online tracking.

**Comment by zero77** [comment]
Once you are aware who’s tracking you, It can be used to manually block domains to limit tracking.

Although, this currently isn’t built in and is lightly more for advanced users but, it’s still useful to see what’s going on.

**Comment by Shifterovich** [comment]
> Once you are aware who’s tracking you, It can be used to manually block domains to limit tracking.

Use PrivacyBadger.

**Comment by Atavic** [comment]
Informational extension that does nothing for user's privacy per-se.

**Comment by Hillside502** [comment]
Just be aware that when Firefox Multi-Account Containers is installed, Lightbeam only shows data for "No container" tabs.
