### ISSUE TITLE
[Suggestion] Chocolatey

### ISSUE THREAD

**Issue by zero77** [privacytoolsIO/privacytools.io#405]
I don’t know what category this would be under and its potentially less about privacy and more about security although, I think it’s worth adding.

Chocolatey, is open sauce and comes as a CLI or with a GUI, and it automatically checks for and installs updates for most applications after they have been scanned by a range of different AVs.

github.com/chocolatey/ChocolateyGUI – GUI
github.com/chocolatey/choco – CLI
chocolatey.org/packages - DB of all supported applications with info

**Comment by hugoncosta** [comment]
I've dabbled a bit with Chocolatey, it's, as their slogan states, a package manager for Windows. Although I agree it should be featured, I too don't know where it could be placed.

**Comment by Vincevrp** [comment]
Closing because not privacy related, and we discourage using Windows.
