### ISSUE TITLE
Include FreedomBox

### ISSUE THREAD

**Issue by shashikanth171** [privacytoolsIO/privacytools.io#407]
Please find more info at https://freedombox.org/ and include Freedom Box under appropriate sections.

**Comment by Hillside502** [comment]
Source
https://salsa.debian.org/freedombox-team/

FreedomBox - Wikipedia
https://en.wikipedia.org/wiki/FreedomBox

FreedomBox - Projects - PRISM Break
https://prism-break.org/en/projects/freedombox/

Open Source FreedomBox Alternatives - AlternativeTo.net
https://alternativeto.net/software/freedombox/?license=opensource

**Comment by blacklight447-ptio** [comment]
It also seems to have  a neat android app on F-droid as well, I  vote to add it as worth mentioning under the file sharing section.
