### ISSUE TITLE
Ghostbin

### ISSUE THREAD

**Issue by huubert** [privacytoolsIO/privacytools.io#408]
Ghostbin is not really secure, because after creating an encrypted paste, it's possible to access it with javascript disabled, which means the content is not decrypted in the user's browser. Also, it requires cookies to even work at all, which shouldn't be needed.

**Comment by Hillside502** [comment]
Open Source Ghostbin Alternatives - AlternativeTo.net
https://alternativeto.net/software/ghostbin/?license=opensource

**Comment by Shifterovich** [comment]
It can be self-hosted, though, if you're concerned about server-side security. But yeah, we're just recommending the main server.

**Comment by huubert** [comment]
I don't consider that secure, but maybe it's just me.
Regardless, it should be the third option in the Paste Services section and not the first, and maybe it should mention that encryptio is not done in the browser in the notes.

**Comment by infosec-handbook** [comment]
Just FYI: 
ghostbin.com runs outdated [Apache 2.4.18](https://www.cvedetails.com/vulnerability-list/vendor_id-45/product_id-66/version_id-199589/Apache-Http-Server-2.4.18.html) and outdated [OpenSSH 7.2 P2](https://www.cvedetails.com/vulnerability-list/vendor_id-97/product_id-585/version_id-194112/Openbsd-Openssh-7.2.html). The security of the [whole server setup](https://www.htbridge.com/websec/?id=rYAkummU) isn't very exemplary. Furthermore, the TLS configuration [supports insecure RC4 for encryption and weak cipher suites](https://tls.imirhil.fr/https/ghostbin.com).

**Comment by infosec-handbook** [comment]
See also [my comparison](https://github.com/privacytoolsIO/privacytools.io/issues/454#issuecomment-385314214) in #454

**Comment by Vincevrp** [comment]
Discussion can continue in #454
