### ISSUE TITLE
Your licenses are conflicting

### ISSUE THREAD

**Issue by timmyrs** [privacytoolsIO/privacytools.io#418]
On privacytools.io there's a CC BY-SA 4.0 badge. However, here on Github, the code for the same website is licensed under the GPL-3.0 license.

**Comment by Shifterovich** [comment]
@privacytoolsIO should resolve this, also consider public domain.

**Comment by infosec-handbook** [comment]
@timmyrs 
As far as I know, CC licenses shouldn't be used for software while they can be used for content. I think this is the case here.

See also:
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

> Version 4.0 of CC's Attribution-ShareAlike (BY-SA) license is one-way compatible with the GNU General Public License version 3.0 (GPLv3). This compatibility mechanism is designed for situations in which content is integrated into software code in a way that makes it difficult or impossible to distinguish the two.

**Comment by privacytoolsIO** [comment]
Good catch, that's fixed now.
