### ISSUE TITLE
fingerprint image

### ISSUE THREAD

**Issue by victorhck** [privacytoolsIO/privacytools.io#42]
Hi

"alt" parameter in fingerprint image it's wrong:
- https://github.com/privacytoolsIO/privacytools.io/blob/master/index.html#L590

've phun!

**Comment by alexbooker** [comment]
Wow  :open_mouth: 

Well spotted. 

Want to send a quick pull request or should I do it :wink:?

**Comment by victorhck** [comment]
I did it!
seeU
