### ISSUE TITLE
Mark services within fourteen eyes jurisdiction

### ISSUE THREAD

**Issue by The-Soulless** [privacytoolsIO/privacytools.io#431]

**Comment by g-monk** [comment]
Agreed. At least we can share with visitors of what’s being monitored and what’s not.

**Comment by Atavic** [comment]
[Here](https://github.com/privacytoolsIO/privacytools.io/issues/421#issuecomment-378723204)'s a related discussion.

**Comment by Atavic** [comment]
That will mark most of the internet, its services and applications.
