### ISSUE TITLE
Add disclaimer to signal

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#432]
As you know, signal requires you to use your phone number in order to use it, but in some countries(like mine), phone numbers are tied to specific people. For example, here, you have to give your id number and use your fingerprint in order to get a phone number, even for prepaid ones! (dunno how it is for other countries).
That is why, at least in my case, using signal pretty much defeats the whole privacy thing.
Please excude my paranoia :P

**Comment by Shifterovich** [comment]
Thanks, and you can use a foreign service https://infosec-handbook.eu/blog/signal-myths/#m2

**Comment by zero77** [comment]
@zeroweb91 
Although, you have to use a phone number to register and for verification, you can use a disposable number.

There are many free disposable number services or it is possible to create your own.

**Comment by Vincevrp** [comment]
@Shifterovich this was implemented in #436, but it seems to be gone?

**Comment by Shifterovich** [comment]
No idea why. Anyway, the warning should be implemented by a label, similar to Riot.

**Comment by libBletchley** [comment]
@zeroweb91
> Please excude my paranoia :P

You're not paranoid in this case:

([PDF](https://github.com/privacytoolsIO/privacytools.io/files/3102795/phone_registration.pdf))
![phone_registration](https://user-images.githubusercontent.com/18015852/56492243-7e442c80-64eb-11e9-90d0-39a919487e44.png)

**Comment by blacklight447-ptio** [comment]
adding a phone number is bad for anonymity, not privacy, signal never claimed to be anonymous.
anonymity is not part of its threat model. closing issue.
