### ISSUE TITLE
Remove Syncany (development has ceased)

### ISSUE THREAD

**Issue by rahiel** [privacytoolsIO/privacytools.io#438]
The [Secure File Sync Software](https://www.privacytools.io/#sync) section recommends Syncany. On [the Syncany website](https://www.syncany.org/) at _What is Syncany?_ you can read:

>  The core team of Syncany is on hiatus for an indefinite amount of time. Feel free to do with the code what the license allows and encourages, but please don't expect any maintenance. The team thanks everyone who has contributed to Syncany in one way or another. 

And at the news section is:

>  13 Jun 2016: The core team of Syncany is on hiatus for an indefinite amount of time. Feel free to do with the code what the license allows and encourages, but please don't expect any maintenance. The team thanks everyone who has contributed to Syncany in one way or another. We might pick up development again, or we might not. Feel free to contact us via e-mail or IRC. 

Given that development has stopped, it doesn't seem wise to recommend and depend on this software.

**Comment by Hillside502** [comment]
Syncany is **long** overdue for removal from privacytoolsIO.

How long? ----- 2 years!
https://github.com/syncany/syncany
