### ISSUE TITLE
nsupdate.info

### ISSUE THREAD

**Issue by g-monk** [privacytoolsIO/privacytools.io#439]
Being new to the project and exploring our resources, I will be asking a lot of questions to know and understand things better. I was just exploring the Prism Break Website, But was wondering why we don’t have nsupdate.info ![Image](https://i.imgur.com/0AnzGCQ.jpg)

I will be also questioning about other services listed on these sources, so I get an understanding of why they aren’t/ should be listed on privacytools.io.

**Comment by Atavic** [comment]
See: https://github.com/nsupdate-info/nsupdate.info

**Comment by g-monk** [comment]
Ok so what I’m understanding is it’s not featured as the IP Addresses are revealed.
