### ISSUE TITLE
Firefox Privacy addons

### ISSUE THREAD

**Issue by victorhck** [privacytoolsIO/privacytools.io#44]
Hi.
In the "uBlock Origin" section you can read:
"OS: Firefox, Safari, Opera, Chromium."
In that sentence OS means Operative Sistems? If so, I think that those are not OS but web browsers, right?

've phun! ;)

**Comment by alexbooker** [comment]
Well spotted. I updated the uBlock Origin description in #47. Care to check it out and tell me what you think?

**Comment by victorhck** [comment]
seems Ok for me...
Thanks!

**Comment by alexbooker** [comment]
Alright, I merged it. Thanks for all your input lately!
