### ISSUE TITLE
Cloudflare Add-on is removed from AMO - pull request needed

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#442]
https://github.com/nym-zone/block_cloudflare_mitm_fx/issues/19

**Comment by Eduardo06sp** [comment]
Are we going to delete the link altogether, or is there some sort of alternative?

**Comment by Shifterovich** [comment]
It should be possible to install the addon from a local file.

**Comment by usingtorisnotacrime** [comment]
Why not update the link to "https://trac.torproject.org/projects/tor/ticket/24351" ?

// It's sucks to know Mozilla took down the addon.

**Comment by ohmynameisrico** [comment]
[this addon](https://addons.mozilla.org/fr/firefox/addon/3prb/) have same functionality.

**Comment by beerisgood** [comment]
@ohmynameisrico: I dont see how this addon detect or block cloudflare. Its like uMatrix but with worse UI.
