### ISSUE TITLE
Suggestion/question: Enpass password manager

### ISSUE THREAD

**Issue by branneman** [privacytoolsIO/privacytools.io#446]
Privacy features:

- No signup required
- Local only by default
- No master password stored
- Optional cloud syncing, self-hosted WebDAV supported
- Great autofill support on all platforms

To me this Enpass seems like a better version of KeePass, with official apps on all platforms and managed syncing of your database. Stuff that's hard to do with KeePass. Next to that it has a much friendlier user interface across the board.

The only disadvantage I know of is that it's closed source, is that also the only reason it's not on the site?

**Comment by Hillside502** [comment]
Closed source is an absolute no-no!

The venerable JohnFastman says all at:-
Enpass Reviews - AlternativeTo.net
https://alternativeto.net/software/enpass/reviews/
