### ISSUE TITLE
Conversations (XMPP messenger) and its OTR support

### ISSUE THREAD

**Issue by infosec-handbook** [privacytoolsIO/privacytools.io#447]
Conversations 2.x dropped OTR support while the main developer announced to continue supporting OTR in Conversations Legacy. However, there are at least two discussions (siacs/Conversations#2908, siacs/Conversations#2943) which give the impression that the OTR implementation in Conversations was/is somewhat insecure and the developer knew it.

privacytools.io currently states "Supports end-to-end encryption with either OMEMO, OTR or openPGP." So, we should either remove OTR or add that there is a Legacy version still supporting it.

**Comment by Shifterovich** [comment]
Create a PR. We could both remove OTR and state that Legacy supports it.

**Comment by Kcchouette** [comment]
Can you close the issue @Shifterovich @infosec-handbook @privacytoolsIO please, as the website already state about Conversation - OMEMO and Conversation Legacy - OTR?
Thank you

**Comment by Shifterovich** [comment]
Thanks for helping with issue cleanup @Kcchouette
