### ISSUE TITLE
Proposal re LiveCD OS - Kodachi

### ISSUE THREAD

**Issue by c0rdis** [privacytoolsIO/privacytools.io#450]
Hi,
while reviewing / translating LiveCD section I've noticed that, similarly to #449, we recommend Puppy Linux but do not even mention Kodachi, which seems to be a great option for privacy/anonymity, contains lots of recommended tools and provides extra anti-forensic protection:
https://n0where.net/secure-anti-forensic-anonymous-operating-system-kodachi

Please vote with thumbs-up / down or share your comments below, once there are enough opinions, I'll create a PR to remove Puppy Linux from top-3 and place Kodachi to the second position.

**Comment by Atavic** [comment]
The critics of this OS say that's a one man project. I haven't used it, while I trust and use Whonix.

**Comment by blacklight447-ptio** [comment]
Ive looked into kodachi, it  seems like it has shady Saudi ties, and on top of that just tries to throw a bunch of security tools on a pile without any real security model, certainly not something we would want to recommend to our users. closing issue  and denying kodachi for inclusion into privacytools.io
