### ISSUE TITLE
Missing Software?

### ISSUE THREAD

**Issue by g-monk** [privacytoolsIO/privacytools.io#452]
Hi guys I wanted to ask if some update or decision was taken regarding the following softwares, because I don’t see Pidgin anymore.

**Comment by Vincevrp** [comment]
I don't recall being it listed. Maybe @Shifterovich can answer this. Closing this for now as #60 is more relevant.

**Comment by Shifterovich** [comment]
I feel like it was listed at some point but I can't find a single reference to Pidgin in the repo.
