### ISSUE TITLE
Friendi.ca Recommendation in Question

### ISSUE THREAD

**Issue by g-monk** [privacytoolsIO/privacytools.io#453]
I agree that the guidelines are open source, cross platform, easy to use and privacy respecting. I as you guys know am intrigued by privacytools.io and want to learn a lot since I am starting out as a rookie. Now I don’t know if this is going to get me yelled at or not, but I wanted to share a conversation that I had on GutHub with the Friendi.ca developers: https://github.com/friendica/dir/issues/45.

My concern here is that a server sending messages and all to the right people is fine, but isn’t your info including conversations being visible to the server owner a bit to extreme? It’s almost like the Facebook Cambridge Analytica scandal. So I was wondering if I could get some justification why it stays on the site or maybe we can advise users to be like hey guys beware of these things and here is what to do so you don’t get in trouble like it’s mentioned for Wire. However I’m a huge privacy person and don’t like prying eyes on my matters, whether they be some friendly debate, romantic message or anything dealing with advice on life. Agreed that these are normal day talks, but knowing someone is looking over your shoulder for who gets what part of you, is a bit creepy.

I am going to be digging into all the projects posted on the website to learn more for myself and also as you guys know am working on my own version of privacytools.io to which no one objected, but it’s going to be more broken down to explain things things in a child like about this stuff. So I’m going to need support and help from you all. 

My only additional criteria will be that the tools are supportive of End-to-end encryption. Based on what I learned so far from Friendica developers. I have yet to reply to the recent, but will do so when I’m free.

**Comment by blacklight447-ptio** [comment]
well tbh, one a social media platform, its to be expected to have all stuff in public, especially to the server admin. whats also good is that they admit it. i wouldn't consider this an issue, as people should be using encrypted messengers for communications anyway, if the communication in question is sensitive. closing issue.
