### ISSUE TITLE
Privacy Possum

### ISSUE THREAD

**Issue by woctezuma** [privacytoolsIO/privacytools.io#459]
I have explained that _Privacy Badger_ could provide a misleading sense of privacy in #335. I have just noticed that there exists a similar add-on, for Chrome and Firefox, called [_Privacy Possum_](https://addons.mozilla.org/en-US/firefox/addon/privacy-possum/), which claims to be stricter than _Privacy Badger_. It might be worth a look at its claims on its [Github repository](https://github.com/cowlicks/privacypossum). Apparently, it is developed by someone who works at EFF, and has worked for 6 months on _Privacy Badger_.

**Comment by beerisgood** [comment]
Anyone tried it and can recommend this addon beside uBlock Origin, uMatrx, Decentraleyes and Firefox Containers?

**Comment by woctezuma** [comment]
I have been using the addon and I don't have any problem with it now. There used to be a problem when I tried to log in on SteamDB.info but this issue has been fixed.

I cannot really tell how much additional privacy this provides for someone who has installed all the addons mentioned above.

**Comment by BurungHantu1605** [comment]
Replace Privacy Badger with Privacy Possu?

https://www.reddit.com/r/privacytoolsIO/comments/bbeumm/recommendation_i_think_that_privacy_badger_on_the/

**Comment by JonahAragon** [comment]
It isn't clear to me how adding this would be better than the combination of add-ons we currently recommend, which pretty much cover all bases.

**Comment by KonoromiHimaries** [comment]
https://github.com/privacytoolsIO/privacytools.io/issues/1301
