### ISSUE TITLE
Consider spyOFF VPN

### ISSUE THREAD

**Issue by hesekiel25** [privacytoolsIO/privacytools.io#460]
www.spyOFF.com fulfills the mentioned points:
-	outside the US (outside Fourteen Eyes as based in San Marino)
-	uses encryption
-	accepts Bitcoin
-	supports OpenVPN
-	has a no logging policy

**Comment by Shifterovich** [comment]
https://www.spyoff.com/en#features states "No data-logging", but I think there should be a page dedicated to explaining what they log. "No logs" is absurd, there are obviously some logs for maintenance. I want to know what is (not) logged.

Also, the website only lets me use PayPal, not Bitcoin.

**Comment by hesekiel25** [comment]
Hi!

Regarding No Logs you can find detailed info here:
https://www.spyoff.com/en/no-logs
https://www.spyoff.com/en/data-protection-regulations (VPN Software)

Regarding bitcoin you were right. There was an issue. Therefore it was hidden.
You can find it now live again:
https://shop.spyoff.com/en/signup/mb2

Best, Mitch

Von: Samuel Shifterovich [mailto:notifications@github.com]
Gesendet: Donnerstag, 17. Mai 2018 15:42
An: privacytoolsIO/privacytools.io <privacytools.io@noreply.github.com>
Cc: Mitch Friendlyduck <mitch@friendlyduck.com>; Author <author@noreply.github.com>
Betreff: Re: [privacytoolsIO/privacytools.io] Missing VPN (#460)


https://www.spyoff.com/en#features states "No data-logging", but I think there should be a page dedicated to explaining what they log. "No logs" is absurd, there are obviously some logs for maintenance. I want to know what is (not) logged.

Also, the website only lets me use PayPal, not Bitcoin.

**Comment by ohmynameisrico** [comment]
The "No log" claim will be tested in the future, when some criminals use their VPN service to do very bad thing.
When you select a VPN, search some court case. These data will tell you the truth.

**Comment by blacklight447-ptio** [comment]
We are not really looking to add More vpn providers at the moment, adding more may just confuse users on which service to choose. closing for now, with possibility to be opened up again once other providers get removed.
