### ISSUE TITLE
AFWall+

### ISSUE THREAD

**Issue by davidtabernerom** [privacytoolsIO/privacytools.io#462]
NetGuard is a good Firewall for Android, but another well known one is AFWall+ (Android Firewall +).
Is a pretty good app, open source, but requires root permissions.
Allows you to filter by appname, IP connection type, LAN, WiFi, etc.
Works well.

Links:
Google Play: [https://play.google.com/store/apps/details?id=dev.ukanth.ufirewall](https://play.google.com/store/apps/details?id=dev.ukanth.ufirewall)
F-Droid: [https://f-droid.org/en/packages/dev.ukanth.ufirewall/](https://f-droid.org/en/packages/dev.ukanth.ufirewall/)
Github: [https://github.com/ukanth/afwall](https://github.com/ukanth/afwall)

**Comment by beerisgood** [comment]
LineageOS have a internal mobile Data & WiFi Control for apps, which is enough for most Users and run without root

**Comment by davidtabernerom** [comment]
@beerisgood Is not in most devices without LineageOS as stock ROM necessary to root and unlock the phone in order to being able to install LineageOS?
I have Lineage and I know there is, but AFWall+ is centralized, well-organized, free, open source, and works flawlessly fine.

**Comment by beerisgood** [comment]
With OnePlus you dont need root to flash LOS. Dont know other phones

**Comment by Primokorn** [comment]
NetGuard is the best except if you already use the VPN service. (Yes there are paid features. What's the problem? It's a pleasure to support such a talented and responsive dev)
I have bugs with AFWall+ that haven't been fixed for months (maybe years) and some advanced features are missing if you don't know how to use iptables.
It's worth mentioning it as a firewall solution though.

**Comment by davidtabernerom** [comment]
@beerisgood True, there are some examples that do not need to root, or that come with CyanogenMod / LineageOS / (other), but I think is not in most phones out there.

@Primokorn I have been using it for years (since CM11) and did not have any problem at all, always working perfectly fine. Maybe there are bugs with specific phones of some brands (?). In any case, I do not think there is a "best" solution as long as it has been working for some people like me.

Anyway, the more, the better. I think both 2 should be mentioned.

**Comment by beerisgood** [comment]
@Primokorn NetGuard the best? Hell, no. You need to pay the App cause the free version is useless. Then the App include Tracking - maybe now since GPDR not true.
I wouldnt trust the app nor the Dev.

So please stop advertising auch a project as "the best"

**Comment by blacklight447-ptio** [comment]
i recommend not Adding AFwall, as it requires root access, which breaks androids security model.

**Comment by blacklight447-ptio** [comment]
After team discussion, we will no longer recommend apps that require a user to root his phone. therefor i will now close this issue.
