### ISSUE TITLE
Should Seafile really be the first choice for a self-hosted cloud solution? You be the judge.

### ISSUE THREAD

**Issue by RichardRMatthews** [privacytoolsIO/privacytools.io#465]
https://github.com/haiwen/seafile/issues/350

**Comment by stevesbrain** [comment]
I respect that this issue needs attention drawn to it, though I'm not so sure this is really a useful issue to open.

**Comment by RichardRMatthews** [comment]
More people should be aware of this before making a choice which self hosting cloud they want to use.

**Comment by stevesbrain** [comment]
@RichardRMatthews My apologies - I mistakenly thought this was an open issue on the actual haiwen/seafile repo; was a derp on my end. I can totally see the relevance here :) Ignore me!

**Comment by RichardRMatthews** [comment]
No problem , everyone mixes things up. Have a nice day!

**Comment by stevesbrain** [comment]
You too :)

**Comment by Vincevrp** [comment]
Seafile was removed in #491.
