### ISSUE TITLE
Password generator not working properly

### ISSUE THREAD

**Issue by Strappazzon** [privacytoolsIO/privacytools.io#467]
I have noticed that sometime the length of the generated password **doesn't match** the one selected by the user (**1-3 characters are missing usually**), as shown here: https://i.imgur.com/Z53sCNQ.png

**Comment by kewde** [comment]
We should probably remove the password generator - cryptography in JavaScript has a track record of being shitty.

**Comment by Shifterovich** [comment]
I doubt people use it, but some pages may link to ptio/password.html. So maybe instead of removing the page we should replace it with a KeePass recommendation?

**Comment by Vincevrp** [comment]
Password generator has been removed in 43a14c3
