### ISSUE TITLE
Cleanup "VPN providers with extra layers of privacy"

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#480]
1. Remove Proxy.sh from the list because http://torrentfreak.com/proxy-sh-vpn-provider-monitored-traffic-to-catch-hacker-130930/
2. Add this link to "Related VPN info" section: https://www.reddit.com/r/Piracy/comments/8ogup1/ipvanish_claims_0_log_policy_busted_for_logging/

**Comment by Atavic** [comment]
Privacyscore has a list of [VPN sites](https://privacyscore.org/list/276/?categories=privacy%2Cssl%2Csecurity%2Cmx) where some don't pass this review:
out of 278 websites, 128 failed critical checks.

**Comment by blacklight447-ptio** [comment]
status on this issue?

**Comment by nitrohorse** [comment]
Interested as well.

**Comment by JonahAragon** [comment]
Killed the VPNs in #1155.
