### ISSUE TITLE
Windows 10 - gdpr update

### ISSUE THREAD

**Issue by mispp** [privacytoolsIO/privacytools.io#484]
Have things changed win GDPR regarding windows?
What i could find online says that volume of basic diagnostics is now much smaller.

As a consequence of GDPR and change in what data gets sent to microsoft, does section "Don't use Windows 10 - It's a privacy nightmare" need to be updated?

**Comment by Atavic** [comment]
*Privacy Nightmare* was the title of a zdnet article that went viral at windows 10 launch.

I'd put a few lines about telemetry data and eventually links to official explanations, as:
https://docs.microsoft.com/en-us/system-center/scsm/manage-telemetry?view=sc-sm-1801#telemetry-data-collected

**Comment by ohmynameisrico** [comment]
Am a not W10 user, but does GDPR changed Windows? Or will Microsoft make "Windows EU edition (collect no data)"?

**Comment by beerisgood** [comment]
Microsoft change their services worldwide to GDPR compatible so they dont need provide a special Windows version.

So yes, it change Windows

**Comment by Atavic** [comment]
And previously there were Windows N editions with no mediaplayer, due to EU complaints.

Windows 7: Windows Media Player and Windows Media Center are missing.
Windows 10: don’t include Windows Media Player, Groove Music, Movies & TV, Voice Recorder and Skype.

**Comment by beerisgood** [comment]
"Say goodbye to the Windows Store, ... , **Windows Defender** ,..."
Cant recommend that

**Comment by Atavic** [comment]
You can debloat on your own with MSMG ToolKit. it creates a slimmed down Windows by customizing, adding or removing features and components as well as enabling or disabling features to Microsoft Windows 7, 8 and 10.

**Comment by Atavic** [comment]
You can debloat on your own with MSMG ToolKit: it creates a slimmed down Windows by customizing, adding or removing features and components as well as enabling or disabling features to Microsoft Windows 7, 8 and 10.

**Comment by Mikaela** [comment]
I am closing this as there hasn't been discussion recently and I don't see what this issue wishes to change from the original issue. I think it might be more clear to open a new issue if there is something concrete.
