### ISSUE TITLE
Regarding add-ons which connect to the internet without user action

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#485]
https://github.com/mozilla/addons/issues/735

Stay safe, everyone.

**Comment by dnguyen01** [comment]
So what is the point of creating this issue?

Also, you need to put all your ideas in readable form. I had to follow a couple issues that you opened & replied to understand what you wanted. So you created an issue on Mozilla's GitHub to penalize people who don't put privacy policy? So what do you want us to do? Are you pretending to be a Mozilla Reviewer (https://github.com/schomery/dictionary/issues/40)?

**Comment by Atavic** [comment]
> “privacy”: [ “sendsUsageDataToThirdParty”, “sendsUsageDataToDeveloper”, “sendsBrowsingData”,
> “sendsProfileData”, “collectsUserData” ]

https://bugzilla.mozilla.org/show_bug.cgi?id=1464916

**Comment by Atavic** [comment]
> “privacy”: [ “sendsUsageDataToThirdParty”, “sendsUsageDataToDeveloper”,
> “sendsBrowsingData”, “sendsProfileData”, “collectsUserData” ]

https://bugzilla.mozilla.org/show_bug.cgi?id=1464916
