### ISSUE TITLE
CopperheadOS may be compromised

### ISSUE THREAD

**Issue by cwcopa** [privacytoolsIO/privacytools.io#486]
_"I consider the company and infrastructure to be compromised. James cannot be trusted and I am effectively no longer part of Copperhead at least per his claims."_

Claimed Daniel "strncat" on reddit. He is one of the core devs.

https://www.reddit.com/r/CopperheadOS/comments/8qdnn3/goodbye/

**Comment by quantumpacket** [comment]
> There's no need to disable updates, it's not possible for them to be created without my signing keys. You could disable the Updater app but it doesn't really matter. James did seize control over the infrastructure but he can't make updates signed by me so users are safe from whatever nonsense he would do. I already wiped the 4 sets of hardware containing the keys so there is no way to make a valid update. I can't do it either. I can't be forced to do it.

> If this was a state sponsored attack or something like that, it has been thwarted. It was certainly an attempt at a hostile takeover of the project and has failed.

**Comment by Atavic** [comment]
Bad news indeed.

Either Daniel gets a winning, based on canadian law, or CopperheadOS will have hard times in the future. He's thestinger on GH.

**Comment by Vincevrp** [comment]
CopperheadOS was removed in #488.
