### ISSUE TITLE
Add Blokada and DNS66 as ad-blockers for android 

### ISSUE THREAD

**Issue by jeroen7s** [privacytoolsIO/privacytools.io#500]
Ad-blockers are a major improvement for privacy
Especially on android it's desperately needed, but there's no decent source online linking to them

Both DNS66 and Blokada are supported by an active community and still in active development,and are both open source

**Comment by jeroen7s** [comment]
Dns66 hasn't had an app update in a while, but it doesn't seem to be completely inactive

But yes Blokada is definitely more actively maintained atm

**Comment by victorhck** [comment]
+ 1 to Blokada

> Free and open Source. Blokada works across all of your apps, not only the browser! It doesn't require root, supports both wifi and mobile networks, and is perfectly safe and simple to use.

**Comment by BurungHantu1605** [comment]
Added Blokada:
https://www.privacytools.io/operating-systems/#aaddons
