### ISSUE TITLE
Add Ultrasound Tracking Detection App 

### ISSUE THREAD

**Issue by swr7hr** [privacytoolsIO/privacytools.io#501]
Ultrasound tracking is growing. And it allows apps to exchange data via inaudible tones using our microphones/speakers. However it can also be used to link phones, separate accounts and more through cross device tracking and it does not need wifi or connected to do it. 

There is an app for Android users which has been developed to help combat this. It is called SoniControl.
https://phys.org/news/2018-05-ultrasound-firewall-mobile.html

**Comment by beerisgood** [comment]
Install a App from devs which include 12 third-party cookies & 117 Third-party requests on homepage? See: https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fphys.org%2F
No thanks

**Comment by swr7hr** [comment]
Thank you for that link. Damn. I guess it is still at nothing for Ultrasound tracking.

**Comment by pahakalle** [comment]
https://sonicontrol.fhstp.ac.at/ seems to the projects main site, but its still not any better, having no https for starters

And heres the test for the site: https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fsonicontrol.fhstp.ac.at%2F

**Comment by pahakalle** [comment]
It seems they host the code on gitlab instance tough https://git.nwt.fhstp.ac.at/m.zeppelzauer/SoniControl

**Comment by blacklight447-ptio** [comment]
because of inactivity, im closing this issue. if someone can recommend another app which stops ultrasound tracking that is privacy friendly, feel free to comment below to open up the issue again.
