### ISSUE TITLE
Consider adding Cryptee

### ISSUE THREAD

**Issue by johnozbay** [privacytoolsIO/privacytools.io#502]
Hey team 👋🏻 

Maker of [Cryptee](https://crypt.ee) here.
[I've launched Cryptee on privacy tools' reddit about a month ago](https://www.reddit.com/r/privacytoolsIO/comments/8t1oqz/a_new_privacy_tool_ive_been_building_for_15_years/), 
with a pretty sweet response rate of [top 15th post](https://www.reddit.com/r/privacytoolsIO/top/?t=year) of this year under r/privacytoolsIO.

Is it possible to add Cryptee under Notes / Docs / Photos ?
I can happily answer any outstanding question or doubt there may be. 
Would love for Cryptee to reach the broader community.

All the very best from Northern Europe,
J

**Comment by Hillside502** [comment]
Hi there in Estonia,

I would love to hear your response to John Fastman's very detailed review on AlternativeTo --- in particular his _Criticisms_:-
https://alternativeto.net/software/cryptee/reviews/

**Comment by johnozbay** [comment]
Hey @Hillside502! Thanks a lot for sending this over! I haven't seen this before, and made me quite happy for many reasons. (Especially because since the writing of his review I've added a few more of the requested features) I will respond to John F. over at AlternativeTo as well, but to keep things consistent I'll respond here first. ✌🏻

### Progressive Web Apps 📲
I'll start with the most important thing, I love native apps as much as John F. does, and dislike the shortcomings of PWAs with a raging fire of thousand suns. PWAs come with _many_ problems. However, as a solo developer, who quit his day job, and is funding Cryptee all out of pocket, this was the quickest way to kick off the service with a single codebase.

Perhaps the biggest shortcoming, and the most requested feature was Offline mode. I'm happy to say that about two weeks ago (~30 days after the launch) I've added this feature, and have gotten tremendous amounts of positive feedback so far. 

Regarding other shortcomings, especially about the privacy concerns of being vendor-locked to using Chrome, I have two alternative plans, and depending on Apple & Mozilla, I will either proceed with short-term plan 1 or short-term plan 2. And finally there's of course a long term plan.

**Short-term Plan 1** 📆

Good news is that PWAs are no longer Chrome-only. [Amazing folks are Firefox are working hard on PWAs as well](https://blog.mozilla.org/firefox/progressive-web-apps-whats-big-deal/). And even today, you can use Cryptee natively on Android using a Firefox PWA if you wish so. (instead of a Chrome PWA) The reason this isn't listed on the landing page is because FF PWA lacks a few mini features, and has some bugs, and once these are fixed I will include firefox on the landing page as well. Moreover, [Apple is bringing deeper support](https://www.goodbarber.com/blog/ios-opens-its-doors-to-progressive-web-apps-a898/)[ for PWAs](https://dev.to/oninross/service-workers-has-finally-landed-in-ios--now-what-110o) [with iOS 12](https://medium.com/@firt/progressive-web-apps-on-ios-are-here-d00430dee3a7). It's exciting times for the web. 

So currently, I see Apple as the tie breaker here. If iOS, Mac OS and Firefox Desktop gets good support for PWAs, then Chrome won't be the monopoly on this, and I'd say this pretty much solves the potential privacy-concerns of many. In the sense that, Cryptee as a web-app, will be as safe as any other web-based privacy provider.

**Short-term Plan 2** 📆

You may be rightfully wondering, "Why not make Cryptee a packaged Cordova-like web-app and Electron app then release it through the App Stores?"

Generally speaking, app stores are no lesser of an evil than the browsers themselves in this context. [Check out this fantastic article about 10 years of app store controversies.](https://www.macstories.net/stories/10-years-of-app-store-controversies/) And there's [worse examples](https://www.engadget.com/2018/05/31/apple-telegram-ios-app-russia-app-store/) like the telegram vs apple too. So I've got a few concerns on this front as well, but it could be an acceptable fallback until there's better PWA support. 

I am already actively testing a wrapped native app for iOS & Android, and Electron for all desktop platforms. If Apple & Mozilla won't bring support for PWAs quickly and well enough, I will start packaging and releasing these before next year.

**Long term plan** 🗓
With growing support from the community, and more paid users signing up, eventually I will be able to afford to expand the team and start developing native apps for all platforms. So at some point in the near future, once Cryptee starts getting more paid users, you can expect native applications.

### Share to/from Cryptee ⬆️⬇️

Good news here too. 
Share 'from' Cryptee is possible, and on the way, as [there's support from browsers. (Here's for Chrome)](https://developers.google.com/web/updates/2016/09/navigator-share)

Share 'to' Cryptee is also going to be possible soon, there's a proposed [Web-Share-Target API](https://github.com/WICG/web-share-target), and [it's in development (at least for Chrome)](https://www.chromestatus.com/feature/5662315307335680).

Again if a good PWA support doesn't land on devices soon, and I end up packaging Cryptee as a Cordova app, this won't be an issue either, since I can quickly address this using a native-bridge [like this one](https://github.com/napolitano/cordova-plugin-intent). 

### Other features ⚙️
I'm actively adding the most wanted features from the community, and have already added some of what John F. wanted as well. Like Offline Mode, Archived Folders, Linking Documents/Notes like a wiki.

Some of the features John's referring to are only possible if Cryptee violates its own threat model or gets a native app.

**OCR** 📸
Almost all OCR tools (both native and web apps) use server-side computing to reduce the burden on devices. This could be possible with a native app in the future, but not today. 

**A browser plugin & web clipper** ✂️
This would require Cryptee to either store the users' encryption keys in memory permanently = against threat model or ask it every time they clip something = inconvenient. 

**Reminders** 🛎
I'm working on a separate Cryptee Reminders. (it's outside of Docs, so I'm passing this one)

**Sharing** 📨
Turns out this is a very legally-complex topic, involving lots of fun-time consulting attorneys. Testing the code already with some close friends, however won't be released until I know for sure that legally it doesn't cause any issues that could get the platform shut down. _File sharing_ in general is a dicey topic. Tons of services got shutdown with copyright violations, and communications act + GDPR complicate things even further. This will arrive, but will take some time.

--- 

I hope that these shed some light on the direction, and address some of the concerns and criticisms.
