### ISSUE TITLE
404 error on piwik.js

### ISSUE THREAD

**Issue by jonathancross** [privacytoolsIO/privacytools.io#510]
[webrtc.html#L160](https://github.com/privacytoolsIO/privacytools.io/blob/master/webrtc.html#L160) references a file (`piwik.js`) that does not exist.

Can be seen here on the live site:  https://www.privacytools.io/webrtc.html

**Comment by Shifterovich** [comment]
That's @privacytoolsIO's analytics. It should be the same as on index, that is:

https://github.com/privacytoolsIO/privacytools.io/blob/7c2131e124cab917a4e05861e0ed00b3e34e6fa8/index.html#L3291-L3311

**Comment by jonathancross** [comment]
Okay, the file [piwik.js](https://piwik.privacytools.io/piwik.js) exists on the server, but not here in GitHub.  It is the root folder. The page `webrtc.html` uses different analytics code and is looking [inside the /stats/ subfolder](https://github.com/privacytoolsIO/privacytools.io/blob/master/webrtc.html#L156).
