### ISSUE TITLE
Remove Muonium as file synchronization recommendation

### ISSUE THREAD

**Issue by basnijholt** [privacytoolsIO/privacytools.io#511]
The project has only 2 contributors and is added by one of the authors of the software package.

I personally think privacytoolsIO should recommend proven solutions, not alpha/beta software.

What do others think?

**Comment by Atavic** [comment]
Most repos seen [here](https://github.com/muonium) are also archived.
Is this cloud think still running?

**Comment by Hillside502** [comment]
@Atavic 
Repos moved to:-
https://gitlab.com/muonium

**Comment by Shifterovich** [comment]
> The project has only 2 contributors and is added by one of the authors of the software package.
> I personally think privacytoolsIO should recommend proven solutions, not alpha/beta software.

I agree. Create a PR if we can get one more approval @Atavic @Hillside502 @kewde

**Comment by Atavic** [comment]
I found the github link on bottom of ```muonium.io``` but repo is active on gitlab. You have to register to use it. Upon registration, you are redirected to ```https://mui.cloud/```

Above page loads:

> font-awesome/css/fontawesome.min.css
fonts/Roboto.css

...and three js scripts. This gives a lot of opportunities to google for fingerprint the users.
Like all cloud solutions that allegedly care about privacy, they really fail at it.

>However, Font Awesome does use services from other companies to provide fontawesome.com, content delivery networks, and to distribute and develop icons and software. The companies behind those services may collect data about you on their own, for their own purposes.

[Does Font Awesome share data about me with others?](https://fontawesome.com/privacy#access)

For a complete list of partners, see https://fontawesome.com/privacy#other-services

That being said, I'll use [IPFS](https://ipfs.io/) over this fingerprinting-riddled cloud solution.
