### ISSUE TITLE
Add DNS.WATCH to the dns section

### ISSUE THREAD

**Issue by Jon-guy30** [privacytoolsIO/privacytools.io#513]
I want you to take a look at DNS.WATCH DNS service. It's a privacy respecting public dns resolver (no logs), is fast and has DNSSEC. Both IPv4 and IPv6 are supported. 

There are other privacy DNS services out there, but this is the only one I've found that has reasonable security. All the other ones are terrible. You can use the GRC.com DNS spoof test to test your DNS security.

https://dns.watch/

**Comment by Mikaela** [comment]
Do we wish to support not-OpenNIC servers? At the moment there is no individual server provider mentioned [on the site](https://www.privacytools.io/providers/dns/).

I wonder if it would be better to direct people thinking about DNS servers to e.g. [DNSPrivacy.org's list](https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Public+Resolvers), but they again seem to list also services like Google DNS.

**Comment by Mikaela** [comment]
@Jon-guy30 Do you have any connection to the dns.watch admin? I wished to include it in https://github.com/privacytoolsIO/privacytools.io/pull/1054, but it turns out to not support DNS over TLS nor DNS over HTTPS nor mention DNSCrypt.

**Comment by blacklight447-ptio** [comment]
Closing because of user unresponsiveness.
