### ISSUE TITLE
Firefox Send: WeTransfer privacy-safe alternative

### ISSUE THREAD

**Issue by maxxer** [privacytoolsIO/privacytools.io#516]
https://testpilot.firefox.com/experiments/send

**Comment by beerisgood** [comment]
Use www.google-analytics.com
No, thanks.
See https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fsend.firefox.com%2F

**Comment by maxxer** [comment]
https://github.com/mozilla/send/issues/897

**Comment by pahakalle** [comment]
@beerisgood unrelated but are you using this? https://tools.google.com/dlpage/gaoptout

**Comment by beerisgood** [comment]
@pahakalle why should i? Opt-out is wrong way.
If the site doesnt respect that, i dont use it
I also dont use any google services or sites (except YouTube)

**Comment by PopeRigby** [comment]
I'm not detecting any trackers on the site
![](https://i.imgur.com/BcXXAVU.png)
![](https://i.imgur.com/pkMbuqx.png)

**Comment by five-c-d** [comment]
Agree with @PopeRigby that the GoogleAnalytics (which was there back in late 2018) seems to be gone now.  However, note that originally the service was 

*  Amazon AWS hosting, with GoogleAnalytics javascript, [per urlscan.io](https://urlscan.io/result/5d93b8c6-901f-47e2-894d-f86b996b23c4/#behaviour)

Recently they moved, and are now 

*  Google GCP hosting, without GoogleAnalytics javascript, [per more recent urlscan.io](https://urlscan.io/result/54ac3248-d824-4ef9-9ed9-b2bc08a779e9/#transactions)

Therefore google *is* still getting some network-layer info methinks.  There is not a tracker, per se, but google has an external dataset they can correlate against.  

Recently firefoxSend was moved into the top-listed position for filesharing == https://www.privacytools.io/classic/#filesharing (up from 2nd place after OnionShare which swapped positions with firefoxSend).

**Comment by blacklight447-ptio** [comment]
Closing issue as we now list Firefox send.
