### ISSUE TITLE
Operating systems worth mentioning request,

### ISSUE THREAD

**Issue by FrostKnight** [privacytoolsIO/privacytools.io#517]
I think you should add Hyperbola Gnu/linux to it. 
It is like archlinux in that it is hard to install, but it would be nice if you added it as a mention even if you say it is not for beginners/easy to use. It is more of an advanced user distro. 

You could say it focuses heavily on being stable, secure/private and lightweight.

It is entirely free software. it focuses on having no blobs/proprietary firmware/software.

It is a very secure distro, it is a fork of archlinux that uses debian packages for stability and security.  Just thought I would mention this to you.  

This is their website:

Hyperbola.info

Let me know if you have interest, if not, oh well. ;)

**Comment by Vincevrp** [comment]
Thanks for your suggestion. We should discuss this in #449.
