### ISSUE TITLE
True Sight (was: Detect Cloudflare+)

### ISSUE THREAD

**Issue by Jon-guy30** [privacytoolsIO/privacytools.io#518]
There's a new "cloudflare detection" addodon called detect cloudflare+. Link here https://addons.mozilla.org/en-US/firefox/addon/detect-cloudflare-plus/

The old link to the cf mitm addon should be removed in the privacy resources section and replaced with this one.

I remember the old addon actually actively blocked cf webpages, this one only shows "Hey! This site has some content (or all!) served by cloudflare, be careful!" You need to decide if you trust the website or not.

**Comment by n8v8R** [comment]
> You need to decide if you trust the website or not.

To list that add-on might not be such a good idea as it exposes privacytools.io hosted resources on CF - a US based service not only but also one where the TLS terminates at the provider's edge servers with this type of TLS SNI certificate for the privacytools.io domain

1. DNS Name: sni209452.cloudflaressl.com
2. DNS Name: *.angrymovies.ga
3. DNS Name: *.awrtdvoucvl.tk
4. DNS Name: *.dallastimesherald.com
5. DNS Name: *.deliverybtc.club
6. DNS Name: *.devkrupaenterprises.in
7. DNS Name: *.dowlingswansea.com.au
8. DNS Name: *.easepristines.top
9. DNS Name: *.ejsx4bnet.ga
10. DNS Name: *.fasnntluve.ga
11. DNS Name: *.fpdftoswf.ga
12. DNS Name: *.fvtxuhwjq.tk
13. DNS Name: *.g-trudysreview.ga
14. DNS Name: *.jekabpiqlssq.tk
15. DNS Name: *.kieulefevre.com
16. DNS Name: *.latestlupusupdate.review
17. DNS Name: *.m330d.com
18. DNS Name: *.murraysbeachrealestate.com.au
19. DNS Name: *.neworiginals.top
20. DNS Name: *.nnkjjwnet.ga
21. DNS Name: *.nvazbmzec.tk
22. DNS Name: *.opencartthemes.online
23. DNS Name: *.openlovelys.top
24. DNS Name: *.outletsofts.top
25. DNS Name: *.palacerares.top
26. DNS Name: *.pathascendants.top
27. DNS Name: *.pathpasss.top
28. DNS Name: *.pdfultimate.ml
29. DNS Name: *.privacytools.io
30. DNS Name: *.r-scatsreview.ml
31. DNS Name: *.rereggkclo.tk
32. DNS Name: *.shenmabt.org
33. DNS Name: *.sightpredominants.top
34. DNS Name: *.spxkxuif.tk
35. DNS Name: *.swanseansw.com.au
36. DNS Name: *.t3n9mxnet.ml
37. DNS Name: *.tihdenrwz.tk
38. DNS Name: *.truehearts2love.com
39. DNS Name: *.urpqmsxpy.tk
40. DNS Name: *.uruiyyabvb.tk
41. DNS Name: *.v99mgtnet.cf
42. DNS Name: *.vivier-ventures.com
43. DNS Name: *.vivierdev.com
44. DNS Name: *.vivierinv.com
45. DNS Name: *.w-shelvest.gq
46. DNS Name: *.xpzpkwuscq.tk
47. DNS Name: *.y94j4enet.ml
48. DNS Name: *.z9ke30net.ga
49. DNS Name: *.zfzyolbxi.tk
50. DNS Name: angrymovies.ga
51. DNS Name: awrtdvoucvl.tk
52. DNS Name: dallastimesherald.com
53. DNS Name: deliverybtc.club
54. DNS Name: devkrupaenterprises.in
55. DNS Name: dowlingswansea.com.au
56. DNS Name: easepristines.top
57. DNS Name: ejsx4bnet.ga
58. DNS Name: fasnntluve.ga
59. DNS Name: fpdftoswf.ga
60. DNS Name: fvtxuhwjq.tk
61. DNS Name: g-trudysreview.ga
62. DNS Name: jekabpiqlssq.tk
63. DNS Name: kieulefevre.com
64. DNS Name: latestlupusupdate.review
65. DNS Name: m330d.com
66. DNS Name: murraysbeachrealestate.com.au
67. DNS Name: neworiginals.top
68. DNS Name: nnkjjwnet.ga
69. DNS Name: nvazbmzec.tk
70. DNS Name: opencartthemes.online
71. DNS Name: openlovelys.top
72. DNS Name: outletsofts.top
73. DNS Name: palacerares.top
74. DNS Name: pathascendants.top
75. DNS Name: pathpasss.top
76. DNS Name: pdfultimate.ml
77. DNS Name: privacytools.io
78. DNS Name: r-scatsreview.ml
79. DNS Name: rereggkclo.tk
80. DNS Name: shenmabt.org
81. DNS Name: sightpredominants.top
82. DNS Name: spxkxuif.tk
83. DNS Name: swanseansw.com.au
84. DNS Name: t3n9mxnet.ml
85. DNS Name: tihdenrwz.tk
86. DNS Name: truehearts2love.com
87. DNS Name: urpqmsxpy.tk
88. DNS Name: uruiyyabvb.tk
89. DNS Name: v99mgtnet.cf
90. DNS Name: vivier-ventures.com
91. DNS Name: vivierdev.com
92. DNS Name: vivierinv.com
93. DNS Name: w-shelvest.gq
94. DNS Name: xpzpkwuscq.tk
95. DNS Name: y94j4enet.ml
96. DNS Name: z9ke30net.ga
97. DNS Name: zfzyolbxi.tk

**Comment by Mikaela** [comment]
It looks like the extension has changed it's name to _True Sight_ and attempts to detect other CDNs too in addition to only Cloudflare. Could you update the issue title and maybe details?

Source: clicking https://addons.mozilla.org/en-US/firefox/addon/detect-cloudflare-plus/

**Comment by pahakalle** [comment]
The github repo of the addon: https://github.com/claustromaniac/detect-cloudflare-plus
