### ISSUE TITLE
Add microG fork of LineageOS

### ISSUE THREAD

**Issue by zayuim** [privacytoolsIO/privacytools.io#519]
Something to consider for the Android section:

**LineageOS for microG** https://lineage.microg.org/

It is a soft fork of LineageOS with microG and the F-Droid Privilege Extension preinstalled in root. Really handy for someone who wants a FOSSDroid phone.

**Comment by Hillside502** [comment]
For "MircoG" read "microG".

> preinstalled in root

Should we be encouraging rooting?

**Comment by zayuim** [comment]
@Hillside502 With this ROM only microG and F-Droid will be installed with system privileges. The people who run this fork somewhat discourages rooting:

> Our ROM doesn't include root by default for security reasons, but you can easily install it: go here, download the appropriate ZIP and install it from the recovery.
