### ISSUE TITLE
[Feature Request] Hosting Providers Section

### ISSUE THREAD

**Issue by zero77** [privacytoolsIO/privacytools.io#522]
I think it may be useful to have a new hosting providers section for people who want to find a good secure and privacy conscious, hosting company for creating vpns or other such hosting.

For example, bahnhof.net

**Comment by Avizini** [comment]
@Hillside502 Are you advertising Cloudron? Never heard of that before and you have posted it in 2 comments.

**Comment by Hillside502** [comment]
Not advertising, as I don't represent Cloudron -- but I thoroughly recommend it.

**Comment by Vincevrp** [comment]
Added in #638.
