### ISSUE TITLE
What about bitmask free VPN service?

### ISSUE THREAD

**Issue by haroon-ali** [privacytoolsIO/privacytools.io#523]
Hi,
Bitmask a free secure VPN service, its android client is available on f-droid few months ago.
https://f-droid.org/en/packages/se.leap.bitmaskclient/

It uses services from leap.se and riseup.net - Requires no email or phone number at registration. You can even use it without a username.

Do you think it should be added to privacytools.io ?

**Comment by Hillside502** [comment]
https://bitmask.net/

Bitmask is still experimental by their own admission.  IMHO this should not be recommended until things stabilize.

**Comment by Vincevrp** [comment]
> https://bitmask.net/
> 
> Bitmask is still experimental by their own admission. IMHO this should not be recommended until things stabilize.

Agreed.

**Comment by Kovaelin** [comment]
Is this worth revisiting now? Also, does anyone know of any differences between this and RiseupVPN?

**Comment by Mikaela** [comment]
Do they fullfil the VPN criteria? 

* https://www.privacytools.io/providers/vpn/#criteria

**Comment by nitrohorse** [comment]
> Do they fullfil the VPN criteria?

Good question -- looks like Bitmask is developed by the non-profit, [LEAP](https://leap.se/en/about-us), which is based in the US. So simply in regards to our jurisdiction criteria, they won't meet it.
