### ISSUE TITLE
Browser worth mentioning: ungoogled-chromium

### ISSUE THREAD

**Issue by skygate2012** [privacytoolsIO/privacytools.io#524]
ungoogled-chromium is Google Chromium with Google integration removed. It also features some changes to enhance privacy, control, and transparency.

[Eloston/ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium)

**Comment by Shifterovich** [comment]
https://github.com/privacytoolsIO/privacytools.io/issues/274#issuecomment-315846026
