### ISSUE TITLE
Suggesting additional FF about:config privacy settings

### ISSUE THREAD

**Issue by gryzor2** [privacytoolsIO/privacytools.io#525]
Hi,

I believe firefox users would benefit from having these settings in about:config :

media.peerconnection.dtmf.enabled 	false
https://bugzilla.mozilla.org/show_bug.cgi?id=1313406

https://bugzilla.mozilla.org/show_bug.cgi?id=1430213
media.peerconnection.rtpsourcesapi.enabled 	false

media.peerconnection.simulcast 	false
https://wiki.mozilla.org/Media/WebRTC/ReleaseNotes/46#IMPORTANT:_Simulcast_landed_and_is_pref.27d_on

privacy.trackingprotection.storagerestriction.enabled 	true
https://bugzilla.mozilla.org/show_bug.cgi?id=1461921

Additionally, these three keys do not exist by default and must be created by users :
---------------------------------------------------------------------------------------------------------
security.ssl.disable_session_identifiers 	boolean 	true
https://bugzilla.mozilla.org/show_bug.cgi?id=967977
(SSL session caches are abused by GAFAM, which use them as low level TCP cookies)

toolkit.telemetry.coverage.opt-out 	boolean 	true
https://dustri.org/b/mozilla-is-still-screwing-around-with-privacy-in-firefox.html

extensions.fxmonitor.enabled boolean false
https://www.ghacks.net/2018/08/25/firefox-62-firefox-monitor-system-add-on-integration/

Cheers,

**Comment by Shifterovich** [comment]
@kewde

**Comment by kewde** [comment]
I have a few Q's abot the following ones?

```
media.peerconnection.rtpsourcesapi.enabled
media.peerconnection.simulcast false
```
What's the reasoning for disabling these two?

**Comment by gryzor2** [comment]
Hi kwede,

No big reasoning ; I tend to disable media.peerconnection.* generally.
I confess I have not looked deep.

**Comment by Atavic** [comment]
*media.peerconnection.enabled* is the master switch. I'm not using any live streaming service, so I disable it.

*rtpsourcesapi* is used by WebRTC.

Simulcast appeared [in FF46](https://wiki.mozilla.org/Media/WebRTC/ReleaseNotes/46).

> Simulcast in WebRTC allows sending multiple resolutions/framerates of the same source.
[Here](https://bugzilla.mozilla.org/show_bug.cgi?id=1288904#c30)

**Comment by Atavic** [comment]
media.peerconnection.enabled is the master switch.
I'm not using any live streaming service, so I disable it.

*rtpsourcesapi* is used by WebRTC.

> [Simulcast in WebRTC allows sending multiple resolutions/framerates of the same source](https://bugzilla.mozilla.org/show_bug.cgi?id=1288904#c30).

**Comment by Shifterovich** [comment]
> rtpsourcesapi is used by WebRTC.

Though you can disable WebRTC without disabling rtpsourcesapi, right?

**Comment by Atavic** [comment]
It seems an API used inside WebRTC: 
https://github.com/w3c/webrtc-pc/issues?q=is%3Aissue+is%3Aopen+label%3ASimulcast

**Comment by Atavic** [comment]
It's an API used inside WebRTC, see [here](https://github.com/w3c/webrtc-pc/issues?q=is%3Aissue+is%3Aopen+label%3ASimulcast).

**Comment by kewde** [comment]
I've had some experience with simulcasting, essentially it will tailor the video resolution to your internet connection. Disabling WebRTC (read: PeerConnection) should take care of it as a whole.
