### ISSUE TITLE
Add wölkli to Encrypted Cloud Storage Services

### ISSUE THREAD

**Issue by asdfghjz** [privacytoolsIO/privacytools.io#526]
Feature: Add [wölkli](https://woelkli.com) to [Encrypted Cloud Storage Services](https://www.privacytools.io/#cloud)
I recommend using it instead of Muonium as it supports desktop usage.

**Comment by Avizini** [comment]
wölkli uses Nextcloud.

**Comment by matsest** [comment]
Agreed. It's a good hosted service which offers Nextcloud (maybe this could be a subsection or something under Nextcloud with more of the hosted secure alternatives?). 
Also supports calendar, contact and notes sync in addition to file sync, which makes for a good replacement for Google Calendar/Contacts/Keep. Storage is encrypted and it also offers TOTP 2FA.

**Comment by Vincevrp** [comment]
[Disroot](https://disroot.org/en) also provides this.

**Comment by jospoortvliet** [comment]
There are loads of good (and bad...) Nextcloud providers. Probably best to link to nextcloud.com/signup (easiest) or nextcloud.com/providers (most choice) for people who want one.

**Comment by JonahAragon** [comment]
@jospoortvliet that kind of defeats the point of making provider recommendations on this site in the first place. Either we make a recommendation after researching them ourselves, like Disroot/wölkli, or don't make one at all and just recommend the software itself (which is what I'd lean towards personally).

**Comment by Mikaela** [comment]
Somewhat related to https://github.com/privacytoolsIO/privacytools.io/issues/816 ?

**Comment by JonahAragon** [comment]
We currently recommend Nextcloud which kind of encompasses all these Nextcloud providers.
