### ISSUE TITLE
[Feature Request] Add FireFox Send to File Sharing

### ISSUE THREAD

**Issue by asdfghjz** [privacytoolsIO/privacytools.io#527]
Feature: Add [Firefox Send](https://send.firefox.com/) to File Sharing

**Comment by beerisgood** [comment]
No.
See https://github.com/mozilla/send/issues/897

**Comment by immanuelfodor** [comment]
I suggest reopening this issue, they are no longer using GA, no third-party requests are present:
- Comment from June: https://github.com/mozilla/send/issues/897#issuecomment-497921993
- The `analytics_id` iconfig s no longer used in the code: https://github.com/mozilla/send/search?q=analytics
- A tool to check the online service: https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fsend.firefox.com%2F#requests

> Third-party requests
> No third-party requests.
> A third-party request is a request to a domain that's not firefox.com or one of its subdomains.
> GDPR: Rec. 69, Rec. 70, Art. 5.1.b-c, Art. 25.

**Comment by immanuelfodor** [comment]
Sorry, I've just seen another ticket, Send is already listed: https://www.privacytools.io/classic/#filesharing
