### ISSUE TITLE
Add Privacy Newsletters

### ISSUE THREAD

**Issue by asddsaz** [privacytoolsIO/privacytools.io#532]
I have TONS of tools I use. It is basically impossible to keep up to date with every vulnerability. It would be super cool if we could have a Privacytools.io mailing list for each tool.

**Comment by Shifterovich** [comment]
What do you mean exactly? Be notified when we add a new thing to the website?

We don't report on vulnerabilities, so this wouldn't keep you up to date with every vulnerability.

**Comment by infosec-handbook** [comment]
I think @asddsaz means something like [this](https://www.cvedetails.com/vulnerability-feeds-form.php). Once, infosec-handbook.eu provided such feeds, however, tracking these reports consumes hours. I recommend to use a dedicated service instead of adding some reports here and there.

**Comment by Shifterovich** [comment]
Yeah, there's enough CVE feeds already. @asddsaz Could you elaborate on what you meant?

**Comment by traumschule** [comment]
isn't this what seclists.org is for?

**Comment by asdfghjz** [comment]
@Shifterovich What I meant was like, lets say somebody found a bug for a tool they could go to the mailing list and notify everyone else.

PrivacyTools.io may also have a spam protected list.

Personally, I didn't know of the Firefox Mr. Robot and Spying Scandals until much after it was uncovered.

**Comment by blacklight447-ptio** [comment]
I think this is a bit out of scope, and it seems there are already a lot of other options available right now. closing issue.
