### ISSUE TITLE
DuckDuckGo Privacy Essentials

### ISSUE THREAD

**Issue by rcsilva83** [privacytoolsIO/privacytools.io#535]
This is a simple to use Firefox add-on which seams to replace both Privacy Bagder and HTTPS Everywhere. Do you think it should be recommended?

Link: https://addons.mozilla.org/pt-BR/firefox/addon/duckduckgo-for-firefox/

**Comment by 3j9fkyahunqoxwqu** [comment]
In this article (that may be bisaed because it written by cliqz, the company that bought ghostery) they compared its speed with other content blockers and the results wasn't good enough, although they didn't included https everywhere and other parts of this addon in the measures.
