### ISSUE TITLE
Comma missing in "If you are currently using * you should pick an alternative here"

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#549]
I'm not a native speaker, but it looks weird without the comma before `you`.

**Comment by Aquakor** [comment]
I'm also not a native English speaker, but I agree with you. I think this is a first conditional sentence. If a conditional clause comes before a main clause, we separate them with a comma, [source](https://dictionary.cambridge.org/de/grammatik/britisch-grammatik/conditionals-and-wishes/conditionals). 

I think we should also consider changing the tense of a conditional clause from present continuous to present simple.

**Comment by Shifterovich** [comment]
I don't think the continuous tense necessarily means "using right now". I think it highlights using it actively. `If you currently use Telegram` sounds like "if you use it at all". So in my opinion the continuous tense highlights that you use it actively - there's nothing wrong with using Messenger for some things and Signal for important things.

Though again I'm not a native speaker. We can fix the commas now and the tense possibly in future if we can get more opinions on it.

@Aquakor could you create a PR fixing the commas?

**Comment by Aquakor** [comment]
@Shifterovich yes, I will create it.
