### ISSUE TITLE
Pond messenger website is down -- project in "stasis" mode

### ISSUE THREAD

**Issue by rtlong** [privacytoolsIO/privacytools.io#56]
In the source here, <https://github.com/privacytoolsIO/privacytools.io/blob/master/index.html#L1361>, the link to the Pond project is down. I don't know anything more about the project, but after a search for it, I found this repo <https://github.com/agl/pond> which explains the project is basically abandoned. Perhaps it'd be better to swap Pond and the current Honorable Mention, RetroShare?

**Comment by alexbooker** [comment]
Well spotted mate.

I'll promote "Retroshare" from "Worth Mentioning" to replace Pond.

Thanks :pray:
