### ISSUE TITLE
Remove Tox recommendation

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#566]
This article / blog explains everything;
https://chefkochblog.wordpress.com/2018/04/05/r-i-p-tox-messenger/

**Comment by Shifterovich** [comment]
@beardog108

**Comment by beardog108** [comment]
Yeah, probably worth removing. Tox was good while it lasted and it still holds value as a project but for actual use there are much better options at this point.

**Comment by tya99** [comment]
That blog is is clickbait. While there were some problems with management in the past those issues have been overcome. I get the feeling the author doesn't really know what he is talking about.

To claim something is 'dead' when there is regular commits and development within the community is just plain incorrect.

https://github.com/TokTok/c-toxcore/graphs/code-frequency
https://github.com/qTox/qTox/graphs/code-frequency
https://github.com/zoff99/ToxAndroidRefImpl/graphs/code-frequency

Also:

https://blog.tox.chat/2018/11/toxcon-2018-report/
https://tox.fahrplan.zoff.cc/booklet.html

**Comment by tya99** [comment]
That blog is is clickbait. While there were some problems with management in the past those issues have been overcome. I get the feeling the author doesn't really know what he is talking about.

To claim something is 'dead' when there is regular commits and development within the community is just plain incorrect.

https://github.com/TokTok/c-toxcore/graphs/code-frequency
https://github.com/qTox/qTox/graphs/code-frequency
https://github.com/zoff99/ToxAndroidRefImpl/graphs/code-frequency

Also:

https://blog.tox.chat/2018/11/toxcon-2018-report/
https://tox.fahrplan.zoff.cc/booklet.html

**Comment by tya99** [comment]
After reading through https://github.com/TokTok/c-toxcore/issues/426 in depth I'd say we should keep an eye on this project but not re-add it at this time.

**Tox by no means is dead like the blog author suggests** however. There is an effort to produce a [full specification](https://toktok.ltd/spec.html). Until clients like [qTox](https://qtox.github.io) and uTox begin to use that core I don't think this should be re-added.

**Comment by quantumpacket** [comment]
It's odd that Chefkoch who got banned from Github recently and who is the author of that blog post suddenly has someone open this issue and link to his blog and then delete their Github account. Makes it suspiciously appear like another chefkoch sock puppet account. Take anything he says and does with a grain of salt,  just saying...

**Comment by Shifterovich** [comment]
I didn't notice it's from CK. He got banned from GH? Why?

**Comment by tya99** [comment]
Re https://github.com/privacytoolsIO/privacytools.io/issues/566#issuecomment-438249651

Another option could be to mark it as "experimental". Looking over privacytools.io it seems there are plenty of things mentioned there that have not undergone formal audits.

In terms of quality I also feel that there are far worse things mentioned there which are unmaintained (bitmessage for example). Perhaps we could mark some of these things as **Experimental** as they do on on https://prism-break.org/en/all/#video-voice

**Comment by quantumpacket** [comment]
@Shifterovich https://github.com/ghacksuserjs/ghacks-user.js/issues/323 details the problems with him stealing other people's work and claiming it as his own. This led to him blindly stealing code which just so happened to contain links to kiddie porn which is what finally got him banned. He's not the best person for anyone to be taking advice from.

**Comment by tya99** [comment]
Maybe at this point it would be appropriate to reopen this ticket.

Perhaps should:

1. Revert the change 
2. Wait for the label feature https://github.com/privacytoolsIO/privacytools.io/issues/146
3. Close this ticket with appropriate label

**Comment by tya99** [comment]
@quantumpacket 

I wonder if that Chefkoch had anything to do with these issues seems like the same writing style.

https://github.com/privacytoolsIO/privacytools.io/issues/474
https://github.com/ricochet-im/ricochet/issues/579
https://github.com/nylira/prism-break/issues/1975

Not sure about that one: https://github.com/ricochet-im/ricochet/issues/568

**Comment by tya99** [comment]
@Shifterovich I think we are in agreement https://github.com/privacytoolsIO/privacytools.io/pull/592 should be accepted, would you like to merge?

**Comment by Shifterovich** [comment]
The label feature is implemented for software that's in the top 3. Could you add <span class="badge badge-warning">Experimental</span> before the description of Tox in #592?

**Comment by tya99** [comment]
I was under the impression that it only worked in the panels. Does this look right?

```
diff --git a/index.html b/index.html
index 72ff030..19afbc7 100644
--- a/index.html
+++ b/index.html
@@ -1316,7 +1316,9 @@ layout: default
 <h3>Worth Mentioning</h3>
 <ul>
     <li><a href="https://jitsi.org/">Jitsi</a> - Jitsi is a free and open source multiplatform voice (VoIP), videoconferencing and instant messaging application.</li>
-    <li><a href="https://tox.chat/">Tox</a> - A free and open-source, peer-to-peer, encrypted instant messaging and video calling software.</li>
+    {% include card.html color="warning" labels="danger:Experimental"
+        <li><a href="https://tox.chat/">Tox</a> - A free and open-source, peer-to-peer, encrypted instant messaging and video calling software. </li>
+    %}
     <li><a href="http://www.ring.cx/">Ring (formerly SFLphone)</a> - Gives you a full control over your communications and an unmatched level of privacy.</li>
 </ul>
```

**Comment by Shifterovich** [comment]
Ah, I forgot to escape HTML in my comment.

Use `<span class="badge badge-warning>Experimental</span>`.

**Comment by tya99** [comment]
ah got it, fixed https://github.com/privacytoolsIO/privacytools.io/pull/592/commits/70305215b518bc0bbba4f7158b0f19bea9c094ad
