### ISSUE TITLE
Add systemd notes in PC Os section

### ISSUE THREAD

**Issue by lmaowski** [privacytoolsIO/privacytools.io#567]
Suggestion comes from [this reddit post](https://www.reddit.com/r/privacytoolsIO/comments/9uwgm1/please_mention_the_risk_of_running_systemdbased/). It has good points and worth mentioning systemd in the PC OS section.

**Comment by Vincevrp** [comment]
This might be a bit out of the scope of this project. @Shifterovich what do you think about this?

**Comment by Shifterovich** [comment]
I don't think PTIO is primarily meant for people who can think about the alternatives to systemd. If you want, you can create a PR and we'll see if it seems appropriate, but by just reading that reddit thread, I'm not convinced this is in scope of PTIO.
