### ISSUE TITLE
Firefox: CanvasBlocker, Neat URL, Smart Referer

### ISSUE THREAD

**Issue by atomGit** [privacytoolsIO/privacytools.io#576]
in addition to the currently listed add-ons on privacytools.io, i would suggest the following:

* [CanvasBlocker](https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/)
* [Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/)
* [Neat URL](https://addons.mozilla.org/en-US/firefox/addon/neat-url/)
* [Smart Referer](https://addons.mozilla.org/en-US/firefox/addon/smart-referer/)

**Comment by Vincevrp** [comment]
Relevant: #99 

Cookie AutoDelete is already on the website.

**Comment by BurungHantu1605** [comment]
Added CanvasBlocker now.
