### ISSUE TITLE
suggested Firefox config tutorial

### ISSUE THREAD

**Issue by atomGit** [privacytoolsIO/privacytools.io#577]
it's an ongoing process, but i've written a fairly extensive tutorial for Firefox (and derivatives) regarding privacy and, to a lessor extent, security and performance - you might want to link to it at privacytools.io - it depends heavily on add-ons already suggested by privacytools, including uBO and uM, as well as the ghacks user.js which i think is very important for those looking for an easier solution rather than doing all the research themselves

[Firefox Configuration Guide for Privacy Freaks and Performance Buffs](https://12bytes.org/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs)

**Comment by hugoncosta** [comment]
Very nice work, some add-ons I hadn't seen yet, thanks! @Shifterovich maybe it'd sit nicely on the [Related Information](https://www.privacytools.io/#about_config) subtitle? Also, didn't you have a similar guide on your personal website?

**Comment by Shifterovich** [comment]
> @Shifterovich maybe it'd sit nicely on the Related Information subtitle?

I agree.

**Comment by atomGit** [comment]
fraid i don't know how - and the guide i wrote isn't on GitHub which, from what i quickly read, is necessary to create a PR?

i think i'd rather leave that up to someone who knows what they're doing :)

**Comment by atomGit** [comment]
yes, my FF guide depends heavily on the ghacks user.js - i'm also working on a relaxed version of their js and another guide 'for dummies'

**Comment by hugoncosta** [comment]
No need to be on github, you can just link your page on the related information subtitle under Firefox. I guess the description should make clear your tutorial encompasses some of the info above and more for those that really want to go all out. Hit me up if you need help with it.

**Comment by atomGit** [comment]
@hugoncosta - i see where in the 'related information' you wanted me to add a link, but i don't see any way to do that - the only options i see are through social media, which i don't use, and here, which is why i started this topic

**Comment by hugoncosta** [comment]
Understood, I'll create the PR for you. Any description in particular you'd like? I was thinking something along the lines of

> Extended Firefox Guide - long guide on ways to improve your privacy and security using firefox

**Comment by atomGit** [comment]
let's hold off a bit - i'm making an important change in the guide, plus i should have the 'for dummies' guide finished in a few days - k?

**Comment by atomGit** [comment]
@hugoncosta - finally getting back to you with this, and requesting your help

i have 2 Firefox config guides which you may want to reference/link on privacytools.io - they are...

[Firefox Configuration Guide for Privacy Freaks and Performance Buffs – 12Bytes.org](https://12bytes.org/articles/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs)

and...

[The Firefox Privacy Guide For Dummies! – 12Bytes.org](https://12bytes.org/articles/tech/firefox/the-firefox-privacy-guide-for-dummies)

the former is a more comprehensive version of the latter

both guides are updated fairly often and they are not perfect - that said, i believe they are some of the more comprehensive guides for FF configuration with regard to privacy - both rely heavily on the ghacks user.js and the uBO and uM add-ons

you wanted me to create a PR to include the guides, but i don't know how to do that

also it would also be super-great if someone could review the guides - if they are referenced on privacytools.io, i don't want them to have any serious mistakes in them

**Comment by hugoncosta** [comment]
I'll make the PR then, we'll continue the discussion there :)
