### ISSUE TITLE
WebRTC Section - Recommend add Chromium sans WebRTC

### ISSUE THREAD

**Issue by m0lz** [privacytoolsIO/privacytools.io#58]
Your web page currently reads ..

How to fix the WebRTC Leak in Google Chrome?
There is no known working solution, only a plugin that is easily circumvented. Please use Firefox instead.

Recommend ..

A suggestion to use Chromium builds from http://chromium.woolyss.com/

There are build options for 32 and 64 bit, with / without proprietary codecs and with / without Sync, WebRTC and Widevine

Have a good read of the site, a lot of good information / advice and a recommend for your site too.
It offers Chromium builds without any google additions, and is not a hack like some third parties would offer claiming they have removed Google features ( but then they add their own agenda "features" ).

Its just pure unsullied Chromium Dev builds

**Comment by alexbooker** [comment]
I'll look into this soon, thanks. In the meantime, could you please post to our [subredditt](https://www.reddit.com/r/privacytoolsio) so we can see what the community has to say?

**Comment by m0lz** [comment]
Sorry but I do not participate there, and have no intentions of joining

**Comment by privacytoolsIO** [comment]
I think it's the best for now to recommend Firefox and TBB.

**Comment by Shifterovich** [comment]
Does anyone have experience with [this](https://chrome.google.com/webstore/detail/webrtc-network-limiter/npeicpdbkakmehahjeeohfdhnlpdklia)?

**Comment by Atavic** [comment]
@Shifterovich never seen that addon before. I strongly suggest:

_Chromium Installer • No sync • No WebRTC • No Widevine_ 

With no google API key and less Bugs than Firefox, according to http://cve.mitre.org/

**Comment by Hillside502** [comment]
@Atavic 

> Chromium Installer • No sync • No WebRTC • No Widevine

Does this mean that build does not phone home **at all**?

**Comment by Atavic** [comment]
Yes, you can: https://chromium.woolyss.com/#browser-settings

**Comment by csagan5** [comment]
I have recently started maintaining [Bromite](https://www.bromite.org/), I thought might be relevant; building Chromium without WebRTC seems not working in v63 (current beta of Chrome), but it's on my list and eventually I'll get it out of Bromite (tried to patch webRTC code to not leak network addresses and device UUIDs, but was not trivial).

**Comment by kewde** [comment]
@csagan5 

Bromite, interesting. #338

**Comment by Shifterovich** [comment]
#367
