### ISSUE TITLE
Remove Google+ share button

### ISSUE THREAD

**Issue by Aquakor** [privacytoolsIO/privacytools.io#584]
The button is useless because Google is shutting down the service as stated [here](https://www.blog.google/technology/safety-security/project-strobe/).

**Comment by Shifterovich** [comment]
Rather than removing it, I think we should replace it with something else, to keep the layout of the share buttons the same.

**Comment by beerisgood** [comment]
@Shifterovich maybe Mastadon

**Comment by Shifterovich** [comment]
Yeah, exactly my thought. Seems like it's not there. Though how do we do that with Mastodon, given its federatedness?

**Comment by Booteille** [comment]
@Shifterovich You can find an example of share button on this project: https://github.com/Aly-ve/Mastodon-share-button

**Comment by Shifterovich** [comment]
@Vincevrp
