### ISSUE TITLE
SpyBot AntiBeacon

### ISSUE THREAD

**Issue by m0lz** [privacytoolsIO/privacytools.io#59]
With regards to your section ..

"Don't use Windows 10 - It's a privacy nightmare"

And recommendations for tools to download to assist locking down Privacy issues / settings not so easily accessed by the general public

Recommendation ( From the same people who we have all been trusting for many years who create SpyBot Search and Destroy )

https://www.safer-networking.org/spybot-anti-beacon/

:+1:

**Comment by m0lz** [comment]
Forgot to mention - The support forum topic for the same ..

https://forums.spybot.info/showthread.php?72686-Spybot-Anti-Beacon-for-Windows-10

**Comment by Atavic** [comment]
This tool alone won't work for long. OS updates reset the changes done with it.
