### ISSUE TITLE
Table or mouseover showing instant messenger pro/con

### ISSUE THREAD

**Issue by tya99** [privacytoolsIO/privacytools.io#596]
I think for the instant messenger section we should have a table or a mouse over. Some sort of way to make a comparison so a user can decide what is right for them.

For example Matrix is great for features and interoperability and end to end security but it does come at the cost of having certain metadata for it to function.

Tox is great because it is server less but that comes at the cost of certain features like push notifications (mobile) platforms which in turn translates to battery lifetime on the device, read receipts and other server side messages.

Ricochet is great because it is anonymous, but obviously comes at the cost of group chat and A/V capabilities.

That sort of thing. I have been thinking about this the last few days and I think it would be a good idea if we brainstormed some ways this could be elegantly implemented.

**Comment by Shifterovich** [comment]
![screenshot from 2018-11-17 16-04-13](https://user-images.githubusercontent.com/4354706/48662473-ab933700-ea82-11e8-939f-36f43b1a614d.png)

Or just add another row.

**Comment by Shifterovich** [comment]
> oh my god which one do I pick

The one that matches your needs. The labels can be used to describe which one is good for what.

**Comment by tya99** [comment]
> The one that matches your needs. The labels can be used to describe which one is good for what.

My comment was more how a user who doesn't really know much about the topic of privacy might react. This is why in the past I've referred people to privacytools.IO and not prism-break. It's usually triggered from a verbal conversation, sometimes online.

When you're hit with a page like https://prism-break.org/en/all/#instant-messaging for example, it isn't immediately obvious which one you should pick or even why, or what is even suitable for your needs. 

I think that it is fair that we handpick a few that we know works well, and have been audited for example [Signal](https://eprint.iacr.org/2016/1013.pdf), [Matrix](https://matrix.org/blog/2016/11/21/matrixs-olm-end-to-end-encryption-security-assessment-released-and-implemented-cross-platform-on-riot-at-last/), [Ricochet](https://ricochet.im/files/ricochet-ncc-audit-2016-01.pdf).

The rest I really believe should be under the "worth mentioning" area. For Tox you could have "no metadata" tag and "person-to-person"

**Comment by Shifterovich** [comment]
Maybe adding

**Pros:**
 - abc
 - def

**Cons:**
 - ghi
 - jkl

to the bottom of each of the top 3 messengers description would work?

### Signal

[...]

**Pros:**
 - very easy to use
 - ...
**Cons:**
 - requires your phone number

### Matrix

[...]

**Pros:**
- very secure
- ...
**Cons:**
- hard to use

(I'm not making claims about either of these messengers, I'm just suggesting how it *could* look.)

**Comment by tya99** [comment]
I think this would be a good way of implementing it.

In regard to matrix being hard to use, I think a better con there would be that metadata needs to exist in order for bridge functionality to exist from: https://matrix.org/~matthew/2016-12-22%20Matrix%20Balancing%20Interop%20and%20Privacy.pdf#page=16

**Comment by tya99** [comment]
Please see https://github.com/privacytoolsIO/privacytools.io/issues/746 I think they are related.

**Comment by JonahAragon** [comment]
We've redone the entire IM/RTC section which hopefully resolves these concerns.
