### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Ticki** [privacytoolsIO/privacytools.io#6]
1. FlashBlock - Stops flash cookies (which is quite a privacy issue).
2. Search engines: DDG, Disconnect Search, Startpage etc.
3. Certificate Patrol - Stops potential MitM attacks.
4. Secure Sanitizer - Prevents malicious software and people from getting deleted browser data.
5. BetterPrivacy - Manages flash cookies from allowed flash content.
6. (?) Google Privacy - Replaces all Google search links with direct links.
7. URLFixer - Handy tool for prevent phising attacks without any external source.
8. (?) Webutation - WOT alternative.

**Comment by alexbooker** [comment]
Hello, @Ticki 

Whilst your suggestions are _very_ much appreciated, GitHub issues are not the preferred channel for them. 

From the [readme](https://github.com/privacytoolsIO/privacytools.io/blob/master/README.md):

> Please do not submit suggestions here on GitHub - this is only for developing the website. Please submit them to our [subreddit](http://www.reddit.com/r/privacytoolsio) instead. Thank you.

**Comment by alexbooker** [comment]
I will close this now //cc @privacytoolsIO

**Comment by privacytoolsIO** [comment]
Ok. I posted it here: https://www.reddit.com/r/privacytoolsIO/comments/3f3jpo/suggestions_received_on_github/

**Comment by Ticki** [comment]
Sorry for that.
