### ISSUE TITLE
The menu doesn't work when being on another page than index

### ISSUE THREAD

**Issue by Booteille** [privacytoolsIO/privacytools.io#608]
**Steps to reproduce:**
1. Go to [Donation page](https://www.privacytools.io/donate.html)
2. On the menu, click on Provider then on Privacy Email.
3. Nothing happens.

This is because we just use an anchor without specifying the page or the anchor in the menu.
We should so replace all entries like this one `<a class="dropdown-item" href="#ukusa">Avoid all US and UK based services</a>` to something like `<a class="dropdown-item" href="index.html#ukusa">Avoid all US and UK based services</a>`.

**Comment by Shifterovich** [comment]
I'll add an index.html prefix to those links if the user is on the donate page.

**Comment by Shifterovich** [comment]
https://github.com/privacytoolsIO/privacytools.io/commit/6f9bad7191637b5be96dae07d225dcacc3fb1966
