### ISSUE TITLE
Mobile responsivity broken again

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#610]
Some sections are wider than 100% of the screen width.

**Comment by Vincevrp** [comment]
I can't reproduce this. Could you add a screenshot?

**Comment by Shifterovich** [comment]
![screenshot from 2018-12-21 12-45-58](https://user-images.githubusercontent.com/4354706/50341249-731dc780-051e-11e9-9b3c-1715bf45a9f4.png)
![Uploading Screenshot from 2018-12-21 12-45-44.png…]()
