### ISSUE TITLE
Fix webrtc.html

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#611]

**Comment by Shifterovich** [comment]
https://github.com/privacytoolsIO/privacytools.io/commit/1ca549dae07b4930cf82208142ea852e162fb85b#comments

Still needs fixing.

**Comment by Vincevrp** [comment]
Why don't we replace it with [ipleak.net](https://ipleak.net)?

**Comment by Shifterovich** [comment]
I agree that there's really no need to host this specific test ourselves. We already link to tons of other websites. And ipleak.net is a great choice as it checks all sorts of leaks.
