### ISSUE TITLE
Split website into pages with clear, actionable information.

### ISSUE THREAD

**Issue by nikhiljha** [privacytoolsIO/privacytools.io#624]
### Problem Description

This is the current organization of the site.

<img width="624" alt="screen shot 2018-11-25 at 12 45 54 pm" src="https://user-images.githubusercontent.com/2773700/48984406-0db9f080-f0b0-11e8-9df3-499315116dd2.png">

To me, the current organization feels too bloated to have on a single page. When I link it to someone, I get hit with  "uhhhh, that's a lot of information." People not familiar with the website are just inundated with so many links and references that very few of them will actually do anything about the suggestions on the site.

There are also [much cleaner websites](https://prism-break.org/en/) with alternatives to popular sites already listed.

### Suggestion

1. Keep the "Why it Matters" section as the front page.
2. Move the alternatives to popular services to a separate page.
3. Create a page with some actionable steps for how to make your digital life more private.

The plan can go something like.
1. Get off Gmail/Hotmail/Yahoo. Email controls every other service you will use, so it is important to keep it secure. (link to alternatives/comparison table goes here)
2. If possible, delete social media accounts by following these guides. (link to that website that tells you how to delete accounts) Be sure to download your data from them first under GDPR!
(and so on)

**Comment by Shifterovich** [comment]
I'd keep it single-page, but some sections (and especially the navbar) need reorderinig/refactor.

**Comment by Vincevrp** [comment]
> I'd keep it single-page, but some sections (and especially the navbar) need reorderinig/refactor. For example all the "theory", like 14 eyes and KDL should be a separate category in the nav.

#145

**Comment by JonahAragon** [comment]
@Shifterovich Any reasons in particular to still keep it single page? There's a *lot* of content, and nobody is going to scroll through the entire site realistically. Splitting the site into 4 sub-pages, `Provider`, `Browser`, `Software`, and `OS`, and keeping the intro to privacy and participation links on the homepage, and some more links to each of the pages seems like it'd be a more user-friendly layout. Not to mention a performance boost:

[![image](https://user-images.githubusercontent.com/3637842/55299192-7404a600-53f7-11e9-93d1-1839332ee73f.png)](https://gtmetrix.com/reports/www.privacytools.io/4JImndTA)

**Comment by Shifterovich** [comment]
Sounds good to me.
