### ISSUE TITLE
[Question] Do Key Disclosure Laws Apply in Iceland?

### ISSUE THREAD

**Issue by gjhklfdsa** [privacytoolsIO/privacytools.io#626]
**Question**: Do key disclosure laws apply in Iceland? Are there any key disclosure laws in Iceland?

**Comment by Shifterovich** [comment]
Most data in the table is taken from Wikipedia. If you can't find anything on Google then they probably don't apply.

**Comment by gjhklfdsa** [comment]
@Shifterovich It is sort of weird for it not to be listed though. There are many more countries than the 19 listed. If I understand correctly, these countries also don't have any specific law regarding this:
- Greece 
- Argentina
- Spain
- Slovenia
- Romania
- Switzerland
- Netherlands
- Hungary
None of these are listed.

**Comment by dngray** [comment]
https://en.wikipedia.org/wiki/Key_disclosure_law#Iceland
