### ISSUE TITLE
CanaryWatch no longer maintained

### ISSUE THREAD

**Issue by xdtnguyenx** [privacytoolsIO/privacytools.io#64]
This isn't really a big issue. I remember seeing a post it a while back but CanaryWatch was no longer maintained. You can check the links below:

https://canarywatch.org
https://www.eff.org/deeplinks/2016/05/canary-watch-one-year-later

Maybe we can either put a "Note: No Longer Maintained" or either remove it; it would not be that useful anymore because the last updated canary dates are in May/June.

**Comment by privacytoolsIO** [comment]
Thanks. I've removed it from the website.

**Comment by alexbooker** [comment]
Thank you 🙏
