### ISSUE TITLE
Lack of Education Makes Your Device More Vulnerable - Not Rooting!

### ISSUE THREAD

**Issue by 0pLuS0** [privacytoolsIO/privacytools.io#640]
I wish the Geek Community who knows better would step forward and speak out against these So Called Geeks that keeping spinning stupidity to the world, seriously!

Telling people that rooting makes you more vulnerable is wrong! 

A lack of skills/education and experience is what makes you vulnerable not root!

```Education is the best weapon!```

What this is, is just taking the easy way out, telling people this, instead of telling them the truth! And the truth is, that if you care, you better edcuate yourself, or seek out a Geek Tech to do the job for you!

It's not helping anyone by keeping people ignorant and making them feel safe, when all this is, is just a False Sense of Security!

Keep your device non Rooted and you will be safe? Really that's the truth here? It's complete and utter rubbish!

As a Unix Geek I've run Windows 20 years and Windows always has Root/Admin access, and I've never had once in 20 years any malware or hack problems ever! Why? Because I'm educated and I know how to use the system without problems! Windows with Admin access or Android, there's no difference! In fact Android is safer because it's a Unix/Linux based system over Windows, and then the Geeks don't even take the time to explain that to the Newbies, all we still see is, Root makes you Vulnerable!

Root doesn't make you less safe or vulnerable, stupidity does!

This is like saying Motorcycles and Guns are Dangerous! They are dangerous in the wong hands!

Let's get real people!

I'm not trying to be a Troll here, I'm a Geek and I hate the stupidity being spread is all, and I hope privacytools.io will stop spreading it and get real here and spread truth instead!

The truth is, by doing this, you are only doing a disservice to people, someone can root their devices and hide it from these Newbies and then control their devices at the root level!

Then you tell them to put some stupid Firewall like NetGuard you promote that doesn't give root access and guess what we have? A half baked application that can't fully protect the system at the root level where the problems will come from!

This is just extreme stupidity going on, if you want to be safe, then the only safe is educating yourself, or getting someone to do the job for you! You need to have FULL CONTROL of the device, so someone else doesn't take FULL CONTROL! It's just that simple!

Without root, you have no control! If you have no control, then someone can take it from you!

There are also bad companies out there doing Analytics/Data Mining on people, also backdoors have been a worry too for years! All of these things happen at the ROOT/KERNEL level!

I have a device by a company with a known history of these problems of Analytics/Data Mining, and possible back doors, but because they are in China, they continue to get away with it!

I know for a fact, because I have spent a lot of time researching this with this company, to also know they have placed Analytics/Data Mining applications in the device, as well as at the Kernel Level!

I have seen more times then I care to remember, using AFWall+ Firewall as example, seeing all these applications and the kernel trying to Phone Home and Spy and Leak Data, to tell you, it's a FACT!

No Root and a half baked firewall that only protects you at the USER Level is no real protection!

So, instead of pasting nonsense like this on your site;

```The following add-ons require root access, which makes your device more vulnerable. Proceed with caution.```

Why don't you start SPREADING TRUTH and help people to Educate themselves about root!

```ROOT DOES NOT MAKE YOU VULNERABLE IGNORANCE DOES! BY BEING IGNORANT SOMEONE CAN ROOT YOUR DEVICE AND TAKE CONTROL FROM YOU!```

```EDUCATION IS THE ONLY WEAPON!```

**Comment by Shifterovich** [comment]
> ROOT DOES NOT MAKE YOU VULNERABLE

If you install an apk, there's only so much a virus can do. With root, there's __a lot__ that it can do.

> This is like saying Motorcycles and Guns are Dangerous! They are dangerous in the wong hands!

I ride a motorcycle. And I think it would be very arrogant to think that if a car turns left in front of me, or blows through stop sign, there's anything I can do about it. "Wrong hands" -- good hands don't give you protection when hit by a car. Good hands can brake only so quickly without blocking a tire and falling when a car turns left in front of them.

If you want to ride a motorcycle or root your phone, there's nothing wrong with that. But I'm not going to recommend anyone to make themselves more vulnerable. This website is not meant for ex-Navy Seals like you:

> [As a Unix Geek I've run Windows 20 years and Windows always has Root/Admin access, and I've never had once in 20 years any malware or hack problems ever! Why? Because I'm educated and I know how to use the system without problems!](https://knowyourmeme.com/memes/navy-seal-copypasta)

but rather for not-programmer-level-technical people looking to enhance their privacy.

> This is just extreme stupidity going on, if you want to be safe, then the only safe is educating yourself, or getting someone to do the job for you! You need to have FULL CONTROL of the device, so someone else doesn't take FULL CONTROL! It's just that simple!
> 
> Without root, you have no control! If you have no control, then someone can take it from you!

It's quite delusional to think that you have __full__ control even when you root your own mobile. If you want full control, write your own software (including OS) and run it on hardware you made yourself.

This is just really absurd:

> Without root, you have no control! If you have no control, then someone can take it from you!

The same can be said about any form of protection. That's like saying

> With [ESP](https://en.wikipedia.org/wiki/Electronic_stability_control), you have no control! If you have no control, then someone can take it from you!

(not to mention that the other sentence makes no sense)

**Comment by 0pLuS0** [comment]
Great to of closed the post, NOT!

To truthful again, any website that is promoting Privacy/Security like this, should not make assumptions about any level of the user like saying Navy Seal as you did.

But Educate and Help people, that's the right thing to do with just a LITTLE INFORMATION is all anyone is asking, but did you do even this? hmm

Anyhow the post should be left open in the interest of helping people so they can read and learn, because No Issue has been resolved until privacytools.io does a better job of helping to educate.

**Comment by infosec-handbook** [comment]
@0pLuS0 
What about starting your own "geek" blog to educate people providing fact-based articles instead of writing lots of opinion-based sentences which end with exclamation marks (41, to be exact). This shouldn't be a problem for a Windows/Unix elite root user with 20+ years of malware-free experience.

Besides, telling people to just root their phone to be in full control of their device isn't about security as you already wrote before:

>rooting isn't making you more or less secure

On the one hand you get more (not all, e.g. dozens of other chips/firmware in the phone remain out of control) possibilities to modify things, on the other hand you open a large attack surface as you wrote, too. 

So, what's your point here?
