### ISSUE TITLE
🌐 Website Issue | EarthVPN

### ISSUE THREAD

**Issue by Ud4ba** [privacytoolsIO/privacytools.io#654]
Hello there :) Good job for your work really apreciate . :) 
A friend of me reported this . https://www.reddit.com/r/privacytoolsIO/comments/a1melf/please_correct_your_webpage_about_earthvpncom/
You should check this . I dont believe a VPN with Turkey's laws is ok... Please change the country .. Thank you :)

**Comment by Shifterovich** [comment]
Is it part of Cyprus or Turkey, in terms of laws?

> Northern Cyprus is considered by the international community to be part of the Republic of Cyprus.

**Comment by Atavic** [comment]
It's Turkish Republic of Northern Cyprus, it's constitution say: the Turkish Cypriot People.
While on Southern Cyprus there's a UK Royal Air Force base: Akrotiri
The island is geopolitically hot, maybe using a VPN based there is not the best solution.

**Comment by Shifterovich** [comment]
> Im 99% certain , the laws there controlled by Turkey.

They are internationally recognized as Cyprus, but recognized by Turkey and themselves as Turkey, so I guess they use Turkish legislation.

> The island is geopolitically hot, maybe using a VPN based there is not the best solution.

I agree.

Can you open a PR @Ud4ba?

**Comment by Ud4ba** [comment]
> 
> 
> > Im 99% certain , the laws there controlled by Turkey.
> 
> They are internationally recognized as Cyprus, but recognized by Turkey and themselves as Turkey, so I guess they use Turkish legislation.
> 
> > The island is geopolitically hot, maybe using a VPN based there is not the best solution.
> 
> I agree.
> 
> Can you open a PR @Ud4ba?
Im kind new here , whats a PR ?

Erdogan is kinda of a dictator in my opionin .. Sadly i live in greece and things arent going so well. Anyway Turkey is for sure anti-privacy country ..

**Comment by Atavic** [comment]
Pull Request, it's explained in the Help section on bottom page, clikc then look for
*Fork a repo* on the left.

**Comment by Atavic** [comment]
*Pull Request*, it's explained in the Help section on bottom page, click then look for
*Fork a repo* on the left.

**Comment by hasanalizxc** [comment]
> 
> 
> > Can you open a PR @Ud4ba?
> 
> Im kind new here , whats a PR ?
> 
> Erdogan is kinda of a dictator in my opionin .. Sadly i live in greece and things arent going so well. Anyway Turkey is for sure anti-privacy country ..

This place is NOT suitable for politics things. For this reason do NOT comment about Erdogan or another president.

Let's talk about EarthVPN. My opinion it is not trusted because of Turkey and Cyprus laws.

Do NOT trust any VPN provider. Make your own Server and make it's logs /dev/null

**Comment by Shifterovich** [comment]
> Make your own Server and make it's logs /dev/null

Sometimes, good idea. Most of the time, terrible idea.

> My opinion it is not trusted because of Turkey and Cyprus laws.

Like I said:

> They are internationally recognized as Cyprus, but recognized by Turkey and themselves as Turkey, so I guess they use Turkish legislation.

So unless someone can give us a good reason to keep it, let's remove it.

**Comment by pahakalle** [comment]
We should probably redo the entire list from sources like https://torrentfreak.com/vpn-services-keep-anonymous-2018/ and others

**Comment by Shifterovich** [comment]
> from sources like https://torrentfreak.com

Why would we change the list that we handpicked to providers from some list on a commercial website?

**Comment by pahakalle** [comment]
@Shifterovich Yeah not the best link for a source, but they still have a good list of secure and good vpn providers with relatively detailed info on them. 
I would never only rely on that one source alone so of course we would need to research each one from different sources.

**Comment by Shifterovich** [comment]
> they still have a good list of secure and good vpn providers

I only went through half of the page:

![screenshot from 2018-12-18 18-38-28](https://user-images.githubusercontent.com/4354706/50172128-99f8b580-02f4-11e9-8d78-f428e6b33add.png)
![screenshot from 2018-12-18 18-38-46](https://user-images.githubusercontent.com/4354706/50172130-9cf3a600-02f4-11e9-8e26-6cdb95033c8c.png)
![screenshot from 2018-12-18 18-39-13](https://user-images.githubusercontent.com/4354706/50172134-9e24d300-02f4-11e9-85f7-964be6977681.png)
![screenshot from 2018-12-18 18-40-13](https://user-images.githubusercontent.com/4354706/50172137-9fee9680-02f4-11e9-8a29-ca110efc4527.png)
![screenshot from 2018-12-18 18-40-27](https://user-images.githubusercontent.com/4354706/50172138-a0872d00-02f4-11e9-876e-ea626a40cefd.png)

**Comment by pahakalle** [comment]
<img width="364" alt="screenshot 52" src="https://user-images.githubusercontent.com/1533244/50173302-acc4b780-02ff-11e9-9f85-c51aa9fd007f.png">
