### ISSUE TITLE
NordVPN is really trusted?

### ISSUE THREAD

**Issue by hasanalizxc** [privacytoolsIO/privacytools.io#664]
Hi All,

Hope you are fine. I was searching information about Nord VPN and found these links.

https://www.reddit.com/r/VPNTorrents/comments/9adi37/i_investigated_the_nordvpn_ordeal_here_is_what_i/
https://nordvpnsucks.blogspot.com/

Please look every link in reddit webpage.

I am confused now it is really secure?

Could you please share your opinions about this issue?

Thanks in advance.

Have a happy life with your loved ones.

**Comment by Shifterovich** [comment]
Is this another "x owned by Tesonet" thread?

This might be relevant: https://www.reddit.com/r/ProtonVPN/comments/8ww4h2/protonvpn_and_tesonet/e21tfqw/

**Comment by dearlygparted** [comment]
Under "Related VPN information" there is a link labeled "Don't use LT2P IPSec, use other protocols." which leads to this gist: https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa

On that gist, they list NordVPN among VPNs to avoid saying: 

"Again I strongly do not recommend using any of these providers."

The fact that PrivacyTools recommends NordVPN while simultaneously linking to a website that recommends against it, detracts from the credibility of the website. 

Please remedy this incongruity post haste!

**Comment by Shifterovich** [comment]
That gist makes two points:
1. Don't use LT2P IPsec
2. Providers that support it are not recommended by Kenn White.

We agree with the first point. The second point can be interpreted as either "don't use these providers" or as "these providers are not recommended but are not advised against either".

And it's Kenn White's subjective opinion.

I don't see how Nord supporting a somewhat insecure protocol breaks the security of Nord's OpenVPN.

**Comment by dearlygparted** [comment]
> The second point can be interpreted as either "don't use these providers" or as "these providers are not recommended but are not advised against either".

"Yes, I know. Many/most of these offer OpenVPN, or special clients for IPSec. But for all of the above, they are actively placing a significant portion of their user base (particularly those with older Androids and desktops) at risk by not using per-user PSKs."

Basically since NordVPN (et al.) "actively" places "a significant portion of their user base at risk" it makes them less trustworthy. Do you disagree with that logic?

**Comment by blacklight447-ptio** [comment]
i did some digging of my own: the conclusion i draw is that nordvpn seems to be fine, they just have too much marketing for my liking, but a marketing campaign is normally not really a reason to make a provider untrusted, so i am closing this issue, if anyone disagrees, feel free to comment below to continue the discussion, and i will open it up again.

**Comment by erciccione** [comment]
I tested NordVPN a couple of years ago, but i abandoned it once found out that was having DNS leaks. I don't know if that's still an issue btw.
