### ISSUE TITLE
OmniROM recommendation and description

### ISSUE THREAD

**Issue by crasm** [privacytoolsIO/privacytools.io#67]
Relevant bits:

> OmniROM was created in response to the perceived commercialization of CyanogenMod. The directors of Cyanogen Inc. refuse to make signature spoofing a default feature of Cyanogen OS, making it harder to stay anonymous, and in particular to hide your identity from Google. OmniROM has signature spoofing enabled as a default feature.

I think this information is unnecessary for the tagline. The [OmniROM About page](https://omnirom.org/about/) and their [first blog post](https://omnirom.org/general/an-exciting-beginning/) don't mention it at all:

> Secondly, we love CM and immensely respect the entire team there and their contributions to the community at-large. It’s a great product, and if they can get 300 million users, that would be amazing for everyone. We are conscious of people who think we’re scavenging disgruntled developers from other projects. This is not our goal. We have positioned Omni as being about the community, and we will not abide bashing of other custom ROM projects. We will do our best to find common ground in the spirit of collaboration and cooperation.

With that said, I'm not sure how to summarize what differentiates OmniROM with a single sentence. Customizability seems to be a major goal?

**Comment by privacytoolsIO** [comment]
Sorry, I don't get it. What do you want to have changed exactly?

**Comment by crasm** [comment]
I'd like to update the OmniROM description so that it's less opinionated. Primarily, I don't think the mention of signature spoofing is relevant, especially considering that [CopperheadOS doesn't provide the feature either](https://github.com/copperhead/bugtracker/issues/213#issuecomment-217594292). Also, the contrast with CM may not be appropriate for a non-enthusiast audience—even if that is was the reason for the fork.

I'm not familiar with OmniROM (product or users), which is why I wanted to ask the community before proposing changes.

**Comment by privacytoolsIO** [comment]
done! thanks for your feedback.
