### ISSUE TITLE
Turn the account into an organization

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#681]
@privacytoolsIO Can you turn the account into an organisation? It would be extremely helpful, because it would let me and @Vincevrp set up CI and things like that.

I already asked in #95, but now it would be very helpful. 

https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by hasanalizxc** [comment]
As i know if you turn the account into an organisation, it can be with paid, right?

**Comment by Shifterovich** [comment]
I don't think the documentation mentions it. https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by hasanalizxc** [comment]
I didn't look the main page :) It looks good
