### ISSUE TITLE
💬 Discussion | Experimental mesh/mixnets? (Yggdrasil & Cjdns/Hyperboria)

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#685]
I am not sure if this is the correct category, but I thought I would at least bring them to attention of this issue tracker. (This is also the last issue I am going to open for now, sorry about the "spam" :smile:.)

The website includes [Self-contained networks](https://www.privacytools.io/#darknets) and I wonder if Cjdns and Yggdrasil would be within scope. They wish to eventually replace the internet, but currently most of people are just linking (peering) over the internet to form a self-contained network. I think they are both currently considered as more or less experimental.

I am personally using them to access devices I have behind NAT or that have static IP as it's faster than Tor, supports UDP, everything is end-to-end encrypted, everything supporting IPv6 should be supported and the addresses are stable based on node keys.

Considering that this repository is about privacy tools, it's probably important to mention that neither attempts to be anonymous, your direct peers will know your clearnet address (even if Yggdrasil currently supports Tor/I2P (socks) peers, there is talk about removing that when they are stable).

The main difference between the two projects is their routing method, Cjdns requires supernodes being a bit more centralised and in my opinion disconnects more frequently, but Yggdrasil is newer and smaller (at the time of writing there are 109 nodes online).

* * * * *

URLs:

* Yggdrasil-network: https://yggdrasil-network.github.io/
* Cjdns README: https://github.com/cjdelisle/cjdns/blob/master/README.md
    * Sorry, this is the best resource I can link to. They also don't offer any prebuild packages that I know of.
* Hyperboria: https://hyperboria.net/
    * Sorry again, I forgot to explain this, the biggest network formed by Cjdns users is called as Hyperboria.

* * * * *

**EDIT/Disclaimer?:** I looked at the interactive Yggdrasil map (only within Yggdrasil http://y.yakamo.org:3000/ has the link) and having 8 nodes under my name, two of them public peers (+ 3 I am root on), I should probably mention that. I don't consider myself as an important figure or anything though, but I am activeish chatter there. I was originally attracted there by prebuild packages and a Debian repository they run and simpler config syntax.

**Comment by Shifterovich** [comment]
> They wish to eventually replace the internet, but currently most of people are just linking (peering) over the internet to form a self-contained network. I think they are both currently considered as more or less experimental.

What are the benefits of using such networks at this point (when they run over the internet)?

I2P and Tor are both anonymous (I prefer I2P because I like the idea of self-contained networks and for Tor it seems like hidden services are its secondary use at this moment -- with the primary being clearnet anonymity). Since the networks you mentioned aren't anonymous, what are the practical uses in terms of privacy?

**Comment by Mikaela** [comment]
> What are the benefits of using such networks at this point (when they run over the internet)?

They can provide static addressing and connectivity to devices behind carrier grade NAT (I have two locations behind CGN and one NAT VPS that I am accessing over them), like Tor hidden services or I2P eepsites. The main benefits over Tor (and possibly I2P, I don't know if it supports UDP?) are speed and UDP support (e.g. [mosh](https://mosh.org/) doesn't work over Tor), while there is the tradeoff of anonymity. They are also end-to-end encrypted even if http or plaintext IRC was used within.

I think they can be called as public intranet VPNs, as you can install a node anywhere, connect to some public peers and then you can reach everything inside.

Sorry about the bad formatting.

**Comment by Mikaela** [comment]
> In what way is it a privacy tool?

I think that wau would mainly be the end to end encryption also encrypting unencrypted traffic such as http, plaintext IRC or telnet within the network.

I could also ask in what way is IPFS a privacy tool considering how it leaks all IP addresses the system has, doesn't support Tor or I2P, everything there is public (or unlisted until detected by https://ipfs-search.com/ (which picks it up from DHT even if the file is never linked anywhere if I have understood correctly)) and it's still listed on the website as worth mentioning, even if it does link to an important privacy notice (https://github.com/privacytoolsIO/privacytools.io/pull/361#issuecomment-344414022 which doesn't mention the file publicity though)?

**Comment by Mikaela** [comment]
I think I am closing this as out of scope. Now at least the search for these software will bring this issue up in case anyone will think about it in the future and the problems of IPFS would probably require a separate issue that I don't have interest opening.
