### ISSUE TITLE
🌐 Website Issue | There's no need for "browser.send_pings = false" for it's already the default setting

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#686]
## Description
Default elsewhere & Firefox nightlies since 2008-02-01. from http://kb.mozillazine.org/Browser.send_pings

**Comment by beerisgood** [comment]
It's still in gHacks user.js: https://github.com/ghacksuserjs/ghacks-user.js/issues/242#issuecomment-350264816

@Thorin-Oakenpants

**Comment by Atavic** [comment]
And it's in pyllyukko's repo. I looked into installed firefox and forks via about:config and issuer is right. Default value is False.

BTW, do not ever trust kb.mozillazine as it appears semi-abandoned (look the last update on bottom page), use searchfox.org instead:

https://searchfox.org/mozilla-central/search?q=browser.send_pings&case=true&path=

**Comment by Mikaela** [comment]
It appears to be becoming true by default https://www.bleepingcomputer.com/news/software/mozilla-firefox-to-enable-hyperlink-ping-tracking-by-default/ .

Yay me for having to open https://github.com/privacytoolsIO/privacytools.io/pull/876 after having fixed this issue only four days ago.
