### ISSUE TITLE
Add a YouTube/video section

### ISSUE THREAD

**Issue by ADepic** [privacytoolsIO/privacytools.io#693]
Alternatives
* Invidio.us
* Newpipe
* Peertube

**Comment by ADepic** [comment]
created pull request https://github.com/privacytoolsIO/privacytools.io/pull/694 . 
The pull request is far from finished however

**Comment by asddsaz** [comment]
Look into PR #671

**Comment by blacklight447-ptio** [comment]
updates on this issue?

**Comment by Mikaela** [comment]
Stuck on https://github.com/privacytoolsIO/privacytools.io/pull/1150 I guess

**Comment by blacklight447-ptio** [comment]
As #1252 has replaced this issuew, I will be closing this.
