### ISSUE TITLE
🆕 Software Suggestion | Consider adding LibreFox

### ISSUE THREAD

**Issue by c0rdis** [privacytoolsIO/privacytools.io#698]
Hi,
we already have FF tweaks under https://www.privacytools.io/#about_config. I propose to consider and add there recently released Librefox. Another option might be including it directly to "Browser recommendation" at https://www.privacytools.io/#browser. 

## Basic Information

**Name:** Librefox
**Category:** Tweaked Firefox for enhanced privacy
**URL to the project:** https://github.com/intika/Librefox
**Description URL:** https://www.ghacks.net/2018/12/24/librefox-firefox-with-privacy-enhancements/

## Description
The development team removed some components from Firefox; the updater, crashreported, and integrated add-ons that "don't respect privacy" were removed from the browser. Connections that Firefox makes by default have been removed by and large as well. Librefox comes without add-ons; several extensions have been created for LibreFox and several more are recommended by the team for installation. The recommended add-ons have been code reviewed.

The Librefox extensions add a dark theme, HTTP Watcher, and Reload button to Firefox. Recommended third-party extensions include uBlock Origin, Cookie Master, First Party Isolation (toggle), User Agent Platform Spoofer, and Browser Plugs Privacy Firefox. Links and some configuration suggestions are listed on the project website.

There is also a Extensions Firewall but it is disabled by default as it is considered experimental at this point in time. It is designed to manage add-ons globally and allow or disallow extension connections.

**Comment by beerisgood** [comment]
LibreFox isn't a own browser. It's just normal Firefox with some tweaks and not every stuff is recommend

**Comment by Kcchouette** [comment]
it's related to #375 so let's close this issue as duplicate

**Comment by c0rdis** [comment]
@beerisgood you're right. The point here is to review their current and planned tweaks (it's a huge and open-source work by them too btw) and to refer it somewhere, as I see it as a nice enhanced solution "off the shelf" without a tedious procedure of manually changing it, which could be hard for less experienced users. Moreover, I believe it could be quite beneficial to collaborate with them and propose certain changes to their project if we see that certain setting is incorrect or missing. 

@Kcchouette I wouldn't close it as duplicate neither even related as it's not a FF fork - as stated, 

> "This project aims at enforcing privacy and security of Firefox without forking the project."

I believe by providing Librefox we're greatly helping users rather than separately recommending FF and then proposing them to go through large sections of manual tweaking and adding necessary add-ons. 

P.S. I'm not proposing to remove those sections, at least for now.
P.P.S. Would be also good to check if our recommended setting is complete against what's presented by Librefox:

> Librefox uses more than 500 privacy/security/performance settings, patches, Librefox-Addons (optional) and a cleaned bundle of Firefox (updater, crashreporter and Firefox's integrated addons that don't respect privacy are removed).

**Comment by c0rdis** [comment]
Closing for now, @intika please let us know when you believe the project is mature enough, so we re-open this one. Also, feel free to suggest any FF tweaks and any other relevant material to privacytools directly :) Good luck with LF!

**Comment by intika** [comment]
Thank you very much, i will do for sure :), and will make my best to come with a version to please everyone :)
