### ISSUE TITLE
💬 Discussion | Add LibreJS Compliance be added to Software Criteria | Software Criteria

### ISSUE THREAD

**Issue by asddsaz** [privacytoolsIO/privacytools.io#708]
**Discussion**: Should all software listed also be LibreJS compliant?
**LibreJS**: https://www.wikipedia.org/wiki/GNU_LibreJS
**Software Criteria**: https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md#software-criteria

PR: #709

**Comment by Kcchouette** [comment]
I think you should be careful with that. Eg protonmail is JS-oriented plateform, and not LibreJS compliant (https://github.com/ProtonMail/WebClient/issues/37)

**Comment by vecna13** [comment]
I would like to see LibreJS compliance as an ideal criterion, even if there are exceptions. I think it would be worth at least having an indicator as to whether or not given software is LibreJS compliant.

**Comment by blacklight447-ptio** [comment]
After some talk, we have decided that librejs compliance is a nice to have rather then a requirement. this is because we currently also don't require all software to be open source as well, we only have a big preference of it.
