### ISSUE TITLE
🆕 Software Suggestion | Syncthing-Fork - Wrapper for Syncthing on Android

### ISSUE THREAD

**Issue by Catfriend1** [privacytoolsIO/privacytools.io#713]
## Basic Information

**Name:** Syncthing-Fork
**Category:** Tools
**URL:** https://play.google.com/store/apps/details?id=com.github.catfriend1.syncthingandroid

## Description
Hi,
I'd like to suggest mentioning Syncthing-Fork (for Android) beside Syncthing as this is an additional platform where Syncthing can be used. It's available on both F-Droid and G-Play:
https://f-droid.org/de/packages/com.github.catfriend1.syncthingandroid/
https://play.google.com/store/apps/details?id=com.github.catfriend1.syncthingandroid

**Comment by beerisgood** [comment]
I don't understand why this dev doesn't help the original project.

**Comment by Catfriend1** [comment]
Long story short: Because that was the case with the original developer, he's given that project to the syncthing core team. Helped out for a while by filing pull requests and now continuing on my repo as the original has zero other people coding for it atm.

**Comment by blacklight447-ptio** [comment]
@catfriend1 do you mean syncthing's development has been halted?

**Comment by beerisgood** [comment]
@blacklight447-ptio don't think so cause both Android and desktop build is maintained

**Comment by Catfriend1** [comment]
Well not to Sound wrong or being misunderstood: the most syncthing (for Android) development was done by myself during the last year. Official is also alive but does just keep basic Syncthing core functionality available like a "stable" channel. So it's not dead, but the fork is intended to try more features out together as soon as they are developed.
