### ISSUE TITLE
Add VPNArea to the VPN list

### ISSUE THREAD

**Issue by anonsubmitter** [privacytoolsIO/privacytools.io#72]
VPNArea:
- [Is based in Bulgaria](https://vpnarea.com/front/)
- [Uses encryption](https://vpnarea.com/front/)
- [Accepts Bitcoin](https://vpnarea.com/front/member/signup)
- [Supports OpenVPN](https://vpnarea.com/front/home/softwarewin)
- [Has a no logging policy](https://vpnarea.com/front/)

**Comment by anonsubmitter** [comment]
[Apparently VPNArea uses a shared key](https://gist.github.com/kennwhite/1f3bc4d889b02b35d8aa#gistcomment-1930733).

**Comment by privacytoolsIO** [comment]
Any updates on this?

**Comment by Atavic** [comment]
@anonsubmitter gist has been forked: https://gist.github.com/ridgewell/e0b34f49f1ff138e43c7577c60363e4d

```
onevpn / 123456789

Proxy.sh / security

VPNArea / vpnareaworks4u

hide.me  /hide.io

ExpressVPN / 12345678

VyprVPN / thisisourkey
```

@Shifterovich _TYPO:_ it's VPNArea, not VPNArena.

**Comment by NeverDucky** [comment]
Some of the VPN providers we list also use a shared key according to that page. VPNArea meets our current criteria so I think either it should be added or we should re-evaluate our criteria.

**Comment by Shifterovich** [comment]
Shared key isn't the end of the world, maybe we should just warn our visitors about this problem.

**Comment by vpnarea** [comment]
Hello,

We no longer have L2TP, we used OpenVPN and IKEv2 only now.

**Comment by vpnarea** [comment]
Just did, we previewed it in HTML and looks okay, pls let us know if any revision is required.
