### ISSUE TITLE
🌐 Website Issue | DNSSEC support?

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#731]
## Description

Why DNSSEC isn't enabled on privacytools.io?

* [Understanding and configuring DNSSEC in Cloudflare DNS](https://support.cloudflare.com/hc/en-us/articles/360006660072-Understanding-and-Configuring-DNSSEC-in-Cloudflare-DNS)
* [DNSSEC Analyzer - privacytools.io](https://dnssec-debugger.verisignlabs.com/privacytools.io)

**Comment by matsest** [comment]
Sites hosted on GitHub Pages does not support DNSSEC (yet). I received this in November after asking them directly:

> We really appreciate feedback on how we can make GitHub even better, and I can definitely understand the value of DNSSEC for GitHub Pages.
> 
> I can't make any promises as to if or when this might be implemented, but I have added your feedback to our feature request list, and will share it with the team for consideration.

**Comment by Mikaela** [comment]
Privacytools.io is using Cloudflare for DNS and as a reverse proxy, so GitHub pages not supporting DNSSEC doesn't prevent it. I think there are many pages with similar setup without issues, for example [mine (DNSSEC Analyzer link)](https://dnssec-debugger.verisignlabs.com/mikaela.info) which until recently had a similar setup, currently I am only using Cloudflare for www.

Of course GitHub pages not supporting DNSSEC would leave Cloudflare's DNS servers vulnerable to cache poisoning while flattening the CNAME, but I don't think that is too different from the case with Cloudflare as reverse proxy as we cannot know what SSL options privacytools.io is using, is GitHub pages contacted over http, https (invalid certificate accepted) or https (valid certificate required).

**Comment by matsest** [comment]
@Mikaela Oh, I did not know about the setup with using it as a reverse proxy and I'm somewhat confused over GitHub's support pages regarding this, resulting in my correspondence with them. 

From my experience with Github using the "[regular](https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/)" setup for DNS with a apex and subdomain with the CNAME my site [fails in DNSSEC validation](https://dnssec-debugger.verisignlabs.com/www.mxe.no) when it gets to the github.io in the io zone. I see that this is a somewhat different case than for privacytools, so perhaps this could be easily resolved :)

**Comment by Mikaela** [comment]
I don't know what was your original message to GitHub support, but from their response I think they were talking about GitHub pages without custom domain, `<username>.github.io`, but that should fix your issue.

(Sorry if I am not making much sense, I am multitasking.)

**Comment by BurungHantu1605** [comment]
<img width="491" alt="DNSSEC" src="https://user-images.githubusercontent.com/11730911/55275101-15b6c500-531c-11e9-8c8a-604f85ea6ff3.png">

Is this correct now? Thanks for your help, guys.

**Comment by Mikaela** [comment]
Thank you :purple_heart:

**Comment by Mikaela** [comment]
However this may have slowed migrating out of Cloudflare, unless you can find more information on DNS transitioning DNSSEC-signed domains than I did. See https://github.com/privacytoolsIO/privacytools.io/issues/374#issuecomment-476564807 for my experience on Cloudflare -> Gandi.net
