### ISSUE TITLE
✨ Feature Suggestion |  Disposable Email and Email Forwarding Categories

### ISSUE THREAD

**Issue by zero77** [privacytoolsIO/privacytools.io#733]
## Description:
I think it may be a good idea to add two new email categories.
Disposable Email and Email Forwarding, both of which help when you need to give out an email but dont want to use your personal one. 
Forinstance, when creating an account or accessing content like downloads.

**Comment by Atavic** [comment]
For temporary emails, see:

https://gist.github.com/Atavic/38bee9a52537a7c4b187175b675800d8

For email forwarding, I hasn't seen any for years. Do you have any example?

**Comment by zero77** [comment]
@Atavic 
> For temporary emails, see:
https://gist.github.com/Atavic/38bee9a52537a7c4b187175b675800d8

Yes there's lots out there, as there's so many it may be worth finding the ones that are least blacklisted.

> For email forwarding, I hasn't seen any for years. Do you have any example?

I haven't used them for a while but, there are also lots out there, i will post examples when i find the ones i use to use.

**Comment by Vincevrp** [comment]
Relevant: https://github.com/privacytoolsIO/privacytools.io/pull/732#issuecomment-464964634

**Comment by John3** [comment]
Actually I can recommend Guerrilla Mail https://github.com/flashmob/go-guerrilla, I had few issues with 10email in the past and with a few other in tha gist list that was not accepted anywhere so pretty useless.

**Comment by John3** [comment]
About "Email Forwarding" I not sure if is the same think I have in mind right now... But years ago I used and was not really useful. Because It forwarded a lot of spam... It suppose to have filter and only forward good email but not always works.

**Comment by Atavic** [comment]
I remember bigfoot... from many years ago.

**Comment by zero77** [comment]
There is 33mail.com although, i have used much better like forward-email but it requires setup. 
https://github.com/niftylettuce/forward-email

Also:
https://github.com/synox/disposable-mailbox

@John3 
Filters is one good use but, you can also use it at a type of disposable email.
Because, it gets blacklisted less often than standard disposable emails.
Also, it can be easier because it allows you to receive all emails in one place instead of using multiple websites and logins.

**Comment by libBletchley** [comment]
forwarding providers:
spamgourmet.com
trashmail.net

**Comment by blacklight447-ptio** [comment]
spamgourmet is shutting down because of the sickness of the maintainer.
In any case we aim to redo the E-mail section after the overhaul of the browser page is complete, so we will keep this idea in the back of our heads when we start.

**Comment by Zcr34** [comment]
> spamgourmet is shutting down because of the sickness of the maintainer.
> In any case we aim to redo the E-mail section after the overhaul of the browser page is complete, so we will keep this idea in the back of our heads when we start.

SpamGourmet is here to stay! (under new leadership)

- https://bbs.spamgourmet.com/viewtopic.php?f=7&t=1793&sid=efa3c335c83d5328dbc7af3cd34b757b

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
E-mail forwarders that are open source:
https://www.anonaddy.com
https://www.simplelogin.io
https://www.ptorx.com
https://www.forwardemail.net
https://www.erine.mail
