### ISSUE TITLE
🆕 Software Suggestion | Manyverse

### ISSUE THREAD

**Issue by Atavic** [privacytoolsIO/privacytools.io#739]
## Basic Information

**Name:Manyverse**
**Category:Social network for Android**
**URL:https://manyver.se**

## Description

A social network off the grid, See the [repo](https://gitlab.com/staltz/manyverse).

It uses the [Secure ScuttleButt](https://www.scuttlebutt.nz/) [protocol](https://ssbc.github.io/scuttlebutt-protocol-guide/).

**Currently in Beta**

**Comment by TNTBOMBOM** [comment]
so it will shift data and the protocol ? like freenet or zeronet ? because that gives security concerns about that.

**Comment by danarel** [comment]
Also seems pretty narrow given that it's only for android users, and android itself is inherently non-secure. Though it's available on F-Droid, which is a plus.

**Comment by Atavic** [comment]
This tool is for android only, I see it as a decentralized alternative to twitter. It is built on top of Secure Scuttlebutt (SSB) like other tools like [patchwork](https://github.com/ssbc/patchwork) for desktops.

I have not enough knowledge to compare SSB with freenet or zeronet.
