### ISSUE TITLE
✨ Feature Suggestion | Darkpatterns Category

### ISSUE THREAD

**Issue by pdjpdjpdj** [privacytoolsIO/privacytools.io#741]
To raise public awareness make a seperate page with several dark patterns explainded that are being used by survcap companies to manipulate users and steer behavior towards desirable.

## Description:

e.g. [on twitter](https://twitter.com/darkpatterns)
(Speaking of twitter. Signing up with a non survcap email (e.g. tuta) is pretty much impossible (works flawlessly on mastodon and github though.)

Could/should also include what websites use which kind of (re)CAPTCHA (version) and it's dependencies. This also communicates the power position of **s**urv**ca**p cor**ps** (SCAPS) Maybe we can graph it using [d3js](https://github.com/d3/d3) (it's also open-source).

**Comment by Atavic** [comment]
SurveillanceCapitalism on sites that force users to login only with Firefox or Chrome browsers.

**Comment by pdjpdjpdj** [comment]
Or even a more general darkpattern of the way websites handicap their mobile website to push their data hungry mobile apps. Also twitter as example, but examples are plenty on this one.

Could also be included:
- Facebook only services.
- Google only services.
- Sites handicapping non-mainstream browsers
- Services pushing you towards privacy unfriendly behavior.

Idk maybe this is not the place to collect those, but then what is?

**Comment by pdjpdjpdj** [comment]
Bad usability is imho a darkpattern in itself because it hinders user adoption which is often crucial.

**Comment by Atavic** [comment]
Upcoming Webauth: ghacksuserjs/ghacks-user.js#644

**Comment by blacklight447-ptio** [comment]
While i would like this, im wondering what the best approach for this would be, i could write a blog post on it and have it linked on privacytools.io, but we could also try to start and actule official privacytools blog

**Comment by JonahAragon** [comment]
Just like #743 I think this might be out of scope for this project at the moment. Not sure if we have the resources to run an active blog on all these topics.
