### ISSUE TITLE
✨ Feature Suggestion | SCAPS transparency and avoidance

### ISSUE THREAD

**Issue by pdjpdjpdj** [privacytoolsIO/privacytools.io#745]
## Description:

I think we should be
1) Avoiding as much ties with Surveillance Capitalism Corporations (SCAPS e.g. GAFA, Alibaba, Tencent, Samsung,...)
2) Being transparent about potential exceptions:
- Facebook page (as of now still required to reach a broad audience imho) - Needs new issue? 
- Github (status of Microsoft (GAFA**M**) while far better than Google/Facebook is not clear to me yet they have pros and cons) - see #742

**Comment by JonahAragon** [comment]
There are already open issues elsewhere regarding our use of GitHub, etc.
