### ISSUE TITLE
💬 Discussion | Ring -> Jami

### ISSUE THREAD

**Issue by leonallen22** [privacytoolsIO/privacytools.io#750]
Ring (https://ring.cx/) has recently changed its name to "jami"
Blog post with more details here: https://blog.savoirfairelinux.com/fr-ca/card/ring-devient-jami/
(Although it's in French)

**Comment by Kcchouette** [comment]
Indeed, you should changed that on the website. No idea why it need feedback…

**Comment by leonallen22** [comment]
@Kcchouette I believe all new issues are tagged with the "feedback wanted" tag automatically, I did not add the tag :+1:
