### ISSUE TITLE
✨ Feature Suggestion | Mention Princeton Web Census

### ISSUE THREAD

**Issue by shortenjukebox** [privacytoolsIO/privacytools.io#751]
## Description:

To help visualize how prevalent web tracking and fingerprinting is, I’d suggest mentioning the [Princeton Web Census](https://webtransparency.cs.princeton.edu/webcensus/index.html) under _Browser Fingerprint § Related Information_ or _Recommended Privacy Resources § Tools_. The study it’s based on was conducted in 2016, though I feel the website is still a timely resource.

**Comment by Atavic** [comment]
Also scroll down on linked page for other Studies Using [OpenWPM](https://github.com/mozilla/OpenWPM).

**Comment by blacklight447-ptio** [comment]
the site itself has google trackers though.
