### ISSUE TITLE
🆕 Software Suggestion | EncryptPad

### ISSUE THREAD

**Issue by misaka00251** [privacytoolsIO/privacytools.io#752]
## Basic Information

**Name:** EncryptPad
**Category:** Digital Notebook
**URL:** [Github](https://github.com/evpo/EncryptPad), [Website](https://evpo.net/encryptpad/)

## Description

EncryptPad is an application for viewing and editing symmetrically encrypted text. Using a simple and convenient graphical and command line interface, EncryptPad provides a tool for encrypting and decrypting binary files on disk while offering effective measures for protecting information, and it uses the most widely chosen quality file format OpenPGP RFC 4880. Unlike other OpenPGP software which main purpose is asymmetric encryption, the primary focus of EncryptPad is symmetric encryption.

**Comment by misaka00251** [comment]
### Known weaknesses
EncryptPad stores unencrypted text in memory. If a memory dump is automatically taken after a system or application crash or some of the memory is saved to a swap file, the sensitive information will be present on the disk. Sometimes it is possible to configure an operating system not to use a dump and swap files. It is a good practice to close EncryptPad when not in use.

**Comment by Vincevrp** [comment]
Considering our "quality over quantity" guideline, this seems useless to me. This could easily be replaced by on of our recommended digital notebooks or file encryption software.
