### ISSUE TITLE
✨ Feature Suggestion | Maturity/independant audit matrix

### ISSUE THREAD

**Issue by pdjpdjpdj** [privacytoolsIO/privacytools.io#753]
## Description:

I think it might be useful to score the listed applications on software maturity, security maturity and or whether the software had an independent audit. Maybe starting out making a large spreadsheet (is that easy/possible on GitHub??) to list the software so we want to rate/check.

What do you guys think about this suggestion?

**Comment by Vincevrp** [comment]
Interesting idea. @Shifterovich maybe this could be implemented using labels?

**Comment by Shifterovich** [comment]
Sounds like a good use case for them. Any information that can be highlighted in < 3 words and differentiates a certain piece of software from the others in the same category fits can be put into the label.

**Comment by JonahAragon** [comment]
I think most issues regarding maturity have been addressed on the site, and we now use labels fairly comprehensively regarding potential issues with tools. For security audits specifically let's move the conversation to #1071.
