### ISSUE TITLE
💬 Discussion | Move site from .io ccTLD

### ISSUE THREAD

**Issue by dg01d** [privacytoolsIO/privacytools.io#756]
Please move the site from the .io ccTLD.

The .io domain is a terrible one to use, as every subscription sees money flowing directly to the people who have carried out an effective genocide of an entire people, and who continue to perpetrate that oppression even today.

The .io domain operates almost exclusively to provide funding and support to the British Military occupation of the Chagos Islands, and their lease of the stolen lands to the United States. That occupation has seen use of the Islands for global surveillance, drone operations and as a CIA Black Rendition Site.

If you haven’t been aware of the issues, please, go and learn about the Chagossian people. The [UK Chagos Support Asociation](https://www.chagossupport.org.uk) has a decent overview of the monstrous actions of the UK and US governments and military treatment of these people. You can see more in the Guardian’s [Chagos Archive](https://www.theguardian.com/world/chagos-islands).

**Comment by Shifterovich** [comment]
The `.io` is part of the project name. There are many links to PTIO online, the subreddit is called privacytoolsIO etc. This is not really something that can be easily changed, sorry.

**Comment by dg01d** [comment]
That's what you call a `Discussion`???

Your site is supporting the near genocide of a people. Your money is helping to pay for a **CIA Black Site**. People who support your work are, likewise, supporting these things.

But you don't care, because you didn't bother to find any of this out? Or because you just don't care?

**Comment by bakku** [comment]
@dg01d It's not that you don't have a point, but where would this stop? Should this project also stop using github because it also has a `.io` domain for some of its services?

**Comment by Shifterovich** [comment]
> But you don't care, because you didn't bother to find any of this out? Or because you just don't care?

Because:

1. I have no control over the DNS
2. We would still need to pay for this domain as to make old links work
3. We would have to change the project's name. This means:
    - updating the graphics
    - renaming reddit community if that is even possible?
    - somehow informing every single person that knows about this project about the name/"brand" change

**Comment by dg01d** [comment]
What's wrong with doing all those things?

Your effective answer to "Your site registration funds a CIA Black Site, yet you claim to be against Surveillance" is "Politics is Hard. Technology is Hard."??

**Comment by Shifterovich** [comment]
Why do you use GitHub if you're against .io domains?

**Comment by dg01d** [comment]
> It's not that you don't have a point, but where would this stop? 

Where should it stop, I don't know. I do know where it can start though - by changing the domain to one that doesn't support the repression of the Chagossians.

> Should this project also stop using github because it also has a .io domain for some of its services?

Should a project which aims to educate people on the global surveillance apparatus use Microsoft GitHub? Do I really need to answer that question, leaving aside the Chagos Islands issue?

**Comment by dg01d** [comment]
> please consider your own hypocrisy of using GitHub actively for the last 8 years.

Aside: I see that "please be civil" is, as usual, honoured solely in the gatekeeping sense, and doesn't apply to Project Members.

My hypocrisy in... using Github?

As opposed to your projects actions in **actively supporting** genocide, colonialism and rendition sites?

Yes, github uses .io domains - I've been in correspondence with them about it before, but never used one of their .io domains for anything of my own. Regardless of that, I've transitioned my own code away from their site, both because of this issue and because of their new owners.

Your supposed attachment to `privacy` is fairly risible when you're hosting your site on a property owned and controlled by the NSA's favourite and most complicit tech company.

Its also pretty clear from this dogpiling above that you're not really interested in any discussion which posits a contrary opinion to your own. You claim to care about people's rights, but only just as long as those people look like you, and as long as caring about those rights means you don't have to actually do anything.

Enjoy your little bubble of privilege.

**Comment by Shifterovich** [comment]
> Aside: I see that "please be civil" is, as usual, honoured solely in the gatekeeping sense, and doesn't apply to Project Members.

If you look at previous threads you will see this rule is followed by project members until it's broken by others. Then it's broken by me in conversations with those people.

> As opposed to your projects actions in **actively supporting** genocide, colonialism and rendition sites?

Actively? That's like saying buying something manufactured in China is actively supporting genocide.

> Regardless of that, I've transitioned my own code away from their site, both because of this issue and because of their new owners.

You seem to like projects that run on .io domains https://github.com/dg01d/KnownPnut (did you actually pay $42 to a company that actively supports genocide for access to the dev API?)

> Its also pretty clear from this dogpiling above that you're not really interested in any discussion which posits a contrary opinion to your own. You claim to care about people's rights, **but only just as long as those people look like you**, and as long as caring about those rights means you don't have to actually do anything.

Can you please provide a source to support the statement in bold?

**Comment by bakku** [comment]
@dg01d I can understand your cause however switching the domain would do more harm than good...CIA and British Military are government funded, them receiving a few dollars less per year won't help much compared to the impact of a domain change on this project.

> Its also pretty clear from this dogpiling above that you're not really interested in any discussion which posits a contrary opinion to your own.

Sorry, but this sentence applies to you as well by immediately getting salty after your proposal was rejected.

Thank you however for raising this point. I did not know this and will think again if I ever come into the situation of getting a new domain in the future.
