### ISSUE TITLE
💬 Discussion | Presence on privacy respecting social media

### ISSUE THREAD

**Issue by pdjpdjpdj** [privacytoolsIO/privacytools.io#757]
While I agree that it's way to early to no longer have a foot inside Facebook/Twitter/... I do think that it would be beneficial to give people options to follow the progress of this awesome project on alternative, more privacy respecting social media.

I'm thinking of:

- Diaspora
- Friendica
- Mastodon
- ...

I'd like to propose managing the mastodon one myself, if we agree that it's a good idea of course. Any other suggestions along this line of thought?

**Comment by Mikaela** [comment]
I think Hubzilla and Pleroma are worth mentioning.

Hubzilla would federate with Mastodon/Pleroma and Diaspora* and while it's more complicated, it would allow multiple people to share the channel without knowing the account password. Pleroma again is similar to Mastodon and supposedly (I haven't read the documentation for either nor selfhost) easier to setup and lighter. It also has a Mastodon UX.

**Comment by Kcchouette** [comment]
>I'd like to propose managing the mastodon one myself

How can we be sure that you'll not fuck up with the IP/data/etc?

**Comment by Mikaela** [comment]
https://social.privacytools.io/@BurungHantu so I think this can be closed.
