### ISSUE TITLE
❌ Software Removal | Brave Browser

### ISSUE THREAD

**Issue by danarel** [privacytoolsIO/privacytools.io#758]
More evidence that Brave is just Malware to push profit towards their own cryptocurrency. 

https://glitch.social/@tessaracht/101572578668968885

"first, they sold exceptions to privacy tracking to Facebook and Twitter, now it comes out they've got a header override that allows them to set header exceptions on demand."

https://laptop-updates.brave.com/promo/custom-headers

**Comment by Shifterovich** [comment]
Please use this thread: https://github.com/privacytoolsIO/privacytools.io/pull/657#issuecomment-462383956
