### ISSUE TITLE
🆕 Software Suggestion | One-Time pad / 2FA apps

### ISSUE THREAD

**Issue by dietercastel** [privacytoolsIO/privacytools.io#759]
## Basic Information

**Name:** FreeOTP
**Category:** One-Time pad/2FA
**URL:** https://freeotp.github.io/

## Description
As per this comparison:
https://blog.devolutions.net/2017/8/updated-most-popular-2-factor-authentication-2fa-compared

Still looking into it's privacy aspects.

**Comment by Atavic** [comment]
See: https://github.com/freeotp/freeotp-android/issues/207

**Comment by Vincevrp** [comment]
[andOTP](https://github.com/andOTP/andOTP) seems to be more actively maintained, and is more feature-rich. I personally use this.

**Comment by danarel** [comment]
Tofu and OTP Auth are great iOS 2FA clients.

**Comment by Vincevrp** [comment]
Discussion should continue in #420. Thanks for the suggestion.
