### ISSUE TITLE
ChatSecure Android has reached end-of-life

### ISSUE THREAD

**Issue by AntiSurveillance** [privacytoolsIO/privacytools.io#76]
ChatSecure officially dropped support of Android platform and recommends ZomApp or Conversations. So Android should be removed (https://twitter.com/ChatSecure/status/780848326002429953)

**Comment by privacytoolsIO** [comment]
Is it possible for ChatSecure iOS users to chat with Conversations Android users?

**Comment by ghariib** [comment]
Quotes from their (ChatSecure) FAQ and their blog

"For a **similar** user experience and the **best compatibility** with the latest features of ChatSecure iOS, we recommend downloading Conversations." (https://chatsecure.org/faq/)

"Soon we will be implementing OMEMO Encryption in ChatSecure iOS,..." (https://chatsecure.org/blog/chatsecure-conversations-zom/)
Conversations is also using the OMEMO encryption.

Other than that they are also recommending Zom (https://zom.im/) (https://github.com/zom) (iOS and Android)

**Comment by kewde** [comment]
address in #192
