### ISSUE TITLE
🆕 Software Suggestion | Librem Key

### ISSUE THREAD

**Issue by dietercastel** [privacytoolsIO/privacytools.io#760]
## Basic Information

**Name:** Librem key
**Category:** One-Time pad/2FA app
**URL:** https://puri.sm/posts/purism-launches-librem-key-only-security-key-to-offer-tamper-evident-protection/

## Description
Second suggestion in the new One-Time pad/2FA app as per #759

**Comment by Vincevrp** [comment]
Discussion should continue in #420. Thanks for the suggestion.
