### ISSUE TITLE
🆕 Software Suggestion | Njalla VPS

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#761]
## Basic Information

**Name:** Njalla VPS
**Category:** Secure Hosting Provider
**URL:** njal.la

## Description

Njalla has started new VPS service. Since Njalla is already vetted to be included in the list for DNS, it can be added to Secure Hosting Provider as well.

**Comment by Vincevrp** [comment]
Good to know, though there's currently almost no information available on their website, unless you create an account.

**Comment by pahakalle** [comment]
Njalla vps specs, prices and supported operating systems for those who don't want to register

![capture](https://user-images.githubusercontent.com/1533244/52637038-d7358a00-2ed6-11e9-9ba7-71f4e848a21e.PNG)

**Comment by Vincevrp** [comment]
Is there any info on where the severs are hosted?

**Comment by pahakalle** [comment]
@Vincevrp not that i can find, i made a support request for that info i will post here when i get a reply on that.

**Comment by pahakalle** [comment]
Took a fast stoll trough the [Njalla ](https://twitter.com/njal_la) twitter and someone said the servers are located in Sweden

**Comment by pahakalle** [comment]
Got a fast answer
![njalla](https://user-images.githubusercontent.com/1533244/52637865-38f6f380-2ed9-11e9-9f07-59c56719c908.PNG)

**Comment by Vincevrp** [comment]
Sounds good, though we might want to wait until they publish some more details on their website.

**Comment by raghavgururajan** [comment]
The following is the information I got from them.
![screenshot from 2019-02-13 14-05-57](https://user-images.githubusercontent.com/28721371/52736785-9b77ee80-2fc2-11e9-8ff6-cebd2e87659f.png)

**Comment by volth** [comment]
@ghost The VPS are actually LXD containers, which is rather untypical for a hosting. I managed to install NixOS without any assistance from the support (just by copying the files and replacing /sbin/init), so it should be the same for GuixSD.

**Comment by JonahAragon** [comment]
This is currently recommended.

**Comment by kjekac** [comment]
@volth Would you mind elaborating a bit on your solution? Which files did you copy? And how did you manage to find the correct settings for your Nix configuration regarding e.g. the bootloader and file system?
