### ISSUE TITLE
✨ Feature Suggestion | Add Simplified Chinese

### ISSUE THREAD

**Issue by White-Clouds** [privacytoolsIO/privacytools.io#765]
## Description:
Please add Simplified Chinese. There are many differences between Simplified Chinese and Traditional Chinese and Traditional Chinese sometimes misleads users of Simplified Chinese.
Translating from Traditional Chinese to Simplified Chinese is not difficult, please add Simplified Chinese.
I'll thank you very much.

**Comment by BurungHantu1605** [comment]
Good idea. Do you wanna do it?

**Comment by White-Clouds** [comment]
Ok. . . I think I can give it a try.

**Comment by linsui** [comment]
@White-Clouds Is there anything I can help with?

**Comment by blacklight447-ptio** [comment]
@white-clouds any updates? Can I close this issue yet?

**Comment by JonahAragon** [comment]
We can only add translations the community creates! If anyone wants to take this over or post an update, we can definitely re-open this issue.

**Comment by tomac4t** [comment]
I am trying to turn it into Simplified Chinese translation. But found it hard to maintaining. [po4a](https://github.com/mquinson/po4a) is a awesome translate tool, but it only support `xhtml`. I feel a little hard to edit so many HTML files. Do you have any idea or tools which could help that? Or I will still do my editing works.

My project: https://github.com/tomac4t/privacytools-zh
Preview: https://loving-jones-5975ec.netlify.com/ (unfinished)
