### ISSUE TITLE
🆕 Software Suggestion | Silence - Encrypted SMS/MMS conversations

### ISSUE THREAD

**Issue by Zig-03** [privacytoolsIO/privacytools.io#766]
## Basic Information

**Name:**
Silence
**Category:**
SMS/MMS Encryption
**URL:**
https://f-droid.org/en/packages/org.smssecure.smssecure/
## Description
I'm not associated in any way with this app.

**Comment by pahakalle** [comment]
For those who don't want to open the url: 
---
Silence is an SMS/MMS application that allows you to protect your privacy while communicating with friends.
Using Silence, you can send SMS messages and share media or attachments with complete privacy.

Features:
* Easy. Silence works like any other SMS application. There\'s nothing to sign up for and no new service your friends need to join.
* Reliable. Silence communicates using encrypted SMS messages. No servers or internet connection required.
* Private. Silence provides end-to-end encryption for your messages using the painstakingly engineered Signal encryption protocol.
* Safe. All messages are encrypted locally, so if your phone is lost or stolen, your messages are protected.
* Open Source. Silence is Free and Open Source, enabling anyone to verify its security by auditing the code.

Please file any bugs, issues, or feature requests at:
https://github.com/SilenceIM/Silence/issues

The source code can be found at:
https://github.com/SilenceIM/Silence

More details:
https://silence.im

Privacy policy:
https://silence.im/privacy

**Comment by pahakalle** [comment]
Silence Changelog:
https://github.com/SilenceIM/Silence/blob/HEAD/CHANGELOG.md

**Comment by Vincevrp** [comment]
#634

**Comment by Zig-03** [comment]
@Vincevrp 
The idea is not to promote SMS/MMS over anything, but to say that In case you really have no other alternatives, but to use SMS/MMS, then use these apps (Silence and perhaps some others). After all encrypted SMS/MMS is better than non-encrypted SMS/MMS, no?
