### ISSUE TITLE
🆕 Software Suggestion | Mail Cow

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#767]
## Basic Information

**Name:** Mail Cow
**Category:** Privacy E-Mail
**URL:** https://mailcow.email

## Description
mailcow is a docker based GNU/Linux mail server suite.

**Comment by blacklight447-ptio** [comment]
As  the orignal poster seems to be gone, and no discussion has taken place for a few months, I am now closing this issue. If anyone is willing to take it up and make a case for mailcow, they will be free to comment here, and I will reopen the issue.
