### ISSUE TITLE
Link Request: Tech Snap Security Podcast

### ISSUE THREAD

**Issue by silvernode** [privacytoolsIO/privacytools.io#77]
I noticed in the Information section you have "Security Now!" included in the list of links. I would like to request the addition of the Tech Snap Podcast. The information is great, especially for those with technical knowledge as the hosts go in to great depth on the topics they cover. Very thorough, insightful and valuable security information for those who want to stay informed and aware. 

[Tech Snap Security Podcast - By Jupiter Broadcasting](http://www.jupiterbroadcasting.com/show/techsnap/)

**Comment by privacytoolsIO** [comment]
Thanks!
