### ISSUE TITLE
🌐 Website Issue | French website not https

### ISSUE THREAD

**Issue by lambtho12** [privacytoolsIO/privacytools.io#770]
## Description
The french translation (https://privacytools.dreads-unlock.fr/) seems to have an invalid certificate. It should be corrected for proper https connection.

**Comment by Shifterovich** [comment]
@Booteille

**Comment by Booteille** [comment]
I fixed it. 

Thanks for the notification.

BTW, sorry for the lack of updates past two months, I am really busy ATM.
