### ISSUE TITLE
❌ Software Removal | Cryptocat

### ISSUE THREAD

**Issue by anon88391** [privacytoolsIO/privacytools.io#771]
Cryptocat is mentioned in the Encrypted Instand Messenger section on the website. Cryptocat is however no longer maintained which potentially exposes users to security risks and as such its use should not be recommended.
Proof that Cryptocat is no longer maintained can be found on its home website:
https://crypto.cat/

**Comment by Vincevrp** [comment]
Fixed in 674b4752743f075f4cfb233124f57817769b4491. Thanks!
