### ISSUE TITLE
💬 Discussion | Cubbit: reinventing the cloud 🐝

### ISSUE THREAD

**Issue by pahakalle** [privacytoolsIO/privacytools.io#773]
Now that Cubbit's kickstarter campaign has started and was successfully funded. I would like to hear your thoughts on it.

https://www.kickstarter.com/projects/cubbit/cubbit-reinventing-the-cloud/

**Comment by Mikaela** [comment]
It looks interesting, but I get the impression that there is some online management portal that is not specific to your node and that can be a single point of failure. Otherwise why only four accounts?

My information is based on only that Kickstarter link.

**Comment by pahakalle** [comment]
@Mikaela If i understod correctly at start it will be like that, but they plan to realease it as part of the node network as well at some point. They have been very active in the comments section in kickstarter.
