### ISSUE TITLE
🆕 Software Suggestion | add notable to digital notebook section

### ISSUE THREAD

**Issue by cyaniventer** [privacytoolsIO/privacytools.io#774]
## Basic Information

**Name:** Notable
**Category:** Digital Notebooks
**URL:** https://github.com/notable/notable

## Description

IMO notable should be placed under worth mentioning section and maybe it can replace any of those 3 above. (Joplin, Standard Notes or Turtl)

**Comment by pahakalle** [comment]
I see no issue on adding this and after they add [encryption](https://github.com/notable/notable/issues/7) this could replace one of the 3 that are currently recommended.
