### ISSUE TITLE
🆕 Software Suggestion | Replace Ricochet with Cwtch?

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#781]
## Basic Information

**Name:** Cwtch
**Category:**  Encrypted Instant Messenger
**URL:** https://cwtch.im/ (source: https://git.openprivacy.ca/cwtch.im/cwtch)

## Description

I get the impression that it's the continuation of Ricochet of which there is a lot of discussion in closed pull request to remove it in https://github.com/privacytoolsIO/privacytools.io/pull/476 and especially in open issue to add a warning to update the  shipped Tor binary onto it https://github.com/privacytoolsIO/privacytools.io/issues/474.

**Comment by blacklight447-ptio** [comment]
Interesting, tried it out but it still seems in early alpha and not ready for practicle use yet, what about Briar? Maybe thats a replacement

**Comment by Mikaela** [comment]
I think Briar is Android app and currently has no way to add contacts who aren't physically in the same space, while Richochet and Cwtch are desktop apps, so it wouldn't work as a replacement in my opinion.

**Comment by blacklight447-ptio** [comment]
@Mikaela There is already a headless client in the works btw. But they are currently focused on the remote contacts feature, which I predict should be ready somewhere this year.  after that briar will become a very interesting project to follow, as it will provide e2e encryption, will be peer to peer, so have no server to seize, and will hide almost all metadata because everything hides inside the tor network( so exit nodes are not a problem either)

**Comment by blacklight447-ptio** [comment]
update: briar remote contacts are now in alpha and expected to release at the end of next month.

**Comment by odiferousmint** [comment]
Cwtch is commonly associated with Ricochet, but I think it would be worth noting that their primary focus *seems* to be group chat and whatnot. I am not entirely sure that they are NOT willing to sacrifice security for these features.

**Comment by Mikaela** [comment]
I am currently somewhat low energy and cannot go into your comment in great detail, but do you think Cwtch would be worth considering as a worth mentioning team chat application?

**Comment by odiferousmint** [comment]
> I am currently somewhat low energy and cannot go into your comment in great detail, but do you think Cwtch would be worth considering as a worth mentioning team chat application?

Yes, definitely! The mentioned "shortcomings" can be fixed, and personally I like their threat model.

**Comment by blacklight447-ptio** [comment]
cwtch is still really alpha software though.
