### ISSUE TITLE
✨ Feature Suggestion | Simple Recommendations

### ISSUE THREAD

**Issue by PythonLinks** [privacytoolsIO/privacytools.io#782]
Thank you for an excellent website.  As a hard core geek it provides mw with just what I need. 
But for beginners, it would make their head swoon.  
How about 5 simple suggestions to start with. 
## Description:
5 Simple recommendations. 
1, Understand the scope of the problem. 
       The government tracks everything you do. 
       Surveillance Capitalism. 
2. Quit using Windows, install linux, you can start with a usb stick or dual boot. 
3. Quit faceook, use any of the following social networks. 
4. Do your searches on Yandex.  The Russian government will not share the results with your government. 
5.  Quit twitter, use ...
5,. Quit using the Internet. 

I am not sure those are the correct 5 simple suggestions, but you get the general idea.

**Comment by libBletchley** [comment]
I think if that guidance were point-blank explicit like that it would alienate that fragile audience who does not consider themselves paranoid but they want to explore their options.  Instead of scaring them off, PTIO gives them the info which will gently bring them to some of those conclusions.

**Comment by 0ndrey** [comment]
The fourth item on the list is amusing.

**Comment by PythonLinks** [comment]
>4. Do your searches on Yandex. The Russian government will not share the results with your government.
It was not my idea.  Someone recommended using 
huawei cell phones, presumably hey track everything you do, but the Chinese government will not share the data with the Western Governments.  Same idea.  Of course those in Chine should then  use an iPhone.

**Comment by 0ndrey** [comment]
> 
> 
> > 1. Do your searches on Yandex. The Russian government will not share the results with your government.
> >    It was not my idea.  Someone recommended using
> >    huawei cell phones, presumably hey track everything you do, but the Chinese government will not share the data with the Western Governments.  Same idea.  Of course those in Chine should then  use an iPhone.

In the next branch about Protonmail one of users has reproached me in distribution of theories of plot, and it in the presence of the obvious proof (for those who understands Russian language) in uncleanliness of owners of mail. Your statement simply does not stand up to any criticism, moreover, it is simply harmful. Using searx.me and startpage.com is quite enough. There can be no question about any yandex.

**Comment by JonahAragon** [comment]
> Of course those in Chine should then use an iPhone.

Apple caved and decided to install iCloud servers in China, did they not?
