### ISSUE TITLE
Add extensions.pocket.enabled false to the firefox about:config tweak list

### ISSUE THREAD

**Issue by FreddyMarsden** [privacytoolsIO/privacytools.io#784]
Pocket is a part of PRISM

**Comment by yssmcl** [comment]
Source?

**Comment by Mikaela** [comment]
I cannot find a source for it being part of PRISM, but I am happy to get it removed from my browser experience regardless of not remembering why I originally didn't like it. I can only find a source for this option.

* [Firefox Help: Disable or re-enable Pocket for Firefox](https://support.mozilla.org/en-US/kb/disable-or-re-enable-pocket-for-firefox)

**Comment by beerisgood** [comment]
Also gHacks user.js disable it too
