### ISSUE TITLE
🌐 Website Issue | HSTS Headers

### ISSUE THREAD

**Issue by JonahAragon** [privacytoolsIO/privacytools.io#792]
## Description:

We should enable HSTS headers on `https://www.privacytools.io/`, as we already redirect to HTTPS anyways. Is that something all our subdomains are capable of?

**Comment by Mikaela** [comment]
Related https://github.com/privacytoolsIO/privacytools.io/issues/731 (DNSSEC) which is also option in Cloudflare config.

**Comment by JonahAragon** [comment]
Implemented.
