### ISSUE TITLE
🆕 Software Suggestion | Private Internet Access

### ISSUE THREAD

**Issue by buster** [privacytoolsIO/privacytools.io#799]
I was wondering why one of the most bigger VPN providers (Private Internet Access) isn't in the list. Is there a reason? 

## Basic Information

**Name:** Private Internet Access
**Category:** VPN Provider
**URL:** https://www.privateinternetaccess.com/

**Comment by JonahAragon** [comment]
I’m not sure but I think in general we typically don’t recommend US based services.

**Comment by Shifterovich** [comment]
Yeah, PIA was never recommended because it's US-based.
