### ISSUE TITLE
✨ Feature Suggestion | add privacy.trackingprotection.cryptomining.enabled

### ISSUE THREAD

**Issue by hasux3** [privacytoolsIO/privacytools.io#809]
hello, this is usefull about:config

privacy.trackingprotection.cryptomining.enabled

**Comment by BurungHantu1605** [comment]
This is enabled by default. We might confuse users with that setting. What do you think?

**Comment by BurungHantu1605** [comment]
thanks

**Comment by atomGit** [comment]
sorry to reopen, but does anyone know how this pref works? is this protection hard-coded, or does it depend on an external blocklist?

**Comment by Mikaela** [comment]
I think it's downloaded from Mozilla as the closest I can get to the source is searching `about:config` for `safebrowsing.provider.mozilla`

**Comment by atomGit** [comment]
i suspect you're right - in `browser.safebrowsing.provider.mozilla.lists` i see...

`base-cryptomining-track-digest256,content-cryptomining-track-digest256`

thanks for pointing me in the right direction
