### ISSUE TITLE
🆕 Software Suggestion | FF ext: ClearURLs (link tracking)

### ISSUE THREAD

**Issue by atomGit** [privacytoolsIO/privacytools.io#813]
## Basic Information

**Name:** ClearURLs
**Category:** privacy (link tracking)
**URL:** amo: https://addons.mozilla.org/en-US/firefox/addon/clearurls/
gitlab: https://gitlab.com/KevinRoebert/ClearUrls

## Description
> This add-on will remove the tracking fields form all URLs which are visited by the browser. 

full descrip on [amo](https://addons.mozilla.org/en-US/firefox/addon/clearurls/)

ClearURLs seems to be a comprehensive, 0-conf option for addressing link tracking (utm=, etc.)

different than all of the other link tracking add-ons, this one a) uses an updated [external list](https://gitlab.com/KevinRoebert/ClearUrls/blob/master/data/data.min.json) and b) has never caused a problem for me that i can recall (been using it several months) - i've never had to whitelist a domain as i have had to do with all of the others i've tried over the years - matter of fact, it doesn't even have (nor seem to need) a whitelist capability

**Comment by beerisgood** [comment]
I recommend NeatURL
https://www.kuketz-blog.de/firefox-neat-url-firefox-kompendium-teil7/

**Comment by atomGit** [comment]
i used NeatURL for a long time and, though it's good, it's not as comprehensive and non-obtrusive as ClearURLs IMO - give it a try and see what you think
