### ISSUE TITLE
💬 Discussion | ghacks user.js not mentioned?

### ISSUE THREAD

**Issue by atomGit** [privacytoolsIO/privacytools.io#814]
i see the pyllyukko user.js is linksed on ptio, but not the [ghacks repo](https://github.com/ghacksuserjs/ghacks-user.js)

i've never used the pyllyukko js so i can't comment on it, but i've been involved with the ghacks crew for years and i can say it is a very comprehensive solution for those looking for a privacy-centric user.js with included scripts to update and maintain the user.js as well as an extensive wiki

the ghacks boys should certainly be considered for mention on ptio IMO

**Comment by beerisgood** [comment]
Ghacks is best user.js

**Comment by BurungHantu1605** [comment]
done
https://www.privacytools.io/browsers/#about_config
