### ISSUE TITLE
🌐 Website Issue | Increase vertical space between "Privacy Tools" cards

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#823]
## Description

![Screenshot from 2019-04-03 09-05-18](https://user-images.githubusercontent.com/4354706/55459369-b395e280-55ef-11e9-8abf-6f3f306414b8.png)

The spacing seems too tight vertically compared to how wide it's horizontally right now.

**Comment by blacklight447-ptio** [comment]
maybe @dawidpotocki could make a PR for this?

**Comment by dawidpotocki** [comment]
On 2019/08/28 11:10AM, blacklight447 wrote:
> maybe @dawidpotocki could make a PR for this?

Sure.
