### ISSUE TITLE
🌐 Website Issue | Track website changes/modification - changelog

### ISSUE THREAD

**Issue by temporarium** [privacytoolsIO/privacytools.io#828]
The privacytools.io site is very practical.

However, I found it much easier to follow when it was all one page, as I had a website tracker checking for changes/modifications and could see right away what was added/removed, etc.

Now, it's all-over-the-place.

**Please consider some kind of change-log feature on your website.**
Please also consider adding RSS.

Thanks!

**Comment by Shifterovich** [comment]
Changelog: https://github.com/privacytoolsIO/privacytools.io/commits/master
Atom feed: https://github.com/privacytoolsIO/privacytools.io/commits/master.atom

**Comment by temporarium** [comment]
Thanks. I'm referring more to the _content_ of the website, not it's design/layout, like "Removed Signal from such-and-such section", "Added Threema", etc.

**Comment by Shifterovich** [comment]
Perhaps this could be useful? https://github.com/privacytoolsIO/privacytools.io/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged -- merged PRs.

That's how content is added.

**Comment by temporarium** [comment]
Thank you for your suggestions, but it's still too... "under-the-hood".

Anyway, it's not the end of the world. I'm not sure why the issue got tagged as "high priority". It's more of a suggestion :-)

**Comment by Shifterovich** [comment]
Because you selected website issue instead of "feature suggestion".

![Screenshot from 2019-04-03 20-32-52](https://user-images.githubusercontent.com/4354706/55503774-aad4f900-564f-11e9-904b-3d2d55eafafe.png)

**Comment by JonahAragon** [comment]
This is probably something we can figure out, but I'm not sure what the best way to handle this would be.

@temporarium FWIW, you can still check out https://www.privacytools.io/classic/

**Comment by Shifterovich** [comment]
Perhaps every PR that adds or removes something should add something like `2019-04-03: Add Turtl` to CHANGELOG.md?

**Comment by Mikaela** [comment]
> Perhaps every PR that adds or removes something should add something like 2019-04-03: Add Turtl to CHANGELOG.md?

I fear this would cause a merge conflicts easily, so it should be something to do after merging a PR.

I think it might be possible to abuse Jekylls blogging capabilties, but it might look ugly in long term.

**Comment by JonahAragon** [comment]
Seeing as /classic/ exists I think we'll close this issue, because the solution outlined in the OP should still work fine. I don't think there's really a way to implement a changelog without updating it manually every time we merge something, or using GitHub releases, both of which seems unwieldy.
