### ISSUE TITLE
✨ Feature Suggestion | Add portuguese version to list of languages

### ISSUE THREAD

**Issue by reginildo** [privacytoolsIO/privacytools.io#830]
## Description: 
Please consider adding my translated version (portuguese) to the list of languages on the site. The translation process is advanced and I'm sure in a few days I will be finished. link: [https://www.privacytools-pt-br.xyz/](https://www.privacytools-pt-br.xyz/)

**Comment by JonahAragon** [comment]
Let us know when it's finished! Is it on GitHub?

**Comment by reginildo** [comment]
Yes. github repo: https://github.com/privacytools-pt-br/privacytools-pt-br.github.io

**Comment by abbluiz** [comment]
> Yes. github repo: https://github.com/privacytools-pt-br/privacytools-pt-br.github.io

It seems like I started translating to Portuguese before knowing that you were @reginildo :laughing: 
https://github.com/abbluiz/privacidade.digital
I suppose we can join forces?

**Comment by reginildo** [comment]
> > Yes. github repo: https://github.com/privacytools-pt-br/privacytools-pt-br.github.io
> 
> It seems like I started translating into Portuguese before knowing that you were @reginildo laughing
> https://github.com/PrivacidadeDigital/privacidade.digital
> I suppose we can join forces?

Sure we can =)

**Comment by abbluiz** [comment]
> Let us know when it's finished! Is it on GitHub?

So, the Portuguese translation is almost 100%
@reginildo and other friend joined forces at https://github.com/PrivacidadeDigital/privacidade.digital

Things missing:
* Around 2 .html files to reach 100% translated :)
* Reviewing the translations and providing enhancements
* Sharing the website around with friends and family (in the works)
* An email server for Portuguese contact (in the works)
* some other things

**Comment by ViniciusALS** [comment]
> Let us know when it is finished! Is it on Github?

The Portugues translation is done and running. You can find it on github at https://github.com/PrivacidadeDigital/privacidade.digital or see the actual website in [Privacidade Digital](https://www.privacidade.digital/).
