### ISSUE TITLE
🆕 Software Suggestion | Libreboot & Coreboot

### ISSUE THREAD

**Issue by YugiFanGX** [privacytoolsIO/privacytools.io#845]
## Basic Information

**Name: Libreboot & Coreboot**
**Category:Hardware**
**URL:https://www.coreboot.org/**

## Description
Open source BIOS

**Comment by beerisgood** [comment]
Core- and Libreboot is nice but have so less supported devices that it's not realy useable. Sadly

**Comment by FrostKnight** [comment]
I use libreboot and coreboot. They are awesome. But coreboot I do admit is harder to work with. If you want to use arch based systems I mean...

**Comment by pahakalle** [comment]
There is as well [Heads](https://github.com/osresearch/heads)
"A minimal Linux that runs as a coreboot or LinuxBoot ROM payload to provide a secure, flexible boot environment for laptops and servers."

**Comment by blacklight447-ptio** [comment]
This seems to be a bit out of the scope currently as we are still a very long way of getting a hardware section, closing for now(we can reopen it once we do have a hardware section).
