### ISSUE TITLE
🆕 Software Suggestion | WriteFreely & Plume

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#846]
## Basic Information

**Name:** WriteFreely & Plume
**Category:** Productivity Tools
**URL:** https://writefreely.org/ & https://joinplu.me/

## Description

Last night around 19 UTC I was replying to @JonahAragon to question whether anyone would be interested in Privacytols.io hosting either of those and I said I would be interested, but wouldn't use them, and wondered whether they are listed on the site which resulted to someone (who is not in my todo screenshot) suggesting me to open an issue.

In any case they are federated blogging platforms using ActivityPub and to me they seem like nice alternatives to WordPress, Blogger, Telegraph (Telegram's blog platform) etc. with a quick glance.

**Comment by Mikaela** [comment]
> Reading through https://flak.tedunangst.com/post/honk I think I'd rather deal with NNTP nonsense than whatever fediverse has to offer.

~ comment in a channel spamming my GitHub activity.

> honk is my take on a federated status updater. One might say it’s opinionated software. Since my opinions are correct, this makes honk the world’s first provably correct social media application.

from its [homepage](https://flak.tedunangst.com/post/honk).

**Comment by Mikaela** [comment]
Note: Privacytools.io is hosting a WriteFreely instance at https://write.privacytools.io/about

**Comment by JonahAragon** [comment]
Seeing as we host a WriteFreely instance I'll close this, since it's listed under our own services. I'm not really sure if they're able to be actually recommended as a tool unless you'd want to add another category, because we currently don't recommend CMS's like WordPress, etc.
