### ISSUE TITLE
🆕 Software Suggestion | Replace Keybase with IndieWeb

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#847]
## Basic Information

**Name:** IndieWeb
**Category:** umm...
**URL:** https://indieweb.org/

## Description

IndieWeb is very wide and I don't know how to put it simply, but in this case, I think that instead of Keybase (https://github.com/privacytoolsIO/privacytools.io/issues/740) it would be better to recommend IndieWeb for linking/confirming identity around the web so you own your identity instead of depending on Keybase to confirm it for you.

In practice this would be adding links with [`rel=me`](https://indieweb.org/rel-me) to both sides, e.g. Privacytools.io and Mastodon, which with some extensions and at Mastodon gives the link a verified mark. There are more example sites doing it without extension on [the wiki](https://indieweb.org/rel-me).

**Comment by libBletchley** [comment]
Keybase has [proven](https://github.com/privacytoolsIO/privacytools.io/issues/740#issuecomment-460076395) to be a disaster in terms of security, policy, and ethics.  Keybase is also more focused on becoming a trendy social network and distracted away from the original identity management goal.  So any identity management alternative has an natural advantage here.

**Comment by JonahAragon** [comment]
Keybase is only recommended as a chat tool at the moment. I don't think recommending IndieWeb anywhere makes sense because it's not really a privacy focused tool, rather a decentralization focused tool.
