### ISSUE TITLE
💬 Discussion | Matrix.org servers hacked

### ISSUE THREAD

**Issue by pahakalle** [privacytoolsIO/privacytools.io#854]
"We’ve taken down the servers which host http://Matrix.org and http://Riot.im for emergency security maintenance - estimated downtime is several hours.  More updates as we have them." -@matrixdotorg on twitter

https://twitter.com/matrixdotorg/status/1116304867683905537

**Comment by JonahAragon** [comment]
This was an issue with their infrastructure and not an issue with either Synapse or Riot, so this shouldn’t affect any of our recommendations or our own homeserver.

**Comment by Mikaela** [comment]
In case someone comes here looking for more details:

* https://matrix.org/blog/2019/04/11/security-incident/
* https://github.com/matrix-org/matrix.org/issues/created_by/matrixnotorg
