### ISSUE TITLE
🆕 Software Suggestion | Adaway

### ISSUE THREAD

**Issue by outis151** [privacytoolsIO/privacytools.io#863]
## Basic Information

**Name:** AdAway
**Category:**  Android Privacy Add-Ons
**URL:** https://f-droid.org/packages/org.adaway/

## Description
AdAway is an open source ad blocker for Android using the hosts file. 
It requires root access

**Comment by JonahAragon** [comment]
How is this better than the currently recommended tool, Blokada?

**Comment by outis151** [comment]
Blockada uses the android VPN feature to route traffic through its filters. This is battery consuming and does not allow the use of VPN services while it is active.

AdAway edits the hosts file of the android operating system (which is like a system-wide dns blocklist only accessible with root access) and does not need to run constantly in the background

**Comment by blacklight447-ptio** [comment]
I wouldn't be recommending users to root their phones anymore, I used to think differently, but rooting breaks androids security model.

**Comment by outis151** [comment]
@blacklight447-ptio I totally agree  with that. 
However the benefit of app backup, adblocking, dns changing, mac changing, more customizability, greenify are definitely worth the risk.
And if you only give root permissions to trusted and opensource apps you sould be reasonably safe

**Comment by Mikaela** [comment]
I think we could close this due to the root access requirement. Would it provide DoT/DoH support by the way?

**Comment by outis151** [comment]
Agreed
and nope it only provides dns based adblocking
