### ISSUE TITLE
💬 Discussion | Sort items in nav bar alphabetically

### ISSUE THREAD

**Issue by victorhck** [privacytoolsIO/privacytools.io#866]
Hello.

I find useful to have the items sorted alphabetically in nav bar. Would be more easy to find an item.
Also I think that Android Privacy add-ons should be live in Software section.
(both IMHO)

Greetings!

**Comment by victorhck** [comment]
I made the PR #971 for this issue.

forget the PR and close the issue if you think is not needed this...

**Comment by BurungHantu1605** [comment]
thx
