### ISSUE TITLE
🌐 Website (Meta-)Issue | longwinded repo-name and submission-template, makes email-notifications non-useful unless tapped

### ISSUE THREAD

**Issue by five-c-d** [privacytoolsIO/privacytools.io#879]
### Description

This is not really a website issue about how www.privacyTools.io functions, but more of a meta-website issue about how these github-issues function when discussing privacyToolsIO matters.  I have one of the webmail-providers recommended by the listings, and in the default configuration here is what I see in my email notifications: 

*  Re: [privacytoolsIO/privacytools.io] ❌ Softw... <s>are Removal | github (&#x23;843)</s>
*  Re: [privacytoolsIO/privacytools.io] ❌ Sof... <s>tware Removal | Signal (&#x23;779)</s>
*  Re: [privacytoolsIO/privacytools.io] ✨ Fea... <s>ture Suggestion | IzzySoft Applists \o/ (&#x23;849)</s>
*  Re: [privacytoolsIO/privacytools.io] 💬 Dis... <s>cussion | Why is PrivacyTools recommending Riot over Wire when it's less private without a warning on unencrypted metadata? (&#x23;840)</s>

The ellipsis indicates where the subject-line of my inbox-display was truncated.  In other words, there are about 42 characters -- fittingly since that is the answer to life the universe and everything -- which my webmail client displays.  If I want to see what the **subject** is then I need the whole subject-line, so I have to hover my mouse on my laptop, or tap/click on the individual email.  I cannot tell at a glance what is being discussed.  

### Feature-request:  elide needless words 

My suggestion is to re-order the listed info and to rename the repo&uid.  

*  Re: [PTIO/www] ❌ github (&#x23;843)
*  Re: [PTIO/www] ❌ Signal (&#x23;779)
*  Re: [PTIO/www] ✨ IzzySoft Applists \o/ (&#x23;8... <s>49)</s>
*  Re: [PTIO/www] 💬 Riot v Wire metadata -- w... <s>as:  Why is PrivacyTools recommending Riot over Wire when it's less private without a warning on unencrypted metadata? (&#x23;840)</s>

And ideally, the items with verbose titles should be manually renamed to put the keywords at the front of the issue-title, like I've done in the 4th item above.  Not sure if other people are using the same kind of email-client as myself, and finding the verbose subject-lines annoying.  Definitely not suggesting it will be easy to change to a new github-uid, most of the TLAs and FLAs are probably already taken, etc.  

But in the short run, cutting out the long repo-name (changing it from "privacytoolsIO/privacytools.io" to the new location of "privacytoolsIO/www" will save a dozen bytes, and cutting out the redundant "❌ Software Removal |" and replacing it with simply "❌" as well as replacing "💬 Discussion |" and "✨ Feature Suggestion |" with simply "💬" and "✨" will save an additional 13-to-19-to-21 bytes.  That would be enough for me to see what an email was about, without needing to manually open-or-hover that email:  

*  Re: [privacytoolsIO/www] ❌ github (&#x23;843)
*  Re: [privacytoolsIO/www] ❌ Signal (&#x23;779)
*  Re: [privacytoolsIO/www] ✨ IzzySoft Applis... <s>ts \o/ (&#x23;849)</s>
*  Re: [privacytoolsIO/www] 💬 Riot v Wire met... <s>adata -- was:  Why is PrivacyTools recommending Riot over Wire when it's less private without a warning on unencrypted metadata? (&#x23;840)</s>

This would let me (and any other enduser with a similar webmail client that renders the inbox in the usual kind of crimped layout) be able to see about 15 letters of the *actual* issue-title.  Getting a four-letter-github-uid, would boost that to 25 letters.

**Comment by JonahAragon** [comment]
This seems like a mail client issue. Any reason you can’t/don’t use [https://github.com/notifications](https://github.com/notifications)?

**Comment by five-c-d** [comment]
@JonahAragon , appreciate the response, and yes, I do get something-like-those, and they work.  Although I believe I've disabled github-notifications, and am in reality just seeing the webmail-client-notifications (which contain the same content).  On my platform I can hover the mouse and expand the popup-notification that the OS provides from the webmail-app, but it is usually not an annoyance to glance at it and flick the mouse 

I also know how to custom-CSS-ize my email client, if I want to see multiline email-subjects without the truncation, or whatever.  But the typical person who is not a dedicated participant is going to see a lot of boilerplate at the beginning of the subject-line.  If like me they try to batch up their volunteer-time, and come back to their privacyToolsIO conversations at a later point (rather than immediately seeing the notification and deciding on the spot "I will respond now / I will never respond") then it is a pain in the default inbox-layout.  All the privacyToolsIO messages look identical because the subjectline is truncated beyond a certain number of bytes... and the boilerplate is longer than that number, at least on some clients.  

Anyways, I don't see this as a high priority, it is just an annoyance  :-)   Feel free to close this at any time, I won't be put out in the slightest.  If I get too annoyed I'll make some CSS to keep my own webmail inbox more-time-efficient, or maybe a subject-line-auto-rewrite script which automatically does the verbosity-trimming I suggested up above?  I figured I would mention it though, in case I'm not the only one that uses the inbox as a kind of todo-list, and was irked that I could not see "the subject" because the subject-line is front-loaded with github's mandatory uid + repo + template boilerplate.

**Comment by JonahAragon** [comment]
The main issue is I think renaming the repo or especially the organization would be far too difficult at this point. Keeping permalinks intact is a big deal, which is one of the reasons we have crap like [this](https://github.com/privacytoolsIO/privacytools.io/blob/master/assets/js/redirects.js), so I'm not sure if this will realistically be possible to solve.

**Comment by five-c-d** [comment]
> renaming the repo

From the <a href="https://help.github.com/en/articles/renaming-a-repository">helpdocs</a> github already does something to try an automagically handle repo-renames.  "When you rename a repo... [visitors are] automatically redirected ...Issues, Wikis, Stars, Followers... [by] redirecting web traffic [plus] all git clone, git fetch, or git push operations... continue to function" 

I'm also a big fan of permalinks still working  :-)  And I dunno how 'actually non-painful' the github repo-rename magic pixie dust really makes things.  

> especially the organization

Renaming the org is another matter, per https://help.github.com/en/articles/renaming-an-organization ...you would need to rename, but then, immediate reclaim the old username (as a "new" org) and leave it empty except for some kind of 'please see our new orgname'.  Tricksy and not likely to work well, since github only kinda-sorta promises it will DTRT 

Right now today, it is a risky change that has little benefit, even 'merely' adjusting the repo-name.  If you get more people alluding to "hard to figure out what the email notifications are referring unto" then you might want to revisit the auto-permalink-magic idea, I guess. 

That said, I thought it was worth bringing up -- as a Someday Enhancement -- because, since there is also talk about **migrating** to self-hosted-gitlab-instance potentially, that spells a one-time golden opportunity for relatively-painless-repo-rename.  Doing a name-change on the repo (or even the "org" name) would almost certainly be possible/plausible *as part* of the switchover, since the switchover itself would entail a new URL -- git.p.io/p/r versus github.com/p/r -- that would be the ideal time to alter the length of r and maybe even p.  Like the famous movie quote:  "someday, and that day may never come, I will call on you to rename the repo to something more terse, when the time is right"   ;-)

**Comment by JonahAragon** [comment]
> there is also talk about migrating to self-hosted-gitlab-instance potentially, that spells a one-time golden opportunity for relatively-painless-repo-rename

I suppose if we did that, that's something to be considered. I'm not sure how likely that is to happen, lots of people are against it.

> But the typical person who is not a dedicated participant...

I would argue currently that casual contributors will only be participating in one or very few issues at a time so it's less of a big deal for them. 

I personally disabled all GitHub email notifications in favor of the web notifications I mentioned previously, which group by repo and show entire issue names, and is far more useful for me personally.

**Comment by five-c-d** [comment]
Yeah, I'm one of the people against leaving github, but if you do move at some point, please keep a mental note ("todo:  pick a terse repo-name and project-name this time around").  Or maybe not, because the 'brand name' of the project is privacyToolsIO and if you start using pTools or some other name you are not just changing the repo-string you are in a real sense "diluting the brand" or at least temporarily confusing it.  

And yes, you are correct, there are three basic phases, or three-and-a-half:  

0.  readership who does not contribute, never visits github/etc ... not a problem
1.  new contributor, first time at github.com/privacyToolsIO ... not really a problem
2.  active contributor but not yet a long-haul contributor ... might be a problem, or at least an annoyance, depends on their email client and whether they have github-web-notifications enabled and how savvy they are with CSS/etc 
3.  dedicated contributor, who can tweak their setup to be efficient (and re-tweak as needed) ... not really a problem at this point, will not discourage them 

I'm personally in phase#2 which is why I happened to notice  ;-)  I'm not discouraged though, personally.  Feel free to re-open this if you want to keep track of it for whatever reason, but I'll close for now since I think everything is pretty well clarified
