### ISSUE TITLE
💬 Discussion | http://vpnscam.com/

### ISSUE THREAD

**Issue by scafroglia93** [privacytoolsIO/privacytools.io#886]
I wanted to let you participate in this readings that I could make on this site.
I believe it is only right to investigate or at least to remove in advance some links to the services mentioned in PrivacyTools

We respect the ethics boys

**Comment by Atavic** [comment]
Related to: https://github.com/privacytoolsIO/privacytools.io/issues/559

I totally agree to what's said here:
https://github.com/privacytoolsIO/privacytools.io/pull/238#issuecomment-322075926

Jurisdiction is my main issue:
https://github.com/privacytoolsIO/privacytools.io/issues/654#issuecomment-448306817

Some VPN say they keep no logs... how can you blindly trust them?
https://github.com/privacytoolsIO/privacytools.io/issues/460

Some VPN changed owners and policies, but most reviews forget about it:
https://github.com/privacytoolsIO/privacytools.io/issues/421
https://github.com/privacytoolsIO/privacytools.io/issues/664

**Comment by five-c-d** [comment]
Duplicate discussion was opened later == https://github.com/privacytoolsIO/privacytools.io/issues/928 , maybe merge them into one?

**Comment by blacklight447-ptio** [comment]
Closing because its seemingly  a duplicate, you can comment if you want it to open again.
