### ISSUE TITLE
🆕 Software Suggestion | Riseup.net as an Email Provider

### ISSUE THREAD

**Issue by r00t34** [privacytoolsIO/privacytools.io#890]
## Basic Information

**Name:Riseup**
**Category:Email Provider**
**URL: https://riseup.net**

## Description
Hi All,

I wanted to see riseup.net in Email Providers section. Doesn't riseup deserve that?

Thanks.

**Comment by BurungHantu1605** [comment]
> **Why is it not recommended to choose a US-based service?**
> 
> Services based in the United States are not recommended because of the country's surveillance programs, use of National Security Letters (NSLs) and accompanying gag orders, which forbid the recipient from talking about the request. This combination allows the government to secretly force companies to grant complete access to customer data and transform the service into a tool of mass surveillance.
> 
> An example of this is Lavabit – a secure email service created by Ladar Levison. The FBI requested Snowden's records after finding out that he used the service. Since Lavabit did not keep logs and email content was stored encrypted, the FBI served a subpoena (with a gag order) for the service's SSL keys. Having the SSL keys would allow them to access communications (both metadata and unencrypted content) in real time for all of Lavabit's customers, not just Snowden's.
> 
> Ultimately, Levison turned over the SSL keys and shut down the service at the same time. The US government then threatened Levison with arrest, saying that shutting down the service was a violation of the court order.

https://www.privacytools.io/providers/#ukusa

**Comment by danarel** [comment]
Another thing to keep in mind is that you have to be invited to join RiseUp. It's not just open to anyone.

**Comment by smnthermes** [comment]
@danarel Riseup uses disk encryption and has a better privacy policy than almost all other providers. 

https://riseup.net/en/privacy tooling

https://riseup.net/en/about-us/policy/government-faq

**Comment by Mikaela** [comment]
I have also understood that there is supposed to be a network of trust rather than inviting anyone random in, so that may make it a bad idea to list it and I have seen RiseUp invites being requested in multiple places and I fear listing it would bring those queries in greater numbers to our Discourse instance.

*I don't have a RiseUp account and never had one.*
