### ISSUE TITLE
🆕 Software Suggestion | IdBloc.co as "Worth Mentioning" in Password Managers or Email Providers

### ISSUE THREAD

**Issue by pauljohncleary** [privacytoolsIO/privacytools.io#891]
## Basic Information

Name: **IdBloc**
Ctegory: **Password Manager / Email**
URL: **https://idbloc.co**

## Description
IdBloc is a service that allows users to use a different email address for every website, mailing list or app (basically anywhere you're asked for an email address). It is a bit like a password manager but for email addresses. Each email address is a random 128-bit number which is deiberately impractical for a user to remember or write down. Emails sent to an IdBloc address are automatically forwarded to the real email address of the user.

The service is designed to stop users from reusing their email address across multiple services, this helps prevent tracking and monitoring in the event of a leak, and significantly reduces the practicality of a targeted attack or dragnet attack on a user. A side benefit is spam reduction and tracking email leakage.

There is a web vault, chrome extension and firefox addon available to create and retrieve email addresses.

I am not sure if it belongs in password managers or email providers, but I think it's an important defense in keeping your identity secure online so should be mentioned. There are a number of blog posts on the IdBloc blog explaining the concept e.g. https://www.idbloc.co/blog/background/2019/04/14/keep-your-address-secret.html

**Comment by JonahAragon** [comment]
Are you affiliated with this provider?

**Comment by pauljohncleary** [comment]
> 
> 
> Are you affiliated with this provider?

Yes, I created it

**Comment by blacklight447-ptio** [comment]
Are the extensions open source?

**Comment by JonahAragon** [comment]
I don't think this can be added as is, as nothing is open about this project + the issues @blacklight447-ptio stated.

As an aside, your pricing also seems strange to me. Why does the $1/month tier—limited to 5 email addresses—exist at all when the point of the service is to have a unique email per service?
