### ISSUE TITLE
💬 Discussion | what should /summary fka /classic highlight? 

### ISSUE THREAD

**Issue by five-c-d** [privacytoolsIO/privacytools.io#896]
Here is <a href="https://www.privacytools.io/classic/">the current /classic</a> page, which is a throwback to the 2015-thru-2018 site design where everything was all in one page.  As part of the design-revamp, most tools are now split into their own subpages, for ease of linking (and SEO and so on), but also to allow "more room" for expanding page-content.  I liked the old layout, because it was 'easy' for a beginner to skim the page and get some solid advice on all their stuff:  browser, im/voip, email, OSes, etc ... as well as some grounding in why privacy matters, how extensive mass surveillance is, and other foundational basics.  

The new layout has advantages, but one of the disadvantages is ease-of-readability.  It will help once the current split-into-subpages design adds some navigation hints (e.g. button where readers can click here for the previous subpage and click here for the next subpage organized in book-with-chapters sort of fashion).  

But I still think that a top-level one-big-page summary of the main recommendations, and the main philosophical/legal points, has value.  Plenty of first-time visitors will not WANT to read a book on tools to improve their privacy:  they will want a "top N tools" list they can skim through which gives them some ready-to-put-into-use-immediately suggestions on what to use instead of chrome + gmail + facebook + windows10, and we don't want to bury torBrowser + tutanota + mastodon + qubesOS away on four different pages of the big-book-of-chapters-layout.  Or rather, we *do* want that, but we also want to have /summary -- the page which summarizes the crucial stuff.  

This isssue is requesting discussion, of WHAT stuff is crucial.  Most people would probably agree that about:config tweaks, are not as crucial as top3 browser-recommendations... and thus, likely it makes sense to put the about:config tweaks onto the /browsers subpage but *not* mention them (except in the form of a "for more information" hyperlink) on the /summary section devoted to top3 browsers.  What should be on /summary though?  Top3 recommendations for sure.  What about the worthMentioning, should those be on the /summary or only on the /browsers subpage, if they exist for a particular tools-category?  What about browser-addons, should that be on the /summary or is that too-much-detail and it should be on the /browsers only? 

<details><summary>Here are the 39 existing /classic sections</summary><p>

id,sectionName             | top1 | top2 | top3 | WM | other
---|---|---|---|---|---
1, nuth2hide| Greenwald#1  | CryptoSeb | rel.links | -
2, quotes                  | Snowden#1 | Snowden#2 | Greewald#2 | - | -
3, 14 Eyes           | AU CA NZ <br /> UK US | DK FR <br /> NL NO | BE DE IT <br /> ES SE | UKUSA laws | 5eyes map  
4, key-disclose      | AU CA FR <br /> IN IE NO <br /> RU SA UK | BE ET FI <br /> NZ NL US | CZ DE IS <br /> IT PL <br /> SE CH | keyDisc & stegan | avoid USA-based 
5, vpn                     | blk proxy trustZ ht area tunn | cStorm expr hide ivpn perfPriv protonV nord | air azire froot mullvad ovpn |  criteria | rel.links 
6, canary          | explanation | examples | rel.links | - | - 
7, browsers  | torBrowser | firefox | brave | waterfox (proposed) | - 
8, b-fingerprint     | explanation | test+canvas | rel.links | - | -
9, b-webrtc          | firefox howto | test  | chrome/etc | - | -  
10, b-addons          | pBadger uBlock cookieDel <br /> httpsEv deCent TOSDR | uMatrix <br /> NoScript | - | - | -
11, b-tweaks          | aboutConfig  | gHacks pyllyukko | rel.links | - | -

id,sectionName             | top1 | top2 | top3 | WM | other
---|---|---|---|---|---
12, webmail         | protonM disroot tuta fence | boxOrg posteo runbox | neomailbox startM kolab | confidant inABox | rel.links 
13, email client           | t-bird | claws | gpg4usb velope enig torBirdy tester | k9 gpg pile | - 
14, email-alts      | bitmessage | retroshare | - | i2pBote | - 
15, search          | searX | startPage | duckDuck | qwant yaCy jive metaGer | searchLinkFix 
16, IM       | signal | riot | ricochet | retroshare chatSecure + konTalk + conversations wire status | ricochet+tor howto 
17, VoIP   | signal | wire | linphone | jitsi tox jami | rel.links 

id,sectionName             | top1 | top2 | top3 | WM | other
---|---|---|---|---|---
18, file-share            | onionshare | firefoxSend | magic wormhole | - | - 
19, cloud svcs           | nextCloud | leastAuthS4 | - | cryptomator cryptPad | - 
20, self-cloud        | pydio | tahoe-LAFS | nextCloud | cryptPad | - 
21, hosting        | bahnhof | datacell | orangeWeb | njalla | - 
22, file-sync               | sparkleShare | syncThing | - | gitAnnex | - 
23, passwd       | bitWarden | keePass | lessPass | masterPass psono passSafe | snowden#3 
24, calendar  | nextCloud | emailSection | eteSync | fruux flock cloudSection 
25, file crypto         | veraCrypt | gpg | peaZip 7zipKeka | cryptomator diskCryptor LUKS | - 
26, self-cont'd | torBrowser | i2p | freenet | zeroNet retroShare gnuNet ipfs | - 
27, social net         | mastodon | diaspora | friendica | gnuSocial | rel.links 
28, dns                     | openNic | njalla | dnsCrypt | noTrack nameCoin piHole | - 
29, notebooks               | joplin | standard notes | turtl | notable paperwork orgMode | - 
30, paste svcs          | privateBin | zeroBin | ghostBin | privateBin-by-disroot | - 
31, produc'y      | cryptPad | etherPad | write.as | cryptee etherCalc dudle LibreOffice | - 

id,sectionName             | top1 | top2 | top3 | WM | other
---|---|---|---|---|---
32, dtop OS       | qubes OS | debian | trisquel | openbsd arch/parabola whonix subgraphOS | win10section 
33, live OS  | tails | knoppix | puppyLinux | tinyCoreLinux | - 
34, mobile OS | lineageOS | ubuntuTouch | grapheneOS (proposed) | replicant omniRom microG | - 
35, android++          | blokada | netguard | orbot | xPrivacyLua | - 
36, router FW         | openWrt | pfSense | libreCmc | openbsd ddWrt | - 
37, win 10               | warnings | w10privacy tool | rel.links | good news | more bad news 
38, resources       | guide links | info links | tool links | - | - 
39, participate             | discourse + reddit | mastodon + twitter | github | riotIM | share buttons 

</p></details> 

<details><summary>Suggest eliding these bits from the /summary page</summary><p>

id,sectionName             | top1 | top2 | top3 | WM | other
---|---|---|---|---|---
1, nuth2hide| Greenwald#1  | CryptoSeb | rel.links | -
2, quotes                  | Snowden#1 | Snowden#2 | Greewald#2 | - | -
3, 14 Eyes           | AU CA NZ <br /> UK US | DK FR <br /> NL NO | BE DE IT <br /> ES SE | UKUSA laws | <s>5eyes map</s> 
4, key-disclose      | <s>AU CA FR</s> <br /> IN IE <s>NO</s> <br /> RU SA <s>UK</s> | <s>BE</s> ET FI <br /> <s>NZ NL US</s> | CZ <s>DE</s> IS <br /> <s>IT</s> PL <br /> <s>SE</s> CH</s> | keyDisc & stegan | <s>avoid USA-based</s>
5, vpn                     | blk proxy trustZ ht area tunn | cStorm expr hide ivpn perfPriv protonV nord | air azire froot mullvad ovpn |  <s>criteria</s> | <s>rel.links</s> 
6, canary          | explanation | <s>examples</s> | <s>rel.links</s> | - | - 
7, browsers  | torBrowser | firefox | brave | waterfox (proposed) | - 
8, b-fingerprint     | <s>explanation</s> | test+canvas | <s>rel.links</s> | - | -
9, b-webrtc          | <s>firefox howto</s> | test  | <s>chrome/etc</s> | - | -  
10, b-addons          | pBadger uBlock cookieDel <br /> httpsEv deCent TOSDR | <s>uMatrix <br /> NoScript</s> | - | - | -
11, <s>b-tweaks</s>          | <s>aboutConfig</s>  | <s>gHacks pyllyukko</s> | <s>rel.links</s> | - | -

id,sectionName             | top1 | top2 | top3 | WM | other
---|---|---|---|---|---
12, webmail         | protonM disroot tuta fence | boxOrg posteo runbox | neomailbox startM kolab | <s>confidant inABox</s> | <s>rel.links</s> 
13, email client           | t-bird | claws | gpg4usb velope enig torBirdy tester | k9 gpg pile | - 
14, email-alts      | bitmessage | retroshare | - | i2pBote | - 
15, search          | searX | startPage | duckDuck | qwant yaCy jive metaGer | searchLinkFix 
16, IM       | signal | riot | ricochet | retroshare chatSecure + konTalk + conversations wire status | <s>ricochet+tor howto</s> 
17, VoIP   | signal | wire | linphone | jitsi tox jami | rel.links 

id,sectionName             | top1 | top2 | top3 | WM | other
---|---|---|---|---|---
18, file-share            | onionshare | firefoxSend | magic wormhole | - | - 
19, cloud svcs           | nextCloud | leastAuthS4 | - | cryptomator cryptPad | - 
20, self-cloud        | pydio | tahoe-LAFS | nextCloud | cryptPad | - 
21, hosting        | bahnhof | datacell | orangeWeb | njalla | - 
22, file-sync               | sparkleShare | syncThing | - | gitAnnex | - 
23, passwd       | bitWarden | keePass | lessPass | masterPass psono passSafe | snowden#3 
24, calendar  | nextCloud | emailSection | eteSync | fruux flock cloudSection 
25, file crypto         | veraCrypt | gpg | peaZip 7zipKeka | cryptomator diskCryptor LUKS | - 
26, self-cont'd | torBrowser | i2p | freenet | zeroNet retroShare gnuNet ipfs | - 
27, social net         | mastodon | diaspora | friendica | gnuSocial | <s>rel.links</s> 
28, dns                     | openNic | njalla | dnsCrypt | noTrack nameCoin piHole | - 
29, notebooks               | joplin | standard notes | turtl | notable paperwork orgMode | - 
30, paste svcs          | privateBin | zeroBin | ghostBin | <s>privateBin-by-disroot</s> | - 
31, produc'y      | cryptPad | etherPad | write.as | cryptee etherCalc <s>disroot3</s> dudle LibreOffice | - 

id,sectionName             | top1 | top2 | top3 | WM | other
---|---|---|---|---|---
32, dtop OS       | qubes | debian | trisquel | openbsd arch + parabola whonix subgraphOS | win10section 
33, live OS  | tails | knoppix | puppy | tinyCore | - 
34, mobile OS | lineage | ubuntuT | graphene (proposed) | replicant omniRom microG | - 
35, android++          | blokada | netguard | orbot | <s>xPrivacyLua</s> | - 
36, router FW         | openWrt | pfSense | libreCmc | openbsd ddWrt | - 
37, win 10               | warnings | w10privacy tool | <s>rel.links</s> | <s>good news</s> | <s>more bad news</s> 
38, <s>resources</s>       | <s>guide links</s> | <s>info links</s> | <s>tool links</s> | - | - 
39, participate             | discourse + reddit | mastodon + twitter | github | riotIM | share buttons 

</p></details> 

In addition to eliding details, I would suggest that /summary ought to *include* more details than it currently does, specifically, that each of the top3 entries should have a short list of pros-n-cons.  This might be 3pros + 3cons for each top3 entry, or might be 5pros + 5cons for each top3 entry, depending on how much space is considered "cluttered".  An example layout of the pros-n-cons on subpages, versus pros-n-cons on the /summary page, can be seen here https://github.com/privacytoolsIO/privacytools.io/issues/882#issuecomment-487785086 -- see also #596

**Comment by JonahAragon** [comment]
I don't want to create a /summary/ page or add highlights to the /classic/ page, but I would be open to adding 3-6 *very important tools* to the index page if we wanted. Something like:

> ### Recommended Browser: Mozilla Firefox
> Firefox is fast, reliable, open source and respects your privacy.
> [Download](https://www.mozilla.org/en-US/firefox/new/?redirect_source=firefox-com)
> [See further browser recommendations >](https://www.privacytools.io/browsers/#browser)

etc.

What should we highlight on the homepage?
