### ISSUE TITLE
✨ Feature Suggestion | SSL Improvements

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#897]
So just on a whim, I ran Qualys SSL Labs [testing](https://www.ssllabs.com/ssltest/analyze.html?d=www.privacytools.io&hideResults=on) on the main site.  Although it scored very well, it does not yet support several features, such as using an ECC-based ChaCha20 encrypted cert which is less-cpu intensive, while being stronger and running HPKP with preloading enabled. It also might to be a good idea to disable some of the weaker CBC ciphersuites with TLS 1.2.

Is this possible?

**Comment by JonahAragon** [comment]
HPKP [is dead](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ). We can definitely change out the cipher suites though, I'll research that this weekend.
