### ISSUE TITLE
💬 Discussion | Discourse Comment/Discussion Board on Sub-pages

### ISSUE THREAD

**Issue by JonahAragon** [privacytoolsIO/privacytools.io#901]
Now that we have a Discourse forum, one thing we could do is embed a "comments" functionality on the pages of our site for people to discuss the tools we recommend. Picture it like Disqus integration, but self-hosted. Discourse has built-in support for this via Javascript that could be very easily and automatically added to all our pages with Jekyll: https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963?source_topic_id=12627

Visually it would look something like the comments section of this blog post: https://blog.codinghorror.com/welcome-to-the-internet-of-compromised-things/#discourse-comments

I think this would be a good way to spur discussion of the tools we feature, and drive traffic to our new forums. What do you all think, should we create a user platform on the website?

**Comment by BurungHantu1605** [comment]
Let's give it a try. I like it.
