### ISSUE TITLE
🌐 Website Issue | Icons out of place on mobile devices

### ISSUE THREAD

**Issue by BurungHantu1605** [privacytoolsIO/privacytools.io#905]
## Description
Icons look out of place currently on mobile devices.

## Screenshots
Looks neat:
![good](https://user-images.githubusercontent.com/11730911/57189124-15be6c00-6f3d-11e9-8b39-2c09a7b0b1cd.jpg)

Does not look neat at all:
![bad](https://user-images.githubusercontent.com/11730911/57189134-2373f180-6f3d-11e9-9ebd-19bcc6662291.jpg)

**Comment by Mikaela** [comment]
I have no idea how would I start fixing this, so I am unassigning myself and setting "help wanted" label.

**Comment by Shifterovich** [comment]
I'm not that good with BS4 but basically we want the buttons and the icons to be in the same div (maybe .row or .col-12) and put the buttons and the icons in separate divs, something like div.col-md-6. And also make the icons section right aligned (ideally with flexbox) but center aligned (.justify-content-center) when the div "collapses" (when size is  < md).

Currently the icons are right-aligned using `.float-right`. I think we should avoid floats as much as possible and use the BS4 grid instead.

**Comment by JonahAragon** [comment]
They should probably be left aligned on mobile, not centered. I’ll see if I have time to take a look later if nobody else figures it out, but I’m sure there’s some way to do that that’s built-in to BS4. 

Definitely need to switch to the grid system if that isn’t what we’re currently using anymore.

**Comment by BurungHantu1605** [comment]
thanks for fixing this @dawidpotocki
