### ISSUE TITLE
💬 Discussion | Reddit Alternatives

### ISSUE THREAD

**Issue by gjhklfdsa** [privacytoolsIO/privacytools.io#909]
I've looked through the listed [decentralized social networks](https://www.privacytools.io/providers/social-networks/) and realized there isn't a single [Reddit](https://www.wikipedia.org/wiki/Reddit) alternative. I figured this would make a good discussion thread.

**Some interesting decentralized projects (possibly open-source?)**:

- [AKASHA](https://beta.akasha.world/)
https://github.com/AkashaProject

- [Aether](https://getaether.net/)
https://getaether.net/opensource/
https://github.com/nehbit/aether

**Centralized but arguably more popular**:

- [Raddle](https://raddle.me/)
https://gitlab.com/postmill/Postmill

- [Voat.co](https://www.wikipedia.org/wiki/Voat)
https://github.com/voat/voat

- [Tildes.net](https://tildes.net/)
https://gitlab.com/tildes/tildes

Any further suggestions? Discussion is open!

**Comment by Mikaela** [comment]
Issue on Voat at https://github.com/privacytoolsIO/privacytools.io/issues/711.

And to your second list, I would add [Tildes.net](https://tildes.net/).

**Comment by Mikaela** [comment]
I was also made aware of Lenmy today which is going to federate.

https://github.com/dessalines/lemmy

**Comment by Mikaela** [comment]
Oh, notabug.io was also mentioned in the Matrix chat https://github.com/notabugio . They also linked to https://github.com/reddit/ so apparently Reddit has some open source code.
