### ISSUE TITLE
💬 Discussion | Hidden metadata on printed documents (yellow dots)

### ISSUE THREAD

**Issue by YugiFanGX** [privacytoolsIO/privacytools.io#910]
https://en.wikipedia.org/wiki/Printer_steganography

There are anonymization tools like DEDA (https://github.com/dfd-tud/deda). But this leads us to the question:
Which printers are safe? Are there printers which are based on libre software?

**Comment by JonahAragon** [comment]
Kind of out-of-scope for this project at the moment. Might be worth mentioning at #904 if you really want something like this included, but I'm not actually sure if any printers can be trusted.
