### ISSUE TITLE
🆕 Software Suggestion | Metadata Anonymization Toolkit (MAT)

### ISSUE THREAD

**Issue by YugiFanGX** [privacytoolsIO/privacytools.io#911]
## Basic Information

**Name:** Metadata Anonymization Toolkit (MAT)
**Category:** Misc
**URL:** https://0xacab.org/jvoisin/mat2

## Description
MAT is free software, which allows the removal of metadata of images (jpg, png), audio (mp3, ogg), torrent and several document file types (pdf, docx etc)

Mat only removes standard metadata from your files, it does **not**:

    anonymise their content
    handle watermarking
    handle steganography
    any overly customized metadata field/system (→jpg,zip)

If you really want to be anonymous, use formats that do not contain any metadata, or better: use plain-text.

And most important, be careful: every format can be watermarked, even plain text (e.g. the SNOW project)!

**Comment by Mikaela** [comment]
[Ships with Tails.](https://tails.boum.org/blueprint/doc/mat/)

**Comment by blacklight447-ptio** [comment]
1+ for mat. Though i recall that developement had paused/halted because the developer was struggling with health problems, does anyone have updates on this situation?

**Comment by l0phty1** [comment]
dev looks very active, busy amount of commits and issues responsiveness, also main dev's blog which alerted me to new release 0.9.0 on 10 May https://0xacab.org/jvoisin/mat2/tags/0.9.0

This would be a great addition for PTIO to recommend.

**Comment by blacklight447-ptio** [comment]
Can we close this issue as accepted and push for a pull request?

**Comment by nitrohorse** [comment]
@blacklight447-ptio yeah, that'd be good. We'll need to determine _where_ to place it... seems like its own category. Maybe https://www.privacytools.io/software/productivity/ ?

**Comment by blacklight447-ptio** [comment]
we could make a small sub category on  the productivity page for metadata clearing tools.

**Comment by blacklight447-ptio** [comment]
@nitrohorse would you be willing to create an initial PR for this?
