### ISSUE TITLE
💬 Discussion | Warning about Privacy Badger

### ISSUE THREAD

**Issue by woctezuma** [privacytoolsIO/privacytools.io#917]
I have noticed that a warning about Privacy Badger had been removed.

The warning was:

> Please be aware that Google Analytics is considered first-party by Privacy Badger, which means that Google Analytics will not be blocked if you do not use another blocker, such as uBlock Origin.

I had added this warning in PR #360 because of issue #335.

I have found out that it was removed silently after [a seemingly cosmetic-only commit](https://github.com/privacytoolsIO/privacytools.io/pull/903/files#r282432425).

**Comment by hugoncosta** [comment]
I too agree that the warning should stay. On the other hand, we could also add that you can, in fact, block Google Analytics with PB.

![screenshot](https://i.imgur.com/9s16USY.png)

**Comment by beerisgood** [comment]
> 
> 
> block Google Analytics with PB.
> 
Or better: use uBlock Origin which can do the same and isn't crap

**Comment by atomGit** [comment]
^ what he said - i'd suggest dumping the Badger as long as uBlock/uMatrix are used (along with some other junk like CanvasBlocker, FPI, etc...) - but maybe i'm not thinking about the noobs?

**Comment by Mikaela** [comment]
PrivacyBadger is supposed to only block trackers, not advertisements. I can understand sites containing advertisements to get money and I don't want to block wellbehaving ads (even if they are a minority), so I am against removing it entirely without a similar alternative with equivalent functionality.

I assigned @BurungHantu1605 earlier due to author of that change.

**Comment by atomGit** [comment]
there's a lot of lists for uBO - you don;t necessarily have to block ads - you can block trackers and other nasties only, but it's a bit more learning and config-ing for the newbies - if interested though, i'll gladly provide some filter list resources for tracker/nasty only blocking

**Comment by infinitewaveparticle** [comment]
Or you can just use AdGuard or Blokada or Netguard and block every google (and every other ad, tracking, telemetry, analytics, etc) server at the dns level.

**Comment by infinitewaveparticle** [comment]
AdGuard also modifies cookies and spoofs your IP - and you can connect to a VPN via proxy.

**Comment by infinitewaveparticle** [comment]
https://github.com/AdguardTeam/StealthMode

**Comment by woctezuma** [comment]
For info, it seems that the Google Analytics issue might have been [fixed](https://github.com/EFForg/privacybadger/issues/574#issuecomment-510036366).
