### ISSUE TITLE
OpenMailBox forum link is dead

### ISSUE THREAD

**Issue by MartijnOud** [privacytoolsIO/privacytools.io#92]
In the email providers section (under "related information") there is a link `OpenMailBox keeps one year logs of meta-data` with a link to a forum post. This link doesn't work any more (404 error).

Link in question: https://www.openmailbox.org/forum/viewtopic.php?id=390

The link is not archived in The Wayback Machine.

**Comment by Shifterovich** [comment]
They apparently moved /forum/ to forum.openmailbox.org.
New link: https://forum.openmailbox.org/viewtopic.php?id=390
