### ISSUE TITLE
✨ Feature Suggestion | P2p Filesharing Client Recommendations

### ISSUE THREAD

**Issue by ghbjklhv** [privacytoolsIO/privacytools.io#920]
**Feature**: Bittorrent/P2p File-sharing Client Recommendations

**What I can recommend**:
There are very few clients directed at privacy.
To get the ball going maybe add:

- [XD Client](https://xd-torrent.github.io/)

- [OFFLoad](http://offload.sourceforge.net/) - Uses [OFFSystem](https://www.wikipedia.org/wiki/OFFSystem) (not Bittorrent)

- [The Owner Free File System](off.system/) - Reboot of [OFFSystem](https://www.wikipedia.org/wiki/OFFSystem) (not Bittorrent)

**Networks I find worth discussing but don't know enough to endorse**:
- [StealthNet](https://www.wikipedia.org/wiki/StealthNet)
- [Calypso](http://calypso.sourceforge.net/)
- [iMule](https://www.wikipedia.org/wiki/IMule)
- [Phex](https://www.wikipedia.org/wiki/Phex#Anonymous_Phexhttps://www.wikipedia.org/wiki/Phex#Anonymous_Phex)
- [Frost](https://www.wikipedia.org/wiki/Freenet#Tools_and_applications)

**But why not ___ protocol?**
Here is a basic list of popular protocols and issues with them:

**IPFS**: No known TOR or I2p Support

**DAT**: Same as IPFS.

**Comment by blacklight447-ptio** [comment]
I warn against using bittorrent based file sharing for privacy purposes, they often leak you ip address by design(not because they are evil, but just because that how they were built to work.)

**Comment by gjhklfdsa** [comment]
@blacklight447-ptio XD uses I2p.

@ghbjklhv I wouldn't add qBittorrent to main, tho. 
Too easy for somebody to leak their IP.

**Comment by nchristensen** [comment]
[BiglyBT](https://github.com/BiglySoftware/BiglyBT/wiki/I2P) (A fork of [Vuze](https://en.wikipedia.org/wiki/Vuze)) support I2P with a plugin. I believe the I2P console also provides a Bittorrent client.

**Comment by Mikaela** [comment]
> IPFS: No known TOR or I2p Support

https://github.com/ipfs/notes/issues/37

**Comment by JonahAragon** [comment]
I haven't heard of the software listed here and it isn't clear to me how they're significantly better than what we currently recommend (namely Syncthing): https://www.privacytools.io/software/file-sync/
