### ISSUE TITLE
🆕 Software Suggestion | Add OFFSystem to Self-Contained Networks

### ISSUE THREAD

**Issue by ghbjklhv** [privacytoolsIO/privacytools.io#921]
**Feature**: Add popular file share management tool - [The Owner Free File System](http://offload.sourceforge.net/) (reboot of [OFFSystem](https://www.wikipedia.org/wiki/OFFSystem)) to [self contained networks](https://www.privacytools.io/classic/#darknets).

**Comment by blacklight447-ptio** [comment]
The download page: https://sourceforge.net/projects/offload/ says it has last been updated in 2013.
This indicates that the project is apparently abandoned. It would not be smart to list this project on privacytools if you ask me,so I am closing this issue. Feel free to comment to upon it up again if you disagree or have more input.
