### ISSUE TITLE
🆕 Software Suggestion | Add loki-net

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#924]
```
https://github.com/loki-project/loki-network
```

**Comment by blacklight447-ptio** [comment]
So where would one add this, self contained networks? Also I would feel a bit uncomfortable with adding new networks, atleast not without some big warnings.

**Comment by Mikaela** [comment]
What is it and why should it be added? Is it more like Tor or I2P? What makes it in-scope unlike https://github.com/privacytoolsIO/privacytools.io/issues/685?

**Comment by Atavic** [comment]
It's an evolved I2P for me. Seems related to #685 but not to #798 IMHO

**Comment by blacklight447-ptio** [comment]
As the initiator of the issue seems to be unresponsive and provides no real case to add loki, ill close this issue. If anyone disagrees, they can comment to ask for it to open up again.

**Comment by KeeJef** [comment]
Hey, CTO of the Loki project here (We develop Lokinet), just noticed this issue. We will be making a more official posting when Lokinet has reached a stable release. For now this issue can remain closed
