### ISSUE TITLE
Discussion | Labels to add to some issues:

### ISSUE THREAD

**Issue by Atavic** [privacytoolsIO/privacytools.io#941]
There are so many issues opened, so similar discussions can 
get some *labels*:

*Firefox*
https://github.com/privacytoolsIO/privacytools.io/issues/121
https://github.com/privacytoolsIO/privacytools.io/issues/339
https://github.com/privacytoolsIO/privacytools.io/issues/341
https://github.com/privacytoolsIO/privacytools.io/issues/525
https://github.com/privacytoolsIO/privacytools.io/issues/310
https://github.com/privacytoolsIO/privacytools.io/issues/306
https://github.com/privacytoolsIO/privacytools.io/issues/878
https://github.com/privacytoolsIO/privacytools.io/issues/641
https://github.com/privacytoolsIO/privacytools.io/issues/841
https://github.com/privacytoolsIO/privacytools.io/issues/735
https://github.com/privacytoolsIO/privacytools.io/issues/516

**Comment by Atavic** [comment]
More on *Firefox* settings, about:config etc.

https://github.com/privacytoolsIO/privacytools.io/issues/917
https://github.com/privacytoolsIO/privacytools.io/issues/878
https://github.com/privacytoolsIO/privacytools.io/issues/860
https://github.com/privacytoolsIO/privacytools.io/issues/815
https://github.com/privacytoolsIO/privacytools.io/issues/785

**Comment by Atavic** [comment]
*VPN*
https://github.com/privacytoolsIO/privacytools.io/issues/664
https://github.com/privacytoolsIO/privacytools.io/issues/521
https://github.com/privacytoolsIO/privacytools.io/issues/559
https://github.com/privacytoolsIO/privacytools.io/issues/480
https://github.com/privacytoolsIO/privacytools.io/issues/460
https://github.com/privacytoolsIO/privacytools.io/issues/886
https://github.com/privacytoolsIO/privacytools.io/issues/928
https://github.com/privacytoolsIO/privacytools.io/issues/914

**Comment by Atavic** [comment]
*XMPP*
https://github.com/privacytoolsIO/privacytools.io/issues/60
https://github.com/privacytoolsIO/privacytools.io/issues/141

**Comment by Mikaela** [comment]
Thank you for the suggestion and especially grouping those issues. I suggested this once in the team room and didn't get feedback and I didn't have the energy to start going through the issues.

**Comment by Atavic** [comment]
For me the problem arises from the many opened issues.

**Comment by Mikaela** [comment]
Todo: label Android issues, I think there are more than the two I just opened.

**Comment by nitrohorse** [comment]
Ok, created a new "Android" label and added it to these issues I found:
- https://github.com/privacytoolsIO/privacytools.io/issues/1068
- https://github.com/privacytoolsIO/privacytools.io/issues/1051
- https://github.com/privacytoolsIO/privacytools.io/issues/1069
- https://github.com/privacytoolsIO/privacytools.io/issues/864
- https://github.com/privacytoolsIO/privacytools.io/issues/863
- https://github.com/privacytoolsIO/privacytools.io/issues/849
- https://github.com/privacytoolsIO/privacytools.io/issues/747
- https://github.com/privacytoolsIO/privacytools.io/issues/713
- https://github.com/privacytoolsIO/privacytools.io/issues/533
- https://github.com/privacytoolsIO/privacytools.io/issues/519
- https://github.com/privacytoolsIO/privacytools.io/issues/501
- https://github.com/privacytoolsIO/privacytools.io/issues/462
- https://github.com/privacytoolsIO/privacytools.io/issues/338
- https://github.com/privacytoolsIO/privacytools.io/issues/420

**Comment by nitrohorse** [comment]
Created a new "email" label also: https://github.com/privacytoolsIO/privacytools.io/labels/%F0%9F%93%A7%20Email

**Comment by Mikaela** [comment]
Thanks :)
