### ISSUE TITLE
Host a PeerTube instance (video.privacytools.io perhaps?)

### ISSUE THREAD

**Issue by Zig-03** [privacytoolsIO/privacytools.io#945]
Just like you are hosting a Mastodon instance at [social.privacytools.io](social.privacytools.io) I'm suggesting to host a PeerTube instance for everyone to upload videos on. In case you are limited in terms of storage, you could set a low quota on user upload size.

**Comment by JonahAragon** [comment]
> In case you are limited in terms of storage

This is the main concern, although I'm also not super keen on hosting content in general because moderating a platform for copyrighted content is time-consuming and we need to focus on other things, especially since we don't quite cover all expenses with donations. Maybe if we were making a comfortable level of monthly donations we could add bigger services like this.

I would also very much like to see https://github.com/Chocobozzz/PeerTube/issues/147 implemented before hosting a service. Offloading storage to Wasabi S3 would be hugely beneficial for us.

**Comment by Zig-03** [comment]
>  I'm also not super keen on hosting content in general because moderating a platform for copyrighted content is time-consuming

I believe this should make the moderator's life so much easier https://github.com/Chocobozzz/PeerTube/issues/138 + someone from the community could volunteer to moderate it for you.

**Comment by blacklight447-ptio** [comment]
Moderation isn't really the problem, we already moderate the other problems. problem is the video platforms like these often gets used to host pirated content, which could mean legal troubles for a small time project like us.

Anyway is its highly unlikely to to happen (right now, at least), Ill close this issue, anyone is free to comment if they think it should be discussed further.

**Comment by blacklight447-ptio** [comment]
Moderation isn't really the problem, we already moderate the other problems. problem is the video platforms like these often gets used to host pirated content, which could mean legal troubles for a small time project like us.

Anyway is its highly unlikely to to happen (right now, at least), Ill close this issue, anyone is free to comment if they think it should be discussed further.

**Comment by Zig-03** [comment]
> Moderation isn't really the problem, we already moderate the other problems. problem is the video platforms like these often gets used to host pirated content, which could mean legal troubles for a small time project like us.

You can avoid pirated content thanks to the moderation tools that peertube provides, such as https://github.com/Chocobozzz/PeerTube/issues/138 (manual video validation by a moderator). So you'd turn that on, and whoever uploads videos will have to wait until **you** take a look at what they uploaded and **you** decide whether it's OK to have that on **your** instance or not. You could even specify in the terms for your instance that validation can take up to 7 or whatever, days. You dictate the rules, so pick the ones that suite your team's possibilities and whatnot.
