### ISSUE TITLE
✨ Feature Suggestion | Add Grin and Beam coins

### ISSUE THREAD

**Issue by bissembert1618** [privacytoolsIO/privacytools.io#947]
## Description:
Please add as donation method the following coins: 
- Grin
- Beam

**Comment by blacklight447-ptio** [comment]
Could you make a case for these coins as why they should be added?

**Comment by Mikaela** [comment]
I would refer to https://github.com/privacytoolsIO/privacytools.io/issues/798 as a reason why they shouldn't be added until otherwise proven.

**Comment by blacklight447-ptio** [comment]
@bissembert1618 I would like to to make a case for these coins and explain why they should be added. If you don't in two days, I will close the issue.

**Comment by blacklight447-ptio** [comment]
Closing because of unresponsive initiator.
