### ISSUE TITLE
✨ Feature Suggestion | Host ZeroNet proxy instance

### ISSUE THREAD

**Issue by filips123** [privacytoolsIO/privacytools.io#952]
[ZeroNet](https://zeronet.io/) is "Open, free and uncensorable websites, using Bitcoin cryptography and BitTorrent network". You could run open ZeroNet proxy on privacytools website.

Also, add ZeroNet as a suggestion on your site.

**Comment by blacklight447-ptio** [comment]
While I don't want to bash on cryptocurrency s, a network involving them often set off alarms in my head. Could you explain what Zeronet would over over Tor? and what do those .bit addresses add over v3 .onion services? To get the conversation started :).

**Comment by filips123** [comment]
It doesn't use cryptocurrencies. It only uses Bitcoin's cryptography and BitTorrent network.

The main advantage over classic onion sites is that sites are distrubited and hosted by visitors.
They can also be interactive and with dynamic content. You can see slides about this on [Google Docs presentation](https://docs.google.com/presentation/d/1_2qK1IuOKJ51pgBvllZ9Yu7Au2l551t3XBgyTSvilew/pub?start=false&loop=false&delayms=3000#slide=id.g9a1cce9ee_0_4).

Althrough it is not anonymous (it leaks IPs), it can be set up to connect over Tor, which makes it more anonymous.

And .bit domains are optional. They are using [NameCoin](https://namecoin.org/) but only to allow memoriable domains. Without it, sites are using addresses (like Bitcoin's) instead of domains.

**Comment by gjhklfdsa** [comment]
> While I don't want to bash on cryptocurrency s, a network involving them often set off alarms in my head. Could you explain what Zeronet would over over Tor? and what do those .bit addresses add over v3 .onion services and why it is worth dedicating server resources to? To get the conversation started :).

I think you are assume ZeroNet is like TOR when it is more like an easier-to-use and more adopted alternative to FreeNet.

It is based on BitTorrent with many privacy hardening features.
NameCoin is used for the domains management.

I personally, only use ZeroNet over .onion trackers which is very easy to set up:

Allegedly, they will have full i2p support soon as well. :)

**Comment by gjhklfdsa** [comment]
> While I don't want to bash on cryptocurrency s

I'm not fully certain what your point is, but [ZeroNet](https://www.wikipedia.org/wiki/ZeroNet) uses NameCoin for making domains more human-friendly. 

NameCoin is actually fairly well adopted in the clear-net.

**Comment by blacklight447-ptio** [comment]
@JonahAragon thoughts?

**Comment by Mikaela** [comment]
I guess the risks would be similar to [Tor2web](https://github.com/globaleaks/Tor2web/) instance

**Comment by filips123** [comment]
@blacklight447-ptio Can you post an explanation, please?

**Comment by blacklight447-ptio** [comment]
After some thought and discussion, it was lately determined that we do not consider it worth it to host a zeronet instance. Mostly because it would be another service to maintain and secure, but also because there seem to be a fairly low demand for it. If we got more reports of people who would want a zeronet instance, we could reconsider it again. :)
