### ISSUE TITLE
🆕 Software Suggestion | Redox

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#954]
## Basic Information

**Name:** Redox
**Category:** Operating System
**URL:** https://gitlab.redox-os.org/redox-os/redox

## Description

![](https://gitlab.redox-os.org/redox-os/assets/raw/master/screenshots/redox%20running.jpeg)

**Comment by gjhklfdsa** [comment]
I gotta say, Redox is so far doing a great job in security.

One being that they use a micro kernel over a monolithic.
Any security expert will tell you abut the security advantages of a micro kernel.

Plus, they are free software. Although, this might change later on and start using non-free firmware.

**Comment by gjhklfdsa** [comment]
Wouldn't recommend adding to main since it is still highly experimental but, I think it would make a great addition to worth mentioning.

**Comment by blacklight447-ptio** [comment]
Also, while redox is nice, it really is not meant to be used as an actule os yet.

**Comment by Zig-03** [comment]
> Plus, they are free software. Although, this might change later on and start using non-free firmware.

Yep, because they use a permissive license (MIT) instead of GPLv3 or similar.

**Comment by blacklight447-ptio** [comment]
Redox is not really appropriate for Daily usage as of now, but it has some great potential.
I close this issue now  and say we won't add it, but will keep an eye on this project as it matures, and maybe open this issue up again at a later point in time.
