### ISSUE TITLE
🌐 Website Issue | Revert to WTFPL

### ISSUE THREAD

**Issue by gjhklfdsa** [privacytoolsIO/privacytools.io#955]
**Feature**: Revert license to [WTFPL](https://www.wikipedia.org/wiki/WTFPL).
Nothing was wrong with [WTFPL](https://www.wikipedia.org/wiki/WTFPL), why was it changed?

**Comment by Mikaela** [comment]
>  Nothing was wrong with WTFPL, why was it changed?

Quoting @JonahAragon from https://github.com/privacytoolsIO/privacytools.io/pull/940

> Releasing our work into the public domain seems like the correct path. WTFPL currently grants users an unlimited license to use our work, which is maybe fine, but CC0 actually revokes all copyright wherever possible, and falls back to an unlimited license where that's legally not a possibility. CC0 also includes a warranty disclaimer (so this merge Closes #919).

@Shifterovich from #919:

> WTFPL is a shitty license. We should use an actual license like MIT or preferably CC0.

Wikipedia: 

> The Free Software Foundation states that "Both public domain works and the lax license provided by the Unlicense are compatible with the GNU GPL." However, for dedicating software to the public domain it recommends CC0 over the Unlicense, stating that CC0 "is more thorough and mature than the Unlicense".[1]

> The Fedora Project recommends CC0 over the Unlicense because the former is "a more comprehensive legal text".[10]

> The Unlicense has been criticized, for instance by the OSI, for being possibly inconsistent and non-standard, and for making it difficult for some projects to accept Unlicensed code as third-party contributions; leaving too much room for interpretation; and possibly being incoherent in some legal systems.[13][14][15] 

* https://en.wikipedia.org/wiki/Unlicense#Reception

**Comment by Shifterovich** [comment]
To elaborate on my comment about it being a shitty license, in #919 we found that it doesn't include a warranty claim unlike actually reasonable licenses like MIT.
