### ISSUE TITLE
🆕 Software Suggestion | How does webbrowser Bromite compare to Firefox and Brave?

### ISSUE THREAD

**Issue by Meteor0id** [privacytoolsIO/privacytools.io#961]
## Basic Information

**Name:** Bromite
**Category:** Webbrowser
**URL:** https://www.bromite.org/

## Description
Bromite claims to be aimed at privacy. It has an Android version as well.

**Comment by blacklight447-ptio** [comment]
@meteor0id would you like to start off the discussion by making a compelling case to include bromite into privacytools.io? :)

**Comment by KonoromiHimaries** [comment]
+ DNS over HTTPS
https://github.com/bromite/bromite/wiki/Enabling-DNS-over-HTTPS

https://nakedsecurity.sophos.com/2019/04/24/dns-over-https-is-coming-whether-isps-and-governments-like-it-or-not/
https://www.cloudflare.com/ssl/encrypted-sni/

**Comment by beerisgood** [comment]
[Bromite](https://www.bromite.org/) is also a very secure browser and use security enhancement patches from GrapheneOS project. (GrapheneOS is the new CopperheadOS)

And for privacy it use privacy enhancement patches from → Iridium, → Inox patchset, → Brave and → ungoogled-chromium projects

Also it exist a (own) F-DROID Repository.

The GrapheneOS dev recommend it too: https://grapheneos.org/usage#web-browsing

**Comment by blacklight447-ptio** [comment]
after researching this, im fairly impressed by it, i think it would fit a nice replacement from brave.

**Comment by nitrohorse** [comment]
I don’t think we differentiate between Android/Desktop/iOS browsers in https://www.privacytools.io/browsers/#browser; we would need to clearly state Bromite is only for Android. Maybe having separate browser sections for mobile OSs would be beneficial?

**Comment by blacklight447-ptio** [comment]
Yes, I would see this as appropriate, then we can link to their specific os based download pages as well. would you be able to make a pull request for this?
