### ISSUE TITLE
🆕 Software Suggestion | Wexond

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#962]
## Basic Information

**Name:** Wexond
**Category:** browser
**URL:** https://github.com/wexond/wexond

## Description

Wexond is an extensible and privacy-focused web browser with a totally different user experience, built on top of Electron, TypeScript, React and styled-components. It aims to be fast, private, beautiful, extensible and functional.

![](https://camo.githubusercontent.com/1dabe8bc1b0244b2a4e4f3be5c4da8aa1333c244/68747470733a2f2f7765786f6e642e6e65742f696d672f73637265656e2e706e67)

**Comment by blacklight447-ptio** [comment]
I have never heard of this browser, and it seems to be nothing more then yet another chromium fork. Appart from the fact that it claims to be private, why would we want to add this.

**Comment by beerisgood** [comment]
Electron is chromium but had a lot security problems in past
Really suggest that then?

**Comment by blacklight447-ptio** [comment]
What I am asking is why we should add it, as i don't see any legitamate reason why.

**Comment by KonoromiHimaries** [comment]
it closed, because wexond not support extensions to advanced protection
