### ISSUE TITLE
🆕 Software Suggestion | Kiwi Browser

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#964]
## Basic Information

**Name:** Kiwi Browser
**Category:** browser
**URL:** https://github.com/kiwibrowser/android

## Description

still support `extensions` to protecting privacy
https://www.privacytools.io/browsers/#addons
https://github.com/NanoAdblocker/NanoCore/issues/238#issuecomment-497933410

**Comment by JonahAragon** [comment]
Unclear to me how this is better than even Chrome... Source hasn't been updated since January :/

**Comment by blacklight447-ptio** [comment]
Yeah, unless @konoromi can provide a strong case for inclusion into privacytools.io, I would close the issue.

**Comment by KonoromiHimaries** [comment]
> Yeah, unless @konoromi can provide a strong case for inclusion into privacytools.io, I would close the issue.

https://www.privacytools.io/browsers/#browser
brave for android dosen't support extension to protect privacy
firefox for android, rumor circulates that just as chrome stops supporting ublock origin in a some time

is there any other alternative for ublock origin in android? no, adblock does not provide sufficient protection.

**Comment by blacklight447-ptio** [comment]
Well brave blocks ads by its own so doesnt need ublock realistically.

**Comment by KonoromiHimaries** [comment]
adblock dosen't support advanced filters, example. https://filters.adtidy.org/extension/chromium/filters/3.txt

**Comment by beerisgood** [comment]
@blacklight447-ptio wrong. Brave replace ads with own
Highly not recommend

**Comment by blacklight447-ptio** [comment]
@beerisgood from what i have heard, this is an optional setting with the bat program, and disabled by default.

**Comment by Mikaela** [comment]
The BAT program is not even available everywhere. 

> Unclear to me how this is better than even Chrome... Source hasn't been updated since January :/

I will also close due to this.

**Comment by KonoromiHimaries** [comment]
@Mikaela please check the new link

**Comment by KonoromiHimaries** [comment]
@Mikaela can you re-check the new link which I added?

**Comment by Mikaela** [comment]
What new link?

**Comment by KonoromiHimaries** [comment]
@Mikaela `https://play.google.com/store/apps/details?id=com.kiwibrowser.browser`

**Comment by hjyoung1** [comment]
Full Up to date source is now available.
https://github.com/kiwibrowser/src
Please reopen this issue. 
Thanks.
