### ISSUE TITLE
🌐 Website Issue | Redirect service links to .onion

### ISSUE THREAD

**Issue by blacklight447-ptio** [privacytoolsIO/privacytools.io#968]
When visiting the .onion version of privacytools.io, wouldn't it be more logical to link to the .onion versions of our services that also support it (like our searx instance). what do you guys think?

**Comment by ghbjklhv** [comment]
Maybe replace where the TOR link is with a clearnet link.
Plenty of spherical images meaning WWW.

Then just make the main URL the .onion link.

**Comment by JonahAragon** [comment]
This is a static site, there's no server-side processing going on to make changes like this.
