### ISSUE TITLE
Why stop recommend Chrome/ Chromium based browser is necessary

### ISSUE THREAD

**Issue by beerisgood** [privacytoolsIO/privacytools.io#969]
Chrome will stop supporting AdBlocker for normal users and only provide that for "enterprise": https://9to5google.com/2019/05/29/chrome-ad-blocking-enterprise-manifest-v3/

So Google (Browser's) are then like AdBlock Plus or even worse.

In my opinion **Privacy**tools shouldn't recommend such browsers.
No matter if it's possible to use (unsecure) sideload ways for install such addons.

AdBlocker is first step for users to block tracking, malware and of course that's important here.
Also ads on safe sites include malware a lot in the past

**Comment by blacklight447-ptio** [comment]
being able to block ads doesnt need to be there for a browser to be privacy friendly, see tor browser for example. Also just because chrome does, does nit mean the all chromium forks will too.

**Comment by Mikaela** [comment]
At the moment only Brave seems to be listed and I am under impression that they wouldn't merge this change and regardless contains a build-in adblocker. Which browser did you have in mind?

* https://www.privacytools.io/browsers/

**Comment by beerisgood** [comment]
@blacklight447-ptio Tor Browser is for anonymous browsing which is another thing.
If forks doesn't follow chrome, they need to use old code or own store. Both aren't good solutions in terms of security.


@Mikaela you mean which I'm recommend?
At the moment: Firefox

Brave use his own ad system which isn't trustworthy

**Comment by blacklight447-ptio** [comment]
@beerisgood Which is perfectly fine, tor browser does the same, also nobody said tor browser is only for anonymity. Its just that you can ude it for that purpose.

**Comment by beerisgood** [comment]
@blacklight447-ptio what did you mean with "does the same"?

Tor browser *is* for browsing anonymously and hide yourself against fingerprinting as much as possible.
But it's not using a AdBlocker or other add-ons which protect you against ads, malware  and if you use such / customize Tor browser in any way, you got a unique build which isn't recommend.
Any way this issue is about Chrome/ Chromium browser

**Comment by Mikaela** [comment]
I am closing this as the only Chromium based browser we list is Brave and it's not affected by this issue. Please correct me if I am wrong.

**Comment by KonoromiHimaries** [comment]
Kiwi Browser https://github.com/privacytoolsIO/privacytools.io/issues/964 is ok in this regard

**Comment by Mikaela** [comment]
[Opera, Brave, Vivaldi to ignore Chrome's anti-ad-blocker changes, despite shared codebase](https://www.zdnet.com/article/opera-brave-vivaldi-to-ignore-chromes-anti-ad-blocker-changes-despite-shared-codebase/) via [nitrohorse on the forum](https://forum.privacytools.io/t/opera-brave-vivaldi-to-ignore-chromes-anti-ad-blocker-changes/844?u=mikaela).

However I think only Brave is open source from those, but I think the same thing is going to apply on other Chromium based browsers too.

**Comment by beerisgood** [comment]
Let's see how "good" Google implement this API restriction
