### ISSUE TITLE
Add paste services

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#97]
Maybe we should add paste services too? I think it's a good idea to have paste services listed, as some people want to share code or simply plain text files with some privacy _(and without pastebin captchas)_.

For example,  [ghostbin](https://ghostbin.com) seems like a good candidate.

[It's open source](http://git.howett.net/paste.git), supports expiration and **encryption** _- perfect for privacy_. 
Supports code highlighting, having an account for managing pastes _- like pastebin, gist.github.com, ..._.

Also

> Ghostbin user accounts exist solely for keeping track of your own pastes.
> No personally-identifying information is retained as part of your user account—even when you use Email. Promise.

**Comment by privacytoolsIO** [comment]
Good idea. Are you familiar with Ghostbin alternatives so we can add more services? http://alternativeto.net/software/ghostbin/?license=opensource

**Comment by Shifterovich** [comment]
[Hastebin](http://hastebin.com) is [open source](https://github.com/seejohnrun/haste-server) too, but doesn't use https. It's really just an alternative to pastebin.

I could recommend zerobin, as it's widely used on I2P, but the [repo](https://github.com/sebsauvage/ZeroBin) says that you should use [PrivateBin](https://github.com/PrivateBin/PrivateBin).

**Comment by privacytoolsIO** [comment]
So lets add Ghostbin, PrivateBin and 0bin.net

**Comment by Shifterovich** [comment]
@privacytoolsIO Why 0bin.net?

**Comment by privacytoolsIO** [comment]
https, open source, can be self hosted. [faq here](https://0bin.net/faq/)

**Comment by Shifterovich** [comment]
@privacytoolsIO It's client-side.

**Comment by kewde** [comment]
I like the proposed websites and as previous mentioned: Hastebin should not be included.

**Comment by privacytoolsIO** [comment]
Just found out that hastebin supports https: https://hastebin.com/

**Comment by privacytoolsIO** [comment]
Should we remove ProtectedText.com? They never released the server source code according to this prism break discussion: https://github.com/nylira/prism-break/issues/1078

**Comment by Shifterovich** [comment]
Interesting. hastebin does support HTTPS, but simply typing "hastebin.com" into the URL bar redirects you to the http version. HTTPS Everywhere doesn't help.

**Comment by kewde** [comment]
A http to https redirect should be the defacto standard.
Any pastebin service that provides encryption and is not open source does not seem like a good choice to me. 

Gostbin, 0bin, PrivateBin are all open source and support HTTPS, I think those should suffice?
