### ISSUE TITLE
✨ Feature Suggestion | Guest-of-the-Month

### ISSUE THREAD

**Issue by five-c-d** [privacytoolsIO/privacytools.io#972]
## Description:  continuation of a discussion in #848 

>> I think guest-blogging might be a hard sell to most
> 
> Well, if you are hoping that Bruce Schneier and Edward Snowden will drop everything

@JonahAragon -- here is a good person to ask:  Fredrik Strömberg, co-founder of Mullvad, in the VPN provider listings since forever, contact info at top of the PDF that was just released, https://www.mullvad.net/media/system-transparency-rev4.pdf where they are talking about building a cryptographically-**provable** no-logging-VPN (with similar but not identical technology to how signal-server uses server-side SGX enclaves to give client-side signal4smartphone the ability to perform remote-attestation *before* uploading the addressbook hashnums -- assuming one enables addressbook integration of course, it is on-by-default but optional).  

Because mullvad is making a publicity-push right now, specifically appealing to "reviewers" aka privacyToolsIO folks with their objective-listings-hats on their heads, they might be receptive to guest-blogger-of-the-month sort of arrangement?  == https://mullvad.net/en/blog/2019/6/3/system-transparency-future/  (which I heard about [here](https://community.signalusers.org/t/system-transparency-is-the-future-within-certain-limitations-it-can-be-used-to-prove-to-the-owner-system-administrator-user-or-a-third-party-exactly-what-is-currently-running-on-the-system-and-what-it-has-been-permitted-to-run-in-the-past/7962))   You can toss a few stock questions every guest-blogger gets asked -- 

*  what is most important to personal privacy in the coming ten years, 
*  what is most important to infosec in the coming ten years, 
*  what politician or political party do you trust the most, 
*  what is the best way to fight global mass surveillance during the next 12 months, 
*  and a basic what-is-your-background type of question maybe 

-- then dive straight into their personal-opinion listing of tool-recommendations for everyday citizenry.  They can annotate their listings with rationale, or discussion, or whatever, or if they are in a hurry just ram it out with "best tool for non-tech-savvy and best tool for more-advanced endusers" in each category they care to make a statement about. 

p.s.  Also, still strongly recommend asking Snowden and maybe Schneier.  Worst they can do, is tell you to stop bothering them please :-)  But they *might* say "okay"

**Comment by blacklight447-ptio** [comment]
We decided that this currently to big of a hassle with our current resources. It may be an idea for the future though, closing for now.
