### ISSUE TITLE
🆕 Software Suggestion | Iridium Browser

### ISSUE THREAD

**Issue by KonoromiHimaries** [privacytoolsIO/privacytools.io#973]
## Basic Information

**Name:** Iridium Browser
**Category:** browser
**URL:** https://iridiumbrowser.de/

## Description

`https://spyware.neocities.org/articles/browsers.html`
`https://github.com/iridium-browser/tracker/wiki/Differences-between-Iridium-and-Chromium`

**Comment by beerisgood** [comment]
Please read https://github.com/privacytoolsIO/privacytools.io/issues/969

**Comment by Mikaela** [comment]
Could you explain in your own words why it should be recommended?

**Comment by KonoromiHimaries** [comment]
because it is a chromium, chromium is fastest compared to firefox and is not a brave https://github.com/privacytoolsIO/privacytools.io/issues/161

**Comment by beerisgood** [comment]
What a explanation xD

I also wonder why you recommend so much Chromium forks. What's your point with that? Are you try to push that browser?

Anyway no advantages against better browser like Firefox (which is fast too and speed isn't everything a browser need)

**Comment by KonoromiHimaries** [comment]
> I also wonder why you recommend so much Chromium forks. What's your point with that? Are you try to push that browser?

I tried, but the difference in performance is significant, for me this barrier is impossible to overcome

**Comment by blacklight447-ptio** [comment]
@KonoromiHimaries Whether chromium is faster depends completely on your setup. Firefox is faster on mine.

**Comment by KonoromiHimaries** [comment]
@blacklight447-ptio i try tested on this simple game `http://slither.io/` and chromium is a winner

**Comment by blacklight447-ptio** [comment]
@KonoromiHimaries On your setup, yes. But on my setup, and many others, firefox is faster. Again it depends on many factors.

**Comment by Kcchouette** [comment]
Best chromium fork should be https://github.com/Eloston/ungoogled-chromium I think

**Comment by KonoromiHimaries** [comment]
> Best chromium fork should be https://github.com/Eloston/ungoogled-chromium I think

@Kcchouette i don't think that so

[![img](https://user-images.githubusercontent.com/5884000/59567059-b178e700-9068-11e9-932c-75c1a7ef7bda.png)](https://ungoogled-software.github.io/ungoogled-chromium-binaries/)

**Comment by blacklight447-ptio** [comment]
I currently don't really see a reason to add this.  Could you give some more argumentation on why you think this should be included?

**Comment by gitbugged** [comment]
> Best chromium fork should be https://github.com/Eloston/ungoogled-chromium I think

Agree with this, since they already include Iridium *and* addition degoogling patches.

**Comment by beerisgood** [comment]
See post from KonoromiHimaries

**Comment by Kcchouette** [comment]
You can use the repo (https://github.com/Eloston/ungoogled-chromium) to use your own-build version @beerisgood

**Comment by beerisgood** [comment]
@Kcchouette most people can't so that's no option

**Comment by blacklight447-ptio** [comment]
After some research, it seems like iridium really slacks behind on keeping up with chromium, therefor we do not see it as a secure alternative. 
Closing issue.
