### ISSUE TITLE
🆕 Software Suggestion | Maemo Leste

### ISSUE THREAD

**Issue by Zig-03** [privacytoolsIO/privacytools.io#974]
## Basic Information

**Name:** Maemo Leste
**Category:** Mobile Operating Systems (Worth Mentioning)
**URL:** https://maemo-leste.github.io/

## Description
Maemo Leste - a Devuan based FOSS OS that aims to provide a free Maemo experience on mobile phones and tablets like the Nokia N900, Motorola Droid 4, Allwinner Tablets and more.

**Comment by blacklight447-ptio** [comment]
While I think it would be agood to keep an eye on this project, Their site reads this: The project is not usable as a daily driver for your device, Maemo Leste is currently in development phase and we are actively searching for developers.

As such, it wouldn't really make sense to add this OS now. Feel free to bump this issue later on when the developers think its production ready, it seems like a really cool project :).
Closing for now.
