### ISSUE TITLE
🌐 Website Issue | That One Privacy Site Compromised?

### ISSUE THREAD

**Issue by jingofett** [privacytoolsIO/privacytools.io#975]
## Description
It seems that the "Simple VPN Comparison" has been compromised. There are a ton of VPN services now with green across the board, that I've never heard of. Such as "Fastestvpn" and "MinecraftVPN". F-secure and Norton are also green across the board.

## Screenshots

![image](https://user-images.githubusercontent.com/8313249/58963554-eea5c500-879c-11e9-9ad6-6c2434715cb6.png)
![image](https://user-images.githubusercontent.com/8313249/58963677-21e85400-879d-11e9-9cbf-e25caeb62ac5.png)
![image](https://user-images.githubusercontent.com/8313249/58963781-4ba17b00-879d-11e9-854b-9621dcdd46f5.png)
![image](https://user-images.githubusercontent.com/8313249/58963813-59570080-879d-11e9-97b8-80ebab8ca07b.png)

**Comment by danarel** [comment]
That does appear to be the case. unless it's a coding error with something he's working on and it shouldn't be live yet. But I would say he's been compromised from the looks of it.

**Comment by JonahAragon** [comment]
I reached out to him via email about this issue, and I'll give him some time to respond.

**Comment by beardog108** [comment]
15 days after making this issue, the comparison still has sketchy entries. I suggest we consider removing the link to his site on our VPN information section. 

If he is merely AFK and comes back to fix it, we can re-add.

**Comment by danarel** [comment]
Yeah, and he's been MIA on Twitter since May 1. I hope he's okay, but his site is certainly compromised at this point.

**Comment by stancl** [comment]
@jonaharagon please remove the link, I'm don't have access to a computer right now.

**Comment by beardog108** [comment]
I ran a vuln scan on the site, it appears the plugin version used to manage the data tables has an SQL injection vulnerability, and unauthenticated shell upload. So yeah the site is definitely fully compromised.

**Comment by beardog108** [comment]
https://gist.github.com/beardog108/49063994ec0ae71c1c83d5c6f875599a

**Comment by beardog108** [comment]
https://www.reddit.com/r/privacy/comments/c30ycv/that_one_privacy_site_compromised_june_2019/

**Comment by beardog108** [comment]
He responded on reddit, we can close this issue now as the site is fine and will be fixed: 

https://www.reddit.com/r/privacy/comments/c30ycv/that_one_privacy_site_compromised_june_2019/erqbcq9

**Comment by JonahAragon** [comment]
> maybe PM them next time

Maybe respond to your emails next time 😝 

Looks good to me.
