### ISSUE TITLE
Add tutorials for some tools

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#98]
I think we should add tutorials for some of the tools. How to install, use, secure the tools, ... I'm willing to help writing them.

Thoughts?

**Comment by privacytoolsIO** [comment]
That would be amazing. Please feel free to write them. We can publish them on a new single page.

**Comment by spiraldancing** [comment]
I've been following PTIO project (mostly silently) for years, now trying to become an active contributor.

Is this still an active task?  Shifterovich, are you still working on it, still want help?  How can I help?

**Comment by Shifterovich** [comment]
I've been very busy lately, but I'd like to start working on it once I get the darknet mirrors to work. I _should_ have a lot of free time in ~1 month.

**Comment by spiraldancing** [comment]
Looks like you are one of the primary contributors.  I'm looking thru the issues list, and I can be available to contribute to almost anything.  If you want help on anything, or want to point me at higher priority tasks, feel free.

I'm a .NET / web developer, 14 years, but very little exp contributing to F/OSS ... I want to change that.

On March 22, 2017 9:59:35 AM CDT, Samuel Shifterovich <notifications@github.com> wrote:
>I've been very busy lately, but I'd like to start working on it once I
>get the darknet mirrors to work. I _should_ have a lot of free time in
>~1 month.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/privacytoolsIO/privacytools.io/issues/98#issuecomment-288426060

-- 
Let's go exploring.
Sent from my mobile; please excuse my brevity.

**Comment by Shifterovich** [comment]
Do you use Wire or Telegram?

**Comment by spiraldancing** [comment]
I'm on Wire, @spiraldancing.

On March 22, 2017 10:12:44 AM CDT, Samuel Shifterovich <notifications@github.com> wrote:
>Do you use Wire or Telegram?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/privacytoolsIO/privacytools.io/issues/98#issuecomment-288430363

--
If you need inspiring words, don't do it.  --Elon Musk
Sent from my mobile; please excuse my brevity.

**Comment by Vincevrp** [comment]
> EFF Project with tutorials to setup and use handy software and tools:
> [Tips, Tools and How-tos for Safer Online Communications](https://ssd.eff.org/)

This one is referenced on the website.

I suggest we can open new issues for more specific guides, tutorials, etc.
