### ISSUE TITLE
💬 Discussion | Add i2p Websites

### ISSUE THREAD

**Issue by ghbjklhv** [privacytoolsIO/privacytools.io#981]
**Discussion**: Many websites have a TOR site attached to their card.
This is great, IP anonymity and security isn't brought up enough IMHO.
I've been trying to compile a separate list for i2p sites:

- SearX: http://ransack.i2p/
(the end)

As you can see, it is very short.
I wanted to ask and see if anybody knows of a site I missed and see if the privacytools.io team would be interested in adding them to their site.

Thanks! :)

**Comment by Mikaela** [comment]
I think we are interested as we are listing I2P in [self-contained networks](https://www.privacytools.io/software/networks/) and I think PR would be welcome.

It might be a good idea to see how is the Tor icon made.

> SearX: http://ransack.i2p/

Where does this come from? I think our instance would fall under #139.

**Comment by ghbjklhv** [comment]
> Where does this come from? I think our instance would fall under #139.
@Mikaela Not sure I follow, bur the [privacytools.i2p](http://privacytools.i2p/) mirror has been down for a while.
Otherwise, we could list [search.privacytools.i2p](http://search.privacytools.i2p/) as a SearX i2p instance.

As for where the i2p instance is listed: https://github.com/asciimoo/searx/wiki/Searx-instances#alive-and-running

**Comment by TNTBOMBOM** [comment]
http://legwork.i2p/ -> P2P Search Engine based YaCy

http://bote.i2p/ -> This provide plugin decentralized email like

http://hq.postman.i2p/ -> This is free of charge email provider, it provide i2p and clearnet email.
