### ISSUE TITLE
🆕 Software Suggestion | Mojeek Search Engine

### ISSUE THREAD

**Issue by FinnBrownbill** [privacytoolsIO/privacytools.io#982]
## Basic Information

**Name:** Mojeek
**Category:** Search Engine
**URL:** https://www.mojeek.com

## Description

Mojeek was the first search engine ever to state in their privacy policy that they don’t track their users, and have been committed to it ever since. Link to original privacy policy from March 2006 - https://web.archive.org/web/20060318104627/http://www.mojeek.com/privacy.html

Mojeek follows a strict no tracking privacy policy. Mojeek does not possess any previous identifying information on you, such as IP addresses, search history or click behaviour. More details can be found in the privacy policy: https://www.mojeek.com/about/privacy.html 

A few privacy metasearch engines are currently listed, but Mojeek is an independent crawler based search engine with its own algorithm and index of web pages. With an index of over 2 billion pages and plans in place to quadruple the size within the next 12-24 months, it is attempting to be a true genuine alternative. This is where those currently listed on privacytools.io get their organic results from: Startpage uses Google results, DDG mainly uses Bing, Qwant uses Bing for their English results, and Searx can use a variety of search engines but mainly Bing.   

About page: https://www.mojeek.com/about

**Comment by blacklight447-ptio** [comment]
While I generally am not a fan of UK based services, do to their creepy government, actully  having a private search engine with an indepent engine is attractive thing to have

**Comment by danarel** [comment]
The independent engine is a big sell. The search results kind of suck (subjective), but I would worry this would draw the same criticism the site gets for listing DDG: It seems to be closed source and bad location for privacy laws.

I could see this in worth mentioning though.

**Comment by blacklight447-ptio** [comment]
@JonahAragon  @Mikaela @BurungHantu1605 some thoughts?

**Comment by Mikaela** [comment]
I am not familiar with Mojeek, but if you checked the links, I can agree with the previous commentors and am fine with it being added as worth mentioning.

**Comment by JonahAragon** [comment]
I'd approve a Worth Mentioning PR, but I don't know enough about it to make it a Top 3 recommendation.

**Comment by blacklight447-ptio** [comment]
After some searching, i haven't been able to find anything especially shady, id say add as worth mentioning.

**Comment by erciccione** [comment]
Closed source and based in a country with very restrictive privacy policies, this 2 should be enough to not list it. Also, I think would be a big mistake to list this search engine with so few research. Basically it's being added as "worth mentioning" only based on what they say on their website.

As a user, i would really like to see more accurate vetting before listing a service.

**Comment by blacklight447-ptio** [comment]
@erciccione  closed source is not a problem at all here, as with services, your not able to verify what runs on their servers. You could only make it a point about being selfhostable. About country, duckduckgo is also in a privacy unfriendly country ( the usa) AND is "closed source", yet it is in our top recommendations, so if these arguments were to stop mojeek from becoming a worth mentioning, you also mean we should directly remove duckduckgo.

**Comment by erciccione** [comment]
> closed source is not a problem at all here

I think it should be, beside the unability to check what is actually running. Being open source denote that a company/service has a community oriented approach and allow external users/contributors to vet the code and propose changes. This is impossible with closed source code, this is literally just trusting an 'about' page.

> duckduckgo is also in a privacy unfriendly country ( the usa) AND is "closed source", yet it is in our top recommendations

Beside the fact that some parts of DuckDuckGo [are open source](https://help.duckduckgo.com/duckduckgo-help-pages/open-source/opensource-overview/), DDG has been around for many years as well, but during this time it has been heavily used and deeply by researchers. Privacy concerns have been rised and the company answered. The same cannot be said for Mojeek.

> ive done over an hour of searching

This is the main issue IMHO. Privacy is a very serious matter, some people could be sensitive subjects who could be risking their freedom. Using one tool or another could change the life of these people. I think a good approach would be to list only services which have been around for some time *and* have been deeply analyzed. I don't think that few hours of research are enough, when there is people's freedom at stake.

My point is, services shouldn't be listed so easily and with so poor analysis. I deeply appreciate the effort and time you put *for free* in this project, but I would personally prefer to see less stuff added to privacytools, but of better quality.

**Comment by blacklight447-ptio** [comment]
Point is, even if there is source code, you have not a clue whats actully running on their service. There is not much more then researching other then searching currently. Its why its only as a worth mentioning, not a recommendation. The worth mentioning only gives other options which might be more privacy friendly if the recommendations are not enough for the reader. Then over time, mojeek can grow and find more ways to either prove itself, or maybe make a slip up.


about quality assurance, you should see the ticket i opened for exactly this issue, and we are still discussing the actule terms of inclusion, besides our currently vague"must be privacy friendly, open source preffered but not required" approach, your free to join up there so we can solve it as a community and improve privacytools.io as the community resource it is :).

**Comment by erciccione** [comment]
> you have not a clue whats actully running on their service

I already acknowledged this, my point was that *Being open source denote that a company/service has a community oriented approach and allow external users/contributors to vet the code and propose changes*

> your free to join up there so we can solve it as a community and improve privacytools.io as the community resource it is :).

I will be happy to participate. Privacytools was one of the first tools i stumbled upon when i first started being heavily interested about privacy, i thought it was time to give back something to this project.
