### ISSUE TITLE
FR Website Issue | Sweden translated by Switzerland

### ISSUE THREAD

**Issue by jodumont** [privacytoolsIO/privacytools.io#986]
on the french version it declare **Switzerland** is a part of the 14 eyes which is false + the flag represent **Sweden** as it is mention in english

![Untitled](https://user-images.githubusercontent.com/5204724/59250139-b41dab80-8c26-11e9-8d6b-d62834afa9a5.jpg)

## Saddly I didnt find the page/post on github to do a PR

But if someones could indicate me where are the french version It will be my pleasure to propose the change ;)

**Comment by Shifterovich** [comment]
We don't host the French translation, it's someone else's project.

I couldn't find who is the maintainer of the French version. Perhaps it's somewhere in the French text?

**Comment by jodumont** [comment]
### it is apparently hosted on this gitlab: **booteille.gitlab.io**
![image](https://user-images.githubusercontent.com/5204724/59301137-35118d00-8c91-11e9-9242-da42ccadc0e8.png)

### which under a **google-cloud IP**
![image](https://user-images.githubusercontent.com/5204724/59301243-6c803980-8c91-11e9-85eb-361e004a8590.png)

**Comment by Booteille** [comment]
Hi!

Thanks for mentioning me, I took the time to fix it.
The french version is hosted on Gitlab : https://gitlab.com/Booteille/privacytools

Don't hesitate to ping me again if needed.

**Comment by Shifterovich** [comment]
Right, I just couldn't find it this time. Thanks @jodumont. @Booteille add a link to your repo to the site.
