### ISSUE TITLE
✨ Feature Suggestion | Telegram Channel Feedshub

### ISSUE THREAD

**Issue by scafroglia93** [privacytoolsIO/privacytools.io#990]
## Description:

Within this telegram channel it will be possible to receive news concerning security issues, releases and everything related to the world of infosec in real time

https://t.me/feedshub

**Comment by beerisgood** [comment]
While I like this, I wonder why not original URLs are used in that channel. Using short URLs isn't a good think

**Comment by 0ndrey** [comment]
So you're offering to register for a proprietary service to read someone's nonsense? Does this channel have a website? Who does this channel belong to?

**Comment by scafroglia93** [comment]
> While I like this, I wonder why not original URLs are used in that channel. Using short URLs isn't a good think

the service that offers the short links has been properly verified by the undersigned.
It is also possible to manage linings more efficiently

**Comment by scafroglia93** [comment]
> So you're offering to register for a proprietary service to read someone's nonsense? Does this channel have a website? Who does this channel belong to?

You should know that it is people like you who damage this world, our goal is to inform people.

Within this channel I am implementing a series of RSS feeds to stay updated in real time on CVE and other issues related to privacy / security.

What is not a proprietary service?
- Is your bank account not a "proprietary service"?
- Is your internet subscription not a proprietary service?

We end with this hypocrisy and begin to do information properly.
Telegram lends itself well to all this compared to the usual site hard to find for the common public who may be willing to do some reading

"The same github is a proprietary service"

**Comment by 0ndrey** [comment]
> 
> 
> > So you're offering to register for a proprietary service to read someone's nonsense? Does this channel have a website? Who does this channel belong to?
> 
> You should know that it is people like you who damage this world, our goal is to inform people.
> 
> Within this channel I am implementing a series of RSS feeds to stay updated in real time on CVE and other issues related to privacy / security.
> 
> What is not a proprietary service?
> 
>     * Is your bank account not a "proprietary service"?
> 
>     * Is your internet subscription not a proprietary service?
> 
> 
> We end with this hypocrisy and begin to do information properly.
> Telegram lends itself well to all this compared to the usual site hard to find for the common public who may be willing to do some reading
> 
> "The same github is a proprietary service"

Thx! Exhaustive!

**Comment by danarel** [comment]
This wouldn't make sense for PTIO users because PTIO suggests that users use other chat apps other than Telegram because it's not as secure and privacy focused as people think it is.

It's not so much that it's proprietary, but it would be weird to suggest that users join a group on an app that's not recommended for privacy.

**Comment by Mikaela** [comment]
>  If you are currently using an Instant Messenger like WhatsApp, Viber, LINE, ___Telegram___ or Threema, you should pick an alternative here. 

* https://www.privacytools.io/software/im/

And I don't think anyone has time to manage a channel and we already have https://forum.privacytools.io/c/news , please feel free to use it.
