### ISSUE TITLE
🆕 Software Suggestion | Replace Margic Wormhole with croc?

### ISSUE THREAD

**Issue by BurungHantu1605** [privacytoolsIO/privacytools.io#991]
I havent personally used either Magic Wormhole or croc, so I need help deciding this. Apparently croc is based on Magic Wormhole but with better usability. I need opinions on this please.

**Comment by blacklight447-ptio** [comment]
we can also have them both. as both seem like actively maintained, proper projects.

**Comment by blacklight447-ptio** [comment]
After some thinking, our current recommendations seem fine, I wouldn't  see a reason to add another as they effectively do the same.
