### ISSUE TITLE
Can I modify the privacytools.io web page?💬 Discussion | 

### ISSUE THREAD

**Issue by zylstra** [privacytoolsIO/privacytools.io#994]
Can I modify the privacytools.io web page?

**Comment by ghbjklhv** [comment]
It is fully Free/Libre and Open Source last I checked.
License information is stored here: https://github.com/privacytoolsIO/privacytools.io/blob/master/LICENSE.txt
Most pervious versions are under the WTFPL.

**Comment by Mikaela** [comment]
> The Creative Commons CC0 Public Domain Dedication waives copyright interest in a work you've created and dedicates it to the world-wide public domain. Use CC0 to opt out of copyright entirely and ensure your work has the widest reach. As with the Unlicense and typical software licenses, CC0 disclaims warranties. CC0 is very similar to the Unlicense.

* GitHub on https://github.com/privacytoolsIO/privacytools.io/blob/master/LICENSE.txt

If you mean https://privacytools.io/ itself, please feel free to open a pull reuqest for discussing your change.

**Comment by zylstra** [comment]
"feel free to open a pull request" ... I should study (https://help.github.com/en/articles/creating-a-pull-request) how to use Github for a couple hours before I can help your project??  No thanks.  (Unless you have a shorter tutorial.)
