### ISSUE TITLE
🆕 Software Suggestion | Add Yggdrasil to Self-contained Networks

### ISSUE THREAD

**Issue by oijkhg** [privacytoolsIO/privacytools.io#995]
**Description**: Add Yggdrasil to Self-contained Networks
**Why?**: The current internet is mostly proprietary and owned by a few monopolies.
These monopolies have been known to over-exert their influence (at least where I am).
Yggdrasil may help us fix this with creating a FLOSS end-to-end encrypted IPv6 network.
**Does it protected your IP**: For the most part, no. But, ideally networks like i2p should work.
**Had this been discussed before?** This issue is made to revive #685 
**Links**:
https://yggdrasil-network.github.io/

https://www.reddit.com/r/darknetplan

**Comment by BearerOfHonesty** [comment]
https://en.wikipedia.org/wiki/Unlicense#Reception sounds like CC0 might be a better choice even if it's more legalese.

**Comment by Mikaela** [comment]
Has our opinion changed half an year later @privacytoolsIO/editorial @privacytoolsIO/services (https://github.com/privacytoolsIO/privacytools.io/issues/139#issuecomment-489439098) @Shifterovich ?

I seem to have referred to https://github.com/privacytoolsIO/privacytools.io/issues/685#event-2042260299 a few times.

Labeling I2P and Tor for them being supported and appearing at [other public peers](https://github.com/yggdrasil-network/public-peers/tree/master/other) (where funnily I have made the latest commit at the time of writing) and VPN as I have referred to it from so many VPN issues and it's the only VPN I am using. I seem to have 8 alive hosts (including those currently offline).

**Comment by Mikaela** [comment]
Assigning myself as I care about this issue and am interested in making a PR to move this forwards at least a bit unless someone comes to close this.

By assigning I mean to only communicate that I care about the issue and I welcome others to submit the PR or say that they wish to do it by themselves, I don't intent to deserve exclusive rights on it.

**Comment by Mikaela** [comment]
@oijkhg What do you think of https://github.com/privacytoolsIO/privacytools.io/pull/1035/files ?
