### ISSUE TITLE
💬 Discussion | Dual Licensing

### ISSUE THREAD

**Issue by ghbjklhv** [privacytoolsIO/privacytools.io#996]
I wanted to start a discussion about the possibility of dual licensing privacytools.io

The current CC0 contains much unnecessary legal lingo and can be confusing.
Although, under some circumstances this may be useful.

My recommendation is to dual license under a simpler license such as the [Unlicense](https://www.wikipedia.org/wiki/Unlicense#License_terms).
https://www.wikipedia.org/wiki/Multi-licensing

**Comment by BearerOfHonesty** [comment]
https://en.wikipedia.org/wiki/Unlicense#Reception sounds like CC0 might be a better choice even if it's more legalese.

**Comment by Mikaela** [comment]
Duplicate or discussed previously _at least_ in https://github.com/privacytoolsIO/privacytools.io/issues/957 https://github.com/privacytoolsIO/privacytools.io/issues/956 https://github.com/privacytoolsIO/privacytools.io/issues/955

**Comment by ghbjklhv** [comment]
@Mikaela This is not a duplicate.
#957 #956 and #955 are about separate licenses.
I propose the idea of using multi-licensing, which doesn't seem to have been discussed before.

**Comment by Mikaela** [comment]
@ghbjklhv What benefit do you see coming from multi licensing as CC0 and something that almost everyone else opposes? Especially considering how CC0 is public domain even if your legislation didn't happen to understand public domain and thus allows you to do anything you want with it.
