### ISSUE TITLE
🆕 Software Suggestion | codecrypt - Post-quantum cryptography tool

### ISSUE THREAD

**Issue by merlinnusr** [privacytoolsIO/privacytools.io#998]
## Basic Information

**Name:** codecrypt
**Category:** software/encryption-tools/
**URL:** https://gitea.blesmrt.net/exa/codecrypt

## Description

This is a GnuPG-like unix program for encryption and signing that uses only quantum-computer-resistant algorithms:

    McEliece cryptosystem (compact QC-MDPC variant) for encryption
    Hash-based Merkle tree algorithm (FMTSeq variant) for digital signatures

Codecrypt is free software. The code is licensed under terms of LGPL3 in a good hope that it will make combinations with other tools easier.

Suggested by Whonix: https://www.whonix.org/wiki/PQCrypto#Software

**Comment by blacklight447-ptio** [comment]
ehh, knowing how inmature and unsettled post  QC crypto is, I would not be comfertable recommending it to users, as they may think its more trustworthy then something like AES or RSA.

**Comment by blacklight447-ptio** [comment]
Because of the above comment by me and the lack of response, I am closing this issue, if anyone still wants to continue the discussion, they are free to comment below here to open it up again.
